### ISSUE TITLE
APR 02: Conflict without Casualties: chapter 2-3

### ISSUE THREAD

**Issue by elle** [Blackmill/book-club#10]
Aiming to read:
- Chapter 2: Drama, misusing the energy of conflict
- Chapter 3: But I'm just trying to help

MC: @HashNotAdam, notes: @lachlanhardy 

See you Tuesday in Zoom: 

Join Zoom Meeting
https://zoom.us/j/914785529

Topic: Blackmill Book Club
Time: Mar 26, 2019 12:00 PM Canberra, Melbourne, Sydney
        Every week on Tuesday. First one: Mar 26, 2019 12:00 PM
        
Please download and import the following iCalendar (.ics) files to your calendar system.
Weekly: https://zoom.us/meeting/914785529/ics?icsToken=5dd411172ce371e9770226b355c2f163863fe4efff5e00b09866a6b7be767b09

One tap mobile
+61871501149,,914785529# Australia
+61280152088,,914785529# Australia

Dial by your location
        +61 8 7150 1149 Australia
        +61 2 8015 2088 Australia
Meeting ID: 914 785 529
Find your local number: https://zoom.us/u/abWGuMO6GJ

**Comment by HashNotAdam** [comment]
## Chapter 2 — Drama

### What is drama?

Drama is what happens when people struggle against themselves or each other, with or without awareness, to feel justified about their negative behavior.

- Drama is about struggling against
- Drama happens with or without awareness
- Feeling justified is the modus operandi in drama—people are spending enormous amounts of energy trying to feel justified
- Drama is all about negative attention behavior—did I mention I have another book?
- Drama is fueled by myths

### The persecutor

- Resorts to criticism, questioning motives, accusations, and insults
- Driven by the belief that the individual is OK and others are not OK, so therefore it’s OK to behave this way
- Myth: you can make others feel bad to get what you want
- Sacrifice respect for being feared

### The victim

- Victims overadapt, surrender, lose assertiveness, accept blame for things they didn’t do, and internalize the negative energy around them to avoid conflict and rejection
- Driven by the belief that others are OK, but they are not OK, therefore it’s OK for people to mistreat them
- Myth: others make them feel bad to coerce them into doing things, or they can make them feel good by approving of them or showing pity
- These emotions also invite criticism from other Persecutors who are frustrated with their avoidance, mistakes and lack of assertiveness. This disapproval serves to further reinforce their feelings of worthlessness.
- Sacrifice self-worth in the interest of keeping the peace and avoiding conflict

### The rescuer

- Meddles in other people's business and offers unsolicited advice
- Driven by the belief that they're OK and others would be more OK if they'd just let him help them, therefore it's OK to behave this way
- Myth: they can make others feel good by doing the thinking for them, by showing them the error of their ways and the benefits of theirs
- Invite others to sacrifice empowerment, competence and accountability, and exchange them for dependence

### What's in a triangle?

Nature hates a vacuum and so every role actively recruits for other roles to fill the gap.

### The internal drama triangle

While someone may exhibit a single drama role externally, it will be backed by an internal drama-triangle.

### There's hope for change

87% of the workplace problems leaders face are related to people issues. How can an organization possibly realize its potential with so much wasteful conflict going on?

Costs approximately $359 billion for annum in paid hours—the drag on our economy is colossal.

Great leaders see drama coming a mile away and choose not to play a role in it. They develop alternative ways of influencing excellence to preserve everyone’s dignity and stay focused on the most important priorities.

### The silver lining

Playing to our strengths is a great way to gain momentum, develop confidence and maximize our potential.

Behind each negative drama role are positive capacities that lay dormant or have been misused.

We need flexible people who can respond to the unexpected and thrive under pressure; these same people can become Persecutors, disregarding rules and setting up negative drama.

People who are conscientious are trustworthy and we can count on them to keep our highest values in mind—they can misuse this strength by falling into Rescuer mode, pointing out what everyone else is doing that’s wrong.

In drama, someone who is warm and caring by nature may play the Victim role, their warmth mutating into emotionality

One of the key qualities of a good leader is the ability to solve problems without creating new ones. What if the energy expended in drama was redirected to leveraging the multiple strengths we have within us?

### Cultural consequences of drama-based leadership

When cultures are defined by drama, the dynamics and consequences are predictable. People are capable of playing all three roles, but often play one of them more consistently.

#### Victim leaders breed victim cultures

Victim leaders avoid conflict, play it safe, second-guess themselves, and anticipate bad things happening. Many Victim leaders are still in their positions because others feel sorry for them or are avoiding the necessary conflict to hold them accountable.

Their environments reflect their leadership type through these symptoms:

- employees with low self-confidence
- loss of respect for the leader
- a gloom-and-doom mentality
- believing that outside forces are in control
- low morale and engagement
- apathy and indifference
- avoidance of conflict
- avoidance of initiative, playing it safe

#### Rescuer leaders breed rescuer cultures

Rescuer leaders are often the ones who were promoted because they were responsible and hardworking. Once in a leadership position, they never learned how to develop and empower others, instead portraying themselves as the indispensable expert who has all the answers. Their culture shows it in these ways:

- low innovation
- low initiative
- fear of failure
- analysis paralysis
- death by meetings
- death by data
- dependence on the leader
- resentment of the leader
- withholding information from the leader
- silos
- low levels of collaboration

#### Persecutor leaders breed persecutor cultures

Fear, guilt and intimidation have worked before, and it’s intoxicating to feel the temporary rush of power. These leaders don’t get honest feedback because people are afraid of them. They aren’t held accountable because nobody will stand up to them. They avoid information that would question their position, power, authority, or effectiveness. And their environment shows it through:

- secrecy, hiding, and avoidance
- cutthroat competition
- fear and anxiety
- blaming, manipulating, and attacking others to avoid responsibility for negative outcomes
- increased risk of abusive behavior
- high turnover
- increased risk of lawsuits

### Which drama role is most harmful?

High performers are four times as productive as average workers and may generate 80% of a business’s profits.

Toxic workers can have an even greater effect on organisations. These are talented and productive people who engage in harmful behavior. What makes these employees so damaging is their combination of high productivity and toxic behaviors. Because of this, they are not held accountable for their behavior, often with the excuse that the company needs their contribution.

Allowing a toxic employee to stay costs a company more than twice as much as the contribution of a star performer.

### Getting rid of toxic employees

The toxic employee has likely built up a cadre of followers or sympathizers who will react negatively at first. Once the noxious employee has left, though, the results are almost always better than anyone could have anticipated. This

**Comment by lachlanhardy** [comment]
Thanks for these, @HashNotAdam, I've incorporated them with mine and added them to the main file: https://github.com/Blackmill/book-club/blob/master/conflict-without-casualties.md
