### ISSUE TITLE
Sand Talk: Feb 16

### ISSUE THREAD

**Issue by elle** [Blackmill/book-club#102]
Continuing on with Sand Talk by Tyson Yunkaporta ([Readings](https://www.readings.com.au/products/27439470/sand-talk-how-indigenous-thinking-can-save-the-world), [Bookshop](https://bookshop.org/books/sand-talk-how-indigenous-thinking-can-save-the-world/9780062975645), [Amazon](https://www.amazon.com/dp/0062975641/))

Aiming to read:

- Romancing the Stone Age
- Displaced Apostrophes

MC: @lachlanhardy  
Notes: @mcgain 

See you 12 pm Tuesday, Feb 16th @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand.

**Comment by mcgain** [comment]
## Sand Talk - Romancing the Stone Age and Misplace Apostrophes

We start with a poem, how does everyone feel about this?

Pat and Lachlan didn’t mind it. 

The seven sisters referenced in the poem refer to the pleades, and are called 7 sisters in many different cultures across the world.

The actual chapter is off to a great start with quotes such as
> I just can’t accept the idea that cane toads are our friends. You might be feeling the same way about some of the things I’m saying in this book, and I empathise with you. I get frustrated when I hear mind-blowing wisdom mixed up randomly with ideas that seem to follow no rational path of logic.

>  He interacts with his phone like it’s a benevolent alien message stick

And

> What the hell is an IP address?


We were literally complaining about that first quote above last week, so it was a great moment of self reflection.

This book goes in so many different directions and that’s a refreshing departure from recent books we’ve read.

Lachlan criticises Yunkaporta’s use of the word Luddite, since he’s using the common definition, verses the word’s original meaning. Richard disagrees. 

It’s kinda ironic that he “half asses” the protection symbol in this chapter. He’s not happy with the shield he carves. 

Lachlan equates Blackfella time and “flow”. Richard and Pat didn’t pick up on this, but it’s a good point. 

What do we think of the education system? Yunkaporta claims it kills the undomesticated mind. Children are less creative soon after starting school. 

Pat says schooling didn’t push him in exactly the directions he needed, but it still broadly worked for him. 

Lachlan and Richard wish they had more time to follow this up more. 

We really wish there were some references here, for “facts” like the reduction of neuroplasticity of children in school, and genetic knowledge of migration patterns.

Compliance isn’t necessarily engagement. Lachlan and Elle work at building cultures at organisations. They talk about individualism vs collectivism, so does Yunkaporta, but unfortunately he doesn’t provide solutions. 

Self management is better than having supervisors dictating everything according to Elle, but Sand Talk doesn’t really provide answers to his criticisms of these things.

On Jobs:

Elle disagrees that the only aim of education is to get people jobs. Society expects us to have jobs. Politics is built around getting people jobs. 

Again, there is no alternative to this provided. Elle suggests a universal income as a solution.

Elle tells an interesting story about Fiji, when the British first arrived, the Fijian people wouldn’t work so the British imported Indians to work on the plantations.

We had some interesting discussion on why we work. This chapter helped us figure out why we work. To fulfil our desire for knowledge, relationships, fun etc.

We can go live off the land, but we’re not really self-sufficient, we still rely on technology and good that society produces. 

Oral cultures vs writing stuff down. Yes, it’s possible to lose data when you write it down, but also you can lose data in oral systems when your culture is wiped out by European settlement. Pat points out the hybrid system is best. Backups!


### Displaced Apostrophes

We loved his summaries of the different kinds of thinking

In low-context information cultures, contracts have to be watertight, but can be looser is higher context cultures. 

People from high context environments get fucked up when they have to go to school since it’s a different approach. It really made Lachlan appreciate how intertwined all these concepts are. 

Elle reckons we should just let children be children, they don’t need to grow up so quickly these days, since we live longer.
**
