### ISSUE TITLE
Sand Talk: March 2nd

### ISSUE THREAD

**Issue by lachlanhardy** [Blackmill/book-club#104]
Continuing on with Sand Talk by Tyson Yunkaporta.

Aiming to read/discuss:

* Immovable Meets Irresistible
* Be Like Your Place
* Which Way

That will conclude the book. New one from March 9th!

MC: @elle 
Notes: @pat

See you 12 pm Tuesday, March 2nd @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand.

**Comment by elle** [comment]
# Immovable meets irresistible

> Bodies in motion, bodies at rest. Unstoppable forces and immovable objects. Big bangs. Every action has an equal and opposite reaction. Ah, but somewhere in between action and reaction there is an interaction, and that’s where all the magic and fun lies... Ganma, a phenomenon of dynamic interaction occurring when opposite forces meet in an act of new creation. It is a principle that guides the interactions of different groups and interests in society, a reflection of the natural processes of self-organizing systems.

Dynamic systems of culture and language change over time

- Hailing from boats -> Hello
- "God be with you" -> Goodbye
- Checking for daggers -> handshakes

Indigenous greeting: "Which way are your going?" or "What is your purpose here?"

> This is what happens when worlds collide and then mingle over time. Living cultures and languages evolve and transform.

Turnaround event: separating spirit and physical worlds, earth camp and sky camp. Sunrise and sunset dreaming. Continual interaction between night and day, beginning and ending, expanding and contracting, like breathing in and out.

> Hybridization is a force that influences the patterns of creation. It happens with plants, animals, cultures, languages, and laws,

--
> There are a lot of opportunities for sustainable innovations through dialogue between Indigenous and non-Indigenous Knowledge systems that might help civilization transition into sustainable ways of living. The problem with this communication so far has been asymmetry—when power relations are so skewed that most communication is one-way,

Risk assessment: example of crocodile in the river or the stock market

The word "safety" does not exist in aboriginal language. "There is no agency in safety, which places a person in a passive role, at the mercy of authorities who may or may not intervene when needed".

Instead there are many words for "protection", "to look out for yourself and for the people around you". And for them to do the same.

- Bush lawyers, Mabo case, and land titles
- Blexit (black brexit)

> Australia situated the colony under the governance of criminal law and the rules and disciplines of war. He says that no law exists to take away the rules and disciplines of war, so those principles still apply to the governance of Australia under section 51 of the Constitution. Ghillar explains that this is why we have **a police force rather than a police service**

--
> This Law cannot be extinguished by the weak curses of land-use agreements and native title policies. This Law cannot be changed through dialogue either—it is the authority that shapes and regulates dialogue to keep it within the sustainable patterns of creation. It is neither the irresistible force nor the immovable object. It is neither the action nor the reaction. It is the thing in between.

## Be like your place

- Weather control system, side effects, and zero research on how it affects land, people, or environment cycles

> If land and people are not even considered as variables in these weather experiments, then it is certain all the interrelated elements of dynamic weather systems and the knock-on effects of geo-engineering are not informing these activities either.

- Pattern to creation: the golden ratio, from nature to our DNA

> The killer boomerang I carved is etched all over with patterns I perceive in the interaction of fresh water and salt water and the movements of sand along the coast. There are points where the pattern is disrupted by entities that are out of relation to the rest of the system. There are also points where the pattern reasserts itself through strange attractors, entities that adapt and spawn new responsive networks of agents in the self-organizing system.

- Culture

> In the home language of my family, there is no word for culture. There is a phrase that approximates that concept, but the meaning is untranslatable into English: aak ngamparam yimanang wunan. If you look at the direct translation of each word, the meaning comes out as “being like our place.”

- Our accent changes to reflect the places we have been to
- Deep visualisation

## Which way

- Knowledge centres

> The Australian people would be able to move on from “sorry” and start saying “thank you” (and maybe, after a while, “please”).

- Our hands and various metaphors
- Dynamic self-organising system

> Connectedness involves forming pairs with multiple other agents who also pair with others. The next step is creating or expanding networks of these connections. The final step is making sure these networks are interacting with the networks of other agents, both within your system and in others.

--
> The interaction protocol is about continuously transferring knowledge, energy, and resources. This means passing on these three things to as many other agents as possible, rather than trying to store them individually.

4 questions:

1. What can we know?
1. What do we know?
1. How do we know it?
1. How do we work with that?

Process of induction

> We had our own personal metaphors for describing this process of induction. I referred to it as spirit, heart, head, and hands. Mumma Doris knew it as Respect, Connect, Reflect, Direct. She insisted on that order. She also noted that non-Aboriginal people seemed to work through the same steps but in reverse.

Guilt: can't accumulate it, can't keep it, you have to let it go. "go. Face the truth, make amends, and let it go."

> My hope is that one day everybody can find a place under the Law of the land where they live, transitioning our living systems into something that is sustainable in the true sense of the word. Oldman Juma calls it the seven families coming home and uniting again. We’d like everybody to look up at the stars and see the same stories there once more. And stop asking the question, “Are we alone?” Of course we’re not! Everything in the universe is alive and full of knowledge.

**Comment by pat** [comment]
Further notes from today's discussion:

Richard: read the previous two chapters as well, did not agree with the chapter focused on violence. Much the same as the rest of us.

## Immovable Meets Irresistable

Pat: the explanation around whichway reminded me of womenjika, which is often said to mean 'welcome', but have heard it translated as 'come with purpose', which could also be a question: 'what purpose do you come here with?'
Lachlan: Similarly with shalom, can mean any of hello/goodbye/peace - and particularly that last option can be an answer when entering others' spaces.
Elle: The references to people wanting something beyond them, e.g. purpose - can be similar to religion.

Yunkaporta notes that there is no word for safety in First Nations languages - and that there is no agency in safety. This is contrasted to protection, where you're actively looking out for yourself and others.
Elle: I like the concept of active protection, but the implicit violence (as punishment) within this remains problematic.

Richard brings up the adoption concept, and there's some discussion about what adoption means. Pat references a short story in the Collisions anthology (Terranora, by Mykaela Saunders) which addresses First Nations adoption somewhat.
Lachlan: the adoption concept as an introduction to culture, feels somewhat similar somewhat to the scholar situation at Ruby conferences. That buddy system approach helps to make people feel grounded in a community, understand the social norms.
Lachlan: visiting a place, once upon a time, required a conversation with the community (town guards, etc) - so there'd be some shared understanding of why you're there, who you connect with. Not so much these days, though City of Maribyrnong does have a welcome pack.
Lachlan: discussions of safety made me think of 'safe spaces' and the challenges of those. Particularly around how you can't guarantee a space will always be safe. Perhaps protection is more accurate - can't promise bad things won't happen, but will have reprocussions/processes if things go bad.
Elle: online it's easy to be anonymous, zero obligations to behave within established cultural/community norms. Not a fan of online anonymity.
Elle: reminded of earlier readings and related conversations (either in this book or in How to be Antiracist) about who makes decisions about what's right or wrong, and how that needs to be a group decision.
Elle: also reminded of how different cultures communicate, whether emotion is present, and/or logic. Anglo/white cultures are more separated, neutral, vs strongly one way or another?
Lachlan: reminded of the concept of [the co-operative overlapping conversation style](https://twitter.com/anildash/status/1363695752929828872).
Elle: find it hard to separate expressing anger from feeling anger (and finds Lachlan's able to find that separation more easily).

The book moves on to bush lawyers, land title, and a suggested reason we have a police force rather than a police service.
Elle: would much prefer the latter.
Richard: Some parallels to How to be Antiracist
Richard: Would be interested to follow up on bush lawyer logic. It is true we're registered in the US, as we sell bonds there. And want to know more about the Mabo case
Lachlan: keen to read an accessible case history for Mabo decision. There's also complexity around Aboriginal heritage, and how it relates to land/title.
Lachlan: there was a legal case recently for [non-citizens who are of Aboriginal heritage](https://www.abc.net.au/news/2020-02-11/high-court-rules-aboriginal-people-cant-be-deported/11953012) and thus cannot be deported.
Richard: Raises questions about how adoption fits into all of this.
Lachlan: Including Yunkaporta's adoption, as discussed early in the book.

(Missed some notes here, my audio dropped out)

## Be Like Your Place

Elle: A lot of my last three months has been about culture (work/study all focusing on that), though the some of the models of culture are based on countries, which isn't really accurate for all the different groups within countries, migrants, etc. 'be like your place' feels limited for the same reasons.
Richard: Returning to the family home after many years of not living there, feel like I've become out of touch of how the river system works. Spotting patterns in systems is more difficult when you're moving around, or living in a city.
Richard: Does seeing these patterns make me a better person? It provides a sense of satisfaction, but don't feel it improves the way I reason through things.
Elle: Culture is not just about the land, it's also about the people.
Lachlan: When you're out in nature, seeing animals as entities/stories (e.g. Galah, Kookaburra) - could perhaps help as a way to see more patterns in nature.
Lachlan: Have been reading up about discussions/importance of birthing trees - depth of time can create such a strong bond for First Nations cultures. Not entirely on board with arguments that say we (settlers) can't experience such bonds.
Lachlan: The weather modification businesses exist, which is scary/dystopian.

## Which Way

The book offers Mumma Doris' metaphor of Respect, Connect, Reflect, Direct, and notes that government/non-Indigenous groups often get it the wrong way around.
Richard: hear how this happens in government interactions generally (i.e. bushfire support).
Lachlan: Thankful we've had a mild summer!

Richard: The final chapter didn't quite have the punch I was hoping for.
Elle: We commented in previous sessions that the focus of the book is not super practical - but it has us thinking differently, and learning a lot, and know that we still have a whole lot to learn.
Richard: There are definitely parts of it that i'll be thinking about for a long time.
Lachlan: I did the hand exercises, not expecting to retain that, but like the process of putting knowledge into fingers/combinations of fingers, can see that being very useful.
Richard: Like counting with one hand to twelve
Elle: Reminds me of haggling with hands only in China
Pat: I've enjoyed the book, even if the ending felt a bit limited. Like others have said, has provided a lot of learning, and will continue to prompt deeper thinking.
Lachlan: Not thrilled with the last chapter either, felt a bit amateur, like a rushed blog post conclusion.
Elle: Though focusing on hands in the final chapter is not surprising, given how often it came up throughout.
Lachlan: There remains the questions of what is sustainable, and how do we get there? Yet to find any good answers especially for the latter.
