### ISSUE TITLE
The making of a manager: Mar 16: ch 3 + 4

### ISSUE THREAD

**Issue by elle** [Blackmill/book-club#106]
Next book is The Making of a Manager by Julie Zhuo ([Readings](https://www.readings.com.au/products/25282474/the-making-of-a-manager-what-to-do-when-everyone-looks-to-you) or [Amazon](https://www.amazon.com/Making-Manager-What-Everyone-Looks-ebook/dp/B079WNPRL2/))

Aiming to read/discuss:  

- Chapter 3: leading a small team
- Chapter 4: the art of feedback

MC: @mcgain 
Notes: @HashNotAdam

See you 12 pm Tuesday, March 16th @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand.

**Comment by elle** [comment]
## 3: leading a small team

- Everything always goes back to people
- Trust is the most important ingredient and building a relationship is up to the manager
- Miscommunication will lead to missing early warning signs, which will lead to bigger problems down the road
- Can you say?
  - My reports regularly bring their biggest challenges to my attention
  - My reports would gladly work for me again
- How to be a manager?
  - Respect and care about your report -> honesty
  - Invest time to help them
- One:ones
  - Discuss top priorities
  - Calibrate what "great" looks like
  - Share feedback
  - Reflect on how things are going

> Every morning, I’ve gotten into the habit of scanning my calendar and compiling a list of questions for each person I’m meeting with. Why questions? Because a coach’s best tool for understanding what’s going on is to ask. Don’t presume you know what the problem or solution is. Too often, attempts to “help” aren’t actually helpful, even when served with the best of intentions.

**Suggested questions**

- Identify
  - What’s top of mind for you right now?
  - What priorities are you thinking about this week?
  - What’s the best use of our time today?
- Understand
  - What does your ideal outcome look like?
  - What’s hard for you in getting to that outcome?
  - What do you really care about?
  - What do you think is the best course of action?
  - What’s the worst-case scenario you’re worried about?
- Support:
  - How can I help you?
  - What can I do to make you more successful?
  - What was the most useful part of our conversation today?

--
- Be honest and transparent about your report's performance
- Admit your own mistakes and growth areas

> I’ve found that by showing up authentically, with my fears, mistakes, and uncertainties out in the open rather than swept under the rug, I’ve been able to build better relationships with my reports.

- Help people play to their strengths
- One thing you shouldn't tolerate: lone wolf who is a divider not a multiplier
- No asshole rule

> “He makes you feel like an idiot.” A huge amount of time was spent dealing with the frayed relationships in his wake.

- You don't always have to make it work
- Move people around quickly

> At the end of the day, if you don’t believe someone is set up to succeed in his current role, the kindest thing you can do is to be honest with him and support him in moving on.... “What I think is brutal and ‘false kindness’ is keeping people around who aren’t going to grow and prosper. There’s no cruelty like waiting and telling people late in their careers that they don’t belong.”

--
> A good question to ask is: If this person were not already at the organization, would I recommend that another team hire him or her knowing what I know?

## 4: the art of feedback

> feedback doesn’t have to be critical. Praise is often more motivating than criticism. And for another, you don’t always have to start with a problem.

- Set clear expectations at the beginning
  -  What success looks like?
  -  What advice ca you give to get them started on the right foot
  -  Common pitfalls to avoid
- Give task-specific feedback as frequently as you can
  - Easiest level, focused on what rather than who
- Share behavioural feedback thoughtfully and regularly
  - State what you perceive
  - Use thoughtfully considered words with specific examples
  - Given in person
  - Engage in a two-way conversation
- Collect 360 degrees feedback

--
- Every major disappointment is a failure to set expectations
  - No one should hear "does not meet expectations" for the first time in their performance reviews
  - Other examples: working with a report on their promotion, assigning challenging project to a report, project launch deadline
- Feedback counts only if it makes things better
  - > The question that should always be in the back of your mind is: Does my feedback lead to the change I’m hoping for?

> simply to give feedback more often and remind yourself that you’re probably not doing it enough.

- Feedback won't stick if the other person feels under threat
- Best way to get feedback heard is to make the other person feel safe

> When you do have critical feedback to share, approach it with a sense of curiosity and an honest desire to understand your report’s perspective.

- Does my feedback lead to positive action?
  - Make your feedback as specific as possible
  - Clarify what success looks like
  - Suggest next steps

> One suggestion that might help you with your next presentation is using the rule of threes—no more than three goals, three sections, and three bullets per slide.

- Delivering critical feedback
  1. You’re such a screwup. What am I going to do with you?
  1. Your work is terrible, and I need to know how you’re going to fix it.
  1. I’m concerned about the quality of work that I’ve been seeing from you recently. Can we talk about that?
  1. Your last few deliverables weren’t comprehensive enough to hit the mark, so let’s discuss why that is and how to address it.
  1. I have a few questions about your latest work—do you have a moment to walk me through it?

> We regret the things we say in anger, and while bridges take months or years to build, they can be burned in an instant.

--
> “Feedback is a gift.” It costs time and effort to share, but when we have it, we’re better off. So let’s give it generously.

**Comment by HashNotAdam** [comment]
# Discussion

@mcgain: She says that creating a shared sense of purpose is easy, which leaves the people and process parts. I've never once had a problem with a shared sense of purpose in a small team.
@JohnTelfer: It's more difficult to get a shared understanding when you've got people who have come from different backgrounds or based in different places. Finding it harder to create a shared goal during COVID.
@lachlanhardy: It _can_ be easy in a small team but it depends on what they are surrounded by.
@elle: The more people you add, the more channels of communications are possible and it's harder to keep track of what's happening.
@mcgain: A lot of those things come down to creating that environment of support.

@mcgain: She says there are two reasons why someone's doing bad work; they don't know how or they're not motivated. Do we agree that those are the only two reasons?
@lachlanhardy: No. /micdrop
@lachlanhardy: You can know how to do good work and you could be motivated to do good work. She seems to correlate "bad" with not having the skills rather than people not knowing how to do good work. What does "good work" look like for this team/company? There's a bunch of other ways you can address substandard work other than firing (training/expectation setting).
@JohnTelfer: I wonder Facebook's got a line of people waiting with the right qualifications. My experience has been there's _at least_ six months of development into new hires.
@elle: How many companies want people "to hit the ground running"‽
@lachlanhardy: She shows no reflection that, if your people are flailing, they might need something other than just more time.

@mcgain: The next section is about trust. She says that "you should strive for your meetings to be awkward". Is that what we should aspire to?
@elle: Just listened to a podcast on trust. You build trust with even small interactions in the office. Trust is like bank credit that needs to be built. When you are remote, you can't see people doing work so it's a lot harder to build or maintain trust.
@mcgain: is uncomfortable "feeling" people. (She says saying "I feel you" helps build trust)

@mcgain: She says "management is about caring for your team members like a family does". Is that too personal?
@elle: Working with people like family is my goal in life. Given short employment contracts and people moving for better pay, it's hard to build a "family".
@lachlanhardy: When companies offer difficult salary negotiations and poor support, it's impossible to be loyal like a family.
@JohnTelfer: One key take away from this chapter is "will my reports work with me again given the chance?" That's the big indicator that you're doing your job well and probably more the point than touchy-feely family stuff.
Chap: Wants to be in a cult

@mcgain: The rest of the chapter is 1-on-1 tips. The most important thing I thought was "don't focus on the worst performers."
@elle: That matches her view that, if you're not performing, you should be fired.
@mcgain: Her logic bears out, but it's so cold.
@lachlanhardy: I wonder how much of this is implicit in how [Facebook] works and, given this is her only job, she doesn't have other perspectives.

@mcgain: She says praise is more motivating than criticism. It's important to be aware that many people only want praise in private.

@mcgain: Does anyone participate in 360 reviews?
@elle: She believes that 360 feedback is objective I [do not agree with this assertment]. It's better than one person's review but not objective.
@lachlanhardy: At Microsoft, they openly admit that your team won't be objective but, by requiring specific examples when giving praise, it can help the manager learn.
@JohnTelfer: 360 feedback can highlight gaps, particularly where someone is managing up and so the manager likely isn't otherwise hearing the complaints of other stakeholders.
@mcgain: Had a very bad experience with it and it was scaped because the team hated it.
@elle: HBR has an article on the fallacy of feedback which can be summarised as "who am I to tell you how to improve‽" Good feedback needs all the context.
@JohnTelfer: It's weird because the author talks about performance management as sacking people.
@lachlanhardy: She's basically saying "this person is not performing; I will, on occasion, provide them feedback to let them know that but otherwise I'm gonna spend my time with the high performers". Like the person who she promoted to manager who then quit and she discusses as if there was nothing they could have done about it.

@mcgain: She says that no one should be surprised when they go into a performance or annual review.
@HashNotAdam: There is a contradiction between the idea that you should be discussing poor performance in advance but also that 1-on-1s are the report's time to tell you about what they need to succeed.
@mcgain: I have found that it is possible to lead a conversation such that they come to the realisation that they need to do better in certain areas.
@lachlanhardy: The book seems to reinforce that it's the report's role to work out how to identify and resolve problems.
@JohnTelfer: She stated that managers exist to create a multiplying effect on either reports but none of this feels like it's her getting the best out of her staff; it doesn't feel like she's actually driving people to succeed with this feedback.
@mcgain: I think the culture of Facebook really shines through.

@elle: Are we enjoying the book? Her perspective is quite limited but I do like that she has a lot of different examples.
@mcgain:  I think you can take this book and learn a bit about how to manage people. Some of the advice I don't agree with but you could implement it and you'd be doing a better job than if you didn't have the advice.
@lachlanhardy: I agree. I have valid criticisms but I have actually been quite enjoying it. She's covering useful materials with lots of examples and one chapter gave me a fresh perspective on stuff that I have been neglecting.
@HashNotAdam: I am simultaneously happy I'm reading the book and happy I'm reading the book in this group and that we can critically analyse it.
@JohnTelfer: I am liking how the chapters are structured and it does give a different perspective.
