### ISSUE TITLE
The making of a manager: Mar 23: Ch 5

### ISSUE THREAD

**Issue by elle** [Blackmill/book-club#107]
Current book is The Making of a Manager by Julie Zhuo ([Readings](https://www.readings.com.au/products/25282474/the-making-of-a-manager-what-to-do-when-everyone-looks-to-you) or [Amazon](https://www.amazon.com/Making-Manager-What-Everyone-Looks-ebook/dp/B079WNPRL2/))

Aiming to read/discuss:  

- Chapter 5: managing yourself

MC: @chaplonglau
Notes: @JohnTelfer

See you 12 pm Tuesday, March 23rd @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand.

**Comment by JohnTelfer** [comment]
Chapter 5 Managing yourself
Executive coach
•	Stacy McCarthy - Hired executive coach - remarkable little internet presence - palette 17, 
•	made 20 page report on her - tldr, if you don't have a good handle on yourself, you don't have a good handle on how to best support your team 
•	Picture yourself 80, sitting on a beach and looking back on your life. What did I want to remember? 
•	Julie starts the chapter with a story on hiring an executive coach that gave a 20-page daa see ei on her strengths, weaknesses, management style and everything in between. What are everyone's thoughts and experiences on executive coaching?
•	(Blackmill costs ~$2000/ 6 1-hour sessions) (Stacy McCarthy has a firm called Palette17 which has a remarkably small internet footprint)  On their site, they state that [We] help leaders identify their core strengths and build a solid foundation and "centre" from which they can lead more effectively. Tell me about you, your past the road you have take to get here, the future. 
•	How do you work perceived strengths and weaknesses. 

Discussion

Elle : Research states that you will be a better leader with an executive coach. People who are new to management
Adam: path would be shorter with a coach
Chap: Stacy Macara leaders identify core strengths
Lachlan: never had a formal mentor, get feedback from the people your advise affects, we are all approaching the text from different angles. There is value in formalising the mentoring relationship.
John: gain an informal mentor for a brood range of experience technical skills and presentations. 
Imposter syndrome
Julie then talks about imposter syndrome. She stresses every manager feels like an imposter sometimes. It's totally normal and you get it because 
- you're often looked to for answers ( and that's pressure)
- you often get put in the position of doing thing you haven't done before like firing someone
How long did it take for everyone here (if ever) to stop feeling imposter syndrome?
 What are your experiences with it?
•	Every manager feels like an imposter sometimes
•	Checking your emails 3 times 
•	Teetering on the edge of a sheer cliff the world watching you waiting to fall
•	The early days of being a boss, disorientation and over whelming.
•	Why does this happen? You are looked to for answers. You are the first person called on.
•	Management isn’t an innate skill

Discussion 

Everyone: agrees that you never overcome imposter syndrome
John: Imposter syndrome leads to checking emails 3 times and not taking risks.
Lachlan: fixed and growth mindsets. Growth mindsets makes imposter syndrome easier to deal with. Writing draft emails in a text doc. Unneeded anxiety and tenancy to do things and not taking risks. concerns about trying and failing.
Adam: we spend more time on these books, does the sample size of your own experience. Re-evaluate the assumptions. Difficult to manage. Can confirm your ideas. 
Elle: has been working on a draft bog post on piggies and imposter syndrome, psychological safety. Praising team mates rather that chastising them. Don’t focus on what needs to be fixed.
How do you get out of the pit
•	Celebrate the wins
•	Visualise 
Chap: on the scientific method for determining the power of visualisation. 
Adam: “what I tell myself is” As a way to get to the point. Use internal monolog to talk yourself  through the problem. Pro Mindfulness but getting better with visualisations is BS. CrossFit training improves when preparing brain to get past the pain barrier.
Lachlan: Don’t beat yourself up for feeling bad. Talking over the problem with a college or partner. 
Elle: Depression and Anorexia misscalabration with reality. Growth v Fixed as Fear, five good things that have happed  today.
John: The benefit of self visualisation comes from taking away the negative thoughts. 
Lachlan: Lean in circles(Cheryl Sanburg) what would that be like at Facebook?
Chap: Leaning in is not a solo sport. In a world where women still face bias and other barriers at work, Circles are a safe space to share your struggles, give and get advice, and celebrate each other’s wins. Whether you need help navigating your new normal at work or are looking for support from women who understand what you're going through, your Circle will give you the boost we all need to take on 2021.

Get to brutal honesty with yourself
•	Who are you as a manager
•	Strengths and weaknesses directly effect how you manage
•	Strategic prowess, multitasking
•	Facets of our personality
•	What works best with what you have

Top leaders come from different moulds 
•	Extrovert Winston Churchill 
•	Introvert Abraham Lincoln
•	Demanding Margret Thatcher
•	Remind you of a favourite relative Mother Theresa
•	Leave a room breathless with their vision Nelson Mandela
•	Avoid the spot light Bill Gates
Understand and Play to your strengths
•	Strength finder 2.0 Tom Wrath
•	Standout Marcus Buckingham
•	Jot down the first thing that comes to mind when you ask the following questions
•	Finding your strengths
o	How would the people that know and like me best describe me in three words?
o	What three qualities that I poses am I the proudest of?
o	When I look back on something that I did that was successful, what personal traits to I give credit to?
o	What are the top three pieces of feedback have I received from my managers of peers?
•	Finding your weakness
o	Weaknesses and triggers
o	Whenever my worst inner critic sits on my shoulder what does she yell at me for?
o	If a magical fairy were to come and bestow on me three gifts that I don’t yet have what would they be?
o	What are three things that trigger me?
•	What are the top three most common pieces of feedback from my manager or peers on how I can be more effective?
•	The biggest barriers that get in my way are?
•	Calibration.
•	Public Speaking 
•	Practice and get better
Treat your manager as a coach
•	If you are not learning from your manager what can you do to fix this.
•	Make a mentor out of everyone
Who do you run meetings 
•	Running across multiple locations
Reflection
•	6 month evaluations
•	If you have the option to take formal training you should take it
•	Invest in your personal learning and growth

Discussion 
Chap: Do you take the time to reflect on goals? What's your method? Do you have a similar timeframe?  Personally, every six months, or you know major life episode, I sit down for a couple hours and fill out [https://yearcompass.com/](https://yearcompass.com/). It's a collection of  questions that I found very helpful for reflecting and planning. I encourage everyone to check it out.
Elle: Personal Kanban with a weekly retrospective with herself. 
Lachlan: Daily list of tasks. Backlog for parked tasks. Asking for feedback making a journal. People don’t like looking into their skills.
Adam: I work with some people who don’t take the time to be overworked.
Lachlan:  some people only focus on the code. Other processes need to be factored in.
Chap: personal development and the Metrix for measuring how you achieve your goals. 
John: planning for skills gaps and factoring in time for PD. 

Next time: chapter 6 Running Meetings and 7 Hiring Well. 
Lachlan to run Adam taking notes
