### ISSUE TITLE
#108 The making of a manager: April 6: Ch 6 & 7 

### ISSUE THREAD

**Issue by JohnTelfer** [Blackmill/book-club#108]
#108 The making of a manager: April 6: Ch 6 & 7 
Current book is The Making of a Manager by Julie Zhuo (Readings or Amazon)
Aiming to read/discuss: chapter 6 Running Meetings and 7 Hiring Well. 

MC: Lachlan

Notes: Adam

See you 12 pm Tuesday, April 6th @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand.

**Comment by HashNotAdam** [comment]
# Discussion

@lachlanhardy: Very similar to previous management books we've read.
@mcgain: Agree but it's good content worth revising

@lachlanhardy: The concept that, while meetings have a purpose, they need to have an outcome has really helped with meeting preparation.

@lachlanhardy: How have you done team strengthening exercises in the past?
@lachlanhardy: One of Blackmill's clients had a new person join the team remotely from the Philippines. They were concerned about how they would get to know this person. The manager suggested everyone bring a photograph to a virtual meeting. Each person spoke about the photo and why it was significant; the story offered insight into each person.
@mcgain: His workplace engaged in triple-H—each person discusses a hero, a hardship, and a highlight. The idea is that people get to know you deeply and, while it works for some personality types, the style of sharing can be quite objectionable to others.
@chaplonglau: The company he works for thrives on pop culture. Each new hire will be interviewed by their manager where they spend 2 hours learning about you and write a Buzzfeed-style article about you (lots of pictures, GIFs, memes) which is sent to the whole company.
@lachlanhardy: Blackmill recommend a welcome email for all new employees. Buildkite have a blog post about an employee's first 4 weeks and, in the 4th week, the employee reflects on what they've learnt and considers how they will contribute. That week, at the all-hands meeting, the employee gives a presentation about themselves, why they joined Buildkite, and what they are bringing to the company. The hiring manager also presents why they hired, what they saw in the person, and what they believe the employee will bring to the team.

@lachlanhardy: Thoughts on refining meeting invitees?
@mcgain: Having this problem at the moment. There are dozens of meetings throughout the week and usually someone from the dev team goes to the meetings. This can waste someone's entire week but important decisions are being made in these meetings so they can't simply opt out of going.
@elle: Some meetings need to happen but one solution would be to embrace asynchronous decision making. For meetings that need to happen, it can help to have someone document the discussion and options and distribute the information before the meeting so the meeting can be focused.
@lachlanhardy: While some people need to be in the meeting, maybe others do not. Using a responsibility assignment matrix, aka RACI (responsible, accountable, consulted, informed), it might be possible to slim down the invite list and then allow others to read the meeting resolutions. Saying this, haven't seen anywhere stick to one of those models because of the administration work.
@chaplonglau: That sounds like a problem for a project manager.
@elle: Knows a company trying to move all decision-making online and asynchronous but expecting this to fail. Both in-person meetings and asynchronous decision-making is required.

@lachlanhardy: Purchased Inclusion Meeting Cards for helping control meetings. For example, the CEO might be given 3 opinion cards and, every time they voice an opinion, a card is removed. Other examples are "beating a dead horse" or roles like "devil's advocate".

@hashnotadam: One suggestion was moving stand-ups to email only but this doesn't feel like the best way to manage that problem.
@elle: Prefers messages on Slack
@lachlanhardy: Keeps tasks in markdown which is updated throughout the day and then posted to Slack
@elle: Office-wide stand-ups where people are on different projects don't make sense unless it's organised like a social catchup. Standups are rarely done well; each person should speak for about 30 seconds and that's why a status message is preferred.
@hashnotadam: Sent another director on leave, and has been filling in including joining a fortnightly leaders meeting. Finding the meeting is just a standup which seems pointless since it's across business and infrequent. It would seem that a fortnightly catchup should be deeper or the meeting shouldn't exist.
@elle: Blackmill recently suggested to a business that engineering managers catch up every couple of weeks but they really need to have an agenda for that meeting (how to standardise things, how to work in a similar manner, etc). A cross-business status update should be an email.
@hashnotadam: The director on leave spends most of the day in meetings. Since he has been gone, those meetings aren't happening and yet to see any downsides. Expect leaders could just be empowered to make decisions.

@lachlanhardy: Has anyone produced a 1-year team hiring plan?
The room: generally non-responsive
@hashnotadam: We do actually produce a plan because we find it takes us a long time to find people we want to hire. At least quarterly, the directors get together and one topic is hiring for the following 12 months. The big takeaway from this section, however, was the manager saying "If I told you that hiring well was the _only_ thing that mattered, would you do anything differently?" We take such a long time to hire but have a lot of people underwater—what if we make it the only priority?

@lachlanhardy: Most businesses seem to fail at describing who they want to hire and their job applications don't even describe the current people in the business.
@mcgain: The inability to write a good job description stems from not knowing your team. If you don't know what gaps there are in the team, you don't know how to fill those gaps.
@elle: Accurately defining roles helps with performance reviews, promotions, and job ad descriptions. It is also useful in job interviews if you know the characteristics of the person you are looking for. Out of all the aspects of the candidate, the least valuable is current skills.

@lachlanhardy: Has anybody ever had an amazing interview experience?
@hashnotadam: [Not even once](https://youtu.be/uGiAxwgrF_k).
@chaplonglau: Interviewed with one company where everyone was passionate. They didn't just say the company values, they embodied them. The interview process was clear and questions were answered efficiently.
@mcgain: Appreciated how the author says she contacts job applicants every few days because it's frustrating when you don't know what's happening.
@lachlanhardy: After 9 months of interviewing with Nokia, told them "if you really wanted me, this deal would be done"—they were gutted.
