### ISSUE TITLE
The making of a manager: April 20: Ch 8, 9, 10, and Epilogue

### ISSUE THREAD

**Issue by lachlanhardy** [Blackmill/book-club#109]
Current book is The Making of a Manager by Julie Zhuo 
Aiming to read/discuss: 

- Chapter 8: Making Things Happen
- Chapter 9: Leading a Growing Team
- Chapter 10: Nurturing Culture
- Epilogue: The Journey is 1% Finished

*Don't worry, all that is only 43 pages*

MC: @elle 
Notes: @lachlanhardy 

See you 12 pm Tuesday, April 20th @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand.

**Comment by elle** [comment]
# 8: Making things happen

A good process means consistently iteration on what works and what doesn't.
Process by itself is not bad. Good process is effective.

> Bad process is heavy and arbitrary. It feels like a series of hoops to jump through. But good process is what helps us execute at our best. We learn from our mistakes, move quickly, and make smarter decisions for the future.

### Start with a concrete vision

> the huge amount of subjectivity in words like help or improve, they don’t do much to create a shared sense of purpose.

- Inspiring vision: bold, measurable, and repeatable. It doesn't describe the how, just what the outcome will be
- Questions to ask:
  - What do you hope will be different in 2-3 years?
  - How would someone describe your team now? and desired reputation in a few years? what is the gap?
  - What would you like the team to be twice as good?
  - What would be the litmus test to assess team performance?
- Good strategy: can be achieved, understands the crux of the problem so that energy is focused on most important goals
- The plan should be based on team's strengths
- Focus on doing a few things well
- Prioritisation: have clarity on "must haves", "should haves", and "nice to haves"

  > If you have three goals for your team this half, force yourself to answer: “If I could only achieve one goal, which would it be?”

  Steve Jobs: "[focus] means saying no to the hundred other good ideas that there are. You have to pick carefully."

- Define who is responsible for what

  > When ownership isn’t clear, things slip through the cracks. This doesn’t just happen in meetings;

- Break a big goal into smaller pieces
  > Nothing worthwhile happens overnight

> Worry about what’s in front of you—don’t worry yet about what’s months or years ahead. Then work with your team to set realistic and ambitious target dates for each milestone. Keep in mind the planning fallacy: our natural bias to predict that things will take less time and money than they actually do. Allot a buffer for dealing with unexpected issues.

--
> Ask people to set and publicly commit to their weekly goals—this creates accountability.

### Perfect execution over perfect strategy

> My manager Chris often reminds us, “It’s not a good idea to design where your kitchen outlets should go when you haven’t yet settled on the floor plan.” In other words, start by understanding the bigger picture. What problems are you hoping to solve with what you’re doing? How do you imagine people will get value out of your work? Based on that, what are the most important priorities for the team now?

- Think about how everything relates to the vision
  > if everyone understands and buys into what they are ultimately trying to do, the tactical, day-to-day decisions become easier because you can look at them through the lens of: “Which option moves us closer toward the future that we want?” When people don’t understand what ultimately matters and why, that’s when conflicts arise.

### Good process is ever evolving

- Manager's role: updating documentation on how the team works

# 9: Leading a growing team

### Big teams vs small teams

- Direct vs indirect management via more levels of managers
- A lot of context switching
- Pick and choose your battles
- Skills that matter are people centric

### Tightrope act of great delegation

> side, the hardest part has been learning how to effectively delegate, which I define as "the art of knowing when to dive in yourself and when to step back and entrust others."

- Grow people by letting them solve difficult problems by themselves

### Giving people big problems is a sign of trust

- But first you need to actually believe your report is capable of solving the problem
- Delegating does not mean simply walking away

### Two heads, one shared vision

> To create a shared vision of what’s important, ask yourself two things. The first is, What are the biggest priorities right now for our team?... second, Are we aligned in how we think about people, purpose, and process?

- People trump projects - great people are the prerequisite for great work

> If you want to build a ship, don’t drum up the men to gather wood, divide the work, and give orders. Instead, teach them to yearn for the vast and endless sea.
> -- Antoine de Saint-Exupéry

### What to do when a manager struggles

- When delegating, acknowledge that people will falter, make mistakes, and doubt themselves

### Aim to put yourself out of a job

- What to delegate: spend your energy on what's important to the organisation, and what you're uniquely able to do better than anyone else. And use this to extrapolate what to delegate to a report
- Identify and communicate what's important

# 10: Nurturing culture

> an organization’s culture is best understood not from reading what’s written on its corporate website but from seeing what it’s willing to give up for its values.

- Balance between autonomy and authoritarian team dynamics
- "Culture describes the norms and values that govern how things get done."

> “I focused on creating the best one-on-one relationships I could. But now I realize that isn’t enough. Because it’s not just about my relationship to the team. It’s also about their relationships with each other, and with the group as a whole.”

### Know the kind of team you want to be a part of

- Understanding the current team:
  - What are the first three adjectives that come to mind when describing the personality of your team?
  - What moments made you feel most proud to be a part of your team? Why?
  - What does your team do better than the majority of other teams out there?
  - If you picked five random members of your team and individually asked each person, “What does our team value?” what would you hear?
  - How similar is your team’s culture to the broader organization’s culture?
  - Imagine a journalist scrutinizing your team. What would she say your team does well or not well?
  - When people complain about how things work, what are the top three things that they bring up?
- Understanding aspirations
  - Describe the top five adjectives you’d want an external observer to use to describe your team’s culture. Why those?
  - Now imagine those five adjectives sitting on a double-edged sword. What do you imagine are the pitfalls that come from ruthless adherence to those qualities? Are those acceptable to you?
  - Make a list of the aspects of culture that you admire about other teams or organizations. Why do you admire them? What downsides does that team tolerate as a result?
  - Make a list of the aspects of culture that you wouldn’t want to emulate from other teams or companies. Why not?
- Understanding the difference
- On a scale from one to nine, with nine being “we’re 100 percent there” and one being “this is the opposite of our team,” how close is your current team from your aspirations?
- What shows up as both a strength of your team as well as a quality you value highly?
- Where are the biggest gaps between your current team culture and your aspirations?
- What are the obstacles that might get in the way of reaching your aspirations? How will you address them?
- Imagine how you want your team to work in a year’s time. How would you describe to a report what you hope will be different then compared to now?

### Never stop talking about what's important
### Always walk the walk

> If you say something is important to you and you’d like the rest of your team to care about it, be the first person to live that value. Otherwise, don’t be surprised when nobody else does either.

### Create the right incentives

- Not LOC
- Include discussion about why? why are we doing this?
- Common incentive mistakes to avoid:
  - Rewarding individuals performance over anything else
  - Rewarding short-term gains over long-term investments
  - Rewarding lack of perceived issues or conflict
  - Rewarding the squeaky wheel - people that try for a pay rise by getting higher offers with other companies
- Understand the reasons behind people's decisions. If you don't know, ask.

> When a report does something difficult that is in the spirit of your team’s values—passing up a lucrative sales deal because of ethical concerns, firing a star performer who is creating a toxic work environment, or admitting openly when they’ve made a mistake—recognize them for it. Acknowledge that it was hard, and thank them for doing the right thing.

### Invent traditions that celebrate your values

Examples: routine lunch and learn, recognise when people are awesome, "fail of the week"...

# Epilogue - the journey is 1% finished

> In another ten years, I know I’ll look back and realize that the path I’m on today is still squiggly. There is much left to learn, and I am far from being the manager I aspire to be. But with time, will, and a growth mindset, the lessons ahead are right there for my taking.

**Comment by lachlanhardy** [comment]
## Chapter 8
Good to have confidence in what you’re making but Richard has never worked in teams that had issues executing. He has worked in teams that built the wrong thing well. Strategy is vital.

Have any of us split work across multiple projects with different timescales?

We’ve mostly seen it at org level, not so much team. When small teams have multiple responsibilities, time boxing each area can work but new things need someone dedicated to keep the context and think deeply enough to develop and drive the direction.

## Chapter 9

The more teams you have, the more you have to delegate, the more control you lose, the more you have to trust the people you’re delegating to.

You have to park your own preferences. The person you’re delegating to may do things differently to how you would do them and you have to become okay with that. The reason you’re delegating is that you wouldn’t be able to do these fully yourself anyway, so getting someone else’s 80% is a progress.

# Our consensus

A solid book covering lots of what we consider modern principles of tech leadership. Our caveats revolve around the same things she calls out herself at the start; this book is based on her career at Facebook, from intern to VP.
