### ISSUE TITLE
An Elegant Puzzle: May 11: Chapter 3

### ISSUE THREAD

**Issue by elle** [Blackmill/book-club#111]
Current book is An Elegant Puzzle by Will Larson ([Amazon](https://www.amazon.com/Elegant-Puzzle-Systems-Engineering-Management/dp/1732265186)).
Aiming to read/discuss: 

- Chapter 3: Tools

MC: @saramic 
Notes: @JohnTelfer

See you 12 pm Tuesday, May 11th @ https://blackmill.co/meet

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand.

**Comment by JohnTelfer** [comment]
Discussion  

Product management: exploration, selection, validation. An excellent section on how to put on the "product manager hat", that is often a useful one. 

Michael: Migrations in Hypergrowth calculations don’t really make sense.  

Elle: High level points on topics. Full of information accurate to the name to solve a puzzle.  

Lachlan: Managers stepping in as glue to hold teams together. But this insight isn’t explained in sufficient detail.  

Adam: the example of Keith Pitt, Minister for Resources, Water and Northern Australia. https://twitter.com/Bowenchris/status/1391613178677657601?s=20 

Answering question indirectly like a politician isn’t great for business.  

The book is providing a lot of information on systems thinking but interested in the referenced books.  

Lachlan: Thinking in a Systemic fasion to incorporate how does this work with other areas. 

Michael: Systems thinking chapter lacks examples. 

Problem discovery 

Michael: Problem discovery. Validating the idea by learning and fail quickly. Is the version of product discovery the same as everyone else's. 

Elle: Define the problem, how do you know this is the right product? 

Adam: the area of product management is a specialist area that will take years to learn. 

Michael: Compounding leverage with a new set of actions. Surviving the next round. Removing quality for a short term gain, quality and velocity are extreme ends of the spectrum.  

John: building quality from the start increases velocity in the long term over short cuts. 

Lachlan: Viewing the selection process as an elimination tournament. Worked on a project where he had to unpick work someone else had done quickly, Building quality early on is a better approach. The cost of unpicking rushed work is high. 

Michael: Write a customer letter to start from the end and take steps backwards from there. 

Elle: Practice your pitch for the product, refine a you build.  

Lachlan: Amazon devs need to write the press release before they start the build process. 

Michael: Identify prior art its better to rely on people you trust rather than misinformation. Find the cheapest way to validate. 

Richard: product management note down all possible solutions. 


Visions and strategies

Adam: getting leaders together to become customer centric, turning vague statements into actionable strategies.  

Michael: splitting the monolith project, (example) where one team has a clear vision and another one doesn’t. 

Elle: Vision split to individual divisions but linked to company goals.  

 

Adam: commonality to the other books they haven’t given examples of operationalising the vision. 

Elle: The job of Admin staff and HR people can be defined by how they look after the people in the vision statement.  Refer to visions and values on a daily basis.  

Michael: renaming BAU to Immediate impact, if something is bringing in new income it should be prioritised if not it shouldn’t be worked on. Blocking out focus hours where you plan to do work.  

Lachlan and Elle: Make time to think about management rather than reacting.  

Adam: Admit you have a problem is the first step. 

 
Michael: Migration as a solution to Magnitudes of scale and tech debt. 

Growing stack becomes obsolete every 18 months 

Richard: Ratcheting as a positive migration tool.
