### ISSUE TITLE
Elegant Puzzle, May 24: Chapter 4

### ISSUE THREAD

**Issue by elle** [Blackmill/book-club#113]
Current book is An Elegant Puzzle by Will Larson ([Amazon](https://www.amazon.com/Elegant-Puzzle-Systems-Engineering-Management/dp/1732265186)).
Aiming to read/discuss: 

- Chapter 3: if there is anything else we wish to discuss
- Chapter 4: approaches

MC: @mcgain 
Notes: @lachlanhardy 

See you 12 pm Tuesday, May 24th @ https://blackmill.co/meet

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand.

**Comment by lachlanhardy** [comment]
### 3.14 Time management

#### Stop doing things

We had a detailed conversation about this section. We all find the concept of deliberately listing out things that we will not or will no longer do a useful tool for stimulating conversations about priorities and achievement. 


## 4. Approaches

Some of us had an instinctive negative response to the idea of policy. The guess is it stems from poor experiences when our own teams needed exceptions that weren't granted.

Others talked about how instead of granting exceptions, what if revising the policy were the response to exceptions?

Firing a mistake-maker fails to correct the system that produced the error. 

Mapping out the flow of work sounds like a useful tool for diagnosis of process issues.

### People over process

He's kind of saying that process is irrelevant and yet that cannot work. People are vital but process must matter.

### 4.4 Managing in the growth plates

We're intrigued by the idea but can think of a bunch of counter-examples

### 4.6 Partnering with your manager

None of this seeemed new except the idea of actually asking this things of one's manager. None of us have ever done that or had it done to us - we just try to reason them from observation.

### 4.9 Close out, solve, delegate

Delegation seems the weak point here. It feels a lot like passing the buck. Delegating to someone with appropriate skills to solve or close out makes sense.
