### ISSUE TITLE
Elegant Puzzle, June 1: Chapters 5 & 6.1, 6.2, 6.3

### ISSUE THREAD

**Issue by lachlanhardy** [Blackmill/book-club#114]
Current book is An Elegant Puzzle by Will Larson ([Amazon](https://www.amazon.com/Elegant-Puzzle-Systems-Engineering-Management/dp/1732265186)).
Aiming to read/discuss: 

- Chapter 5: All
- Chapter 6: Sections 1, 2, and 3.

MC: @HashNotAdam  
Notes: @mcgain 

See you 12 pm Tuesday, June 1st @ https://blackmill.co/meet

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand.

**Comment by HashNotAdam** [comment]
# Discussion

## Opportunity and membership

@HashNotAdam: The framework Larson proves for creating a positive culture is "an inclusive organisation is one in which individuals have access to opportunity and membership. Opportunity is having access to professional success and development and membership is participating as a version of themselves that they can feel comfortable with".
@JohnTelfer: That is a noble ideal but these statements rarely match reality.
@lachlanhardy: It's also unlikely this encompasses everything needed to foster a positive culture.

@HashNotAdam: The section on membership spent time discussing ways to get people to connect through socialising. Larson advocates for having a range of events that suit different groups. In support of this idea, Adam has seen a failure to vary events whereby the company only does 1 event, an annual Go-Kart day at Phillip Island, and that event is promoted in job ads as a required character trait. Recently, an alternative event, Axe Throwing, has been proposed which really doesn't solve the problem.

@elle: The definition of culture is not just "opportunity and membership". While the definition varies, it would usually include values, beliefs, practices, and norms of the business. A healthy culture is one where people can bring their whole selves to work and not feel like they need to hide behind "masks" and appearances. An inclusive team culture will have opportunities and memberships but social events are not enough to achieve this.
@lachlanhardy: Not only is this not enough to build a positive culture but it also only works at a large scale. Not many of us can have "17 extracurricular events".

## Select project leads

@HashNotAdam: It is stated that to ensure a range of people apply for, and are awarded, project lead roles, we should define a scope and goals, announce the project, nudge people, select your project leader, sponsor that leader, notify those who were not selected, kick off the project, and record. This is stated to be a lot of work but it should be valuable.
@lachlanhardy: It would be good to see how it works in an environment with fewer projects.
@elle: You can't improve until you start keeping track of how you are performing including metrics on diversity at various roles and levels.
@JohnTelfer: Having the process public is the fairest way to do it but it could be challenging for smaller businesses that don't have HR teams that can provide the metrics.
@elle: One element that is missing is a system for mentorship and sponsoring.

## Make your peers your first team

@HashNotAdam: Larson says that the greatest happiness comes from being part of a close team of peers who prioritises themselves above the teams they support. It was particularly challenging to consider how you might explain to the team you support that they need to be deprioritised for the needs of the team peers and how the supported team would take that information.
@lachlanhardy: A managers responsibilities are not just to their team and this makes it explicit. It's common for people (all the way to the C-suite) to have internal conflict but they don't even consider talking to their peers. If leaders are not in alignment, there are serious issues.

## Consider the team you have for senior positions

@HashNotAdam: It is suggested that you should have a process that encourages internal candidates to apply for senior roles but they are to be evaluated equally with external candidates. This goes against recent advice that internal candidates can be better because they already understand the business and culture. It also felt like Larson is proposing that those internal to the business get a more difficult run because you have a greater capacity to validate them.
@lachlanhardy: You couldn't put those requirements on an external candidate. They wouldn't accept being asked, for instance, for a 90-day plan that you could implement without them.
@HashNotAdam: Even the idea that internal candidates could interview external candidates seems bizarre because they couldn't be truly objective.
@JohnTelfer: It seems to be counter to the discussion of being open and transparent.

@HashNotAdam: If you have internal candidates, why are you even looking externally‽ If your internal candidates are not suited, explain to them why and help them with a strategy to become eligible before going external.

## Kill your heroes, stop doing it harder

@elle: We all agree that we shouldn't have heroes but it's problematic when one of those heroes is your founder.

@HashNotAdam: In a previous role because a "hero" simply from being reliable compared to the lead who _thought_ he was a 10x and it's not fun for anyone. Ended up leaving because, while the work was interesting, the environment was not. A learning since becoming a business leader is, when issues are systemic, the hardest task is convincing the rest of management that there is an issue that needs to be addressed.

@elle: Is there a solution to a company of heroes where management doesn't want to address the core issues?
@JohnTelfer: Do nothing and wait for the heroes to burn out and then be prepared to take over once they're gone. It's a management problem; you don't pile work onto the heroes you diversify it and treat all your team members equally and actually give people a fair workload and share the promotional opportunities around. Develop people equally; give PD to everyone; don't just promote white guys who've been there for years.
@JohnTelfer: Larson says "without policy your tool is stepping back and allowing the brokenness to collapse under its own weight. A deeply flawed system can't be solved by band-aids but it _can_ easily absorb your happiness to slightly extend its own viability".
@elle: It needs to come with a change in management mindset, it can't be managed bottom-up.
@HashNotAdam: Can't see how the problem _could_ be solved without management because the book defines a hero as someone being coerced into the role due to systemic issues. After spending over a decade trying to change this behaviour at work, the only reason change has begun is because all directors have felt the pain and agree that change is needed. Leadership showing a united front gives the rest of the business permission to adapt.
