### ISSUE TITLE
Elegant Puzzle: June 8: Chapter 6: Sections 1-4

### ISSUE THREAD

**Issue by elle** [Blackmill/book-club#115]
Current book is An Elegant Puzzle by Will Larson ([Amazon](https://www.amazon.com/Elegant-Puzzle-Systems-Engineering-Management/dp/1732265186)).

Aiming to read/discuss: 

- Chapter 6: Sections 1, 2, 3, 4

MC: @matthewborden 
Notes: @mcgain 

See you 12 pm Tuesday, June 8th @ https://blackmill.co/meet

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand.

**Comment by mcgain** [comment]
# 6.1 Roles over Rocketships

### What is the role of luck in your careers?

Elle says relationships help you make your own luck

Lachlan has never set a career goal, so everything’s luck

Adam says nepotism has guided his. He doesn’t feel exceptional

Richard says he thinks it’s 95% luck, 5% success

Lachlan points out privilege makes a difference

### Matt brings up tenure

What are our experiences of tenure? 

John has done cycles of 7 years, but done multiple roles in each job

He’s suspicious of people who’ve been somewhere less than a year, but also of people who have been at a place for more than 7 years, since he thinks people will lack flexibility

Lachlan says there’s a theory that when you start a job your actual impact is 0, but your eventual impact is huge. Over time the company gets all your knowledge, and you get no new learning from the company. When this happens, you should change teams to help reset some of that.

Matt is curious about the stable era of a company and people’s development during that period. 

Elle has a problem with people who are only after titles, people don’t stay long enough in a place to develop the craft and mastery. 

People change jobs to get more money and better titles, also to get diverse stock options. 

Companies pay huge costs, onboarding, hiring etc. when they lose people, it makes Elle sad that companies don’t invest more in their current employees

### Lachlan wonders if anyone applied the career narrative approach to their own careers?

How do you even explain that to people eloquently? - Matt 

Lachlan says teams are immutable, when you change any element, it’s a whole new team. He saw this at his time at Microsoft, with several different bosses changing the way the team, and he, worked

# 6.2 Running a humane interview process

John has had panel interviews where people have conflicted, a bad sign. On the plus side, he’s had good feedback from the interviewers after the fact

There’s nothing worse than getting to the end of an interview process and finding out they’ve decided they were hiring for the wrong role

The book has a list of things that are important to keep in mind when interviewing. Stuff like “be kind to the candidate”

Lachlan thinks it’s a good list, obvious, but good. Stuff like role descriptions aren’t done often enough

>  I just love this list - Lachlan

Matt takes a general point of give your candidates time to prepare in an interview

### Has anyone had a company express interest? 

A couple of different perspectives. Lachlan has been headhunted, which is gratifying.
Richard deliberately tries to take an interest in the candidate in an interview, his objective is to learn something new from the candidate

John asks if loose, tech interviews are better than govt style interviews with criteria published in advance to prep for

### Matt asks if anyone has been trained to interview people?

Lachlan has trained other people to train people

Richard has had interviewer training, mainly in diversity topics, but also in order to get everyone on the same page with regard to what we’re actually interviewing for. He’s also trained people to take pairing interviews.

Lachlan brings up that the book doesn’t mention that all this process takes up a huge amount of time. Lot’s of unanswered questions around the amount of effort this takes.

John says there’s lots of legal issues with crappy processes, you need to be able to defend yourself if you get sued for this. 

Elle adds that rubrics are super important to give candidates a level playing field. 

The BeApplied interview process is pretty cool, they focus on mitigating bias

Elle judges companies on the hiring software they use

# 6.3 Cold Sourcing

Matt questions his cold sourcing advice. He tried it on LinkedIn and it only selected people in his circles. Pretty useless

*General noises of agreement*

Adam doesn’t have big company clout, so finds hiring really hard. He’s thinking of trying LinkedIn, in the past he’s mostly got people from meetups. Adam assumes he doesn’t see the good people is because there working in other companies. 

Lachlan has done a lot of hiring over the years. He once found a super diverse company and tried to poach as many people as possible from it.
