### ISSUE TITLE
Elegant Puzzle: June 15: sections 6.4-7.1

### ISSUE THREAD

**Issue by elle** [Blackmill/book-club#117]
Current book is An Elegant Puzzle by Will Larson ([Amazon](https://www.amazon.com/Elegant-Puzzle-Systems-Engineering-Management/dp/1732265186)).

Aiming to read/discuss: 

- Sections 6.4 up and including 7.1

MC: @elle 
Notes: @matthewborden 

See you 12 pm Tuesday, June 15th @ https://blackmill.co/meet

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand.

**Comment by elle** [comment]
## 6.4 Hiring funnel

- Identify candidates
  - Inbound
  - Sourced
  - Referrals
- Motivating them to apply
  - Spend time
  - Clearly define the role
- Evaluating
  - Certainty of success
  - Candidate experience
  - Efficiency - to reduce team investment time in hiring processes
- Closing

Metrics!

Extend the funnel to include:

- Onboarding - how long to become productive?
- Impact - performance rating?
- Promotion - how long to first promotion?
- Retention - are they sticking around?

Tricky to define useful metrics...

## 6.5 Performance management

> If you want to shape your company’s culture, inclusion, or performance, this is your most valuable entry point.

- Career ladders - levels, guide for self-reflection and in coaching
- Performance designations - "explicit statement of how an individual is performing against the expectations of their career ladder at their current level over a particular period of time."
  - Reviews?
  - 360 reviews of self, peers, managers, reports
  - Calibration system - with consistency as a goal. Compare against the ladder, not others, review distribution
- Performance cycles - how often?

## 6.6 Career levels, designation momentum, level splits

> Designation momentum. This is the term for the natural tendency of a performance process to consistently produce the same evaluations for the same people despite changes in performance.

- Level expansion

> If a company is experiencing particularly frequent level expansion, it is usually a sign that progression, compensation, or recognition has been overly tied to your level system, and you should identify mechanisms to reduce pressure on leveling.

- Level drift
- Career level clustering
- Time at level limits
- Crisis designations: or retention-driven designations

## 6.7 Creating specialised roles

> If you can’t find a sponsor, it’s usually important feedback that leadership doesn’t believe the new role will have a good return on invested energy.


## 6.8 Designing an interview loop

Does not:

- Reference how career ladders guide role requirements
- Sitting down with the team to define gaps
- How to address diversity gaps


## Book as a whole

1. Introduction
1. Organisations
1. Tools
1. Approaches
1. Cultures
1. Careers

**Comment by matthewborden** [comment]
## 6.4 Hiring funnel

Metrics in the hiring process
- Identified that setting up a system to instrument the hiring process can be really useful to understanding the outcomes of the process. However, even companies with the metrics fail to feed the results back into the hiring process and improve upon it.
- The book refers to A/B testing within the hiring process, however, this can be difficult without the scale that the author is operating in (Eg, difficult to A/B test with high-quality signal in a small business)

Motivating candidates to apply
- Selling candidates on the mission and alignment of the role

Hiring to fit the requirements of the role
- Hiring across multiple skill sets (identifying the core competencies of a successful applicant and defining this within a rubric)
-  How can change be achieved in respect to hiring someone different to the rest of the company (in skill set and background)?
    - Training for managers
    - Change is driven by identifying the requirements of the role and looking for someone to fill the holes (weakness and missing capabilities within the team)
     - When people talk about “Lowering the bar, in relation to hiring” - Those people don’t have a bar, or it’s unrelated to the role.
    - Using rubrics and job scorecards can remove bias from the interview process.
     - Setting salary guidelines for each role, and each level (to prevent underpaying or overpaying)
- How long does it take people to get promoted? - This is a lagging metric and in a small company, this isn’t as applicable.

## 6.5. Career levels
Career levels can help with inclusion (because they are an objective measure of performance)
Standardized answer to “How to get promoted?”

Performance designation?

- "Explicit statement of how the individual is performing against the career ladder."
- 360 reviews
    - These can be a very long process but can yield useful feedback from many different perspectives.
    - Elle mentions reading a recent paper about leadership styles, which used 360 reviews to effectively measure emotional intelligence.
     - Feedback needs to be fast and delivered with recency, this makes 360 reviews a poor tool because of the lag in delivery of the feedback.
     - 360 reviews can put the burden on the team rather than on the manager. 
- Asking “May I give you some feedback, now?”
     - This approach requires a culture of trust to deliver feedback frequently.
    - Constructive feedback is delivered immediately and it makes you aware of the problem so that you can deal with it and move on. This leaves performance reviews to be more positive so that they put the emphasis on behaviours that your colleagues or manager encourage.
   - The two different systems can work well together (360 performance review and frequent feedback)
   - The “Fallacy of feedback”
       - Beware of adopting the attitude of “I know how to work better than this person”
       - Building upon positive feedback, praise the person when they do the behaviour you want rather than providing constructive feedback.
- “What do you do at your work for your reviews?”
         - Annual reviews
         - Self-reflections
         - 360 requires honest feedback (feedback on what’s wrong requires trust)
         - 360 reviews can shake things up when done anonymously

Calibration systems
- The calibration process should be transparent and launch a conversation about performance.
- Reports should have an understanding of their progression within the career ladder.
- Example: Army has the concept of time at level
      - Kick out people who don’t reach a certain level within a certain time frame.
      - Spending too much time at particular levels means you are unable to progress at all.

## 6.7 Skipped - Creating specialized roles

## 6.8 Designing an interview loop
The chapter does not:
- Reference how career ladders guide role requirements
- Sit down with the team to define gaps in capabilities
- Talk about diversity gaps in designing an interview loop

Generally good advice in this chapter but difficult to implement without a lot of data, which is primarily only going to be available at bigger companies.
- Lachlan liked the idea of using two people with a fast iteration cycle for designing the hiring process, instead of a committee.

“Don’t hire for potential. Hiring for potential is a major vector for bias”
- Hiring for potential more useful for junior roles (where no track record or relevant experience)
- “Potential” has many different meanings to different people, and this can lead to subjectivity and hiring for characteristics similar to the hiring manager (or interviewers).
- An alternative for hiring for potential is to hire for:
    - Have they demonstrated grit?
    - Have they demonstrated they can learn?
    - Are their values aligned with your organization's values?
    - Can they show gratitude rather than ego?
- We don’t like the term “culture fit”
    - A better alternative is to ask:
        - Do they care about the purpose of the organization?
        - Do they agree with the mission?
        - Do they believe in the values of the organization?

**Comment by elle** [comment]
Great notes. Thank you @matthewborden
