### ISSUE TITLE
Feminist City, June 29 - Chapter One

### ISSUE THREAD

**Issue by pat** [Blackmill/book-club#118]
We're continuing to read through Feminist City ([Readings](https://www.readings.com.au/products/31682297/feminist-city), [Bookshop](https://bookshop.org/books/feminist-city-claiming-space-in-a-man-made-world/9781788739818), [Amazon](https://www.amazon.com/gp/product/B07ZY6LYLF/)). After covering the introduction on June 22nd, we're now getting stuck into __Chapter One: City of Moms__ for our next session.

MC: @pat
Notes: @lachlanhardy

See you all at 12pm AEST, June 29th @ https://blackmill.co/meet

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via gday@blackmill.co.

**Comment by lachlanhardy** [comment]
# Chapter 1: City of Moms

This first chapter seems like a rant, mostly about men being shit rather than cities being shit. Nothing wrong with that but not sure if that's a different book. Like how can we change a city to stop people rubbing your pregnant belly or giving you advice?

It is very academic in terms of terminology and references but not in approach. It feels like personal opinion that has references rather than a structured academic argument.

The London Underground was opened in the 1860s so it is no wonder that it's not built for modern life. The author mentions that only 51 stations are accessible, but her reference is an article from 2014. By 2017 it was up to at least 70+ and is now higher. This book was published in 2019.

We had a conversation about gender mainstreaming and its general lack of intersectionality. Cambridge, UK, is a very bike-centric town. Lovely experience to ride with so many other people also doing that. Except it is much harder for people with certain disabilities as there is little car parking in the city centre.

The car conversation continued with suburbs, which effectively require a car. Suburbs tend to be insular, isolating places. When you're home, why leave? We talked about conurbations, and transport models.

What does the author mean by suburbia? Box Hill, Dandenong, Frankston were all their own towns before joining the conurbation of Melbourne. We don't think those are quite what she means. More like Mill Park or Deer Park or further out. Places that aren't on train lines or well serviced by public transport.

This lead to a discussion around property usage, empty nesters, investment properties, and housing crises.

To change any of this for the better requires changing how we value people.
