### ISSUE TITLE
Feminist City - July 6th: Chapter Two

### ISSUE THREAD

**Issue by lachlanhardy** [Blackmill/book-club#119]
We're continuing to read through Feminist City ([Readings](https://www.readings.com.au/products/31682297/feminist-city), [Bookshop](https://bookshop.org/books/feminist-city-claiming-space-in-a-man-made-world/9781788739818), [Amazon](https://www.amazon.com/gp/product/B07ZY6LYLF/)). We're now up to __Chapter Two: City of Friends__ for our next session.

MC: @HashNotAdam 
Notes: @pat

See you all at 12pm AEST, July 6th @ https://blackmill.co/meet

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via gday@blackmill.co.

**Comment by pat** [comment]
Some notes from today's session - though there was so much nuance and tangents that I didn't write down.

* Wishing we had perspectives of more women in our discussions, though Elle has many notes.
* Hadn’t realised how important/special Sex and the City was at the time. Can see parallels with how Schitt’s Creek depicts gay men.
* City of Mom (Chapter One) reflections: wasn’t expecting the focus on policies rather than infrastructure/architecture. There’s a lot of talk about what is *not* a feminist city - defining the absence of things.
* Could be more examples of women’s friendships beyond young single women?
* Another reference to suburbs in this chapter, how they are not designed for making new friendships more easily.
* Not convinced about cities being prime places to find friendships - cities can be lonely, unless you’re particularly proactive.
* The challenges of establishing friendships when moving to a new city - and most cities are like this, New York is an exception because of so many people moving in and out.
* With regards to lesbian-friendly neighbourhoods, the paper referenced with regards to Montreal doesn’t match Richard’s experiences in that same neighbourhood, and he doesn’t see causation between what’s in these neighbourhoods and what makes a lesbian-friendly neighbourhood.
* Elle: wonders why the focus on queer women got subsumed into this chapter, when it could have been its own chapter.
* Struggling with the stories of the author's world, and would prefer to hear about the world more generally (less story).
* Is this book more useful for building a further reading list?
* The author’s reflections of her childhood are a little rose-tinted, the dangers are played down.
* The city can give you anonymity, which means you can be less accountable (much like the Internet).
* Growing awareness around women’s safety in cities, in relation to our own actions, travel at night, etc.
* Appreciated the point about how public spaces are actually private for girls, because their normally private spaces are when they’re policed (by parents, patriarchy, etc). Hanging out in a mall is far less about shopping and more about freedom.
* Are the distinctions in city structures, etc - is it more between masculine vs feminine, or between sporty vs not? Some reflections of the book rang true beyond the gender. The book doesn’t delve into this but should?
* Can there be changes to cities that help women, but if you can frame it in how it can help men (by countering toxic masculinity), then it’s maybe more likely to happen?
* A few hints towards solutions in the chapter - ie. seating, privacy.
* Safe spaces for those discriminated against versus men’s clubs. The particular problem is autonomous power.
* The rape culture of single-gender schools, and how that flows through to those in power.
* The depiction of male friendships in the book is perhaps limited, isn’t a reflection of the full variety of what male friendships can be.
