### ISSUE TITLE
Unlearn: August 31: chapters 9 + 10

### ISSUE THREAD

**Issue by elle** [Blackmill/book-club#127]
Unlearn by Barry O'Reilly ([Readings](https://www.readings.com.au/products/25863080/unlearn-let-go-of-past-success-to-achieve-extraordinary-results), [Bookshop](https://bookshop.org/books/unlearn-let-go-of-past-success-to-achieve-extraordinary-results/9781260143010), [Amazon](https://www.amazon.com/Unlearn-Success-Achieve-Extraordinary-Results-ebook/dp/B07HYBYBW7)).

Aiming to read:
- Chapter 9: unlearning  with people and organisations
- Chapter 10: unlearning incentives

MC:  @elle 
Notes: @lachlanhardy 

See you all at 12pm AEST, Aug 31st @ https://blackmill.co/meet

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via gday@blackmill.co.

**Comment by elle** [comment]
## 9: unlearning with people and organisations

> When work becomes routine and guards are let down, complacency sneaks in and performance suffers. That’s exactly when the level of concern should be raised.
 
- Silos are bad!
- Pyramid of advantage or catastrophe model
  - medical industry: predisposing factors to error, near misses, accidents, and accidents that harm the patient. The typical threshold reporting in health care was between near misses and accidents.
- deviant behaviour - normalising bad behaviour - broken window
- chaos monkey

> People do not change their mental model of the world by speaking about it; they need to experience the change to believe, see, and feel it.

#### Key components to relearning systems of learning

1. Understand the system by gathering data
1. Identify the competencies for success
1. Design the work
1. Think big but start small
1. Make the new behaviour really easy to do
1. Make opportunities to try the new behaviour
1. Test it by real people
1. Constantly stimulate the system of learning to avoid complacency
1. System is adopted and people stay "agile"

> This can be as small and easy to do as asking others in your organization what the most helpful mistake is that they recently made. How did it help them make a new discovery to improve what they were working on?

#### Informal learning by Victoria Marsick and Marie Volpe

- Integrated with daily routines
- Internal or external jolt
- Highly conscious
- Influenced by chance
- Inductive process of reflection and action
- Linked to learning of others

#### Dimensions of the learning organisation questionnaire (DLOQ)
- Original 43 questions
- Marsick and Watkins: 21 questions

**Comment by lachlanhardy** [comment]
# chapter 9

His NASA example seems poor as he’s talking about unlearning on an organisational level while providing examples that indicate a lot of people in the organisation were concerned about issues but management was ignoring them.

He also seemed to be implying that orgs need periodic catastrophic failures in order to trigger unlearning. Seems super callous when those failures are people’s deaths.

# chapter 10

How does one trigger the unlearning? How do we predictably get people to recognise that new options might be more valuable than the same old patterns?

Are we reinforcing bad behaviours by the metrics we use to measure the different groups? Does giving Sales particular goals separate and isolate them from the goals of the Product group?

We spent a bunch of time talking about gaming metrics and whether that's the point.
