### ISSUE TITLE
Australia's second chance: 21st: ch 3 + 4

### ISSUE THREAD

**Issue by elle** [Blackmill/book-club#130]
Australia's second chance by George Megalogenis ([Readings](https://www.readings.com.au/products/23737378/australias-second-chance-what-our-history-tells-us-about-our-future), [Bookshop](https://bookshop.org/books/australia-s-second-chance/9780143783640), [Amazon](https://www.amazon.com/Australias-Second-Chance-history-future-ebook/dp/B012NU15Y4/)).

Aiming to read:

- Chapter 3: the beginning of diversity
- Chapter 4: cracking the code

MC:  @HashNotAdam 
Notes: @saramic

See you all at 12pm AEST, Sep 21st @ https://blackmill.co/meet

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via gday@blackmill.co.

**Comment by saramic** [comment]
### Tue 21 Sep 2021 - ch 3 & 4

pre-book club banter
- @HashNotAdam is not in the car doing carpool karaoke but he does have a synthesiser and guitar in the room
- @HashNotAdam has a package in the office but no energy to go in
- @pat has prioritised work over book club
- Nick can't make it either
- Sugendran - "feels weak post-work incident" @lachlanhardy
- John - seems to be less available since childcare has been shut - but he did make it in the end

Discussion start
- "any strong feels?" @lachlanhardy
- @HashNotAdam fast-forwarded the book to see when we reach the current century and reported we need to read 80% before we get to 2001
- @HashNotAdam  "don't really care about history"
- @elle  "getting a great history lesson"
- @lachlanhardy "view of history is changing a lot"

- @HashNotAdam took the discussion to why even have a penal colony? why do we punish criminals? is it to make them feel worse? or those that are hurt feel better? - in this case in relation to the fact the being sent to Australia seemed to often not be as bad as the people back in England imagined

- @mcgain turned toe discussion to "do we want economic growth?" - if the only answer is mass migration do we want it?

- [degrowth](https://en.wikipedia.org/wiki/Degrowth) - people are questioning that growth is what we want at all times? that continual growth is the underpinning of our society but what if earth can't sustain that?

- if we are to continue with mass migration - what comes first? the migrants or infrastructure to support them? historically have we planned our infrastructure well?

- if the aim should be happiness over economic prosperity? how could we measure happiness? is migration good for that? were the First Nations People prosperous and happy with NO migration? what about global happiness? migration may lead to better happiness globally?

- migration is always better for the economy - in particular, Australia which requires migration for economic growth

- the book mentions a lot of "miscommunication" between England and the Colony. It was clear that the Colony needed to be smarter and diverged from what the "mother ship" wanted. A lot of the class divisions that were in the UK were not brought across.

- What happened in the United States was very different as well - https://www.history.com/topics/colonial-america/mayflower

- how did they expect to develop - given the contentious importing of women

- outside of the book a story of "an arsonist ancestor got shipped to Norfolk Island" - the original location of the penal colony but not really mentioned in the book
- later got shipped to Van Dimens land - where the prison was better than Norfolk and it had women
- the convict got married in prison. This also seemed a way out of prison. Not sure why but they could get married in the first place.
- marriage led to having separate quarters in the prison for the newlyweds
- getting married gave them some extra benefits
- they had 6 kids in 5 years after which the mother died and the "arsonist convict" raised all 6 and they all made it to be adults.
- the first few kids were in prison but at some stage, they did their time and were free to go

- one of the policies was to not have migrants with more than 3 kids? why?
- the women arriving were picked prior to being sent over and were expected to marry within 2 months, really? hard for us to relate

- we brought in a short discussion of the mention of the first night being an orgy - although there is this article suggesting ["the myth of Sydney's foundational orgy"](https://dictionaryofsydney.org/entry/the_myth_of_sydneys_foundational_orgy)

- it is hard for us to understand and adjust to what live would have been like back then in terms of violence, marriage, etc
- for example the large loss of people in Ireland and the UK in general. As well as the large loss of Irish due to the potatoes famine
- how does this compare to the slaughter of Aborigines from some 1 million originally down to 250,000 in the first few 10's of years?

- mid 19th century Melbourne was defined the richest metropolis in the world, on what criteria? how was this measured?

- the "corn laws" may have changed things https://voxeu.org/article/quantitative-assessment-repeal-corn-laws - a sort of minimum wage - could create artificial boom
- sheep more valuable for food over wool at some stage
- farmeres were raking it in
- interesting to follow wool price over time, there seem to have been even recent booms prior to "maybe synthetic materials like nylon taking over?"
- grazier used to be synonymous with wealth
- without any actual figures @lachlanhardy says graziers had heaps of money even 40 years ago

- discussion of land splitting to all heirs of a family caused "strip farming" in countries like Russia which were then not as easy to commercialise with modern farming equipment and scale

- Melbourne squatters got large plots of land - economically exploit

- massacre map https://c21ch.newcastle.edu.au/colonialmassacres/map.php

- how many wars have been backed by [Terra nullius](https://en.wikipedia.org/wiki/Terra_nullius) means "nobody's land"

All in all we seem to be enjoying the book and the interesting history lesson - very different from what most of us learnt at school circa 80's
