### ISSUE TITLE
Australia's Second Chance: Chapters 13 & 14

### ISSUE THREAD

**Issue by lachlanhardy** [Blackmill/book-club#135]
Australia's second chance by George Megalogenis ([Readings](https://www.readings.com.au/products/23737378/australias-second-chance-what-our-history-tells-us-about-our-future), [Bookshop](https://bookshop.org/books/australia-s-second-chance/9780143783640), [Amazon](https://www.amazon.com/Australias-Second-Chance-history-future-ebook/dp/B012NU15Y4/)).

Aiming to read:

* Chapter 13: Wartime and Our Migrant Self
* Chapter 14: Return to Melbourne: The Postwar Waves

MC: @elle
Notes: @HashNotAdam

See you all at 5pm AEST, Nov 2nd @ https://blackmill.co/meet

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via gday@blackmill.co.

**Comment by elle** [comment]
In the inner-city suburb of Carlton, where the Italian wave was most concentrated, real house prices, after adjusting for inflation, would not return to their late 1880s levels until the early 1980s.

**Comment by HashNotAdam** [comment]
# Discussion

These chapters lead to a lot of general discussion about Australia with minimal direct connection to the text.

@elle: Hasn't been enjoying the book; it's like reading a history, rather than economics, lesson.
@mcgain: A history lesson isn't necessarily a bad thing but he doesn't supply evidence for the point so we get history without the elements that could change our minds.
@elle: Assumed the title, Australia's Second Chance, meant we would look at Australia's failings and then consider how we could do better but we are in part 3 and are still analysing 80 years ago.

@lachlanhardy: Megalogenis is not an academic writing history for the purpose of educating; this is intended to be a position for debate but most of our conversations are wondering where the author is trying to lead us and when will he deliver on an argument.

@mcgain: Something that stood out was migration to Melbourne after WWII. One reason was Melbourne was Australia's manufacturing base and the other was house prices were lower after a crash ("Collingwood was a slum"). These factors brought immigration back into focus in Melbourne. Would like to have learnt more about this.

> In the inner-city suburb of Carlton, where the Italian wave was most concentrated, real house prices, after adjusting for inflation, would not return to their late 1880s levels until the early 1980s.

Illustrates how well off 1880s Melbourne was and interesting how long it took to recover and how house prices have "gone crazy" in the last few decades.
