### ISSUE TITLE
Make It Stick: Dec 7: Chapters 2 & 3

### ISSUE THREAD

**Issue by lachlanhardy** [Blackmill/book-club#139]
Make it Stick by Brown, Roediger, and McDaniel ([Readings](https://www.readings.com.au/products/17781177/make-it-stick-the-science-of-successful-learning), [Bookshop](https://bookshop.org/books/make-it-stick-the-science-of-successful-learning/9780674729018), [Amazon](https://www.amazon.com/Make-Stick-Peter-C-Brown-ebook/dp/B00JQ3FN7M/)).

Aiming to read:

* Chapter 2
* Chapter 3

MC: @HashNotAdam  
Notes: @mcgain 

See you all at 5pm AEST, Dec 7th @ https://blackmill.co/meet

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via gday@blackmill.co.

**Comment by mcgain** [comment]
Notes

Chapters 2 & 3

Is this going to be another one of those “should have been a blog post” books? 

The chapter was interesting, according to Nick and Adam, but we probably could have skipped this?	

## Reflection is a form of Practice

A surgeon knew from experience that he had to use a special method the surgeon invented to save a patient’s life. Adam was really scared by this. Do we just have to get lucky and get the surgeon who has done this before?

Nick didn’t find this example gripping to begin with, but later on, he thought it was good. When the book talks about how the surgeon thinks about what he was going to do in the coming surgery, and reflected on a previous surgery, it was good. 

Adam saw echos of pre-retros and retros in these stories. We already do these things in our world.

We talked a bit about retrospectives. The consensus was that when they’re good, they’re good, but unless done properly, they can be a waste of time. Frequent retros are good, according to Elle. 

Elle says context is really important in memory. When she’s visiting a place, she can recall people she’s met there more easily. 

Nick points out we’re going to be going over the same ground over and over again. We will talk freely about topics, but the book will cover them over many chapters. 

Adam notes that he doesn’t take notes on these books, so how is he going to remember this stuff? Does anyone actively try to remember this stuff?

Elle highlights and then adds self reflection. Sometimes she re-words the highlights into her own words. Kirsten takes notes too, but hand writes them, which she thinks will improve retention. 

*General nodding*

Richard plans to present on all the stuff he’s learned, to force him to review this all the books in this book club so far.

This book has brought out OG Adam. He’s been doing additional research. He’s noticed that the research referenced is significantly less confident in its wording. The book has to be definitive and strongly worded to get the message across.  

Elle learned how to solve a rubix cube recently, but rote learned it without understanding. I see echoes of our criticism of Execute Program last week.

Adam criticises the book for focusing only on exact recall, it hasn’t talked about how this stuff can aid creative processes. 

Nick says that the last two chapters have been about the same thing. Reading something, then retrieving that information later. This book club might just be the ultimate way to learn!

Kirsten tried a technique recently. She made a mind palace kind of thing to remember a garment exhibit and it worked better than taking photos of the exhibits.

Adam wonders how is it that adding extra quizzes really transforms C students to A students. Also, what if all those students are placed back on a bell curve. That’d suck

Elle really liked the story about the university lecturer who failed at adding unscheduled tests into his curriculum, but adding scheduled tests worked really well.  

Elle teaches and they go through books together. She’ll have memorised 

Lachlan reports on a recent podcast with Seth Godin. Half the western world regained their commuting time recently. What did we do with it? Watch more tv? This got him thinking about what we do with our time. Do we want to spend our time re-reading educational books.

Kirsten talked about spending her free time listening to more podcasts and books. But she’s learned that slack time is super important. Doh! Many of us have experienced stimulus overload on a continuous basis. It’s difficult to cut off. We’ve all experienced this, but when we’re depressed, the last thing we want to do is to listen to our own thoughts.

Richard asked how to be “calm” and stop over stimulating, when you’re over stimulating to avoid your own thoughts. Elle talks about “island life” as a solution to this. People learn to slow down pretty quickly. Counselling can also help, because it forces you to reflect. Silent retreats, just going away for the weekend, living alone and just sitting down and doing nothing all come up. 

People don’t know how to not be busy. Our society values business, but that’s not good, Elle says. Moving out of the city will help too.

“There’s no word for busy in French” - Adam

Grief has a big impact on these kinds of things too

How is this related to the book? Dunno, it seemed related at some point?

Lachlan ties it all together. Learning is how we grow. When we get “busy” then we get frozen and can’t progress. In order to learn, we have to have that extra slack time. After 12 years of business, Adam is happy to be out of scrambling startup mode and has more time now.

Richard says he has a problem, where if things are going well, he has to accelerate and push harder. This doesn’t work well and it causes other people stress. It’s a problem he hasn’t solved yet. Elle replies that if you don’t stop and reflect, it can really exacerbate impostor syndrome. 

Lachlan doesn’t have an answer to this. Adam says he’s got such a huge backlog that none of it matters, accelerating isn’t even remotely possible because the mountain of work is so huge.
