### ISSUE TITLE
Make It Stick: Jan 18: Chapter 6

### ISSUE THREAD

**Issue by nickspragg** [Blackmill/book-club#142]
# Make it Stick by Brown, Roediger, and McDaniel (Readings, Bookshop, Amazon).

Aiming to read:

Chapter 6 - Get Beyond Learning Styles
MC: @kcomandich
Notes: @mcgain 

See you all at 5pm AEST, Jan 18th @ https://blackmill.co/meet

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via gday@blackmill.co.

**Comment by mcgain** [comment]
### Notes for chapter 6

### General feelings about the chapter

Josh felt the chapter was hard to get in to initially, because that first example was way too long. Richard gesticulated wildly in agreement. Elle and Nick agreed. 
> “Why was it such a long story?” 

>“Longwinded and unhelpful!”

Does anyone know their learning style? Asks Kirsten
Elle has believed in learning styles in the past, but felt learning appropriately to the topic was more important

Nick talked extra details. Ironic he found, given the rambling story at the start of the chapter.

### Learning Styles

Josh criticised the chapter’s criticism of learning styles, while presenting a bunch of other learning styles.

Nick asks if we could figure out what learning style Bruce had from the initial story. No one could tell. 

The bit immediately after the story Nick added, focused on how people see themselves affects performance. Despite some contradictions in the idea, Kirsten reckoned the gist of it was fine. It’s not that you think you can do the thing, it’s that you could potentially do it.

Elle said it’s a good lead chapter, this chapter and the previous one should have come first! Perhaps “Chapter 8: Make it Stick” will tie everything together?

### On Dynamic Testing, example vs rule based learning and structure building

Kirsten asked if anyone had done Dynamic Testing before?
 No one seems to have, nor do we seem to know whether we’re example or rule based. Josh likes examples. Richard says he’s both, when he’s missing a rule, he wants one, but when missing an example, he wants and example.

On High vs Low Structure Building, Nick is definitely a structure building person, but he wonders if this ties in to last week’s Rubik’s cube discussion. Lachlan says he goes slower now, to develop an understanding of the underlying concepts. 

### Successful Dropouts

Nick wondered what people thought of the examples of “successful dropouts”. Lachlan wants less focus on old predatory white men. Nick reckons these people probably had more support structures than most people. It’s the old self made man (with a startup fund from mum and dad)” schtick. 

Josh got in trouble at work for insinuating that luck plays a part in success.

People who associate intelligence with success reinforce their beliefs continually. They’ve lived particularly sheltered lives. If they go work at google and are surrounded by other intelligent people and see their success, reinforcing the loop.

Kirsten pointed out the study of Kenyans who’s families value indigenous knowledge vs academic knowledge. It’s all about the values surrounding the child. That said, Ballet is classist bullshit, but if the kid wants to do it, despite all your values to the contrary, what are you going to do?

Richard said his IQ is 82, but Nick didn’t believe him. Lachlan did heaps of IQ tests as a kid, and in the Army, but he never got told the result. 

### Fluid vs Crystallised Intelligence

Crystallised is the world knowledge you’ve built up from experience, whereas fluid knowledge is how you react in the moment to new ideas and stimuli. This reminded Kirsten of the difference between being intelligent and intellectual. You can be one, but not the other. For example, Nick’s father has loads of science knowledge about food, but can’t cook. 

There are other classified intelligences, like kinaesthetic intelligence, but there’s no particular evidence for it. This seems really weird to Lachlan, why isn’t there enough evidence for learning styles?

This is a bit like the Milgrim (Stanford Prison) experiments, we won’t do these experiments again, but we’ll keep using the flawed results. 

### Takeaways

The takeaways were great. Richard found good stuff in the summary, but couldn’t find those points expanded in the actual chapter. 

Elle liked the Analytical, Practical, and OTHER intelligence model. It’s more supported by research. 

Nick listened and read this week. Kirsten and Josh both only listened to audio. Kirsten took notes and has found skimming them aids recall. Richard commented that this is a mid-tier learning tool, according to previous chapters. Not as good as testing, but better than simple re-reading. Richard finds testing too hard to generate, so can’t be bothered. Lachlan pointed out that the difficulty is a good thing. Preparing the tests are a valuable learning method. 

We talked flash cards for a while. Anki was mentioned.

### Final Thoughts

Josh pointed out that we haven’t talked about focusing on your weaknesses rather than strengths. He’s had the opposite advice. 

Nick is annoyed that this book so far hasn’t addressed motivation. Bah! Nick wonders if the book assumes that if you’re reading it, you’re already motivated. Lachlan admitted to being a capitalist pig, who only cares about money. He doesn’t spend a lot of time introspecting about his higher purpose in life, just living and working on self-sufficiency is plenty.

Lachlan pointed out Steven Levitt interviewing Angela Duckworth on the No Stupid Questions podcast. Duckworth wrote Grit, there are grit score calculators on the website. Levitt calls Duckworth on this, claiming this test is probably bullshit, an interesting discussion is had. What do you do if you can’t do your life’s passion any more? Do you find something different to focus on? This is a trait of people, they’re like this for reasons. It’s not motivation, but it leads to it. Elle has also listened to a podcast about a little girl who becomes an amazing violinist. She strains her fingers and couldn’t practice any more, and got tutoring while she was injured, but eventually realised she couldn’t fiddle any more, so switched her career and focused on something else with all her energy.

Peter Singer only keeps 30% of his income and donates the rest. Effective Altruism is a whole thing. Nick thinks that shouldn’t be a thing. That’s what taxes and governments are for.
