### ISSUE TITLE
Make It Stick: Feb 1: Chapter 7

### ISSUE THREAD

**Issue by mcgain** [Blackmill/book-club#143]
### Make it Stick by Brown, Roediger, and McDaniel (Readings, Bookshop, Amazon).

Aiming to read:

Chapter 7 - Increase Your Abilities
MC: Josh
Notes: @kcomandich

See you all at 5pm AEST, Feb 1st @ https://blackmill.co/meet

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via gday@blackmill.co.

**Comment by kcomandich** [comment]
(Josh) Marshmallow experiment - it’s part of the replication crisis discussion
- early studies didn’t control certain factors
- pulling from childcare at Stanford is not representative of the general public’s socioeconomic conditions
- People who are privileged and have more support tend to do better

Otherwise, the other examples in the chapter are pretty fascinating though. For example “training the tongue to see”

(Adam) The brain isn’t a muscle - if you train one part, it doesn’t make other parts stronger.

(Richard) Neuroplasticity - is reassuring. There is some possibility to change our brains.

(Tom) IQ is less genetic than you might think.
Even having a feeling of greater mental capacity [can help you]
The dilemma doctors face with placebos - you feel like you’re better but it’s not it.

(Nick) Overestimating your ability tends to make you perform worse ‘cos you don’t put in the effort

(Josh) A lot of hope that you can change things later in life (vs. things being set from a young age)

(Tom) Twin studies - show it is about brain structure.
Genetics - natural inclination to do certain things but not hard wired.

(Elle) 30,000 (300,000?) words project
The more words you introduce - higher chances vocab, etc, skills will be better.

(Elle) For me it felt like 3 or 4 chapters in one.
Carol Dweck - Growth Mindset. Elle listened to a podcast that criticised the marshmallow experiment.
Theory - modern children don’t have the same willpower, concentration. Turns out modern children could resist the marshmallow for longer. 

(Lachlan) Marshmallows are way less cool now. They might have had a bag of skittles for lunch.

(Nick) The way we bring up kids is different now. We’re teaching them a different set of life skills, earlier. Has a bigger impact.

(Elle) How comfortable kids are with screens & computers.
Liked the chapter because there were less stories/anecdotes. Could have talked more about deliberate practice - didn’t mention failing and learning from mistakes.
Mnemonic Castles - more for recalling than understanding, so is it for real learning?

(Josh) Useful for keeping a plan (in a memory palace).

(Richard) suggests using physical places for memory palaces.
- Wonder if it’s more effective for him - when he’s tried palaces before it hasn’t worked.
- Memory & story telling - in a previous book from book club.
- Indigenous Australians use this a lot.
- There’s a theory that Stonehenge could be used for that.
- He’d constructed an imaginary palace he hadn’t been in before - that didn’t work.

(Lachlan) Miles Cameron - The Red Knight, Arthurian Cycle Tale
- https://christiancameronauthor.com/book-author/miles-cameron/
- a reenactor in Canada, has memory palaces as the magic system in the novels
- the people who have palaces in the books imagine a place that is important to them - for example a nun having the garden in the abbey.
- another character has a learning hall with the goddess Athena in the middle - different doors for different types of knowledge

(Richard) Do you change which thing you want to recall (at the same place in the palace)?

(Lachlan) You’d have to have a taxonomy for it. 
How do you cope when the model of the data turns out to be wrong? How to extend to account for new stuff you’ve learned?
Need a system that can grow & extend

(Richard) I’d confuse myself by doing what the numbers guy does
(Josh) Numbers guy - found it fascinating. Don’t memorise just the image, also they have sounds.

(Nick) I think all these techniques are a brilliant demonstration of things in Ch. 1-3 - spaced practice, variable practice. These things are great for retrieval before you actually master the material. 
How do you get to master? Not covered in this chapter.

(Elle) Is his objective more “make it stick” rather than mastery?

(Nick) There are different ways to learn.

(Adam) He did say you have to do the mastery part first, then this is for retrieval

(Josh) It’s confusing because at the end he suggests these are useful on your way to mastery.

(Elle) As a developer it’s more useful to have an index in a database of developer knowledge rather than the info itself.
- Read a book when younger on memory castles - used a castle one time when doing a presentation - constructed a story with 20 items. Remembered 17 out of the 20. Her school did a memory score. Then she promptly forgot the tricks.

(Tom) Story is not visual or spatial.

(Josh) Mark Twain’s sketches to help him remember, and his kids putting posts in the ground to associate things, to help with practicing retrieval

(Richard) Wished they’d talked about the kind of learning that was used at that time. Peg? method?

(Josh) It’s hard to pin down which are the more important techniques.

(Nick) Do we think any of these techniques could be used for physical activity?

(Josh) Definitely heard of the visualisation side of things - visualises what you’re going to do before you do it.

(Tom) Seems like an awkward transition - walk through a mind palace while dancing? - seems like an awkward way.

(Nick) Lachlan & Elle learning the Rubix cube - learning patterns. There are actions - physical actions. Driving - mental cues from stuff we see.

(Kirsten) “Where Are Your Keys” aka “Language Hunters” - Game for learning languages using gestures.
https://www.languagehunters.org/
https://whereareyourkeys.org/

(Elle) Learning bike riding - need to practice them or you’ll forget. You don’t need to do the full process to acquire them again, but need a refresher.
Like phone numbers - only ones remembered are the ones used on a regular basis.

(Josh) The neuroscience in the chapter is fascinating. 
Power of Habit book - also has interesting examples of people who lose their use of their memory but still had habits that helped them. Neuroplasticity is fascinating. 

(Nick) Still unsure about the book. Thinking the book is about mastering knowledge. Well these are valid techniques for memorisation. Memory athletes - wonders if they’ve lost some ability to learn & master in a sense of truly understanding what they’ve learned.

(Richard) [The book has] Multiple techniques for passing exams but?

(Lachlan) Definition of learning seems to be academia - if I don’t care about academia - how to use it in career & personal life?

(Richard) Terrible at remembering people’s names but there are tricks

(Elle) Tricks - repeat the name 3 times in conversation with them
OR visualise their name so you can see the letters on their body
OR associate their name with a word

(Nick) Always find - next time you see them, even if you think you remember it, feel free to comfortably ask them - sorry I forgot, what was your name again?

(Tom) Remembering the name of someone at a cafe - Jacob - only way Tom remembered after 3 weeks - that werewolf from Twilight (helps to associate)

(Elle) whenever we watch a movie, L opens up wikipedia & reads the plot & all the actors & follows links to see what else they’ve done. E never remembers actors’ names, while L does remember them. Connects the dots and reinforces memory.

(Nick) Memory is an odd thing. Couldn’t remember something for an hour, then got home & immediately remembered it.

(Elle) Having a shower & thinking about a programming problem (or a walk, after waking up, etc) - this has a name but she can’t remember it.
- In the past, buy a CD/cassette, on the way home to listen, read the liner notes vs. today - Spotify weekly mix, don’t look up the artist/song names. Lachlan learns about them and looks them up - reinforces the knowledge.

(Josh) more likely to find other bands you like this way.

(Lachlan) Wondered what happened to this one artist - finally looked him up - he’s still releasing albums, just under is own name instead of the other name, missed the last 10 years of them.

(Nick) Talking memory techniques - when hearing a song in the car when out, ask Siri to make a note, ask phone to remember so he doesn’t even try to remember it.

(Elle) Does this with Shazam - Shazam connects to Spotify - creates a playlist of songs to look up. 'Cos a list of things is hard to go back to.
