### ISSUE TITLE
The art of gathering: 01 and 08 March: Chapter 2

### ISSUE THREAD

**Issue by elle** [Blackmill/book-club#147]
Next book: The art of gathering, how we meet and why it matters by Priya Parker ([Readings](https://www.readings.com.au/products/26567315/the-art-of-gathering-how-we-meet-and-why-it-matters), [BookShop](https://bookshop.org/books/the-art-of-gathering-how-we-meet-and-why-it-matters/9781594634932), [Amazon](https://www.amazon.com/Art-Gathering-How-Meet-Matters-ebook/dp/B07637KVXL))

Aiming to read:
- Chapter 2

MC: @sugendran
Notes: @lachlanhardy 

See you all at 12pm AEST, Mar 1st & March 8th @ https://blackmill.co/meet

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via [gday@blackmill.co](mailto:gday@blackmill.co).

**Comment by elle** [comment]
- Different purposes:
  - Work meetings
  - Social gatherings - bonding
- Who:
  - There's always a bob
  - Exclusion -> gentlemen's clubs, whites only
- Number of attendees:
  - Blackmill workshops: 8-10
  - Rails Camp - when it got to 200, it was too much. 120 mark was good
- Where is important
  - Gentle Giant Moving Company => people with disabilities?
  - Woon at the museum => creativity
  - The Château Principle => do we feel equals?
  - Displacement
  - Dinner party with awkward sitting arrangements
  - Too big venue - Brooklyn Beta at the Navy Yard
- Through the examples you can illustrate a point, whereas if you just said the conclusion in one sentence, it will not explain the logic, or validate the statement. We do the same in the workshops

**Comment by lachlanhardy** [comment]
Sugendran is MC and got us all to use the 'Cabin' background filter in Whereby (a plain wood panelling). Apparently this is part of an experiment we'll see more of.

NickS: I found this chapter hard. The author reveals her biases and I found the explicit exclusion difficult. Even though she uses the term 'diversity', I don't think her approach here represents a true consideration of that means.

The example of the city council appears to be the only time she reflects to realise, after the fact, that other people should have been included after all.


Sugendran: Let's talk about meetups. As I experience them, they're very inclusive - any one can join and is, theoretically, welcome. Should they be more exclusive in some ways? I went to a meetup for engineering leadership and a third of the attendees were grads. Should they have been there? Is that a distraction from the purpose?

NickW: Does watching junior talks kill the vibe and motivation to attend for senior people?

Pat suggests that the type of interest group matters: a language group vs a skill/work/training level group (Ruby meetup vs CTO meetup)

We spent a while on this. What if groups are split into smaller events for some purposes? Is that exclusion? Does it help people be served by the group better?

"Specificity sharpens the gathering because people can see themselves in it."

NickS made some interesting points about our expectations of inclusivity in public events are different to our expectations for private or closed events.

Also, NickS: Some closed events transition to open/public events to help them reach a critical mass of attendees which mean they are self-perpetuating.

Do we as Society have a purpose and is part of that purpose to have ideas about what is acceptable by people who are part of our society?

How does the size of the gathering impact the dynamics?

Some people talk less, for a variety of reasons. Social anxiety, desire to let others speak, availability of opportunities to begin speaking.

**Comment by lachlanhardy** [comment]
We only really covered the first half so will do the rest next week.

**Comment by lachlanhardy** [comment]
# Second half!

How much does the type of food affect the environment and define the vibe of the meeting?

Ruby Australia meetups are generally a standard pizza and booze thing. Melbourne Ruby had a couple of years of different foods and Richard found that far more compelling.

These days Melbourne Ruby has the ice-cream trip afterwards. An explicityl non-booze choice. How does that affect the vibe?

Are after-event events a different gathering? Do they have a different purpose?

Let's talk about meetups that follow a different pattern. Some do food and drink first which allows people to make social connections and form groups - giving new attendees people to enjoy the content with. The lack of food earlier can be a source of stress/anxiety that can alleviated.

In tech meetups, perhaps people think the purpose is the content delivery, but if you asked people why they go many would say the social connection and community. What if the purpose were to engage and form community? Content would still be a part of that, but the focus is different.

We talked a bit about the history of Ruby meetups in Australia.

Part of the purpose of these gatherings is to get people to be willing to commit a couple of hours of their time to actually show up and participate.

According to the book, the more specific we can make our purpose, the better the gathering. The environment or setting can affect that significantly. So the venue and other aspects of the set up must serve the purpose.

One of the issues with the tech meetups were talking about is they're old, have history and multiple organisers, and thus have less curated and defined purpose?

Let's talk about different kinds of gatherings. Workshops, or team knowledge sharing events.

Lachlan described how Blackmill workshops are structured and the benefits he sees there.

NickW talked about an event he went to where people were assigned countries to represent and the lunch provided to them depended on that country's wealth. After lunch, the interactions differed greatly.

We talked about remote/distributed events that are uneven: 8 people in a room and one or two online etc.

How does collaboration work in uneven remote sessions? (mostly it sucks)

Richard extends the discussion to the layout of the physical environment for meetings. One person out the front? Desks/tables/chairs facing a particular direction? Sitting at a round table?

Elle raised that all the workshops she has liked were highly participatory. 

One started with the facilitators asking the learning goals and aiming the session at that. A retro revealed that people wanted more real-life examples than had been provided and so the second session was targeted entirely to deliver that.
