### ISSUE TITLE
The art of gathering: March 22: Chapter 4

### ISSUE THREAD

**Issue by elle** [Blackmill/book-club#149]
Book: The art of gathering, how we meet and why it matters by Priya Parker ([Readings](https://www.readings.com.au/products/26567315/the-art-of-gathering-how-we-meet-and-why-it-matters), [BookShop](https://bookshop.org/books/the-art-of-gathering-how-we-meet-and-why-it-matters/9781594634932), [Amazon](https://www.amazon.com/Art-Gathering-How-Meet-Matters-ebook/dp/B07637KVXL))

Aiming to read:
- Chapter 4: create a temporary alternative world

MC:  @pat
Notes: @mcgain

See you all at 12pm AEST, March 22th @ https://blackmill.co/meet

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via [gday@blackmill.co](mailto:gday@blackmill.co).

**Comment by mcgain** [comment]
Discussion notes: Chapter 4 - The art of Gathering

This chapter focuses on Etiquette vs Pop-up rules

Etiquette is a set of customs and rules to rule our interactions in polite society

Nick’s idea of etiquette is different from how it is portrayed in the book. Calls during breaks and being late to workshops? That’s not good etiquette! This refers to the author's initial example of the chapter, where latecomers to a meeting are made to do pushups.

Given the company had this culture of customer focus Nick asks if the author was right to be annoyed at this culture to the extent of punishing people?

Josh thinks that setting up rules in your gathering doesn’t remove all the existing etiquette rules that are there. Anton points out that etiquette has failed because we have different cultures, and groups. Wolf wonders if the nebulous nature of unwritten rules, etiquette, can be exploited for bad. Rigid rules are less exploitable because they are explicit

Adam enjoys rules based groups, but can those rules be exclusionary? We'll revisit this topic later.

Nick got this out of the chapter: It’s about communicating the intent of the gathering beforehand. Clear communications are the key. A great example of this are conferences with codes of conduct, explicit breaks etc. Wolf adds, this allows people to consider whether the group is for them or not. 

Adam wants to sit in the grey area though. The Dinner en Blanc sit males and females opposite, and is exclusionary. This didn’t sit well with Pat or Kirsten either. Gender binary bullshit is problematic and the expense is also exclusionary. Wolf is more generous though, this is just an example of a structured event, the author perhaps doesn’t explicitly endorse it. Half the chapter is about this though, hard not to see it as an endorsement.

Kirsten helps run a Miss Fisher convention, and the president wants to run it in a fancy hotel, but Kirsten feels this is exclusionary. It’s expensive. This a continuing theme that runs through our conversations today. Rules can create fun, but how do you know whether they're actually good?

Adam points out that sometimes, this is ok. Not all events can be for everyone. The trick is figuring out which events should be for all, and some should be exclusive. Tech events do this well, and poorly. 

Another consideration: Mandatory events vs optional ones. 

Revisiting the initial topic of duscussion, Forcing people to do push up feels a lot like bullying. Ignoring the customer focus of the org isn’t necessarily a good thing.


Nick points out that there’s no consideration of refining rules over time. Anton reckons these rules are just all made up and are not necessarily great ones. 
Pat describes an event he recently went to where there were pop up rules, but the MC was able to adjust them on the fly when problems came up. 

Nick asks how do you figure out punishments for breaking the rules? 

There is conflict between the intended experience from the organiser, vs the what the participants get out of it. This cropped up in the last few sessions too.


We had a discussion on bringing phones to events. Should you be going if you are on call? Or if you have a babysitter? This is tricky.

Anton raised the subject of the chapter “alternate worlds”. He thinks it’s cool to create that. Nick added that the game of warewolf is typical of this. An alternative world is the secret sauce of Railscamp. That alternative is what makes it special. Richard pointed out that LARPing is an extreme version of this. Pop up rules are very important there to keep immersion, but also protect the wider public.

Sugendran finds a lot of work events uncomfortable, beer and pork is exclusionary to muslims for example. It’s hard to create inclusive work events. In New Zealand, Pat pointed out that “Ruby Retreats” (used to be railscamp) made an attempt at making it a no-alcohol event. This got some backlash, some people want booze. We had a big discussion around solving this specific example, with lots of opinions offered. Notably, feedback could be solicited from attendees, but this is susceptible to selection bias.

Nick shared a breakfast event at Culture Amp, that works well for mothers, since they have trouble getting out in the evenings. Nick found it was great, even for him without those constraints. Too many tech events are the same, Anton claims. We should be trying new formats. Constant change, or too many ruby events won’t go well though, Pat points out. So a small amount of change? Adam thinks removing alcohol from Railscamp would align it better to its intent. Loud minorities often drown out the fact that most people might be happy to try different things. 

Wolf visited a retreat recently, and at the beginning, they created norms for the event. Exploring this at the start made a good compromise between what the organisers wanted, verses the attendees. 

How often do changes in rules fail because the objectors are not brought along for the change and communicated with early enough?

Events with hug comfort level labels (like a traffic light party) sound good. Conferences use different coloured lanyards to achieve this for photographable status.

Adam finished by pointing out that we need to understand the reasons behind the rules before we can change them.
