### ISSUE TITLE
The art of gathering: Apr 5: Ch 6

### ISSUE THREAD

**Issue by elle** [Blackmill/book-club#151]
Book: The art of gathering, how we meet and why it matters by Priya Parker ([Readings](https://www.readings.com.au/products/26567315/the-art-of-gathering-how-we-meet-and-why-it-matters), [BookShop](https://bookshop.org/books/the-art-of-gathering-how-we-meet-and-why-it-matters/9781594634932), [Amazon](https://www.amazon.com/Art-Gathering-How-Meet-Matters-ebook/dp/B07637KVXL))

Aiming to read: 

    Chapter 6:  Keep your best self out of my gathering

MC: @kunzmann
Notes: @antulik

See you all at 12pm AEST, April 4th @ https://blackmill.co/meet

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via [gday@blackmill.co](mailto:gday@blackmill.co).

**Comment by antulik** [comment]
**Discussion notes**

Josh: let's turn off the video off to try the masks off exercise similar to what was mentioned in the book.

What is fresh for you?

You can turn your camera on if you'd like to go next.

We go in a circle to share our stories: Josh, Nick, Richard, Lachlan, Mike, Adam, Nick W, Anton, Elle, Pat

No singing for Pat.

Josh: thanks for participating in the experiment

Richard: what effect of the experiement did we get in this group? 

Nick W: in the world forum example, sharing will help to establish bonds. It helps connect people and add additional opportunities and perspective. When founder share their stories and easier to get invested in their stories. That's at least my hope of the effect of 15 toasts

Elle: As per previous book by B. Brown to be vulnerable. Elle tells a story about workshop where people opened up which in a result created special connections. There is a podcast about white house and politicians, in the past they lived close to each other, but now they live far apart and that affects their relationship, which is more official now.

Nick W: if you only see people at work, that you see them at the arena and see other side of people

Richard: I agree, but I don't think the book chapter makes that point clear. The chapter didn't talk enough about the reasons why and outcomes. It feels like a piece of entertainment and theather, rather than a thing that makes a change in the world.

Pat: Not sure about theather, 15 toasts and economic forum is a hard job. It's a pre-event, the question how it flows to the main event. I think there is a value in 15 toast event. But is the impart in itself or more broadly.

Nick W: for our local example, speaking honestly in the group it make me feel connected. Nudging people in the right direction helps.

Lachlan: I'm interested about "dark themes" part of the chapter? A lot of conferences are inspirational, but you need to talk about how you got there through bad bits, but it's not often seen. Do you have experience with that?

Elle: You can't have growth without challenges.

Nick: I tried to be open-minded in this chapter. I found it challenging to get past the nature of examples and people involved and author is coming across as a hero. One part resonated is communicate your goals clearly, which is in the chapter and book. You need to give heads up to people.

Adam: Previous chapters were about picking your guests, but this chapter is about people who you didn't invite.

Nick: http://15toasts.com/ is self promotional

Nick W: I think of it as TED and TED X. This is instructions how to run TED X. 

Nick: TED talks are online, but these are in-person events.

Lachlan: We are not the audience for it. (world forum)

Nick: I looked it up because I was curious about it. It's not highly ranked in google.

Nick W: "Persuasion" idea in another book has effect on vulnerability. 

Elle: Shares story when at one event women were reading personal letters. But her book wasn't as good as the letter.

Lachlan: comparison to TED events is strong here. Author and her friend curate the experience. 

Nick: Does this chapter read as a group therapy session?

Lachlan: not sure, what's the purpose though?

Nick: Vulnerability is an important aspect.

Pat: There is a danger of an event to go into group therapy zone. It helps break down stigma. But it's a fine line to tread.

Elle: I won't do a period party

Josh: It might be seen as a traumatic experience, not a celebration

Nick W: Nick W tells a story how two boys were invited to period party without knowing it. 

Kirsten: People are people, even with BDSM friends circle.

Lachlan: The author is working with professional people who are very guarded of their private life. That would be a very boring event. It's just a way to get more real conversation. 

Adam: How many times can you use that trick before those private stories become stripted.

Elle: Americans love dramatic actions. Elle shares a story about American comedian.

Lachlan: Tells a story about comedian and difference between American and Australian culture.
