### ISSUE TITLE
The first 90 days: May 10: Chapter 2

### ISSUE THREAD

**Issue by HashNotAdam** [Blackmill/book-club#156]
Book: The first 90 days by Michael D Watkins ([Bookshop](https://bookshop.org/books/the-first-90-days-updated-and-expanded-proven-strategies-for-getting-up-to-speed-faster-and-smarter-revised/9781422188613), [Readings](https://www.readings.com.au/products/16500449/the-first-90-days-updated-and-expanded-proven-strategies-for-getting-up-to-speed-faster-and-smarter), [Amazon](https://www.amazon.com/First-90-Days-Strategies-Expanded/dp/1422188612))

Aiming to read:

- Chapter 2: Accelerate your learning

MC: @nickspragg
Notes: @HashNotAdam 

See you all at 12pm AEST, May 17th @ https://blackmill.co/meet

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via [gday@blackmill.co](mailto:gday@blackmill.co).

**Comment by elle** [comment]
## 2: Accelerate your learning

- Baseline question: how did we get here?
- The pressure to do almost always comes from within rather than outside forces
- Simply displaying a genuine desire to learn and understand -> credibility and influence
- Coming in with the answer alienates people
- Learning agenda: learn about the past, present, and future
  - Past: performance, root causes, history of change
  - Present: vision and strategy, people, processes, land mines, early wins
  - Future: challenges and opportunities, barriers and resources, culture
- Identify who you can learn from the most -- from within and outside the organisation
- Structured learning methods: ask the same five Qs:
  1. What are the biggest challenges the organisation is facing (or will face in the near future)?
  1. Why is the organisation facing (or going to face) these challenges?
  1. What are the most promising unexploited opportunities for growth?
  1. What would need to happen for the organisation to exploit the potential of these opportunities?
  1. If you were me, what would you focus attention on?
- Once you gathered insights, observations, and questions, gather the team, share your thoughts and invite a discussion. This will teach you about substance and team dynamics.
- Methods for learning:
  - surveys
  - interviews
  - focus groups
  - analysis of critical past decisions
  - process analysis
  - tours
  - pilot projects
- Learning plan template!

### Checklist

1. How effective are you at learning about new organisations? Do you sometimes fall prey to the action imperative? To coming in with “the” answer? If so, how will you avoid doing this?
2. What is your learning agenda? Based on what you know now, compose a list of questions to guide your early enquiries. If you have begun to form hypotheses about what is going on, what are they, and how will you test them?
3. Given the questions you want to answer, who is likely to provide you with the most useful insights?
4. How might you increase the efficiency of your learning process? What are some structured ways you might extract more insight for your investment of time and energy?
5. What support is available to accelerate your learning, and how might you best leverage it?
6. Given your answers to the previous questions, start to create your learning plan.
