### ISSUE TITLE
Next book: Antifragile: July 12th

### ISSUE THREAD

**Issue by elle** [Blackmill/book-club#163]
Book: Antifragile: Things That Gain from Disorder by Nassim Nicholas Taleb ([Bookshop](https://bookshop.org/books/antifragile-things-that-gain-from-disorder-9780812979688/9780812979688), [Readings](https://www.readings.com.au/products/16515947/antifragile-things-that-gain-from-disorder), [Amazon](https://www.amazon.com/Antifragile-Things-That-Disorder-Incerto-ebook/dp/B0083DJWGO))

Aiming to read:
- Prologue and appendix 
- Chapter 1: Between Damocles and Hydra

MC: @lachlanhardy 
Notes: @mcgain 

See you all at 12pm AEST, July 12th @ https://blackmill.co/meet

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via [gday@blackmill.co](mailto:gday@blackmill.co).

**Comment by mcgain** [comment]
Notes:

The book opens with an exhaustive table of contents. This book is separated not into sections, but into smaller books.

Book 1: The Antifragile
Book 2: Modernity and the denial of antifragility
Book 3: A nonpredictive view of the world
Book 4: Optionality, technology and the intelligence of antifragility
Book 5: The nonlinear and the nonlinear
Book 6: Via negativa
Book 7: The ethics of fragility and antifragility

**Prologue**

Some things benefit from shocks and bad stuff, when exposed, they get better. Let's call this concept Antifragile
Antifragile is not the same thing as robust, it is beyond it, but people often combine the two concepts
Fragile -> Robust -> Antifragile

Instead of predicting how something will break under stress in order to predict it, it's better to predict which things are fragile and improve them.

By supressing randomness, we're actively harming things overall, since the antifragile stuff can't grow from it

Black Swan events are large scale unpredictable and irregular events that change the world. We're going to get more of them because our modern world is so interdependent. 

Mother Nature is good at responding to Black Swan events because she is antifragile

Fragility is measurable, risk is not

"some economists and other lunatics can claim -against experience- to 'measure' the future incidents of these rare events"

Rationalists have taken all the mystery out of life and try to remove risk, but it doesn't work. 

Simple systems are better than complex ones, but they're harder to build

The definition of Antifragility comes from the definition of fragile. IF you explicitly define fragile as stuff that breaks when exposed to stressors, then there are three qualities. Stuff that breaks, stuff that doesn't break, and stuff that gets better.

Then there's a bunch of pontificating about how the author has to say something now that they've noticed this thing. The author is ethically obliged.

The book is written at three levels
	1. Literary and philosophical
	2. An appendix
	3. Backup material with more elaborate arguments

Fragile, Robust and Antifragile form a triad, and are relative not absolute terms. Then follows a big table of triads in different categories.


**Chapter 1**

A box of champagne glasses is fragile, the opposite of that is not robust, but antifragile

We don't have a word for this, weirdly, so the author made one up. The concept doesn't appear in Brooklyn English, or Soviet Russian, or many others.

Damocles, thanks to his sword, is fragile

The Phoenix is always reborn into the same form, and is robust

The Hydra is antifragile

We didn't have words for many basic colours in the past, but we could still see them. We were culturally, not biologically colour-blind. The same is true of antifragility, although we didn't have a word for it, it was still there and people could interact with the concept. 

Mithridatization, the taking of small doses of poison to build up a resistance is a form of proto-antifragility

Hormesis is the same concept, generalised. Small doses of poison can actually be beneficial in some cases.

Domain blindness is a thing, what we learn in a classroom or in one domain, is hard to translate to other domains.
Ex: Banker doesn't bother carrying his cases, but then exercises in the gym. Americans are against price controls, but for the Federal Reserve, which controls interest rates. This is what makes it hard for us to see antifragility
