### ISSUE TITLE
Oct 25: Team Topologies: Chapter 3

### ISSUE THREAD

**Issue by elle** [Blackmill/book-club#167]
Book: Team Topologies: Organizing business and technology teams for fast flow by Matthew Skelton and Manuel Pais.
Link: https://teamtopologies.com

Aiming to read:

- Chapter 3: team-first thinking

MC: @lachlanhardy 
Notes: @quintrino

See you all at 12pm AEST, October 25th @ https://blackmill.co/meet

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via [gday@blackmill.co](mailto:gday@blackmill.co).

**Comment by lachlanhardy** [comment]
Notes from @quintrino:

Richard/Josh: Not a memorable chapter ()
Lachlan: Dunbar's number info cool, more info than just the 150 that everyone else quotes
Richard: How do deep trust organizations exist if (as the book claims) you can only have high trust at 15. 
Lachlan: Dunbar's number is based on primate skull sizes, also very much averages
Lachlan: Potential for higher numbers based on higher empathy, charisma, etc
Nick: Trust is also contextual (don't trust your doctor to refactor your code) 
Nick: A novel way to measure close connections is how many people could you crash on the couch for a week
Lachlan: The 150 is about not just remembering them, but what their capabilities are. 
Richard: The 15 person team limit feels very accurate. 
Lachlan: Horizons is interested but really difficult to figure out how to apply it.
Sugendran: Horizons encourages team ownership and discourages re-orgs. 
Lachlan: Team Lead little steps (on time to meetings, etc) can be seen as just Respect, but good to frame it as putting the team first. I wonder how different this is in other cultures
Lachlan: Acording to 6 degrees of Culture you have different cultural approaches and it might mean they mind handle these issues differently. They may also have the issue of needing to encourage more individualist focus. 
Sugendran: I haven't seen a difference in different cultures, they all seem to believe in the team's success. 
Lachlan: My experiences were mostly the negative clashes, such as failing at communicating they knew a project wouldn't work. 
Lachlan: Some challenges around convincing people that the "team" will help achieve. 
Sugendran: Stable teams are always promoted as a solution, but I'm yet to see stable teams.
Richard: I think stable teams can handle a degree of change if you have a strong team culture already. 
Josh: the stable team can also be the domain. 
Sugendran: How long is a stable team? 
Lachlan: Yeah, stable doesn't really get a duration assigned to it. 
Lachlan: Pamela's Knights work sounds interesting. 
Sugendran: Rewarding the team is a better approach than rewarding the individual. 
Sugendran: You should reward the outcome of a team, which is seperate to performance management. 
Josh: You'd want the team to be part of the conversation of "if a feature is worth it". 
Lachlan: if you're rewarding Impact rather than effort, you want them to have a voice on what they think will provide impact. 
Lachlan: Whole team training budget are often individual, but entertainment budget are often collective. 
Lachlan: Trusting people to do the right thing, I feel we all agree that too much cognitive load is going to be negative on the team. 
Josh: it has a good breakdown of the different types of cognitive load
Richard: Lots of this information feels already well covered, but it would feel an omission if it wasn't in the book. 
Richard: I'm reading Modern Software Development by Jess Humble and there's nothing new in it, but it covers all the important stuff that modern teams should be doing. 
Josh: the idea of using Cognitive load to help with determining team creation feels really valuable. 
Lachlan: The book could use a better definition of domain. 
Sugendran: I think it was business domains
Richard: Ownership in an individual is a really good sign of someone progressing towards a senior engineering skill set. 
Josh: I didn't like the colocated statement. I believe you can work effectively remotely. 
Richard: I'd be keen to talk about that more as well. 
Lachlan: It's a shame they released this book in 2019, 1 extra year and it would have talked much more about remote. 
Lachlan: This first section does still feel a bit like the setup for the future sections.
