### ISSUE TITLE
NOV 1: Team Topologies: Chapter 4

### ISSUE THREAD

**Issue by lachlanhardy** [Blackmill/book-club#168]
Book: Team Topologies: Organizing business and technology teams for fast flow by Matthew Skelton and Manuel Pais.
Link: https://teamtopologies.com

Aiming to read:

- Chapter 4: Static team topologies

MC: @sugendran
Notes: @lachlanhardy 

See you all at 12pm AEST, November 1st @ https://blackmill.co/meet

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via [gday@blackmill.co](mailto:gday@blackmill.co).

**Comment by sugendran** [comment]
[team-topologies-chpt-4.pdf](https://github.com/Blackmill/book-club/files/9957135/team-topologies-chpt-4.pdf)

**Comment by elle** [comment]
Transcription of had written notes ^:

## Chapter 4

- Can we do SRE without a Paas?
  - No
  - Have freedoms that don't want to work with each other
  - Trying to build an SRE culture but have lots of people with ops who don't want to do that
- PaaS: Standardisation
  - productivity booster
  - Enables access and control
      - access for people who need it for work
      - control for large org
  - Prevents dance of "where can I make this change?"
- End to end ownership
  - Need common tooling/platform - Deliberate choice not to own everything
  - Alternative is that we have common knowledge and reduced cognitive load
  - It's easy from a business perspective to enable access to all for everything
  - Breaks least principle
  - Tends too be unscoped in small orgs
  - Large orgs go the other way and restrict access to all
  - Is scoping related to domain size?
  - Small org =- full domain
  - large org == small domain
- Team topologies are elastic
  - Teams morph as required
  - IaaS creates friction
  - SRE generates PaaS -> reduces friction
- Access end to end
  - If you can't validate in production, you are too removed
- Don't forget to teach people how to use the tools

## Chapter 3: remote work

- Books was written pre-covid
- Favours office-based comms
- Things to try:
  - Open mic audio for the team
  - Open channel messages instead of DMs
