### ISSUE TITLE
Post Growth, 14th March: Chapters 3 and 4

### ISSUE THREAD

**Issue by pat** [Blackmill/book-club#178]
Book: [**Post Growth: Life After Capitalism**](https://timjackson.org.uk/ecological-economics/postgrowth-book/) by Tim Jackson

Aiming to read:

* Chapter 3: The Limited and the Limitless
* Chapter 4: The Nature of Prosperity

MC: @pat
Notes: @HashNotAdam

See you all at 12pm AEDT, March 14th @ https://blackmill.co/meet

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via [gday@blackmill.co](mailto:gday@blackmill.co).

**Comment by HashNotAdam** [comment]
# Discussion

## Chapter 3: The Limited and the Limitless

There is a general feeling that, once again, this book could have been a blog post, and this chapter could have been a couple of Tweets.

It is discussed that there are limits, but there is no validation of this; we are expected to take it on faith. Whether or not limits exist is a debated topic amongst the group. Given a lack of references, we are left with only opinions. There was a discussion in the 90s about running out of oil within 30 years. More oil was found, but it does suggest it is a limited resource. On the other hand, while there might be a limit to oil, we have been transitioning to green alternatives, so might we be bypassing the limit on oil to find limitless energy?

![Scene from the movie "Mean Girls" where Cady says "The limit does not exist"](https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExNzg5NDIxZTQxOGZkYTc1ZWVhNmVkN2Q0MzgwMjgzZGRjOWQ5ZTc3OSZjdD1n/7JvlHfd7C2GDr7zfZF/giphy.gif)

The presented argument is that we must choose between growth and the planet. If we were to _really_ invest in the green economy, might that create growth through investment and productivity gains? There are many examples of large investments creating new industries, including the world wars, COVID, the space race, DARPA, and other Government funding (CSIRO).

Now that the majority agrees that we need to protect the planet, maybe we would see greater investment if we weren't held back by the need for growth. It's possible this is an Australia-centric view, however, given the lack of response from our nation.

Earlier in the solar movement, there was a debate about whether people should be able to receive compensation for power exported to the grid, which raises the question, "who does this growth serve?"

It was discussed in the book that "GDP is growing faster than the carbon content of the GDP is declining". We can innovate all we like, but if it doesn't reduce the use of resources fast enough, it doesn't matter.

A lot of developing nations have argued that they want the same opportunities we had to grow standard of living through the use of fossil fuels. They want to grow, which under a growth-only mantra, is an acceptable position to take. It's a very privileged position to be able to tell them that we've decided we're finished with growth now. Is it entitlement for others to believe they should have what we had or should we, the rich nations, subsidise their development so they might grow in a more sustainable manner. On the surface, subsidising other nations would seem to reduce domestic GDP but is it possible that, by removing our subsidies for fossil fuels and using those funds to produce green alternatives locally for export to developing nations, the growth in Australian businesses might cancel out the impact upon GDP?

## Chapter 4: The Nature of Prosperity

There were more references to sex than was expected.

This chapter leans heavily on Jackson's previous work, "Prosperity without Growth", including the five domains of human functioning: spiritual; social; psychological; physiological; and sexual. In previous books, we've spoken about happiness from a personal and work interpersonal standpoint but it's nice to consider it at a societal level. While we need to be careful about prescribing values to other cultures, these needs seem fundamental but the challenge is measuring them.

[Maslow's Hierarchy of Needs is a whitewashed version fo indigenous knowledge](https://shanesafir.com/2020/12/before-maslows-hierarchy-the-whitewashing-of-indigenous-knowledge/), taken from the Blackfoot Nation of North America.

The book discusses money as a proxy to happiness and how that measure works when tracking the poor but, as income increases, the utility to greater income reduces until it starts to turn negative. When considering prosperity—as opposed to just happiness—the concept of health is introduced and we discussed the idea of a prosperity Goldilocks zone. Our culture considers right-to-choose with regard to health as important—which is why we don't outright ban smoking or alcohol—and so finding that balance point is difficult. If we include health in our metric for prosperity, we know we have made large gains in areas like infant mortality but, more broadly, it could be a difficult needle to move. Maybe it would be possible to focus on growth-related health issues, such as polution. There is also concern that having health-related targets might create incentive to "eradicate" those with genetic health issues to get the numbers up.
