### ISSUE TITLE
Post Growth, 21st March: Chapters 5 and 6

### ISSUE THREAD

**Issue by kunzmann** [Blackmill/book-club#179]
Book: [Post Growth: Life After Capitalism](https://timjackson.org.uk/ecological-economics/postgrowth-book/) by Tim Jackson

Aiming to read:

Chapter 5: Of Love and Entropy
Chapter 6: Economics as Storytelling
MC: @kunzmann
Notes: @pat

See you all at 12pm AEDT, March 21st @ https://blackmill.co/meet

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via [gday@blackmill.co](mailto:gday@blackmill.co).

**Comment by pat** [comment]
Notes from the session, which ended up just being focused on Chapter 5, with Chapter 6 being postponed to next week.

- chapter was supposed to be about the relation between love and growth
- ends up being more about health, second law of thermodynamics
- love was a bit of an afterthought
- tenuous framing around a lecture by Ludwig Boltzmann that was not recorded.
- the points about balance resonated though, and the influence of capitalism in making us unhealthy because of the need for growth.
- arguments worked despite the framing.
- appreciated the point about needing resources to capture even solar energy - so not even renewable energy is free, and the resources degrade, so entropy still impacts.
- 7% ROI required to be successful with solar energy in Germany, but 25% in Egypt, because of money systems.
- Counterpoint: if entropy is inescapable, and continual resources are needed anyway, then what's the point?
- Efficiences can kick the can down the road?
- The resources needed are changing over time.
- Creating a society that is not extractive feels more like science fiction than colonising other planets.
- How do we "set ourselves up for success" with regards to reduced resource usage, etc.
- We're not good at valuing (putting a price on) natural resources - e.g. water
- Flip to the earlier counterpoint: how much deprivation is worthwhile for ongoing survival? How do we plan for multiple generations ahead?
- the impact of profit-seeking in the health system
- "we seek material satisfactions for non material needs" - many non-physical needs don't actually need material responses. Capitalism has us wired that way though.
- if we had healthier (more balanced) internal systems - i.e. mental health - then we would likely be less capitalist in needing support personally, and would allow us capacity to tackle external things.
- appreciation of the prose, of it being a less of a business book.
- recommendations for Ian M Banks' Culture series, and Becky Chambers' Monk & Robot series for post-scarcity societies in fiction.

Other reflections:

- The book is perhaps stuck on a capitalism/corporations vs communism/government binaries. Keen to look beyond that, e.g. collectivism.
- Labels are hard and evolving and mean different things at different times, to different people. Communism, Socialism, etc.
- Trying to stick to old definitions could be problematic, that's essentially conservatism? But also need to understand how we got here.
