### ISSUE TITLE
June 4: Primed to perform chapters 3-4

### ISSUE THREAD

**Issue by elle** [Blackmill/book-club#18]
Primed to Perform](https://www.amazon.com/Primed-Perform-Performing-Cultures-Motivation-ebook/dp/B00S590OQI)

Aiming to read:
- Chapter 3: rethinking performance
- Chapter 4: the yin and yang of performance

MC: @HashNotAdam 
Notes: @mcgain

See you Tuesday in Zoom:

Join Zoom Meeting
https://zoom.us/j/914785529

Topic: Blackmill Book Club
Time: Mar 26, 2019 12:00 PM Canberra, Melbourne, Sydney
Every week on Tuesday. First one: Mar 26, 2019 12:00 PM

Please download and import the following iCalendar (.ics) files to your calendar system.
Weekly: https://zoom.us/meeting/914785529/ics?icsToken=5dd411172ce371e9770226b355c2f163863fe4efff5e00b09866a6b7be767b09

One tap mobile
+61871501149,,914785529# Australia
+61280152088,,914785529# Australia

Dial by your location
+61 8 7150 1149 Australia
+61 2 8015 2088 Australia
Meeting ID: 914 785 529
Find your local number: https://zoom.us/u/abWGuMO6GJ

**Comment by elle** [comment]
## 3: Rethinking performance

Life achievements correlated more to childhood creativity than childhood IQ

Tactical vs adaptive performance:
ability to execute a plan vs person's ability to diverge from the plan

> VUCA stands for volatility, uncertainty, complexity, and ambiguity. Tactical performance is not enough to address VUCA. People and organizations need to adapt.

- The distraction effect
- The cancellation effect: performance based rewards tend to cancel out the neutral sense of play, thus reducing persistence
- The cobra effect - gaming the system
- The great wave


## 4: The yin and yang of performance

> Everybody has a plan until they get punched in the mouth. Then, like a rat, they stop in fear and freeze.

--

> we define a high-performing culture as the system that maximizes adaptive performance through total motivation.

Yin and Yang OR Tactical vs Adaptive performance

> Strategy helps us focus all our energy on a few critical targets. It is a force of strength. Culture, on the other hand, allows us to react to the unpredictable. It is a force of agility. Together, they create a complete view of performance.

--

> ...personality traits did not significantly correlate to their adaptive performance at all. Neither did their feelings of autonomy. But total motivation did.

--

> Emergence occurs when the individual components of a collective are able to organize themselves into a system that is far more complicated than the sum of its parts. These systems are almost always self-organized and have incredible levels of adaptive performance.

Complexity theory

> emergent organizations must encourage citizenship. Citizens teach and help one another, spread new ideas, and share innovations.

**Comment by HashNotAdam** [comment]
# Chapter 3: Rethinking Performance

## Creative destruction

"The correlation to lifetime creative accomplishment was more than three times stronger for childhood creativity than childhood IQ" — Newsweek

"Those who came up with more good ideas on Torrance's tasks grew up to be… software developers." Creativity is crucial.

“Managers don’t kill creativity on purpose… yet in the pursuit of productivity, efficiency, and control—all worthy business imperatives—they undermine creativity.” — Professor Teresa Amabile, Harvard Business School

When building high-performing organisations, you need to understand and optimise two different, opposing types of performance:

- Tactical performance: how well a person executes a plan (productivity, efficiency, and control)
- Adaptive performance: a person's or organisation's ability to diverge from the plan (volatility, uncertainty, complexity and ambiguity)

Adaptive performance behaviours are very difficult and sometimes impossible to measure. As a result, they are almost always neglected.

## The distraction effect

Study by Dan Ariely, professor at Duke and the author of *Predictably Irrational*:

- In each task, some students are given incentives up to \$30 or $300
- In the first task, they are asked to press 2 keys on a keyboard as many times as possible. In this task, the \$300 group outperformed the $30 group
- In the second task, the were asked to find 2 numbers in a grid that add up to 10. This time the \$30 group outperformed the \$300 group by 32%

When a job requires only tactical performance, indirect motivators *can* increase performance but, when adaptive performance is required, indirect motivators can make performance worse.

The economic pressure distracted them because they focused on the stakes, not just the work.

When Ariely asked students to solve simple anagrams while other students look on, they were similarly derailed by the emotional pressure (50% reduction).

## The cancellation effect

A study at the Max Planck Institute showed that providing rewards to toddlers decreased their motivation to keep helping. After being rewarded, helping the research assistant was a matter of calculation. This is the cancellation effect.

The cancellation effect occurs when a person's total motivation is reduced to the point that they completely stop focusing on adaptive performance.

Numerous studies exist showing that performance-based rewards cancel out the natural sense of play, reducing persistence.

Organisations that use indirect motivators must make trade-offs between tactical and adaptive performance:

- quantity vs quality
- individuality vs teamwork
- near-term vs long-term results

## The cobra effect

When Delhi wanted to reduce the cobra population of the city, they provided bounties for dead cobras. Entrepreneurs created cobra farms to raise more snakes. When the scheme was uncovered, the bounty was removed and the snakes were released from the farms, leaving the population greater than before the bounty.

Every job creates the opportunity for *maladaptive performance*. When a person's total motivation is low enough, they begin to find the shortest possible path to alleviate the pressure they are feeling.

Companies presume (incorrectly) that these cobra effects are a result of bad apple that snuck through the hiring process rather than flaws in the culture. These are typically addressed through indirect motives (for example, punishment).

## The great wave

As ToMo decreases, adaptive performance disappears and is ultimately replaced by maladaptive performance.

A mortgage company tried to create a high-ToMo culture with their loan officers just before the GFC. Previously, during the height of the boom, they ramped up emotional and economic pressures.

### The distraction effect

Near the end of the month when their performance was about to be tallied: they would spend an hour each day tallying; were irritated by calls that didn't lead to sales; stress mounted; and customer experience suffered.

### The cancellation effect

Those whose jobs were more in jeopardy took shortcuts. When part of a customer's application seemed dubious, they would let it pass. If a customer needed help, they wouldn't have the persistence or creativity to find a solution.

### The cobra effect

They showed mortgage brokers how to game the system.

# Chapter 4: The Yin and Yang of performance

ToMo is more powerful when it's instilled throughout an entire organisation

## Yin and Yang

Strategy is "a plan of action designed to achieve a long-term or overall all".

A high-performing culture is the system that maximises adaptive performance through total motivation.

There is no plan that can properly anticipate or address every form of VUCA that your organisation encounters; your organisation needs to adapt at every level all the time.

Adaptive and tactical performance are like yin and yang.

Strategy helps us focus all our energy on a few critical targets. It is a force of strength. Culture, on the other hand, allows us to react to the unpredictable. It is a force of agility. Together, they create a complete view of performance.

## The fuel of adaptability

Wharton professor Adam Grant and his colleagues were able to show that purpose and play increase creativity and that even environments that seem completely tactical on the surface can benefit from adaptive performance.

## Emergence

Termites adapt constantly and autonomously to changing environmental factors and act as a strong community without any leadership. Each type of termite knows their purpose and enacts their job without direction.

## Mounds for people

Emergence occurs when the individual components of a collective are able to organize themselves into a system that is far more complicated than the sum of its parts. These systems are almost always self-organized and have incredible levels of adaptive performance.

## The study of complexity

Emergence is studied as part of a field call complexity theory.

"How do simple components self-organise to form incredibly complex and adaptive systems?"

A company that creates a culture of high adaptability will be the most successful. Adaptive organisations are truly built to win.

Benyamin Lichtenstein of The University of Massachusetts and his colleagues have identified a set of conditions that are required before high-performing, adaptive organisations can emerge:

- individual members must be adaptive within their environment
  - organisations must encourage and allow people to come up with better ways of performing their jobs and serving their customers ("encouraging novelty" and "allowing experiments and fluctuation")
  - play is directed toward giving people the ability to experiment in the areas that have the greatest needs for adaptability
- emergent organisations must encourage citizenship
  - citizens teach and help one another, spread new ideas, and share innovations

## Born to adapt

"Many people believe, as I do, that when staircases are constructed between psychology and biology, the best strategy is to work from the top down as well as from the bottom up" — Murray Gell-Mann

Psychological experiments have shown us how ToMo leads to individual adaptability. Complexity theory explains how it also works to produce the most adaptive organizations possible. Biology explains the rest.

University of California researchers Robert Boyd and Peter Richerson propose that our brains evolved in response to climate variability.

Our larger brains gave us the ability to experiment, learn, communicate, and, ultimately, create cultures. Culture allowed us to adapt via memes instead of genes. “Social learning enhances ability to respond to temporal and spatial variations in the environment,” according to Richerson and Boyd. “Cultural evolution allows speedy tracking of a rapidly fluctuating environment because it supplements natural selection with learning and other psychological forces.”

We are born to be adaptive performers. This is why we have a total motivation instinct.

## Yin and Yang in balance

One of the most interesting exemplars of the yin and yang in balance is Wikipedia, which, while not a business organization, is still perhaps the highest performing organization ever created.

A researcher once tested Wikipedia’s adaptability by deliberately introducing thirteen errors into articles on the site. Every one of them was corrected within three hours.

You need to balance adaptive performance with tactical performance. In the case of Wikipedia, tactical performance means consistency across pages that are edited by completely different people from around the world. Despite having no formal structure, the volunteers produce pages that have incredible consistency in their organization.

You should never use employee satisfaction as the measure of your culture’s strength. It’s easy enough to create satisfaction. But satisfaction does not always lead to adaptive performance.
