### ISSUE TITLE
Post Growth, 28th March: Chapters 6 and 7

### ISSUE THREAD

**Issue by mcgain** [Blackmill/book-club#180]
Book: Post Growth by Tim Jackson
Link: https://abookapart.com/products/inclusive-design-communities

Aiming to read:

    Chapter 6: broadening the community
    Chapter 7: The Return to Work   

MC: @mcgain 
Notes: @kunzmann

See you all at 12pm AEST, March 28th @ https://blackmill.co/meet

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via [gday@blackmill.co](mailto:gday@blackmill.co).

**Comment by mcgain** [comment]
### Chapter 6
**Symbiosis**
 Apparently competition is one of the "most fundamental driving forces in nature", but it looks like this chapter will argue that **symbiosis** is equally important.

**Metaphors**
Memes can influence economics! It's partially a "confidence trick". Narrative is important
Metaphors help us communicate if they resonate.

Darwin's theory of evolution has resonated so powerfully it has eclipsed scientific "hard-nosed objectivity". Social Darwinists have applied this metaphor to politics and society, inventing phrases such as "survival of the fittest". "Might is right" is a dubious doctrine, the book claims. It has led to eugenics and genocide.

Actually, it turns out Darwin was inspired by an economist called Malthus. He claims that population will always outstrip the means to sustain it. These theories lead us to believe that we must struggle to the top, and that we must grow to escape scarcity. 

**The actual argument**

"Growth matters when there is a material insufficiency" so actually, we do need to grow to get past that, but it's hard to know when to stop, and how to stop. Capitalism has failed to give us these answers, and also failed to protect the environment, or give us real stability (Great Depression, Market Crashes, Our Current Market instability).

The Great Depression was a "crisis of over-production". Production had outstripped demand. "Capitalism responded by stimulating demand".

"Consumer capitalism trades not on happiness but discontent". To make us buy new things, they have made novelty and fashion important. We crave new things and endlessly search for contentment, something that cannot be purchased, despite the promises of advertising and keeping up with the Joneses. 

Note for myself: We sometimes veer into the self-help category in this book club, which is almost the archetype for this argument.

If we recognise the above, we can start to see why consumerism must fall, and what we can replace it with.

**Symbiotic Collaboration**
Symbiosis is fundamental to evolution. From a bacterial level and up. This is just as good a metaphor as Survival of the Fittest for societies purposes. Our survival as humans relied and relies on mutual cooperation. Of course, it's not either or. As usual, the answer is in the middle. This is novelty vs tradition and conservatism, we need both.

It's hard to not be competitive, we're wired for fight or flight responses. "Modern society is founded on stress"

**Flow**
Flow "brings with it one of the highest levels of fulfillment it is possible for human beings to experience"
It doesn't matter where you get it from, so aim for environmentally friendly flow.

**Comment by josh-flood** [comment]
Summary notes of discussion:

On competition vs symbiosis

How much do we really see these in society?

Chapter 6 did resonate & mostly on board - but is the point more to drive the conversation towards how to move forward?

The book finally comes to a point - ties growth into capitalism and human behaviour and asks the question how do we move forward?

Would be a tough sell to just say stop growing. So it is good that it is steering towards this question.

Darwinism has permeated our society - 'survival of the fittest'. This ignores the other part of nature which is symbiotic relationships.
Multicellular life would not exist without collaboration. Competition in nature is balanced with cooperation / collaboration.

One idea is to change the narrative / metaphor to start changing society.

Maybe it is more rooted in times of scarcity?

Growth matters when there is a material insufficiency - bringing everyone up to a certain standard. But capitalism doesn't give an answer about when to stop - what is the sufficient standard & how do we stop or slow down once it is reached?

Are we even at that point yet? There are still so many people living in poverty despite all the growth.

Chapter 7 introduces quadrant: novelty <-> tradition & self <-> other

Perhaps we've always wanted to be in the novelty / self quadrant & capitalism has just enabled us to get there (rather than it driving us there). Humans have been competing with one other long before capitalism.

How do we convince people to pivot what they are competing on? People are addicted to things that are bad for them.

Book says 'balance is required' but that is not particularly helpful in the face of things like addiction.

We think we're competing on happiness - but really we're trading on discontent. Always comparing ourselves to others.

Capitalism is good at growth - but not good at protecting the environment or providing stability (markets have crashed several times).

Is increasing demand inherently bad? Or only in the context of limited resources.

A frustration with the book: it often has frivolous footnotes while simultaneously failing to provide backing for main points.

Virtuous cycle / flywheel. Are we really worse off? It is hard to find something to compare to.

Many places have the same cycles of spending but at different volumes. Would be interesting to compare this between different countries with an eye on where money flows.

We understand how to increase productivity in developing countries, but will it be the same cycle of over production leading to depression? Particularly if the rest of the world has moved on & no longer wants to consume the excess.

America gets a cold - the rest of the world gets the flu. Knock on effects.

Chapter 7 teaser: One good thing is for people to be working. It is also good for people to get into a flow state - one of the highest levels of fulfilment in human life. How do we create the conditions for more people to be able to be in a flow state in work & life?

**Comment by kunzmann** [comment]
Summary notes of discussion:

On competition vs symbiosis

How much do we really see these in society?

Chapter 6 did resonate & mostly on board - but is the point more to drive the conversation towards how to move forward?

The book finally comes to a point - ties growth into capitalism and human behaviour and asks the question how do we move forward?

Would be a tough sell to just say stop growing. So it is good that it is steering towards this question.

Darwinism has permeated our society - 'survival of the fittest'. This ignores the other part of nature which is symbiotic relationships.
Multicellular life would not exist without collaboration. Competition in nature is balanced with cooperation / collaboration.

One idea is to change the narrative / metaphor to start changing society.

Maybe it is more rooted in times of scarcity?

Growth matters when there is a material insufficiency - bringing everyone up to a certain standard. But capitalism doesn't give an answer about when to stop - what is the sufficient standard & how do we stop or slow down once it is reached?

Are we even at that point yet? There are still so many people living in poverty despite all the growth.

Chapter 7 introduces quadrant: novelty <-> tradition & self <-> other

Perhaps we've always wanted to be in the novelty / self quadrant & capitalism has just enabled us to get there (rather than it driving us there). Humans have been competing with one other long before capitalism.

How do we convince people to pivot what they are competing on? People are addicted to things that are bad for them.

Book says 'balance is required' but that is not particularly helpful in the face of things like addiction.

We think we're competing on happiness - but really we're trading on discontent. Always comparing ourselves to others.

Capitalism is good at growth - but not good at protecting the environment or providing stability (markets have crashed several times).

Is increasing demand inherently bad? Or only in the context of limited resources.

A frustration with the book: it often has frivolous footnotes while simultaneously failing to provide backing for main points.

Virtuous cycle / flywheel. Are we really worse off? It is hard to find something to compare to.

Many places have the same cycles of spending but at different volumes. Would be interesting to compare this between different countries with an eye on where money flows.

We understand how to increase productivity in developing countries, but will it be the same cycle of over production leading to depression? Particularly if the rest of the world has moved on & no longer wants to consume the excess.

America gets a cold - the rest of the world gets the flu. Knock on effects.

Chapter 7 teaser: One good thing is for people to be working. It is also good for people to get into a flow state - one of the highest levels of fulfilment in human life. How do we create the conditions for more people to be able to be in a flow state in work & life?
