### ISSUE TITLE
Post Growth, 4th April: Chapter 7

### ISSUE THREAD

**Issue by mcgain** [Blackmill/book-club#181]
Book: Post Growth by Tim Jackson
Link: https://abookapart.com/products/inclusive-design-communities

Aiming to read:
    Chapter 7: The Return to Work   

MC: @elle 
Notes: @mcgain 

See you all at 12pm AEST, April 4th @ https://blackmill.co/meet

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via [gday@blackmill.co](mailto:gday@blackmill.co).

**Comment by mcgain** [comment]
My impressions of Chapter 7.

Work is good, work brings fulfilment. "Work is essential to the human condition"

Covid helped us realise that all the badly paid, undervalued jobs like cleaning, teaching and nursing are actually essential

Also, we don't value unpaid labour such as domestic chores, parenting, caring for relatives etc.

labour != work. "Labour maintains the conditions for life". Work is the stuff capitalism values.

Physical labour is valuable, but society doesn't consider it such, instead, we go to the gym

Creative work gives us flow, which is the best state to be in.

Actual work doesn't really look like that most of the time. There are many "Bullshit Jobs". 

Robots will enslave us all

**Comment by elle** [comment]
## 7: The return to work

> Sputnik also heralded a new relationship between humanity and planet earth...It was a reminder that ‘the Earth is the very quintessence of the human condition’. And nature itself, ‘for all we know, may be unique in the universe in providing human beings with a habitat in which they can move and breathe without effort and without artifice’.

p. 108

> For Carl Sagan, it was the beginning of that quest for life elsewhere... ‘one step toward escape from [our] imprisonment to the earth’.

Why?

Hannah Arendt: appeal for reflection in a complacent world that is trivial and empty

### Life on the frontline

- Frontline: essential roles during covid, people who are used and overworked and underpaid, negative surplus
- Market economy (surplus income) vs subsistence economy (supporting to a minimum level)

### Labour's love lost

- Labour -- maintains the conditions for life, ie baseline for health, foundation for society to flourish. Examples: parenting, caring for the elderly, housework, unpaid, around human existence (growth, metabolism, decay), physical work around biological necessities
- Work -- not really defined in this section of the book

> we will drive to the gym, sign up to exercise classes, train for marathons, just to retrieve that sense of physical wellbeing that comes from an active physical life. And we will do all this while barely noticing that we live in a society where physical labour is denigrated as unpleasant, unnecessary and unrewarding.

### Love and Saint Augustine

According to Arendt: the only true happiness lies in labour - because it is part of being alive -- which is why any of these jobs are named purposeful and thus pay less

> In its purest form, it is a state where the future is diminished to nothing, the past is irrelevant and only the present remains. ‘The happy life is the life we cannot lose,’

Present is happiness. Also, how many engineers do we know that find refuge in making things by hand??

> The human response to a world of impermanence is to try and construct a world of permanence: a world that is not entirely and incessantly subject to the unforgiving cycle of regeneration and decay.

The need for maintenance

### The rewards of flow

> Whereas labour involves care and sustenance, work is the domain of creation and creativity. It calls on craft and skill and vision. It is about the dreaming of dreams and the making of things.

Finally a definition of work.

Work has an enormous potential for fulfilment.

> Csikszentmihalyi notes that people often experience flow at work more easily than they do in their leisure time, particularly in a world overloaded with vicarious, passive pleasures. Work is the place where skills develop and challenges are met.

Are there not skills developed in the home while growing your family??

> Flow erodes the boundary between self and the world.

Big statement, with no support material. Also for:

> But for the duration of the task at least, the experience of flow allows us to dispense with the necessities of the ego and to merge individual action into the building of a common endeavour.

### Bullshit jobs

- Jobs that are neither satisfying nor valuable to society

> The aim of world-building is to offer us security. To be successful in that task, human artefacts must endure over time. They must abide. They must offer the permanence that is missing from the natural world. Without this quality of durability, the human world fails in its most essential task: to offset the anxiety of our own impermanence, to diminish the fear that continually undermines our happiness.

--
> Durability is the first casualty of the restless innovation that keeps capitalism going. Craft and creativity are subjugated to mass production in pursuit of increased efficiency and the expansion of profit.

And

> a persistent decline in durability dressed up as relentless novelty.

### The robots are coming

- Slow (card handwork) vs fast sector (automate all the things for higher productivity)

### The work of art

- Art is important to society - why?? transcendence??

> In the hands of a raw and unbridled capitalism, even what seems like decent work is already corrupted.

- Transformative power of connection to others

### The life of the mind

> Amongst those rewards is the ability to ‘think what we are doing’. And by doing so, to reap the benefits that come from understanding the human condition and finding our place in the world.
