### ISSUE TITLE
Financial Intelligence: Preface, Part One 1 & 2

### ISSUE THREAD

**Issue by lachlanhardy** [Blackmill/book-club#183]
Book: Financial Intelligence by Karen Berman and Joe Knight with John Case
Link: https://financialintelligencebook.com/

Aiming to read:
    Preface
    Part One: Section 1: You Can't Always Trust the Numbers
    Part One: Section 2: Spotting Assumptions, Estimates, and Biases

MC: @HashNotAdam 
Notes: @mcgain 

See you all at 12pm AEST, May 2nd @ https://blackmill.co/meet

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via [gday@blackmill.co](mailto:gday@blackmill.co).

**Comment by mcgain** [comment]
### Preface
This book will teach us four things:
* Understanding the foundation (of financial measurement)
* Understanding the art (of quantifying the unclear)
* Understanding analysis (in order to make better decisions)
* Understanding the big picture (where finances are but a part of the wider context)

And prompt us to take these actions:
* Speak the language
* Ask questions
* Use the information in our jobs

### Part One
## Chapter 1: You can't always trust the numbers

Accounting and finance turn out to be vague and full of manipulation, as they're not an exact science. It's more of an Art, and bias can influence the numbers. Bias is not a criticism, but a measure of the numbers being skewed in a particular direction.

**Income Statement**
Shows revenue, profit etc. for a period. Also called a profit and loss statement, statement of earnings or more

Sometimes, judgement calls must be made such as to when to count an order. When it's delivered? Ordered? Paid for? Is it CapEx or OpEx?

**Operating Expenses (OpEx)**
The costs to keep a business going from day to day. Salaries, rent, power bills etc. These are listed on the Income Statement and are subtracted from Revenue to calculate the Profit

**Capital Expenditures (CapEx)**
The purchase of items that are long term investments, like new computers, or computer systems. These do not show up on the Income Statement, but the Depreciation of those investments do. Instead, they show up on a Balance Sheet

## Chapter 2: Spotting Assumptions, Estimates and Biases
 
What questions should we ask about financial numbers?
* What were the assumptions in this number?
* Are there any estimates in the number?
* What is the bias those assumptions and estimates lead to?
* What are the implications?

**Accruals**
The portion of a revenue or expense item that is recorded in a particular time span. The idea is to match costs to revenues so you know how much something costs. Product development 

It's important to know what the costs were when developing a new product in order to figure out how to price the product, and ultimately, to know how much money you made from it verses how much it cost is. 

**Allocations**
The appointments of costs to different departments or activities within a company.

Allocating and accruing is an art, you can make the books look very different by moving things around. Development costs go into the R&D book, but the cost of raw materials to make a product goes into the cost of goods sold, and so affects the gross profit.

**Depreciation**
A method to allocate the cost of equipment and other assets to different products and services (as shown on the Income Statement). The idea is to match closely the cost of the products and services with what's sold. 

Valuing a company is hard, there are a bunch of methodologies, all useful in one way or another.
* Price to earnings ratio (compare the earnings of the company with its peers in the market)
* Discounted cash flow (How much money does the company make each year, you're effectively buying that cashflow)
* Asset valuation (How much stuff does the company own and what is it worth?)

There are many other methods of valuation, but they are less reliable.

All methods, even the reliable ones, are built on many assumptions and biases.
