### ISSUE TITLE
June 11: Primed to perform chapters 5-6

### ISSUE THREAD

**Issue by mcgain** [Blackmill/book-club#19]
Primed to Perform](https://www.amazon.com/Primed-Perform-Performing-Cultures-Motivation-ebook/dp/B00S590OQI)

Aiming to read:

- Chapter 5: The Blame Bias
- Chapter 6: Frozen or Fluid

MC: @elle
Notes: @antoinemacia

See you Tuesday in Zoom:

Join Zoom Meeting
https://zoom.us/j/914785529

Topic: Blackmill Book Club
Time: Jun 11, 2019 12:00 PM Canberra, Melbourne, Sydney
Every week on Tuesday. First one: Mar 26, 2019 12:00 PM

Please download and import the following iCalendar (.ics) files to your calendar system.
Weekly: https://zoom.us/meeting/914785529/ics?icsToken=5dd411172ce371e9770226b355c2f163863fe4efff5e00b09866a6b7be767b09

One tap mobile
+61871501149,,914785529# Australia
+61280152088,,914785529# Australia

Dial by your location
+61 8 7150 1149 Australia
+61 2 8015 2088 Australia
Meeting ID: 914 785 529
Find your local number: https://zoom.us/u/abWGuMO6GJ

**Comment by elle** [comment]
## 5: The bias blame

### Our bias to blame causes us to lead through indirect motives

--

> Indirect motivators can lead to narrow, short-term increases in tactical performance that are easy to measure.

--

We look for reasons to explain outcomes that don't fit our intuition.

We find it hard to believe in random acts of kindness.

It takes very little to make someone feel like a citizen.

> Our intuition struggles to believe that people’s decisions can be so dramatically affected by small changes to their context.

Monopoly game: did I win because of skills? or privilege?

Same as with web application, we tend to blame ourselves, rather than the system.

> The more removed we are from someone, the more likely we are to blame them.

Fundamental attribution error

> Because the blame bias causes us to blame the player, not the game, we focus on prodding the player, not changing the game. The easiest way to prod is through indirect motivators. We concoct more potent sticks and carrots. We spend weeks on performance evaluations, but very little time on culture building. We invest all sorts of energy in hiring the right people and then underestimate the influence of our culture once they arrive.

Motivators survey: "Surprisingly, pay didn’t even make the top three—they ranked it fourth."

> Across each industry, employees believed that their colleagues had less total motivation than they did (see Figure 13). And not just a little bit less. On average people believed that their colleagues were 19 points lower on ToMo than they were!

**Antidote: believe people are motivated and have potential. Like a self fulfilling prophecy. "Pygmalion effect"**

> By tricking the officers into believing that some of their students were naturally high performers, the blame bias was eliminated. With no blame bias standing in the way, these leaders naturally became higher ToMo. For example, if high-CP students had a problem learning a military concept like VUCA, the leader didn’t blame the learners. It couldn’t be their fault because they had such high command potential. Therefore the leader is forced to confront the context rather than the individuals. ToMo increases. If average-CP students struggle with a concept, it is easier to blame them. When the learners are blamed, the leader naturally gravitates toward indirect motivators, and thus ToMo decreases. With it, performance decreases.

--
> The Pygmalion effect is the flip side of the blame bias. Once blame is eliminated, expectations increase. When expectations increase, a leader more naturally uses the principles of total motivation, which inevitably improve performance.

--
> high expectations create high performance, low expectations diminish it.

Treat people according to how we expect them to perform.

REAP model of feedback:

1. Remember: assume positive intent
1. Explain: come up with 5 possible scenarios to explain the behaviour
1. Ask: why?
1. Plan: together identify the root cause of the problem and develop a plan to remedy it

**Toyota Way "Genchi Genbutsu"**

**> Adaptive performance demands objectivity and an open mind.**

## 6: Frozen or fluid

### When we most need fluid organisations, we freeze them instead

> No one person can impose adaptability. That’s what culture is for.

Lemonade stands experiments: one groups was given space to play and experiment

Crossroads:

1. Foundation: focus on building a product, or a product and a culture.
1. Scale up: many opt for skills and quantities rather than cultural fit.
1. Institutionalising - around 150 people, organisations become too large for informal processes.
1. Renewal

Case study: Medallia

Medallia's founders: "culture is not secondary to our mission. It’s the only way to achieve the mission.”

> She’s lived in five different countries, where she realized that many things she took as fact were actually culturally determined.

--
> "...that, our modus operandi had been: ‘hire smart, talented, nonjerk people and they’ll do the right thing.’ But we realized that many smart, decent, good people were not coachable because they were afraid of not being perfect.”

--
> Pressman had struggled to codify the criteria for the culture interview. She and Hald still wanted their “no jerks” culture, but in reality, they were searching for something more nuanced than just decency. They could have crossed their fingers and hoped to hire people who naturally saw the world their way. But they decided to develop a scalable framework for the culture interview by hiring a psychology doctoral student from Stanford.

--
> the difference between average and distinctive performance lay in a person’s whys.

Induction / onboarding: a week long onboarding program:

1. Welcome letter and two gifts: fitbit to grow your health and wellbeing, and a kindle to grow your mind
1. On the first day, new hires are asked to do something to make the company a better place
1. Each person is asked to do something to challenge their self-imposed barriers to personal growth
1. Hiring manager describes the special spark that led to the job offer

> Today, Medallia has one culture leader for every two hundred fifty people, a data scientist who applies rigorous metrics to culture and performance, and over twenty certified cultural interviewers.

--
> Onboarding primes play, but it’s not enough to maintain a high–total motivation culture.

- Leaders are taught to actively combat the blame bias and assume good intent.
- Create space for play
- People meet weekly to share what they've learnt and celebrate victories - to increase play and purpose, of feeling sense of belonging and pride in their work
- Performance reviews are more about self-reflection exercises, and review conversations about what they've learnt. Feedback is designed to help that person grow, not to establish a year-end grade.
- Career ladders to help people understand the skills they need to learn over time. The ladder criteria include tactical skills for each role, as well as cultural and leadership behaviours.

> “If you look at the cost per hire alone, our culture programs more than pay for themselves.”

**“a tree that is unbending is easily broken.”**

Summary:

- The objective of a high-performance culture is to maximise adaptability.
- Adaptive organisations require adaptive individuals—people with high levels of creativity, problem solving, persistence, and citizenship.
- ​Individuals adapt when they have high total motivation. The more that people work for the direct motives, and the less that people work for the indirect motives, the more adaptive they will be.
- ​Great organisations build high-ToMo cultures. They resist their bias to blame individuals. They resist the temptation to freeze. They balance the yin and yang of tactical and adaptive performance.

**Comment by lachlanhardy** [comment]
Added notes to main file: https://github.com/Blackmill/book-club/blob/master/primed-to-perform.md
