### ISSUE TITLE
Empowered: November 8: chapters 19–25

### ISSUE THREAD

**Issue by HashNotAdam** [Blackmill/book-club#201]
Book: [Empowered](https://www.goodreads.com/en/book/show/53481975) by Marty Cagan and Chris Jones

Aiming to read:

Chapters 19–25
MC: @elle 
Notes: @HashNotAdam

See you all at 12pm AEST, November 8th @ https://blackmill.whereby.com/bookclub

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via [gday@blackmill.co](mailto:gday@blackmill.co).

**Comment by elle** [comment]
### 19: Customer-centricity

- Comes from the top
- True customer - of the customer facing products, rather than  stakeholders, internal users or advertising partners
- Customer story telling 
- 3 x one-hour customer interactions per week

### 20: integrity

- Integrity is the foundation for good decision making
- The product manager is the messenger - passing bits of informations between all involved
- Dependability: to establish trust and thus move work forward. Make promises they can deliver on

> This means not making a commitment unless and until her product team has had the opportunity to do sufficient product discovery to reasonably consider the risks of value, usability, feasibility, and viability. And just to be explicit, that means leaning on the expertise and experience of the designer and engineers.

- Company's best interests perceived as acting in the best interests of the company, not just the team's. And share the overall purpose of the work with the team.
- Accountability: willingness to take responsibility for mistakes and reflecting on what could have been done bette.

### 21: decisions

- Empowered teams -> pushing decisions down to the product team level
- Want good decisions that lead to good outcomes. We want leaders and stakeholders to understand and respect our rationale
- Right-size decision analysis - level of risk and consequences
- Collaboration-based decision making - not consensus model or voting model. Or even benevolent dictator model. But rather decisions around value??
- Resolving disagreements - by running tests and collecting data
- Transparency - written narrative with FAQ section
- Disagree and commit 

### 22: effective meetings

- Synchronous meetings with relevant stakeholders

> If there's a way to serve the purpose asynchronously, then that's generally a better path. A status update or communicating information about a new release are great examples.
- 3 types:
  - Communication - for example all hands
  - Decisions - use narrative writing to help inform decisions
  - Problem solving - post-mortem
- Organising effective meetings
  - Purpose: why are we meeting
  - Attendees: be careful with who attends the meeting, that they should be there
  - Preparation
  - Facilitation
  - Followup

> the bottom line for meetings is (a) make sure that if you call a meeting it is truly necessary and warrants the time of all the attendees, and (b) prepare for the meeting to make sure it is efficient, effective, and accomplishes its purpose.

### 23: Ethics

4 big risks:

1. Will the customer buy it, or choose to use it? (Value risk)
2. Can the user figure out how to use it? (Usability risk)
3. Can we build it? (Feasibility risk)
4. Can the stakeholders support this solution? (Business viability risk)

And rather than add ethics under business viability, add a fifth one:

5. Should we build it? (Ethical risk)

And a question the team should ask: how does ethics apply yo me in my job?

> Good product teams need to understand the implications of the solutions they're designing—not just on revenues, but on that broader stakeholder community.

https://calebhearth.com/dont-get-distracted

And what to do if you identify an ethical issue?

> Speak up in a thoughtful way, raise your concerns, but not in a holier than thou nor accusatory way. Try to explain in a way that makes it clear that you care about protecting the best interests of the company.

### 24: Happiness

Manager's job is not the employee's happiness but rather their job is to make sure they are not unhappy or miserable.

"What is happiness?"

- Meaningful work - discuss and reinforce why we do this work, in public and private
- Personal relationship
- Personal recognition
- Work habits
- Modelling good behaviours: role model the behaviour you wish to see
- Career planning


### 25: leader profile: Lisa Kavanough
#### Path to leadership

4 key skills:

1. **Self awareness**: what are the behaviours that may have served you well earlier in your career, but now are no longer advantages?
2. **Courage**: going forward despite discomfort, having the courage to let go
3. **Rules of engagement**: trust their teams while still ultimately being responsible for successful outcomes. Rules of engagement are simply an agreement with the teams on what type of visibility the leader needs in order to give the teams the space they need to work. What information does the leader need in order to trust? What context does the team need to understand to be successful? What does the team need to feel safe in surfacing risks and problems early or asking for help?
4. **Disrupting yourself**: working on long-held habits and commit to change


Review of Part 2

**Comment by HashNotAdam** [comment]
# Discussion

1. **Ethics in Business and Technology:**
  - The group discussed how businesses often prioritise viability over ethics. This issue was highlighted with examples, such as the ethical responsibilities of software engineers in situations where technology could have unintended consequences.
  - A key point was the need for businesses to consider ethical implications from the start, rather than as an afterthought.
 
2. **Airbnb and Ethical Business Practices:**
  - A detailed conversation focused on Airbnb, questioning whether its business model is ethical, considering its impact on rental markets and local communities. The discussion included a debate on the extent to which Airbnb is responsible for rental problems in Australia.
  - The group discussed regulatory measures taken in some areas, such as limiting the duration a property can be listed on Airbnb, and debated if Airbnb as a company is unethical or if it's the misuse of its platform that raises ethical issues.
 
3. **Cryptocurrency and Regulation:**
  - Cryptocurrency was discussed in the context of its ethical challenges, particularly the lack of regulation in its early stages and how this freedom attracted users. The group pondered the balance between innovation and ethical responsibility in the realm of cryptocurrency.
 
4. **Role of Individuals and Leaders in Upholding Ethics:**
  - Personal responsibility in maintaining ethical standards was emphasised, with a focus on the roles of individuals and leaders within companies. The discussion highlighted that while companies should have ethical frameworks, individual responsibility, especially in leadership, is crucial.
 
5. **Ethical Education and Training:**
  - Members shared their university experiences of studying ethics, specifically in computer science and software engineering courses. They discussed the approach to teaching ethics and its relevance in their professional fields.
 
6. **Real-World Examples of Ethical Dilemmas:**
  - Practical examples were given, such as a bug in a warehouse robot leading to an accident. This sparked a discussion on the chain of responsibility, from the individual engineer to higher management levels, in ethical scenarios within software development.
 
7. **Ethics in Decision-Making Processes:**
  - The group talked about integrating ethical considerations into decision-making processes in corporate environments. This included discussing cases like WeWork, focusing on the accountability of executives and the broader implications of their decisions.
 
8. **Ethical Implications in Specific Business Decisions:**
  - Examples discussed included the ethical considerations in business decisions like prioritising profit over societal impact, and the potential consequences of such choices.
