### ISSUE TITLE
Empowered: November 15: chapters 26–36 (Part 3)

### ISSUE THREAD

**Issue by HashNotAdam** [Blackmill/book-club#202]
Book: [Empowered](https://www.goodreads.com/en/book/show/53481975) by Marty Cagan and Chris Jones

Aiming to read:

Chapters 26–36 (Part 3)
MC: @kunzmann
Notes: @elle

See you all at 12pm AEST, November 15th @ https://blackmill.whereby.com/bookclub

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via [gday@blackmill.co](mailto:gday@blackmill.co).

**Comment by elle** [comment]
## Part 3: staffing

### 26: Competence and character

> Trust is a function of two things: competence and character. Competence includes your capabilities, your skills, and your track record. Character includes your integrity, your motive, and your intent with people. Both are vital.
> ~ Stephen Covey

- Competence:
  - Necessary skills or hire for potential (but in that case, coaching will be needed)
- Character:

> So rather than narrowing a very large pool of people to the small subset that are perceived as a cultural fit, I argue to instead keep the pool very large and just filter out the relatively few assholes... yet so many companies and managers hire either people who are cultural fits but not competent, or they justify hiring an asshole because they believe the person is exceptionally skilled.

**Discussion:**

In product, can understand the requirement for skills, but in engineering, hiring for a specific mindset and potential is important rather than knowledge in a specific framework. But even then you need some technical guidance in the team, to be able to coach and guide the people with less experience.

It is important to define what knowledge is required, and even this book fails to define that well.

Do not like writing people off as an asshole, because people can change, and it might depend on the context and environment. There are a lot of nuances in those situations. And the book argues that once again coaching might be useful.

10x developer is rebranded as an asshole engineer.

Some companies are afraid of firing someone because they know a specific part of the code. It can be job security -- when you do a thing that no one else can do, which can be a deliberate behaviour, working alone in the worst part of the codebase, and getting all the shit work. So there are two sides to each situation. So should look at the systemic structures that help create this situation.

It is the manager's responsibility to deal with a toxic person. You can blame the manager for basically everything -- for not taking action on x situation. But you should also evaluate if it was a good decision at the time.sla

### 27: Recruiting

- Do not rely on the HR manager
- Building a network of potential recruits is an ongoing activity
- Make this a priority

**Discussion:**

- Going to your network can mean that you hire people like you.
- Seems like they are advocating to not using recruiters.
- Between 4 hours on product management tasks, and hiring, there isn't any time left for anything else. But hiring someone will help do more things. Also delegation.

### 28: Interviewing

- Curate the interview team
- Alignment on what will be interviewed: skills and experience
- Objective: resolve any open questions
- Generally hire for competence, but sometimes hiring for potential is a bet and will require coaching
- Lacking domain knowledge can be a benefit, the right person with the right skills will also bring fresh perspective
- Fav interview question: stack rank competences in order of strongest to weakest: execution - creativity - strategy - growth

### 29: Hiring

- Do reference checks personally
- Check social media for any signs of aggression/thoughtless, how they interact with others

How about bring them in to work with them and see how they communicate??

### 30: Remote employees

- Two major types of activities: discovery and delivery
- Delivery is easier to accomplish while working remotely
- Discovery less so. Communication flows easier when working synchronously. Working remotely impacts dynamics of how the product manager, product designer and tech lead collaborate to discover a solution worth building
- And what we get is artefacts in the shape of online documentation rather than prototypes
- Trust: Discovery requires trust and psychological safety -- but some candid feedback is harder to give async and thus chances of damaging trust are higher.
- Time: Also async discovery takes longer.

**Discussion:**

- Starting a project is easier when people are in the same room, bouncing ideas and aligning on the work
- Audio open channels are useful for connections
- Beware of video call fatigue

### 31: Onboarding

- Good onboarding saves countless hours of grief and damage control
- Establish competencies
- Establish solid relationships: with the team, execs, stakeholders... and learning about all the different business functions
- Exposure to true users and customers
- APM programs: stands for Associate Product Managers

**Discussion:**

- So many companies do it badly and not assign a buddy to new people
- Harder remotely

#### Helpful checkpoints

- At the end of her first day. Has she made at least one hopefully future friend on the team? Does she know what is expected of her?
- At the end of her first week. How was her first week? Has she had a chance to get to know personally every member of her product team?
- After she receives her first pay check. It's normal for the new employee to do a subconscious assessment of the choice she made in joining your company.
- After her first month. At this point, the new employee has a fairly good idea of the company and her potential in it.
- After her first 60 days. Has she scored a public “win” that helps establish her value to the company?
 
### 32: New employee bootcamp

> New‐hire orientations, while they're great for helping a new employee feel welcomed and integrated into the organization, fall far short in preparing product people on some of the more important aspects of their role. Things like making hard decisions and gaining a high level of trust among peers.

Questions to consider when designing the bootcamp for PMs:

- How are decisions made? How have they been made in the past?
- What is important to the company now? What are we working toward?
- How can I get people to trust me?
- What's the most important thing to do right now?

Exercises may include:

- Strategic context
  - Sharing vision, financial models, customer discovery, who the customers are (past and future)
- Intro sessions from product people or similar to tell stories from own personal experience
  - Establish relationships and trust
- Product  workshop

> The Bootcamp reinforces a culture of learning and growth. When the product person leaves the Bootcamp she's not asking, “What do I do today?” She already knows the next, right thing to do. She's equipped to make decisions quickly and the relationships she's already built help her get to results faster.
> 
> This is how we empower product people—by providing them with the information they need to succeed and then trusting them to do the right thing.

**Discussion:**

- Might be more suitable to a big company with more resources
- Shopify did bootcamp when they were 25. Github when they were 600.

### 33: Performance reviews

- Should not be the primary feedback tool
- Use one:ones for ongoing feedback

### 34: Terminating

- Don't only consider the problem employee, but also consider the rest of the team that is having to deal with the issues and carry the burden. As well as the message it sends to the team and broader organisation by not correcting the problem
- There might be compliance-related responsibilities
- Toxic people are usually coupled with great skills. However...

> But in every case, I've found that removing the toxic person was the right thing to do, and that others in the organization would rise to the occasion and the broader organization was grateful for the improvement in the workplace atmosphere.

### 35: Promoting

- Most tangible sign of success as a manager is when their reports get promoted
- Need to provide a clear path to the next career goal - but performing an assessment of current knowledge and skills against what is required for the new role. This generate a list of gaps to work through and discuss how they can learn and demonstrate necessary skills. Might be useful to run through self-assessment to compare with manager's assessment.
- When people are ready, sometimes the organisation isn't (no opening for the role)
- When promoting ICs to management positions -> brand new set of skills. Should be done for the right reasons. Higher pay shouldn't be a good reason for this career change.
- Promotion -> retention
- Managers who promote reports will attract people wanting to work with them

### 36: Leader profile: April Underwood

- Product manager archetypes are dictated by the market requirements

> The best product leaders are not just great at defining and building products—they understand that a product is only as good as a target customer's understanding of why they need it. That a platform is only useful if it's being used in ways which accrue value to the developers building on it as well as their customers. That products must be built within a set of constraints that preserve the health of the business.
> 
> These insights—the purviews of marketing, partnerships, finance, and so many other functions—are important inputs to building products.
