### ISSUE TITLE
Empowered: November 22: chapters 37–44 (Part 4 and some of Part 5)

### ISSUE THREAD

**Issue by lachlanhardy** [Blackmill/book-club#203]
Book: [Empowered](https://www.goodreads.com/en/book/show/53481975) by Marty Cagan and Chris Jones

Aiming to read:

Chapters 37–44 (Part 4 and some of Part 5)
MC: @lachlanhardy
Notes: @kunzman

See you all at 12pm AEST, November 22nd @ https://blackmill.whereby.com/bookclub

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via [gday@blackmill.co](mailto:gday@blackmill.co).

**Comment by kunzmann** [comment]
Part IV: Product Vision & Principles

How do we deliver on the mission statement?
- create a compelling product vision
  - keeps focus on customer
  - north star for product org
  - inspires people
  - meaningful work - how you can positively impact lives of customers, not feature lists
  - leverages industry trends
  - clarity of future so architecture will support future efforts
  - evangelism tool - can help recruit strong product people

Session notes:
- sharing Roadmap vs Vision externally
  - we like seeing roadmap sometimes, but feature lists can be risky - seen as a commitment or is outdated once you change focus
- business outcome (contract signed) vs feature that is actually used
  - how do we feel about it as engineers?
  - is the customer important enough to tick boxes?
- some samples (like in Part V) would have helped here
  - part seems a bit undercooked because it was allegedly covered in a previous book
- reminded of first 90 days STARS model:
  - Start-Up
  - Turnaround
  - Accelerated growth
  - Realignment
  - Sustaining success

37. Creating a compelling vision
What is a strong product vision?
- customer centric - solve problems for the customer
- tells from the perspective of users and customers - how will it improve their lives
- provides a north star
  - align multiple product teams to row in the same direction
  - what is the end game?
- scope & timeframe
  - 3-10 years
- leveraging industry trends
  - discern between fads & trends
  - which trends are relevant
  - mobile / cloud computing / big data / machine learning / AR / IOT / edge computing / cosumerization of the enterprise
  - real trends are not fleeting
  - don't lose site of solving actual customer problems
- CEO or GM will need to feel connected to this vision, to be able to sell it externally

38. Sharing the product vision
How to communicate?
- vision type video
  - describes the future world
- storyboarding
  - emotion, not details
- recruiting / evangelism tool
- architecture / team topology could be informed by a good product vision

39. Product principles and ethics
Product principles
- ease of use vs security
- ethics - malicious use

40. Leader profile: Audrey Crane
- Theatre background informed leadership approach
  - working toward common goal with diverse set of skills
  - working within budget constraints
  - no 'line readings' - directors stand back & let experts deliver
  - help people bring their best
  - believe in people, with high expectations
  - give clear constructive feedback
  - celebration

Part V: Team Topology
- how many product teams should we have?
- with what scope & responsibility?
- what skills are needed on these teams?
- what are the dependencies between teams?
- remote teams bring added complexity
- will need to evolve over time, engineering leaders & product leaders working together

Session notes:
- team topology drift - initial team structure no longer relevant to current business focus
- reporting structure / cross functional teams
- internal design agency model doesn't work if designers aren't 'on the team'
- really good platform teams can reduce the need for individual designer / infra assigned to a cross functional team
- bit of discussion about Culture Amp matrix model (no longer in use)
  - guild / hr / career
- bit of discussion about platform teams & group examples of how vision has impacted team topology or architecture successfully

41. Optimizing for empowerment
- ownership
  - teams need to be empowered to make the changes they need to make
  - cognitive load
- autonomy
  - when problems are given, they have enough control to solve it in the way they see fit
  - minimising dependencies makes this easier
- alignment
  - architecture
  - business

42. Team Types
- platform teams
  - common services written once and shared between many product teams
  - high leverage
  - reduce cognitive load of other teams
- experience teams
  - UX of users: Apps / UIs / Journeys
  - customer facing or customer enabling
  - could be divided by user type / marketer segment / step in journey

43. Empowering platform teams
- enable experience teams - indirect impact
- keep the lights on - bugfix / performance & compliance issues between 10-50%
- shared team objectives with experience teams
  - example add video into cms
  - ecommerce company adds new payment type
- some companies have started treating internal platforms like external ones

44. Empowering experience teams
- topology aligned by customer
  - user type or persona
    - riders / drivers
  - market segment
    - electronics / fashion
  - customer journey
    - onboarding team / retention
  - sales channel
    - self service / direct sales
  - business kpi
    - new user growth / conversion
  - geography
    - north america / apac
- reporting structure (e.g. by tech domain) doesn't have to map to cross functional team
