### ISSUE TITLE
Storytelling with Data: January 31st - Intro and chapter 1

### ISSUE THREAD

**Issue by lachlanhardy** [Blackmill/book-club#207]
Book: [Storytelling with Data](https://www.storytellingwithdata.com/books) by Cole Nussbaumer Knaflic

Aiming to read:

Chapters: Intro and chapter 1
MC: @elle  
Notes: Josh

See you all at 12pm AEDT, January 31st @ https://blackmill.whereby.com/bookclub

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via [gday@blackmill.co](mailto:gday@blackmill.co).

**Comment by elle** [comment]
# Storytelling with data

by Cole Nussbaumer Knaflic

# Intro

- Bad graphs are everywhere. Easy to create nowadays with increased access and proficiency in   tools to work with data
- There is a story in the data
- **Q: When I’m asked to show the data, I feel…**
- Telling stories with data is becoming more important skill in a data-filled world for data-driven decision-making
- Area where business and mathematics intersect — and using data to inform and influence better business decisions

Google’s Oxygen project

[[How Google Sold Its Engineers on Management](https://hbr.org/2013/12/how-google-sold-its-engineers-on-management)](https://hbr.org/2013/12/how-google-sold-its-engineers-on-management)

[[Project Oxygen: An inside look at what makes a good manager](https://www.betterup.com/blog/project-oxygen)](https://www.betterup.com/blog/project-oxygen)

Six key lessons:

1. Understand the context
2. Choose an appropriate visual display
3. Eliminate clutter
4. Focus attention where you want it
5. Think like a designer
6. Tell a story

<img width="1188" alt="six-key-lessons" src="https://github.com/Blackmill/book-club/assets/57038/7d27ef10-1933-4852-9595-cb376db9023f">

# Chapter 1: the importance of context

- Project success does not start with data visualisation
- Start by understanding the context

## Exploratory vs explanatory analysis

> *Exploratory analysis is what you do to understand the data and figure out what might be noteworthy or interesting to highlight to others.*
> 

> *When we’re at the point of communicating our analysis to our audience, we really want to be in the explanatory space, meaning you have a specific thing you want to explain, a specific story you want to tell*
> 
- Displaying exploratory data is not useful. It might be tempting to display the robustness of the analysis, or all the evidence.
- Focus on what the audience needs to know

## Who, what, and how

Questions to ask:

- To **whom** are you communicating? — who is the **audience** to ensure they hear the message
- **What** do you want the audience to know? — be clear on how **you** want the audience to act
- **How** can you use the data to make your point? — desired **action**

### Audience

- Too broad is not good, cause you can not communicate with different people with different needs the same way → ineffective communication
- Identifying the decision maker is one way to narrow the audience group → we will be better positioned to understand how to resonate with them and communicate in a way that will meet their needs

### You

- Does the audience already trust you? or do you need to establish credibility?
- These questions influence how we present the findings and structuring the communication

### Action

- What do you need your audience to know or do?
- By having a clear understanding of why they should care about this
- Misconception: the audience knows more than the presenter — but the presenter is the SME

> *This puts you in a unique position to interpret the data and help lead people to understanding and action.*

**Prompting action**

Here are some action words to help act as thought starters as you determine what you are asking of your audience:

```jsx
accept | agree | begin | believe | change | collaborate | commence | create | defend | desire | differentiate | do | empathize | empower | encourage | engage | establish | examine | facilitate | familiarize | form | implement | include | influence | invest | invigorate | know | learn | like | persuade | plan | promote | pursue | recommend | receive | remember | report | respond | secure | support | simplify | start | try | understand | validate
```

## Mechanism

- How will you communicate to your audience?
- A range from live presso to written doc → amount of control we have vs the level of details needed

<img width="594" alt="mechnism-continuu,m" src="https://github.com/Blackmill/book-club/assets/57038/5ce50c5d-4948-4af8-8337-3f08f4b1fcac">

- Slidument

## Tone

- What tone do you want your communications to set?

## How?

- What data is available that will help make my point?
- Data becomes supporting evidence of the story to tell

## Example

- **Who**: The budget committee that can approve funding for continuation of the summer learning program.
- **What**: The summer learning program on science was a success; please approve budget of $X to continue.
- **How**: Illustrate success with data collected through the survey conducted before and after the pilot program.

When working on crafting the communication, here are more questions to ask:

- What background information is relevant or essential?
- Who is the audience or decision maker? What do we know about them?
- What biases does our audience have that might make them supportive of or resistant to our message?
- What data is available that would strengthen our case? Is our audience familiar with this data, or is it new?
- Where are the risks: what factors could weaken our case and do we need to proactively address them?
- What would a successful outcome look like?
- If you only had a limited amount of time or a single sentence to tell your audience what they need to know, what would you say?

## The 3-minutes story and big idea

- Boil down the “so what?” into one paragraph → and then down even more, to a concise single statement (reminds me of “Other people matter”)
- If you had 3 minutes to tell your audience what they need to know, what would you say? → a great way to ensure that we are clear and can articulate the message (Webjam)
- Elevator pitch!!
- The Big Idea boils it down to a one sentence with three components:
    - It must articulate your unique point of view (POV);
    - It must convey what’s at stake; and
    - It must be a complete sentence

## Storyboarding

- Visual outline of the content
- Establishes a structure for the communication
- Helps to think how the pieces fit together
- Don’t start with a presentation software
- Post-it notes are easy to move around and rearrange while exploring diifferent narrative flows

> *When it comes to explanatory analysis, being able to concisely articulate exactly who you want to communicate to and what you want to convey before you start to build content reduces iterations and helps ensure that the communication you build meets the intended purpose.*

**Comment by kunzmann** [comment]
Session notes - Storytelling with Data: Intro & Chapter 1

First impressions:
- All pretty new, new type of book
- Examples are appreciated

New idea of coming at the graphs / visuals from the perspective of who is going to be looking at the graph & what story  or message you want them to hear & what action do you want them to take.

Is it a bit manipulative? Maybe, but also it can be framed as being respectful of people's time. Cut to the chase, keep it simple.
Don't throw up the barrier of a convoluted, hard to understand visual to get through before you can actually talk about what you want to talk about.

Data folks might find it hard to get out of the weeds and distil the insights from the data to others.

How do you feel about creating data visuals?

- depends on context, if it is to present a success story, perhaps excited, if it is to show how something is not performing well, maybe dread
- intimidated - how do you even gather the data
- pretty neutral

How easy is it to access the visual once it is created. Is it something that needs to be updated frequently and accessible?

What is the objective of the chart (context of rubocop todo items chart)?
- answer 'are we headed in the right direction?'
- encourage people by seeing the progress

Google Oxygen project
- HR - used data to convince managers to be better managers (i.e. work on leadership skills)

Might be worth also thinking about potential unintended (& unwanted) consequences of producing a visual. For example in in the Rubocop example, would this put pressure on contributors to avoid putting in legitimate TODOs - making mental notes instead or skipping certain things altogether.

Exploratory vs Explanatory analysis

Seems to be a presenter focus rather than audience. What does the audience want to learn from this?

Presenter has to be capable of a lot - deep data analysis & people skills.

Detail level + Level of control

Slidument - "a cross between a slide deck and a document"

Strategies for presenting visuals used in the groups experience, do you have a preference?
- Drawing the graph as you go. Gives you more control over where people are focused & you get to explain important bits along the way.
- Presenting it live gives you more control vs document which can be (mis)interpreted in isolation.
- Depends on the audience.
- Research up front, summarise & send out - then meet to discuss. It is harder to 'wing it' in some circumstances (e.g. a skeptical audience).
- Working out peoples motivations & storytelling is most important. You can show data on smoking & that won't convince many to quit.
- People want really simplified data - sometimes they just want a pie chart!

Reductive. Simplification can be good, but there is a point where it becomes unhelpful / absurd / facile.

"If I had more time, I would have written a shorter letter" - Blaise Pascal (or Mark Twain or whoever else!)

Graphs themselves are a useful skill set, but if you combine it with these more nuanced tips & storytelling it can be so much more impactful.
