### ISSUE TITLE
Storytelling with data: Feb 28: Chapter 5

### ISSUE THREAD

**Issue by lachlanhardy** [Blackmill/book-club#211]
Book: [Storytelling with Data](https://www.storytellingwithdata.com/books) by Cole Nussbaumer Knaflic

Aiming to read:

Chapter 5: think like a designer

MC:  @HashNotAdam 
Notes: @elisechant

See you all at 12pm AEDT, Feb 28th @ https://blackmill.whereby.com/bookclub

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via [gday@blackmill.co](mailto:gday@blackmill.co).

**Comment by elisechant** [comment]
General comments: 
* The book is discussing charts in isolation of context, it would be good to understand desired outcome. 
* A great supplement to the book could be - now that there is a nice data story established, how can this be adapted to suit different audiences. 

Discussed "Ticket volume over time" chart: 

![Screenshot 2024-02-28 at 1 03 05 pm](https://github.com/Blackmill/book-club/assets/2195815/8022785b-3436-4e4a-89df-57ade058a0ce)

* Even though adding text was something discussed, thoughts that this chart introduced too much text, eg 1 title not 2 titles, eg Inclusion of waffley "Data source" text.  
* Chart is still not articulating the volume of tickets that are behind. 
* Chart is not articulating why in the initial 2 months the employees were able to keep up with load. 
* Unclear from data provided why monthly ticket volume being serviced fluctuates so significantly. 
* Decoded that 1 employee can service roughly 15 tickets per month.
* Consensus that chart is still not providing clarity about why the issue is occurring. 

Discussed "Issues vs Satisfaction by model" chart: 

![Screenshot 2024-02-28 at 1 04 13 pm](https://github.com/Blackmill/book-club/assets/2195815/551b455a-d16f-4a2d-9740-e0586474774c)

* Agreement that there was also too much text, making the chart more unreadable.
* Difficultly with understanding raw data from y axis as direction had been reversed. 
* Acknowledged that people read this chart differently, and may have therefore interpretted a different data story.

Discussed "Peak Break-up Times" chart: 

![Screenshot 2024-02-28 at 1 03 54 pm](https://github.com/Blackmill/book-club/assets/2195815/e782f14d-5dd7-4cef-a25e-97028b5f19a9)

* Assumed US related, and therefore less breakups occurring over winter.
* Text was distracting from data set.
* Annotation description text was a bit sassy, and expressed author's commentary and not a qualified data point.
* Unable to extract much value from this chart without correlating with another metric, eg year-on-year, length of relationship etc.

Discussed "Acceptance" P149:

* Some considered Acceptance to be a bad idea. Not necessarily a bad thing if people do not accept, as it may take time for idea presented to settle on persons.
* Consideration to be give for pre-socialising data story in order to achieve Acceptance.

**Comment by elle** [comment]
# 5: think like a designer

- Form follows function

### Affordances

- Things that make it obvious how to use the product
- Good design fades into the background so we don’t even notice it

How?

1. Highlight the important stuff
    1. Bold, italics, and underlining → titles, labels, captions, and short word sequences
    2. Uppercase → short word sequences. Avoid using different fonts as a highlighting technique
    3. Colour → use sparingly
    4. Inversing elements → use sparingly
    5. Size
2. Eliminate distractions
    1. Not all data are equally important → use space to get rid of noncritical data
    2. When detail isn’t needed, summarise
    3. Test taking out the extra data
    4. Push necessary, but non-message impacting items to the background → to de-emphasise them. Light grey works well for this
3. Create a clear hierarchy of information

<img width="1125" alt="5-new-marriage-rates-by-education" src="https://github.com/Blackmill/book-club/assets/57038/bfc6b247-826f-472b-a653-c22276e99afa">

Line graphs → easier to see trends over time

### Accessibility

- Usable by people of widely varying technical skills
- Don’t over-complicate
    - If it’s hard to read, it’s hard to do
- With type choices:
    - Make it legible → consistent and easy-to-read typeface
    - Keep it clean → visual affordances
    - Use straightforward language → simple over complex, fewer over more words.Spell out acronyms
    - Remove unnecessary complexity → favour simple
- Text is your friend
    - Must haves: chart title, axis title/label
    - State in words the conclusion you want people to reach
    - Make important words stand out
    - Action titles - for example: “estimated 2015 spending is above budget” → setting expectations and ensuring audience will not miss it
    - Annotate important or interesting points directly on a graph - label the important metrics, rather than all the data points

<img width="523" alt="5-peak-breakup-times" src="https://github.com/Blackmill/book-club/assets/57038/6ae74611-6d8a-402d-aba9-bf346820b2db">

<img width="530" alt="5-tickets-example" src="https://github.com/Blackmill/book-club/assets/57038/6c0a51fc-212f-46c3-97b2-a7d1d0228807">

### Aesthetics

- Aesthetic design is perceived as easier to use and are more readily accepted and used over time…
- Mimic aspects from effective designs to create your own — stop to reflect why those designs are effective
- Be mindful with colour
- Pay attention to alignment
- Leverage white space
- Paying attention to detail signals respect for your data and audience

<img width="436" alt="5-distribution-by-customer-segment" src="https://github.com/Blackmill/book-club/assets/57038/8bd169fe-12e8-4fe3-ad4d-a2991c865aa3">

### Acceptance

- For a design to be effective, it must be accepted by its intended audience.
- People resist change because they are uncomfortable with the new and are familiar with the old.
- Strategies for gaining acceptance:
    - Articulate the benefits of the new or different approach
    - Show side by side to demonstrate a superior solution (before and after)
    - Provide multiple options and seek input
    - Get a vocal member of your audience on board - ask for feedback and incorporate it - buy-in
    - Test proposed design with someone who doesn’t have vested interest to ensure the design is effective. And also to confirm what they like and what question do they have.

> Hearing these things from a non-biased third party may help you uncover issues with your design that are leading to the adoption challenge you face with your audience. The conversation may also help you articulate talking points that will help you drive the acceptance you seek from your audience

<img width="1340" alt="5-recap" src="https://github.com/Blackmill/book-club/assets/57038/6754e2b3-0c2f-4247-a600-df4e821b47f0">
