### ISSUE TITLE
Getting to Yes – APR 03: Prefaces to start of II: The Method

### ISSUE THREAD

**Issue by lachlanhardy** [Blackmill/book-club#214]
Book: [Getting To Yes](https://en.wikipedia.org/wiki/Getting_to_Yes) by [Roger Fisher](https://en.wikipedia.org/wiki/Roger_Fisher_(academic)) and [William Ury](https://en.wikipedia.org/wiki/William_Ury)

Aiming to read:

- Preface to the Third Edition
- Preface to the Second Edition
- Acknowledgements
- Introduction
- Chapter 1: Don't Bargain Over Positions 

MC: @lachlanhardy 
Notes: @elle 

See you all at 12pm AEDT, April 30th @ https://blackmill.whereby.com/bookclub

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via [gday@blackmill.co](mailto:gday@blackmill.co).

**Comment by lachlanhardy** [comment]
Notes and thoughts on _Chapter 1: Don't Bargain Over Positions_

> The most common form of negotiation, illustrated by the above example, depends upon successively taking—and then giving up—a sequence of positions.

> Any method of negotiation may be fairly judged by three criteria: It should produce a wise agreement if agreement is possible. It should be efficient. And it should improve or at least not damage the relationship between the parties. (A wise agreement can be defined as one that meets the legitimate interests of each side to the extent possible, resolves conflicting interests fairly, is durable, and takes community interests into account.)

The most common form does not meet these criteria.

> Bargaining over positions creates incentives that stall settlement.

You start out extreme so that you can get to something reasonable. It's much simpler and more efficient to start at something reasonable and discuss the value of it.

> Positional bargaining becomes a contest of will. Each negotiator asserts what he will and won’t do. The task of jointly devising an acceptable solution tends to become a battle. Each side tries through sheer willpower to force the other to change its position.

> Each move you make within a negotiation is not only a move that deals with rent, salary, or other substantive questions; it also helps structure the rules of the game you are playing.

As with everything implicit, cultural background has a role to play here and you may find partway through a negotiation that the common understanding you expected is simply not there.

> [Their} method, called principled negotiation or negotiation on the merits, can be boiled down to four basic points. These four points define a straightforward method of negotiation that can be used under almost any circumstance. Each point deals with a basic element of negotiation, and suggests what you should do about it.
> 1. People: Separate the people from the problem.
> 2. Interests: Focus on interests, not positions.
> 3. Options: Invent multiple options looking for mutual gains before deciding what to do.
> 4. Criteria: Insist that the result be based on some objective standard.

> Proceed independent of trust.

This is remarkably deep and resonates with me strongly. How far can you proceed without determining trust or distrust? You need to trust that the other parties will comply with the end agreement, but do you really need trust along the way? I'm very interested to read more on this in the relevant chapter. (on People, I think)

> The four propositions of principled negotiation are relevant from the time you begin to think about negotiating until the time either an agreement is reached or you decide to break off the effort. That period can be divided into three stages: analysis, planning, and discussion.

**Comment by elle** [comment]
## Preface to the third edition

> A generation ago, the term “negotiation” also had an adversarial connotation. In contemplating a negotiation, the common question in people’s minds was, “Who is going to win and who is going to lose?” To reach an agreement, someone had to “give in.” It was not a pleasant prospect. The idea that both sides could benefit, that both could “win,” was foreign to many of us.
> 

> The challenge is not to eliminate conflict but to transform it. It is to change the way we deal with our differences—from destructive, adversarial battling to hard-headed, side-by-side problem-solving.
> 

# Part I: the problem

## 1: Don’t bargain over positions

- **Three criteria to judging a negotiation:**
    - It should produce a wise agreement if possible
    - It should be efficient
    - It should improve or at least not damage the relationships between the parties
- **Definition of a wise agreement:**
    - Meets legitimate interests of each side to the extent possible
    - Resolves conflicting interests fairly
    - Is durable
    - Takes community interests into account

### Positional bargaining

- Definition: each side takes a position, argues for it and makes concessions to reach a compromise
- Each side is locked into a position, to be defended against an attack.
- Our ego becomes identified with this position → “saving face”
- More attention to positions means less attention to the real underlying needs and concerns of each party → agreement becomes less likely
- It means pressure to yield to the other side — and can end up with ultimatums
- Endangers ongoing relationships. Positional bargaining leads to anger and resentment, because one side sees itself being to the rigid
- The more sides or people are involved, the worse it becomes
- Being nice is no answer. On hard vs soft negotiations:

> Rather than emphasizing a goal of victory, they emphasize the necessity of reaching agreement. In a soft negotiating game the standard moves are to make offers and concessions, to trust the other side, to be friendly, and to yield as necessary to avoid confrontation.
> 

### Positional Bargaining: Which Game Should You Play?

| Soft | Hard | Solution: Principled negotiation |
| --- | --- | --- |
| Participants are friends.
The goal is agreement.
Make concessions to cultivate the relationship.
Be soft on the people and the problem.
Trust others.
Change your position easily.
Make offers.
Disclose your bottom line.
Accept one-sided losses to reach agreement.
Search for the single answer: the one they will accept.
Insist on agreement.
Try to avoid a contest of will.
Yield to pressure. | Participants are adversaries.
The goal is victory.
Demand concessions as a condition of the relationship.
Be hard on the problem and the people.
Distrust others.
Dig in to your position.
Make threats.
Mislead as to your bottom line.
Demand one-sided gains as the price of agreement.
Search for the single answer: the one you will accept.
insist on your problem.
Try to win a contest of will.
Apply pressure. | Participants are problem-solvers.
The goal is a wise outcome reached efficiently and amicably.
Separate the people from the problem.
Be soft on the people, hard on the problem.
Proceed independent of trust.
Focus on interests, not positions.
Explore interests.
Avoid having a bottom line.
Invent options for mutual gain.
Develop multiple options to choose from; decide later.
Insist on using objective criteria.
Try to reach a result based on standards independent of will.
Reason and be open to reason; yield to principle, not pressure. |

These approaches can provide an agreement, but will it be a wise one?

Negotiation at two levels:

- One level, negotiation addresses the substance: for example salary, lease, price
- Second level, focuses on the procedure for dealing with the substance, for example method (hard, soft), the meta game.

The second level usually happens unconsciously. Only when dealing with someone from another culture, that we realise we should establish a process.

A better way → change the game. The method is called **Principled Negotiation** or negotiation on the merits:

- People: Separate the people from the problem.
- Interests: Focus on interests, not positions.
- Options: Invent multiple options looking for mutual gains before deciding what to do.
- Criteria: Insist that the result be based on some objective standard.

Three stages:

1. Analysis — diagnose the situation, gather info, organise it
2. Planning — generate ideas and consider how to handle people problems? which interests are most important? are the objective realistic? define criteria to evaluate options?
3. Discussion — parties communicate back and forth, looking for agreement

> To sum up, in contrast to positional bargaining, the principled negotiation method of focusing on basic interests, mutually satisfying options, and fair standards typically results in a wise agreement. The method permits you to reach a gradual consensus on a joint decision efficiently without all the transactional costs of digging in to positions only to have to dig yourself out of them. And separating the people from the problem allows you to deal directly and empathetically with the other negotiator as a human being regardless of any substantive differences, thus making possible an amicable outcome.
