### ISSUE TITLE
Getting to Yes – APR 17: Chapters 2 and 3

### ISSUE THREAD

**Issue by lachlanhardy** [Blackmill/book-club#216]
Book: [Getting To Yes](https://en.wikipedia.org/wiki/Getting_to_Yes) by [Roger Fisher](https://en.wikipedia.org/wiki/Roger_Fisher_(academic)) and [William Ury](https://en.wikipedia.org/wiki/William_Ury)

Aiming to read:

- Chapter 2: Separate the People from the Problem
- Chapter 3: Focus on Interests, Not Positions

MC: Christian
Notes: @lachlanhardy 

See you all at 12pm AEDT, April 17th @ https://blackmill.whereby.com/bookclub

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via [gday@blackmill.co](mailto:gday@blackmill.co).

**Comment by mcgain** [comment]
### Chapter 2: Separate the People from the Problem

Negotiators are people first, we have to take this into account. This can be a help or a hindrance. 
* Good <- Mutual respect and a good working relationship can smooth negotiations
* Bad <- People can get angry, hostile, fearful

Whatever else you are doing in a negotiation, always ask "am I paying attention to the people problem?"

Every negotiator has two interests
* The people
* The substance

Usually, there is an ongoing relationship to maintain, and that relationship gets entangled in the substance. 
Positional bargaining puts those relationships at risk. It's too easy to conclude the arguer doesn't value the relationship.

Solution: Disentangle the relationship from the substance; deal directly with the people problem
This means you should understand what the other side is thinking.

"Conflict lies not in objective reality, but in people's heads". We can establish the truth, but that is only one thing that needs to be resolved in the negotiation.

Solve the person, rather than the problem. Here's how:
1. Put yourself in their shoes
2. Don't deduce their intentions from your fears
3. Don't blame them for your problem
4. Discuss each other's perceptions
5. Look for opportunities to act inconsistently from their perceptions
6. Give them a stake in the outcome by making sure they participate in the process
7. Face saving: Make your proposals consistent with their perceptions

**Emotion**
1. First, recognise and understand emotions, yours and theirs
2. Pay attention to "core concerns"
3. Consider the role of identity
4. Make emotions explicit and acknowledge them as legitimate
5. Allow the other side to let off steam
6. Don't react to emotional outbursts
7. Use symbolic gestures

**Communication**
1. Listen actively and acknowledge what is being said
2. Speak to be understood
3. Speak about yourself, not about them
4. Speak for a purpose

**Prevention works best**
1. Build a working relationship
2. Face the problem, not the people

**Comment by mcgain** [comment]
### Focus on Interests, Not Positions

For a wise solution, reconsile interests, not positions
Interests define the problem, although they are usually hidden. A negotiator might not even explicitly know their interests.
Your position is what you decided on, your interests are the motivations that led to the decision.

Behind opposing positions lie shared and compatible interests, but also conflicting ones.

**How to identify interests**
1. Ask yourself "Why are they taking this position?"
2. Ask yourself "Why wouldn't they just accept what I want?" 
3. Realise that each side has multiple interests
4. The most powerful interests are basic human needs (see Maslow's Heirarchy)  
5. Make a list (pros/cons, the answers to the above)

**Talk about interests**
1. Make your interests come alive
2. Acknowledge their interests
3. Put the problem before your answer
4. Look forward, not back
5. When asking why, look forward, not backwards
6. Be concrete, but flexible
7. Be hard on the problem, soft on the people
