### ISSUE TITLE
Getting to Yes: April 24th: Chapters 4 + 5

### ISSUE THREAD

**Issue by elle** [Blackmill/book-club#217]
Book: [Getting To Yes](https://en.wikipedia.org/wiki/Getting_to_Yes) by [Roger Fisher](https://en.wikipedia.org/wiki/Roger_Fisher_(academic)) and [William Ury](https://en.wikipedia.org/wiki/William_Ury)

Aiming to read:

- Chapter 4: Invent options for mutual gain
- Chapter 5: Insist on using objective criteria

MC: @lachlanhardy 
Notes: @mcgain 

See you all at 12pm AEDT, April 24th @ https://blackmill.whereby.com/bookclub

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via [gday@blackmill.co](mailto:gday@blackmill.co).

**Comment by HashNotAdam** [comment]
## Invent Options for Mutual Gain

All too often negotiators "leave money on the table" by focusing on a single dimension. Inventing options is a valuable skill for a negotiator. Instead of splitting the whole orange and throwing away the peel, one party might like the peel while the other the flesh.

Most people come into a negotiation in the belief that they have the right answer, and so the negotiation is a straight line between the positions the parties entered with. The major obstacles to creating options are: premature judgement; searching for the single answer; the assumption of a fixed pie; and thinking that "solving their problem is their problem".

Invent creative options by: separating the act of inventing options from the act of judging them; broaden the options on the table rather than look for a single answer; search for mutual gains; and invent ways of making their decisions easy.

Inventing options involves four types of thinking: the particular problem; descriptive analysis; what should be done; and specific and feasible suggestions for action. The Circle Chart represents these four types of thinking as quadrants in a circle and articulates that the thinking occurs in stages.

![Screenshot 2024-04-28 at 14 17 43 Large](https://github.com/Blackmill/book-club/assets/902714/b210c40e-92c7-41f4-977a-ea7b629c06d9)

Another way to generate options is to example the problem from the perspective of different professions and disciplines.

You can also think of "weaker" versions of your options in case a sought-for agreement proves beyond reach. Understand where you disagree on the first-order agreement, then seek a second-order agreement.

Consider changing the scope. If you can't get agreement on the whole, maybe you can split it into multiple negotiations and seek agreement in parts.

Look for mutual gain. There almost always exists the possibility of joint gain. You will almost always want to look for solutions that will leave the other side satisfied as well. An outcome in which the other side gets absolutley nothing is worse for you than one that leave them mollified.

One way to dovetail interests is to invent several options all equally acceptable to you and ask the other side which one they prefer. You want to know what is preferable, not necessarily what is acceptable.

Look for precedent. Find a decision or statement that the other side has made in a similar situation, and try to base a proposed agreement on it.

Offers are usually more effective than influencing with threats. What can you invent that might be attractive to them but low in cost to yourself? Try to draft a proposal to which their responding with the single word "yes" would be sufficient, realistic, and operational. When you can do so, you will have reduced the risk that your immediate self-interest has blinded you to the necessity of meeting the concerns of the other side.

## Insist on Using Objective Criteria

Regardless of how well you invent ways of reconciling interests, you will almost always face the reality of conflicting interests. These differences cannot be swept under the rug.

Usually, negotiators attempt to solve differences via a battle of wills (positional bargaining). This type of negotiation comes at a high cost. To reach an agreement, someone will need to back down from their position. If, on the other hand, the negotiation is based on objective criteria, the potential cost drops. Concentrate on the merits of the problem, not the mettle of the parties. Be open to reason, but closed to threats. People using objective criteria tend to use time more efficiently, talking about possible standards and solutions.

Objective criteria need to be independent of each side's will. They should also be both legitimate and practical, and should apply to both sides.

When considering procedural solutions, look at other basic means of settling differences: taking turns; drawing lots; letting someone else decide; etc.

Once you have decided upon objective criteria and procedures, consider the following when discussing them:

1. Frame each issue as a joint search for objective criteria
1. Reason and be open to reason as to which standards are most appropriate and how they should be applied
1. Never yield to pressure, only to principle

It is possible that parties agree on the merit of multiple standards, but the values from those standards differ, splitting the difference is perfectly legitimate.

**Comment by elle** [comment]
## 4: Invent options for mutual gains

### Diagnosis

- Usually people believe they already know the right answer — or the only creative solution is splitting the difference, or all the answers lie in a straight line between the two sides
- Four major obstacles that inhibit creative solutions:
    - Premature jugdement
    - Searching for the single answer → narrowing the gap between positions, not broadening the options
    - The assumptions of a fixed pie - either/or thinking, either I win or you do
    - Thinking that solving their problem is their problem - it seems disloyal to think up ways to satisfy them, reducing the legitimacy of the other side’s views

### Prescription

- Separate inventing from deciding
- Before brainstorming:
    - Define purpose: what would you like to get out in the end
    - Choose a few participants: the higher the number, the harder it is to get to a decision
    - Change the environment: away from regular discussions
    - Design an informal atmosphere: to help the sides relax
- During brainstorming:
    - Seat the participants side by side - physically as well as psychologically working together, rather than opposites
    - Clarify the ground rules - for example, no criticism
    - Brainstorm
    - Record ideas in full view
- After brainstorm:
    - Start with the most promising ideas
    - Invent improvements for promising ideas
    - Set a time to evaluate ideas and decide
- Consider brainstorming with the other side - increased risk that people will raise something biased despite establishing the rules
- Clearly separate the generating ideas from deciding phases
- The Circle Chart → for generating ideas, involves four types of thinking:
    1. Factual situation
    2. More general thinking: Descriptive analysis: the situation in a more general terms
    3. Even more general in thinking: what ought possibly to be done - more theoretical
    4. Specific feasible suggestions for actions - what can be done?

--
- Look through the eyes of different experts → is another way to generate fresh ideas
- Invent agreements of different **strengths**
- Change the **scope** of the proposed agreement
- Look for mutual gain — while identifying shared interests
- Ask for their preferences
- Make their decision easy
