### ISSUE TITLE
The Essential Deming: Jun 12: Giving up, final thoughts, and an article

### ISSUE THREAD

**Issue by Traymore** [Blackmill/book-club#221]
Book: [The Essential Deming](https://deming.org/the-essential-deming-new-book-on-dr-deming-work/) by Edward Deming

Aiming to read:

https://itrevolution.com/articles/out-of-the-cyber-crisis-deming-in-the-world-of-cybersecurity/
and maybe some random bits of the book that look interesting

MC: @mcgain 
Notes: @elle 

See you all at 12pm AEDT, Jun 12th @ https://blackmill.whereby.com/bookclub

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via [gday@blackmill.co](mailto:gday@blackmill.co).

**Comment by Traymore** [comment]
My notes on Chapters 3 and 4 of the book:
Deming

**There are four parts to Profound Knowledge** 
**1. Know the system**
What is the aim of the system? 
That aim must be clear to all!
Management meets aims by optimising the system
Management changes the boundaries of the system to meet aims
You need someone outside the org to observe and teach
**2. Statistical Knowledge** 
Big mistake to attribute special case failures to common system problems and vice versa
Be wary of facts, they change when you change measurement systems. Also when there is subjective information
**3. Dunno what this was**
TBD
**4. Psychology**
Removal of a demotivator is not a motivator
The merit system is the destroyer of people. Instead
* Institute Leadership
* System of rewards must be aimed at cooperation

**14 Points to Transform Management**
1. Always be improving, and be consistent in improving
2. Don’t accept shoddiness
3. Don’t use inspection to ensure quality, instead, build quality  into the system and process
4. Don’t use the lowest cost vendor and switch and change. Instead build loyalty and trust
5. Don’t just improve by optimising within the system. Improve the system always too
6. Train on the job. People must also understand the inputs to their jobs to be able to improve
7. When diagnosing a problem, look at the whole system, not just the end point where the problem showed. See also 5 why’s and other retrospective techniques
8. Drive out fear
9. Break down barriers between departments
10. Eliminate slogans, exhortations and targets
11. Eliminate quotas and management by numbers
12. Remove barriers that prevent pride in work/workmanship
13. Have a program of education and improvement
14. It is everybody’s job to do all this

**Comment by elle** [comment]
## **Out of the Cyber Crisis – Deming in the World of Cybersecurity by John Willis**

Article: https://itrevolution.com/articles/out-of-the-cyber-crisis-deming-in-the-world-of-cybersecurity/

### 1. Mission-focused

> *“**Create constancy of purpose** toward improvement of product and service, with the aim to become competitive and to stay in business, and to provide jobs.”*
> 

By this, he meant an aim, direction, or purpose—a desired outcome. Fewer companies still have a shared purpose across the organisation

Build quality into the work.

### 2. Adapt or die

> *“Adopt the new philosophy. We are in a new economic age. Western management must awaken to the challenge, must learn their responsibilities, and take on **leadership for change**.”*
> 

Embracing a new mindset.

Today, leaders wait until there’s a problem before they fix it. This approach must be replaced with a process of continuous learning, continuous improvement, continuous adaptation, and continuous change.

### 3. Stop inspecting quality

> *"**Cease dependence on inspection to achieve quality**. Eliminate the need for inspection on a mass basis by building quality into the product in the first place.”*
> 

Inspecting a product once it’s built doesn’t improve its quality. Inspection merely discovers a lack of quality. Quality isn’t something to be added at the end but to be designed into the product from the get-go.

Just as we improve the product, it is about improving the process.

### 4. The fallacy of the lowest bidder

> “*End the practice of awarding business on the basis of price tag. Instead, **minimize total cost**. Move toward a single supplier for any one item, on a long-term relationship of loyalty and trust.”*
> 

Tighter relationships with fewer suppliers lead to increased process alignment and lower overall costs.

Purchasing departments think of the bottom line, not the best option or product for the purpose it is needed for.

Think: standardising the tech stack to support across the company

### 5. Never stop improving

> *“**Improve constantly** and forever the system of production and service, to improve quality and productivity, and thus constantly decrease costs.”*
> 

Try to be a step ahead, rather than a step behind. Anticipate what needs to be done.

### 6. Train for a systems thinking mindset

> *“Institute training on the job.”*
> 

When people are being trained, they need to understand what the job involves and why it’s done in the first place. Then, they need to continually learn through practical experience, experimenting with new methods and ideas, studying results, and striving to be as perfect as pragmatically possible.

### 7. Don’t manage — lead

> *“Institute leadership. The aim of supervision should be to **help people and machines and gadgets to do a better job**. Supervision of management is in need of overhaul, as well as supervision of production workers.”*
> 

Leadership isn’t about who is in authority and who gets punished. It is about improving the process.

Most organisations think one of a manager’s main functions is to put out fires: all the problems that crop up over the normal (and abnormal) course of business. Problems like security vulnerabilities…. Incidents are software quality issues that need to be dealt with quickly and quietly. This is not leadership. This is firefighting. 

### 8. No fear

> *“Drive out fear, so that everyone may work effectively for the company.”*
> 

“What would you do if new software engineers broke the system?” The developer replied, “If they can break our system on the first day of work, they have done their job, and we have not.”

- Psychological safety.
- Blameless post-mortems. Blame the system, not a person.
- No command-and-control leadership → instead build trust
- Eliminate fear: the fear of not getting a bonus; the fear of making a mistake; the fear of not meeting annual goals; and the fear of not measuring up to their peers.

### 9. No silos

> *“Break down barriers between departments. People in research, design, sales, and production must work as a team, to foresee problems of production and in use that may be encountered with the product or service.”*
> 
- Inefficiency paradox: optimising parts of the system results in a suboptimal system.
- Incentives leads to competition rather than collaboration.
- The company as a single entity, a cohesive system, where everyone is focused and working towards the same goal.

### 10. No slogans

> *“Eliminate slogans, exhortations, and targets for the workforce asking for zero defects and new levels of productivity. Such exhortations only create adversarial relationships, as the bulk of the causes of low quality and low productivity belong to the system and thus lie beyond the power of the workforce.”*
> 
- Maginot Line thinking is when you expend considerable resources in an effort to counteract a past threat.
- Many efforts are to prevent outside attacks, where in reality, many breaches come from inside the network.
- Simple slogan won’t solve our problems.

### 11. Quality, not quotas

> *“Eliminate work standards (quotas) on the factory floor. Substitute leadership. Eliminate management by objective. Eliminate management by numbers, numerical goals. Substitute leadership.”*
> 
- Quotas oversimplify quality craftsmanship into neat little numbers managers can understand.
- Think 100% test coverage. Or LOC metrics.
- The team can decide to improve the code by deleting unused code, or refactoring into a more efficient code with less LOC. But teams are not incentivised to clean up, but rather to ship new features.

### 12. No barriers to pride

> *“Remove barriers that rob the hourly worker of his right to pride of workmanship. The responsibility of supervisors must be changed from sheer numbers to quality. Remove barriers that rob people in management and in engineering of their right to pride of workmanship. This means, inter alia, abolishment of the annual or merit rating and of management by objective.”*
> 
- As a manager, you let the people on your team shine
- From Wikipedia: The merit system is the process of promoting and hiring government employees based on their ability to perform a job, rather than on their political connections. It is the opposite of the spoils system.
- Generally, people want to do good work and be proud of their work. Don’t stand in their way.

### 13. A self-learning organisation

> *“Institute a vigorous program of education and self-improvement.”*
> 
- A place where people teach themselves.
- Google’s “20% time”, thought’s “investment time”

> Andrew Clay Shafer says, “You are either a learning organization or you are losing to one that is.”
> 

### 14. Transformation is for everyone

> *“Put everybody in the company to work to accomplish the transformation. The transformation is everybody’s job.”*
> 
- Starting with SLT and all the way down, diffusing through every level.

**Comment by elle** [comment]
Discussion notes:

- We liked how the article added a layer of translation to explain the concepts more clearly, as well as provide relevant examples.
- Quality is inspirational, especially without having metrics, but one how do you know you have good enough quality, and two, startups with limited budget cannot continue to polish and refactor instead of getting to market
- Having different departments doing different functions, for example, product is separate from engineering and design, or engineers are separate from QA is never leads to good outcomes
- In some companies, without QA, the delivery process will fall apart
- Taking rules as dogma is problematic, rather than understanding why the rules exist
- Taking ideas from the army, teaching people to be generalist or think in their feet, rather than micro-managing them with direct commands. Grow leaders, rather than peasants. Or T-shaped skilled people.
- System thinking is tied to leading rather than managing. Having time to stop and think about what we should be doing? How we can improve the system?
- Setting the systems to protect people from themselves
- Deming breaks performance into 4 categories, which is less granular than most perf reviews systems:
  - Exceeding
  - Above
  - Average
  - Below average
- MS performance reviews and how it changed in recent years - from stack-ranking to encouraging collaboration and growing others.
- Ford slogan around safety is everywhere.
- Deming really liked statistical data, so it is a paradox that quality metrics are not well defined
- You can't take one principle and apply it separately. They all support each other, like a whole system
