### ISSUE TITLE
Primed to Perform: Chapters 12-13

### ISSUE THREAD

**Issue by mcgain** [Blackmill/book-club#23]
Primed to Perform

Aiming to read:

Chapter 12: Compensationism 
Chapter 13: The Hunting Party
MC: @elle 
Notes: @HashNotAdam 

See you Tuesday in Zoom:

Join Zoom Meeting
https://zoom.us/j/914785529

Topic: Blackmill Book Club
Time: Jun 18, 2019 12:00 PM Canberra, Melbourne, Sydney
Every week on Tuesday. First one: Mar 26, 2019 12:00 PM

Please download and import the following iCalendar (.ics) files to your calendar system.
Weekly: https://zoom.us/meeting/914785529/ics?icsToken=5dd411172ce371e9770226b355c2f163863fe4efff5e00b09866a6b7be767b09

One tap mobile
+61871501149,,914785529# Australia
+61280152088,,914785529# Australia

Dial by your location
+61 8 7150 1149 Australia
+61 2 8015 2088 Australia
Meeting ID: 914 785 529
Find your local number: https://zoom.us/u/abWGuMO6GJ

**Comment by elle** [comment]
## Chapter 12 Compensationalism

**Auto glass example:**

- Commission but with base pay rate
- Quality vs doing things quick

> While money is a poor motivator, it can be an effective activator, overcoming someone’s inertia.
> It can be the reason you take a job or switch from a low-ToMo company.

**Bad examples:**

- Cancellation effect: approving bad loads
- Cobra effect: recommending unneeded services, fixing exams

--
> an incentive scheme like sales commissions could have
> a positive or negative affect on the total motivation of your people,
> depending on how the rest of the culture makes them feel.

Problem is that many sales positions are very much commission based.

The more critical adaptive behaviours are,
the less effective a pay-for-performance scheme is likely to be.

The more times you answer no,
the more damaging pay-for-performance and goal-based bonuses are likely to be:

But why are most of these questions in double negatives??

1. Is the job routine, with very little VUCA?
2. Do your people face no conflicts of interest?
3. Is your company insulated from the financial and reputational risks
   that come from an individual’s distraction, cancellation, or cobra effects?
4. Is teamwork unimportant to drive the highest levels of performance?
5. Can you fairly measure important behaviours,
   especially adaptive behaviours?
   When adaptive behaviours are both important and hard to measure,
   it’s unlikely that pay-for-performance systems will be fair.
6. Can you determine the value of the behaviours you care about?
   You can figure out how much to pay someone per widget,
   but you may struggle to put a value on more complex contributions.
   You also may not know how valuable a behaviour is until months
   or years have gone by.
7. Are your people resistant to emotional pressure, economic pressure, and inertia?
8. Is ToMo naturally high in your company?
9. Is it easy to align incentives between your customers, your employees, and your company?

**About tying performance reviews with pay raises:**

> Lear replaced annual performance reviews with quarterly discussions
between each employee and supervisor.
> The conversations focused on gaining new skills,
and mitigating weaknesses.
> The conversations had “no connection to decisions on pay. None.”
> They even ended annual individual raises. Salaries change according to local market conditions.

--
> By taking away concerns about money and status, we’ve freed employees to relax and hear what their managers have to say, and vice versa.”

- The Feedback Fallacy, Marcus BuckinghamAshley Goodall
  - Article: https://hbr.org/2019/03/the-feedback-fallacy
  - Podcast: https://castro.fm/episode/V3EaG8

> the company decided to end commissions in 2011.
> What a difference it made.
> As one salesperson reflected, “It’s removed the ‘me, me, me’ mentality.
> Now I want to share information with everyone on the team,
> and everyone is willing to pitch in
> because it doesn’t hurt me to help my colleagues.”

## Chapter 13: The Hunting Party

> If your kitchen were infested with bugs, you would have a few options.
> You could hire ten people to stand guard and squash them whenever they appear.
> Or you could have those ten people give your kitchen
> a thorough cleaning and keep it spotless thereafter.

**About free-rider behaviour:**

> Free-rider behaviour was greatest
> when the person felt the activity itself
> had little intrinsic meaning or value.
> Free-rider behaviour was also high
> when the person’s individual contribution could not be determined.

**Eliminating free ride behaviour:**

- Increase intrinsic meaning and value of the work to the person
- Define how contributions are accomplished and measured
- Role design
- Knowing the other people - an early step to building community

### Marketplaces vs societies

**Benefits of strong community:**

- Reduces emotional pressure.
  When you’re working in a strong community,
  it feels safe to be vulnerable.
  Because you feel safe, your play and purpose are not canceled out by anxiety.
- Reduces economic pressure by making you feel less afraid of punishment. 
- Increases your sense of purpose because the identity of the group is naturally stronger.
- Inspires sharing knowledge, sharing perspectives, and drives curiosity and play.

Marketplace economic dynamics do not work the same at a team or organisation.
People believe it does because of four faulty assumptions:

1. Organisations don’t need citizenship to scale adaptive behaviours.
2. Cooperation and consistency among players in the organisation is not needed.
   But consistency is critical for tactical performance in an organisation. And adaptive performance can’t occur without cooperation and citizenship.
3. Organisations don’t need participants to improve shared resources.
4. Organisations don’t carry the costs of cobra effects.

**Society, a different model for community building**

> In a society, ToMo drives behaviour, not monetary signals or Darwinian forces.
> Identity, performance management, compensation design, and leadership behaviours
> are all pieces of the puzzle.
> But there is one more cultural key that we have yet to describe:
> the overall structure that brings all those parts into harmony.

**Dunbar number:**

Social interaction is mentally taxing, therefore, there is a strong connection
between size of brain and the group size we interact with.

> Dunbar has shown that if you don’t interact meaningfully with someone within four months, your feeling of emotional closeness will quickly degrade.

- Villages (150-200)
- Bands (50)
- Hunting parties (15)
- Confidants (4-5)

> The first step is to eliminate the phrase “span of control” from managers’ vocabularies.

^ ?

**Questions to consider, to encourage bands:**

- Is there a natural grouping where the knowledge
  that comes from play should be pooled and exchanged?
  The group could form around a topic, or a specific objective.
- How can you help each band form a common identity,
  based on trust and caring?
- How does the band build credibility?
- How do you encourage the band to include apprenticeship
  in its behavioural code?
- What routines and resources are needed
  for the band to share knowledge effectively?
- How will the band learn together?

> The relationship between the performance of a hunting party
> and its cohesiveness is highly reciprocal.
> Bonding leads to high performance and high performance leads to bonding.

**To encourage confidants:**

- Mentorship program.
- Create leaderless subteams of no more than five people
  to work closely over extended period of time.

**At Gore-tex:**

> Bill Gore’s own company has no bosses,
> no job titles,
> no “employees,”
> and no organizational chart.
> Project teams—its version of hunting parties—
> are formed organically as people have ideas.
> Through the power of play and purpose,
> they have to convince their colleagues to support them.

- Sponsors, not bosses
- Leaders, not managers
- Personal commitments, not job titles
- Guidelines, not rules
- Investments, not expenses
- Associates, not employees

**Waterline principle:**

> “The waterline principle means that
> it’s ok to make a decision that might punch a hole in the boat
> as long as the hole is above the waterline
> so that it won’t potentially sink the ship,
> But, if the decision might create a hole below the waterline
> which might cause the ship to sink,
> then associates are encouraged to consult with their team
> so that a collaborative decision can be made.”

**Questions:**

- Does your organisation behave more like a marketplace, or a society?
- Does every person have the opportunity to form confidant relationships with their peers?

**Other:**

- Your Approach to Hiring Is All Wrong by Peter Cappelli
  - Article: https://hbr.org/2019/05/recruiting
  - Podcast: https://castro.fm/episode/gw6FNU

**Comment by HashNotAdam** [comment]
Richard has found that there are many people working for Shopify in Australia that feel that their career options are limited. He has been speaking with leaders about adding elements of play into roles to increase job satisfaction.

The boundaries of play can be difficult to define. Lachlan told a story about Atlassian where there are some guaranteed days to work on personal projects. Should you wish to continue working on your project beyond the guaranteed days, first you must convince 2 peers and then, if more time is required, you convince the founders. The popular JavaScript library, Raphaël, was concived in this time, however, Dmitry Baranovskiy could not approval to build it at Atlassian. On one hand, this could be seen as a missed opportunity since Dmitry left Atlassian and built a popular framework. On the other hand, if this product has no value to Atlassian, maybe things worked out for the best.

# Compensation

Like all motivators, pay-for-performance is neither inherently good nor inherently bad. Depending upon the circumstances, it can be either, both, or neither. The key to building a high-ToMo organization is knowing when pay-for-performance works and when it doesn’t.

## Clear as (auto) glass

Compensating staff with a commission structure can prove motivational so long as:

- output is easily measured;
- quality problems are readily detected;
- blame is assignable; and
- the interests of the customer and employee are aligned (e.g. both have an interest in speed)

There was some concern within the group that the discussion of the rate of failure and effect on clients was overlooked. It is possible that, while the output increased, the failure rate may also have increased. The book attempts to infur that this was controlled by indentifing who installed a failed windscreen and ensuring that that person fixed the job, however, it was not explicitly stated that there was no net effect.

## Driven to distraction

A poorly targetted commission structure will cause a good employee to make a choice between doing what is best for the company and what is best for their pocket.

## Compensation and cancellation

> Performance-based rewards tend to cancel out the natural sense of play, reducing persistence. And sometimes they cancel out even more.

A bank attempting to incentivise high performance in their small business loan division found that a commission structure lead to a large increase in bad loans.

## The cobra effect

> While the cancellation effect can be harmful, most concerning of all is when a compensation system creates cobra effects.

When incentives are poorly aligned, good people will act poorly particularly if their livelihood relies on meeting the goals that are being incentivised (economic pressure and emotional pressure from bosses).

## When should you pay for performance?

> If the employee deeply believes that his company does the right thing for its customers, the sales commission slightly increases ToMo.

> The more critical adaptive behaviors are, the less effective a pay-for-performance scheme is likely to be.

> If your people have high levels of ToMo, the negative effects of pay-for-performance are less likely to hurt them.

For the 9 questions below, the more times you answer "no", the more damaging pay-for-performance and goal-based bonuses are likely to be.

1. Is the job routine, with very little VUCA?
2. Do your people face no conflicts of interest?
3. Is your company insulated from the financial and reputational risks that come from an individual’s distraction, cancellation, or cobra effects?
4. Is teamwork unimportant to drive the highest levels of performance?
5. Can you fairly measure important behaviors, especially adaptive behaviors?
6. Can you determine the value of the behaviors you care about?
7. Are your people resistant to emotional pressure, economic pressure, and inertia?
8. Is ToMo naturally high in your company?
9. Is it easy to align incentives between your customers, your employees, and your company?

> Profit sharing (whether at the team, group, or organization level) is also a form of variable compensation, and is more likely to increase ToMo (and provide a cash-flow buffer for the organization during bad times).

Lachlan has concerns about The Feedback Fallacy, referencing the HBR IdeaCast podcast ([What Managers Get Wrong About Feedback](https://podcasts.apple.com/au/podcast/hbr-ideacast/id152022135?i=1000436157223)). Human beings are unreliable raters of other human beings; this is known as the idiosyncratic rater effect. More than 60% in the variance in rating is a function of "me" and the more ratings points you add the more error you get.

Our performance systems should not attempt to define the truth of a human being at work—because none of us can do that—we should define the truth of what each team leader thinks, feels, or reacts in response to a person on a team. We may not be good raters of each other, however, we are good raters of our own experiences and judgements.

Instead of asking the question "are they a top performer", you would ask "do I always go to them for excellent work". This changes the perspective so that you are reporting on yourself instead of others.

See also [The Feedback Fallacy](https://hbr.org/2019/03/the-feedback-fallacy)

# The Hunting Party

Every time you create a team or division in your organization, you’re making a big cultural decision

## Many hands make heavy work

> Free-rider behavior was greatest when the person felt the activity itself had little intrinsic meaning or value. Free-rider behavior was also high when the person’s individual contribution could not be determined. These two findings substantiate the view that role design is still the most powerful cultural key… The third most significant driver of free-rider behavior was whether the person simply knew the other people—an early step to building community.

## Marketplaces and societies

Most businesses are designed around a marketplace where people compete with each other to be the best and the worst are replaced.

When people compete, they try to hide their "secret sauce" which reduces the likelihood of others thriving.

> It is very difficult to create consistency, cooperation, or citizenship of any kind across players in the marketplace.

> Organizations require a different model for community building: the society.

## Building a society

Anthropologist and evolutionary psychologist Robin Dunbar found that humans:

- can only maintain social networks of around 150 people (a village);
- create deeper connections with about 50 people (a band);
- tend to form natually groups of 15 for close collaboration (a hunting party); and
- only manage about 5 very close friends (confidants).
