### ISSUE TITLE
Resilient Management: Intro & Chapters 1-2 (August 13th)

### ISSUE THREAD

**Issue by lachlanhardy** [Blackmill/book-club#27]
New book! [Resilient Management](https://abookapart.com/products/resilient-management)

We want to blitz this one in 2-3 sessions. Great way to try out the book club and see if you learn something!

We're aiming to read:
- Intro
- Chapter 1: Meet Your Team
- Chapter 2: Grow Your Teammates

MC: @mcgain 
Notes: @lachlanhardy 

See you 12pm Tuesday, August 13th @ https://appear.in/blackmill

Ping gday@blackmill.co if you want a calender invite and access to the Slack beforehand.

**Comment by mcgain** [comment]
We ended up doing the intro and chapter 1 only. My MC notes:
# Resilient Management

## Chapter Introduction

This book is here to help us manage teams

### What makes a team?

2+ people who share a strategic objective

There's plenty of ways of defining a team, but it doesn't really matter

#### Lexicon
* Teammates - the people in the team you manage, the people who report to you
* Discipline - function specific area of the org you work in. Design, FED, etc.
* Functional Team - a group of people who work in the same discipline
* Feature Team - people from different disciplines, working together on a feature
  
Teams are the atomic units of every org

### Stages of group development
There are four stages a team can go through
* Forming - Few patterns or processes, might only just have formed
* Storming - Friction occurs because of differences
* Norming - Starting to find the grove, differences are worked out, clarity emerges
* Performing - Everyone is communicating well, and you're shipping

Any change in personell, project or leadership can cause backsteps

> Can anyone tell what stage their team is in? I think so.

#### What's in this book
Leadership, human growth and resiliency skills

#### What's not in the book
Strategy, Managing managers, Project managing

The chapters of the book serve the different stages of group development, chapter 1 is Forming

## Chapter 1

_One of your primary jobs is to foster a foundation of trust on your team_

To do this, you need to understand them

Not everyone thinks or behaves like you do. Some people like public celebrations of promotion, others do not. 

It takes time an effort to learn your teammates' different needs

### Humans' core needs at work

Two bits of the brain are relevant
* Prefrontal Cortex - Rationality and logic
* Amygdala - lizard brain

Humans have six core needs in the workplace (BICEPS)
* Belonging
* Improvement / Progress
* Choice
* Equality / Fairness
* Predictability
* Significance

These are more or less important depending on the individual, so ask them about which ones are important to them

> How do they compare to the ones in Primed to Perform?

#### Same stimulus, different responses

People can react differently when these different needs are affected. 

Desk moves are a great example of this, they can threaten each one of those needs, causing some people to dislike them

* Belonging - Removes a locality based social group
* Choice - Desk movements are often dictated, removing the choice from the individual
* Equality / Fairness - Some groups might be advantaged over others (closer to the windows etc.)
* Predictability - Breaks the routine of showing up to work in the same place day after day
* Significance - Could remove a person from a high status desk

### Work style and preferences

It's helpful to gather more information from your teammates over and above the core needs list.

_I'd like to ask you some cheesy questions to help better support you_

#### Grumpiness
* _What makes you grumpy?_
* _How will I know you're grumpy?_
* _How can I help you when you're grumpy_

#### Feedback and recognition
* _In what medium do you prefer to recieve feedback (in person, email, chat)?_
* _When do you prefer to recieve feedback, in 1:1s or when it happens?_
* _How do you prefer to recieve recognition - publicly or privately?_
  
#### Goals and support
* _What makes 1:1s the most valuable for you?_
* _What are your goals for this year, and the next three months?_
* _What do you need from your manager?_
* _What do you need from your teammates?_
* _What do you need from your peers outside the team?_

#### The wordy question
_Human learning and growth requires the right amout of four things: new challenges, low ego, space to reflect and brainstorm, and timely and clear feedback. How are these four going for you? Is there one you need more or less of?_

#### The most important question
_What's your favourite way to treat yourself?_

They also need to get to know you as well as you know them!

### Help the team get to know you
Pay attention to your own superiors' styles, sharing your approach with your teammates helps you work together

There are different kinds of managers, people who focus on _getting shit done_ vs those that focus on growing the team, and so on

Your style will change how you do various things; coaching, giving feedback, scoping work, communicating news etc.

What do you optimise for during those activities?

There's a MadLib to help us figure this out

#### Sharing with your teammates

An example, where a lead optimises for _long term relationships_, demonstrates that when that approach is understood by both parties, it improves things

Once you've done your MadLib, share what you learned with your teammates.
* _What do you optimize for in your role?_
* _What do you how your teammates will lean on you for?_
* _What management skills are you currently working on learning or improving?_
  
### Coaching questions

A list of useful questions to ask of ourselves
