### ISSUE TITLE
Feb 12: chapters 5-6

### ISSUE THREAD

**Issue by elle** [Blackmill/book-club#3]
Next book club chat, read chapters:

* 5: Managing a team
* 6: Managing multiple teams

Please post any comments/issues/questions for discussion here.

**Comment by saramic** [comment]
My notes on Ch5
- why do we think leadership is natural? how do we practice in the workplace?
  > Similarity with Family - although you get thrown in the deep end
  > organised experiences with organisations like scouts, dance clubs where management of a group to achieve a goal is modelled and taught
- A manager should have a _large_ impact on an organisation, a lot of senior dev's seem not to be able to grasp that and wonder why they don't transition
- Managers role is to
  - keep team focused
  - make sure tech deliveries are met
- Managers need not be _most_ technical in the team - different roles
  - still need to stay technical
    - keep career options open
    - credibility
    - understand processes
    - forse bottlenecks
- Job of a team lead is about "determining shortest path through system to implement new feature"
- some code vs no code (pure manager)
- dysfunctions
  - **Not shipping**
    - know when to push and when not to - sounds easy :)
    - do things that hurt regularly to remove bottlenecks
    - resource contentions for being able to ship
      > reminds me of book [Tom DeMarco "Slack, Getting Past Burnout, Busywork, and the Myth of Total Efficiency"](https://www.amazon.com/Slack-Getting-Burnout-Busywork-Efficiency/dp/0767907698)
  - **People drama**
    - "brilliant jerk" - people dramas
      > we find pairing, inter team one-on-one's and a regular rotation of contractors has helped that - that said we are becoming less contractors and one team so no inter-team rotation - key to hire the right "cultural fit" - the person who will excel at our place of work
      > have seen a number of examples of people underachieving in one job only to change jobs and excel - just the right fit?
      - nip it in the bud quickly
  - **Unhappiness due to overwork**
    - "system sustainability" over "technical debt" 20%
      > I have seen this work and not work, really have to get business onboard
    - make it fun
      > had this in first team I lead at RedBubble - we had the most boring job, recreating platform for DR in cloud in a test driven way but we were the fun team!
  - **Collaboration problems**
    - regular catchups, non work related activities
      > I would still prefer a coding dojo/coding competition over go carts
- promoted over a peer
  - be vulnerable, open, pick your battles, be mature
    > be mature, interesting that that needs still to be mentioned, maybe it is mentioned to evoke that thought of maturity :)
- The shield
  - manager to be the shield
    > only once was I not shielded, when I worked directly under the CEO
    > ability to switch context from reporting to higher level stakeholders, to dealing with underperformance, to celebrating a team win all before lunch
- how to drive good decisions
- Create data driven team culture
  > have seen 2 extremes of this, it will be done when it is done and if you don't get the increase in A/B test then throw it all out and try again
- look into future
...
- Good/Bad Mgr., Conflict Avoider/Tamer
  - save env. for disagreement
  - consensus and voting does not work, not equal stakes/knowledge/context
...
