### ISSUE TITLE
Nov 19: Dare to lead: Part 1, section 5 and Part 2

### ISSUE THREAD

**Issue by HashNotAdam** [Blackmill/book-club#41]
Aiming to read:

- Part 1, Season 5: Curiosity and Grounded Confidence
- Part 2: Living into our Values

MC: @HashNotAdam
Notes: @mcgain

See you 12pm Tuesday, November 19th @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the Slack beforehand.

**Comment by elle** [comment]
My notes for Part 2:

# Part 2: Living into our values

People try to: **prove, perfect, perform and please.**.. trying to show the crowd that we deserve to be there.
People forget **why** we are here. Forget our values.

> A value is a way of being or believing that we hold most important. Living into our values means that we do more than profess our values, we practice them. We walk our talk—we are clear about what we believe and hold important, and we take care that our intentions, words, thoughts, and behaviors align with those beliefs.

### Live your values

**Step 1: We can't live into our values that we can't name.**
Pick 2-3 and ask yourself:

- Does this define me?
- Is this who I am at my best?
- Is this a filter that I use to make hard decisions?

**Step 2: Taking values from BS to behaviour**

- 3 supporting behaviours
- 3 detracting behaviours

**Step 3: Empathy and self-compassion**
The two most important seats in the arena Regardless of our values, we must consider our privilege and be empathetic

> Regardless of the values you pick, daring leaders who live into their values are never silent about hard things.

--
> Silence is not brave leadership, and silence is not a component of brave cultures.

### Living into Our Values and Feedback

> One of the biggest challenges we face, especially at work, is staying aligned with our values when giving and receiving feedback.

#### Guidelines for being ready to give feedback

1. ...when I’m ready to sit next to you rather than across from you.
1. ... when I'm willing to put the problem in front of us rather than between us
1. ...when I'm ready to listen, ask questions, and accept that I many not fully understand the issue
1. ... when I'm ready to acknowledge what you do well instead of just picking apart your mistakes
1. ... when I recognise your strengths and how you can use them to address your challenges
1. ... when I can hold you accountable without shaming or blaming
1. ... when I'm open to owning my part
1. ... when I can genuinely thank someone for their efforts rather than just criticising them for their failings
1. ... when I can talk about how resolving these challenges will lead to growth and opportunity
1. ... when I can model the vulnerability and openness that I expect to see from you

#### Getting good at receiving feedback

Thinking:

- There's something valuable here. Take what works and leave the rest
- These people care about this as much as I do
- I stay connected, I stay courageous, I stay authentic, I stay curious

### Workplace values

> Each of these has been operationalized into behaviors that we are all held accountable for demonstrating.

For example:

- Be Brave
  - set clear boundaries
  - lean into difficult conversations
  - talk to people, not about them
- Serve the work
  - Take responsibility for consumers' experience
  - Responsible for the energy I bring
  - Take ownership of adapting to fast pace environment
- Take good care
  - Treat colleagues with respect and compassion
  - Practice gratitude
  - Mindful of others' time

> Operationalized values also drive productive decision making.
