### ISSUE TITLE
Dec 3: Dare to Lead: The End and final impressions

### ISSUE THREAD

**Issue by mcgain** [Blackmill/book-club#43]
We're almost at the end of the book!

To finish we need to cover Offloading strategies, and the Story Rumble onwards.

We'll also discuss our final impressions of the book, and choose a new one.

MC: @elle 
Notes:  @mcgain

**Comment by agc0610** [comment]
Hi Richard, 
Lachlan invited me to join in this book club, and I'm excited to see y'all happen to be reading a book I finished recently! I've got the time and day, just wondering about the place. Thanks. :)

**Comment by elle** [comment]
My notes:
## Part 4: learning to rise

> Many parents have gone from helicopter parents to lawnmower parents. Instead of preparing the child for the path, we prepared the path for the child.

--
> The Learning to Rise process is about getting up from our falls, overcoming our mistakes, and facing hurt in a way that brings more wisdom and wholeheartedness into our lives.

--
> The reckoning is as simple as that: knowing that we’re emotionally hooked and then getting curious about it.

instead of being affected by our emotions without any self-control, or ignoring them, or taking them out on someone else

> How do we recognize that we’ve been snagged by emotion? From the wisest part of us—our body. We call emotions feelings because we feel them in our bodies—we have a physiological response to emotions.


### Offloading strategies

1. Chandeliering - flipping out or overreacting
1. Bouncing hurt - not dealing with hurt feelings because our ego gets in the way with anger, blame, and avoidance. Ego likes blaming, finding faults and coming up with excuses. All forms of self protection. Often the first hustle is shaming others for their lack of “emotional control.
1. Numbing hurt
1. Stockpiling hurt - as a result, we can experience many symptoms including anxiety, depression, burnout, insomnia, and physical pain.
1. The Umbridge - masking real pain, without connecting to other people
1. Fear of High-Centering - deny your feelings because of fear of getting stuck - not moving backwards or fowards

### Strategies for reckoning with emotions

> I define calm as creating perspective and mindfulness while managing emotional reactivity.

- Controlled breathing to help with emotional grounding
- Permission slips to feel certain emotions

### Story Rumble

> In the absence of data, we will always make up stories... The first story we make up is what we call the "shitty first draft"

--
> In our SFDs, fear fills in the data gaps. What makes that scary is that stories based on limited real data and plentiful imagined data, blended into a coherent, emotionally satisfying version of reality, are called conspiracy theories.

- Stay open minded
- Create time, space, and safety for people to reality check their stories... to ask questions 

> A confabulation is a lie told honestly. To confabulate is to replace missing information with something false that we believe to be true.

- Beware of opinions that are held as fact

**Try to write down:**

- The story I’m making up:
- My emotions:
- My body:
- My thinking:
- My beliefs:
- My actions:


**Questions to ask:**

What more do I need to learn and understand about

- the situation?
- the other people in the story?
- myself?

> The power of “the story I’m telling myself” is that it reflects a very real part of what it means to be a meaning-making human. It’s disarming because it’s honest. We all do it. This is why it works across diverse environments and with all people.

**Comment by mcgain** [comment]
notes added
