### ISSUE TITLE
Dec 10: (new book!) Thinking Fast and Slow - Intro, Chapters 1 & 2

### ISSUE THREAD

**Issue by lachlanhardy** [Blackmill/book-club#44]
**New Book!**

[Thinking Fast and Slow](https://www.amazon.com/Thinking-Fast-Slow-Daniel-Kahneman/dp/0374533555) by Daniel Kahneman.
  > _The central thesis is a dichotomy between two modes of thought: "System 1" is fast, instinctive and emotional; "System 2" is slower, more deliberative, and more logical. The book delineates cognitive biases associated with each type of thinking, starting with Kahneman's own research on loss aversion._

##Aiming to read:

- Introduction
- Chapter 1: The Characters of the Story
- Chapter 2: Attention and Effort

MC: @agc0610
Notes: @elle 

See you 12pm Tuesday, December 10th @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the Slack beforehand.

**Comment by elle** [comment]
Notes:
--
**What surprised you about this reading?**

- Lachlan: casually defining biases
- Elle: biases are usually automatic thinking and the only way to change them is to consciously stop and think about the situation and create new neural connections so that next time, those new connections become automatic.
- Antoine: immediate thinking about the librarian but not consider stats to think of farmers.
- Lachlan: would not occur to me to consider occurrences, rather than just resemblance.
- Aimee: never been thought to challenge and change our snap judgements
- Richard: reminded of the "Shitty First Draft" from "Dare to Lead", which probably comes from System 1

**About mastery**

- Practice again and again takes conscious work to make it automatic system 1
- Which can explain gut feelings about something -- it is basically learned knowledge that has been internalises but not consciously thought upon

**What is something that really confused you or made you feel ambivalent?**

- Richard: first time noticed a two step process to find a specific answer
- Lachlan: some information is kept differently. Different storage types is a good metaphor

**Müller-Lyer Illusion**

> Now that you have measured the lines, you—your System 2, the conscious being you call “I”—have a new belief: you know that the lines are equally long. If asked about their length, you will say what you know. But you still see the bottom line as longer. You have chosen to believe the measurement, but you cannot prevent System 1 from doing its thing; you cannot decide to see the lines as equal, although you know they are. To resist the illusion, there is only one thing you can do: you must learn to mistrust your impressions of the length of lines when fins are attached to them.

**If we cannot untrained system 1 about what we see, what are the implications for us as team leaders at work? in regards to biases, and gender equity? how not to perpetuate exclusion in the products we build?**

- Elle: Standardise the process and diversity inputs
- Richard: aware of biases in interviews and focused on the different ways man and women answer questions. Women are much more likely they were apart of the team, rather than man taking the credit. Now that I knew that, and paid attention, it was easier to overcome that biases. Basically learning about the problem and dig deeper into the underlying behaviours and their causes.
- Lachlan: standardise the rubric and train people involved in the process. Unconscious bias training. Best solution: I can't stop myself being biased, but I need to tell myself these things at every interaction. Not train yourself out of biases, but add a step to counter pre-existing thinking with new ways of thinking and new knowledge.
- Cognitive illusions of the mind - for example during depressive thinking, and making up stories. Need to consciously reconsider the stories we tell ourselves.

**Attention, effort, and context switching**

When doing an effortful task, switching the attention to do a different task has a mental tax of switching. And with all the distractions that we have in our work day, may it be email, or slack, or twitter or... the price is context switching is high, productivity suffers because people have trouble now days being in a state of flow.

The myth of task and context switching...
