### ISSUE TITLE
Thinking fast and slow: chapters 25-28: Tue 18th

### ISSUE THREAD

**Issue by mcgain** [Blackmill/book-club#52]
Aiming to read:
Chapter 25: Bernoulli's Errors
Chapter 26: Prospect Theory
Chapter 27: The Endowment Effect
Chapter 28: Bad Events

MC: @HashNotAdam 
Notes: @mcgain 

See you 12pm Tuesday, Feb 18th @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the Slack beforehand.

**Comment by elle** [comment]
**25: Bernoulli errors**
- Question: what choice did you take?
- Utility theory: defines outcomes as states of wealth
- Side note: When it costs me nothing to gamble, why not gamble?
- Side note: Game
- Utility function — law of diminishing returns
- Startups face bad choice so they are usually risk seeking
- Considering gains and losses should only be done in reference to the starting point, which is why people talk about pay raises in percentages
- Anthony thinks in gains and is therefore risk averse (he can only gain...) while Betty thinks in losses (can only lose) and this is risk-seeking
- Divorce settlement 

**26: Prospect theory**
- Define outcomes as gains and losses, not states of wealth
- Reference point from which the options are evaluated is all important!
- “In Bernoulli’s theory you need to know only the state of wealth to determine its utility, but in prospect theory you also need to know the reference state.”
- 3 cognitive features: evaluation, judgement, and emotion
- Evaluation: adaptation level
- Judgement: diminishing sensitivity 
- Emotion: loss aversion 
- “The response to losses is stronger than the response to gains”
- Many options we face in life are mixed with risk of loss and possibility of gain
- “Professional risk takers in the financial markets are more tolerant of losses, probably because they do not respond emotionally to every fluctuation.”
- Mixed gambles -> risk averse choices
- In bad choices -> risk seeking preferences 
- “Rabin’s theorem: anyone who rejects a favourable gamble with small stakes  is mathematically committed to a foolish level of risk aversion for some large gamble”
- Flaws:
  - “high probability of winning a large sum sets up a tentative new reference point. Relative to your expectations, winning nothing will be experienced as a large loss”
  - Prospect theory and utility theory also fail to allow for regret. Decisions are not made separately and independently. If you choose to gamble and lose, one regrets the “greedy” decision 

**27: Endowment effect**
- The more you have, the less you care for a new one of the same thing (the more income you have, the less you care for an extra dollar)
- Indifference curves assume that utility is determined by present situation
- Changing anything and the new situation is evaluated as pluses and minuses
- Side note: NY list of pros and cons
- A preference for status quo is a consequence of loss aversion!
- Flaws:
  - Tastes are not fixed, they vary with the reference point
  - The disadvantage of a change loom larger than its advantages, including a bias that favours the status quo
- Endowment effect: would you sell a ticket to a band you like for a lot more money?
- This is a great example of the difference between econs and humans. Also the difference between good for trading and goods to use and enjoy.

**28: Bad events**
- Negativity dominance: bad is stronger than good
- Side note: if you want a favourable memory, length of event doesn’t matter. Ensure it ended on a high note (earlier in the book?)
- “Bad impressions and bad stereotypes are quicker to form and more resistant to disconfirmation than good ones”
- “Long-term success of a relationship depends far more on avoiding the negative than on seeking the positive... good interactions outnumber bad interactions by at least 5 to 1.”
- Friendships: years to develop, ruined by one action 
- Goals are reference points: not achieving a goal is a loss, exceeding a goal is a gain. People work harder to make the goal, but exert less effort to exceed it.
- Golfers will try harder to avoid a bogey than to achieve a birdie -> example of asymmetric intensity of motives
- Work agreements usually means any change is considered a loss (concession) one side makes. “Loss aversion creates an asymmetry that makes agreements difficult to reach.”
- In the animal world, this concept explains the success of defenders 
- Hardware store example -> reminds me of Uber’s algorithm raising prices during a terrorist attack in Sydney 

Question: what can we take from all of this?

**Comment by mcgain** [comment]
*Conversation Notes*
The theory induced blindness stuff was pretentious and annoying. How do these chapters relate to the topic of the book anyway?

Adam and Antoine are enjoying this part of the book, Elle and Richard are not. 

As non-academics who don’t have the time to reconsider everything all the time, how do we get past our theory induced blindness?

Pre-mortems are good for this 

Theories are not often globally applicable, can't utility theory be the best thing in some cases, and prospect theory in others?

Utility theory was relevant for centuries, and his new theory just builds on it, so all the crowing over defeating it seems a bit much.

The million dollar salary question prompted some ideas about how we are not the mean. We don’t make the same decisions as most of the people in this book.

The author was 75 when the book was published, and is an arrogant successful  academic. The books tone might be explained by this

That said, we’re impressed by him bringing in “adversaries” and working with them, and also addressing criticism of his work. 

We've often said we don't choose the option he expects in some of his examples. On the topic of not thinking the same way as he’s expecting, we still agree that loss and gain are different things and so despite some of us making the less common choice, we still accept the theory.

Context is important here, where did the money come from? How did we earn it? Or were we just given the money?

This topic might relate to gambling and how winners often lose it all. 

Adam has modernised some of the phrases in this book
Big Dick Energy - Endowment effect
FOMO - Loss aversion 

Two people equally value 10k and also extra vacation days, loss aversion means they won’t swap them. This example is also possibly confused by external factors. 

We discussed some real life examples of gainm, like people taking vacation days instead of a raise. We talked about perks and how people value the utility of them differently.

Negativity has a higher impact in a workplace than positivity. In Golf apparently people fight hard when they’re over par, then slack off once they’re back to par. 

If we assume there’s a 5:1 ratio of positive and negative events to balance things out, then wouldn’t it be a good idea to try to reduce negativity instead of adding positives, in order to have an overall good effect.

We don’t focus on removing negatives because it’s hard. A lot of hard things can’t be fixed by policy. Speaking of policies, we shared examples where implementing these policies (such as leave or training policies) can take ages.

*What did we get out of these chapters?*

Be more conscious of loss aversion

Taxi drivers, on rainy days should milk it, but instead they give up once they’ve met their target. On nice days they slog for ages to meet that target. This sounds familiar to us programmers, sometimes we should just call it a day.
