### ISSUE TITLE
The Pragmatic Programmer, 20th Anniversary Edition: Foreword to Chapter 1  – March 17th

### ISSUE THREAD

**Issue by lachlanhardy** [Blackmill/book-club#54]
https://pragprog.com/book/tpp20/the-pragmatic-programmer-20th-anniversary-edition

Aiming to read:
- Foreword
- Preface to the Second Edition
- From the Preface to the First Edition
- Chapter 1

We'll also determine a plan to work through the rest of the book.

MC: @elle 
Notes: @mcgain 

See you 12 pm Tuesday, March 17th @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand.

**Comment by elle** [comment]
# The Pragmatic Programmer

## Forward

> This community is very different from others I'd been a part of. There is a unique dedication to learning and practicality that is both refreshing and intimidating

Reminded me of Nadia's talk at Ruby Conf AU 2019

## Preface to the second edition

- Updated references and re-examined assumptions
- Included exercises (with straightforward answers) and challenges (open-ended questions)

### About jargon

> jargon — either perfectly good English words that have been corrupted to mean something technical, or horrendous made-up words that have been
assigned meanings by computer scientists with a grudge against the
language.

--
> Sometimes, there are perfectly good jargon words for
concepts, words that we’ve decided to ignore. Why? Because the existing
jargon is normally restricted to a particular problem domain, or to a
particular phase of development. However, one of the basic
philosophies of this book is that most of the techniques we’re
recommending are universal: 

## Preface to the first edition

> your user wants it to do). As a programmer, you are part listener, part advisor, part interpreter, and part dictator. You try to capture elusive requirements and find a way of expressing them so that a mere machine can do them justice. You try to document your work so that others can understand it, and you try to engineer your work so that others can build on it. What’s more, you try to do all this project clock.

--
> There is no best solution, be it a tool, a language, or an operating system. There can only be systems that are more appropriate in a particular set of circumstances.

Adjust your approach to suit the current circumstances and environment.

### What makes a pragmatic programmer?

1. Early adopter/fast adapter
1. Inquisitive
1. Critical thinker
1. Realistic
1. Jack of all trades

### Individuals vs teams

### Continuous process

> “Kaizen” is a Japanese term that captures the concept of continuously making many small improvements.

## 1: a pragmatic philosophy

### Topic 1: it's your life

Attitude and philosophy of approaching problems and their solutions.
If you're frustrated, change it.

### Topic 2: the cat ate my source code

Take responsibility, don't be afraid to admit ignorance or error.
But for that you need team trust.

> Don’t blame someone or something else, or make up an excuse. Don’t
blame all the problems on a vendor, a programming language, management,
or your coworkers. Any and all of these may play a role, but it is up
to you to provide solutions, not excuses.

Easy to do when someone left the project.

Offer options instead of excuses. Instead of "it can't be done", explain what can be done to salvage the situation.

**Challenges:**

1. How do you react when a service person tells you something cannot be done?
1. When you don't know something, follow up to learn what you don't know

### Topic 3: software entropy

- All the disorder! "Rot" or "technical debt", usually because of culture or psychology.
- Broken window syndrom
- Work on quality instead of neglecting the source code
- Scouts guideline: leave the codebase better than you found ti

**Challenges:**

1. Choose 3 problems in your codebase to fix
1. Why did the first broken window happen? what was the reaction? what did you do about it?

### Topic 4: stone soup and boiled frogs

Look for strategy for instigating change.

**Challenges:**

1. How do you decide you're making a stone soup or a frog soup? is the decision subjective or objective?
1. Situational awareness

### Topic 5: good enough software

> The phrase “good enough" does not imply sloppy or poorly
produced code. All systems must meet their users’ requirements to be
successful, and meet basic performance, privacy, and security standards. We are simply advocating that users be given an
opportunity to participate in the process of deciding when what you’ve
produced is good enough for their needs. 

- Define how good your software should be.
- Involve your users
- Avoid feature scope
- Know when to stop

**Challenges:**

1. What do you prefer: perfect software a year from now? or complex software with some bugs? or simpler software quicker with fewer bugs?
1. Monolith or microservices?
1. Can you think of software with feature bloat?

### Topic 6: your knowledge portfolio

> Your ability to learn new things is your most important strategic asset. But how do you learn how to learn, and how do you know what to learn? 

Broaden your knowledge and keep learning

### Topic 7: communicate

Learn to communicate with others, we do not live in a vaccum

## Tips

1. Care about your craft
2. Think about your work - never run on auto pilot. Constantly be thinking, critiquing your work in real time.
3. You have agency
4. Provide options, don't make lame excuses
5. Don't live with broken windows
6. Be a catalyst for change
7. Remember the big picture
8. Make quality a requirement issue

**Comment by mcgain** [comment]
# Conversation Notes

## The Foreword
20 years ago this stuff was new and exciting, it’s all old to us. But, there are plenty of people who could still use this advice, even today. Michael pointed out that there are people who've been doing the same thing for 20 years and even things like version control would be new to them.
	
The author of the foreword, Saron Yitbarek of CodeNewbies, doesn’t tinker. Lachlan thinks it’s a good idea to get her to write the preface since she brings newbies in. On the other hand, she specifically doesn't learn random stuff, only things that forward her goals.

We then talked about the list “What makes a pragmatic Programmer” some of the categories fit us, others don’t. 

Antoine didn’t expect Jack of All Trades as a concept to be praised, since he is one, but he’s happy about it. We talked about T Shaped people, perhaps specialization and a broad base is ok?
Michael doesn’t consider himself a specialist, but is a tinkerer. 

## Chapter 1

**It’s Your life** is new material for the 2nd edition, but we didn't talk much about it.

**The Cat Ate My Source Code.** This section Blew Richard’s Mind 10 years ago! It also reminded Michael of the book Atomic Habits, which encourages building such things.

Elle told a story about trust in teams, and how this is hard to build. Nick points out the retrospective mantra. “Everyone did the best job they could, with the best of intentions, in the environment of the time". This is key to building trust in teams. Michael suggests using the language of the team. “The team decided”, “the team did this”.

Getting the tone right in Pull Requests is difficult, since it can be construed as an attack. Nick suggested using emoji’s to indicate how important each comment is. Elle found that at Thoughtbot, with developers of equal power and talent, code review suggestions were always ultimately up to the developer. 

Lachlan talked about wasting time on frustrating problems. That feels bad, but in this particular case, because the team is was safe space, it was fine. The team acknowledged that this was probably a bad idea since so much time was wasted. They did not fall for the sunk cost fallacy. 

Challenges: How do we react when a bank teller or someone comes up with a lame excuse? Badly, according to Elle. Nick says this is because we think we know more than the other person and he encourages us to assume that people know things that we don’t, and have good reasons to discount them.

Developers are the “edge case”, most people are not developers and use software differently. Michael reminds us to actually talk to the users. 

**Software Entropy **
Broken windows theory: Lachlan says there are many criticisms of this theory. It was a simplistic analysis. Mayor Juliani of NY took up the theory and made it work, but crime dropped normally anyway across the entire US. There are concerns of racist policing as well. [Adam finds it hard not to yell at this article about Broken Windows](https://www.theatlantic.com/magazine/archive/1982/03/broken-windows/304465/) 

Tom has only worked on buildings with entirely smashed windows. His coping strategy is to at least not break any more windows.
Elle paraphrases the scouting term – “leave the codebase in a better state than you found it”. For example, don’t make the code climate score worse. Michael pointed out that this is often misunderstood by people who end up making things worse anyway. Tom talks about quality ratchets. You can’t add new warnings or problems when you add code.

Richard pointed out that we just moved on from Lachlan’s criticism of the broken windows theory. Adam isn’t so sure the theory has been debunked. Nick talks about keeping a positive mindset. Lachlan pointed out that there is a difference between social disorder and crime, and linking them isn’t correct. Instead there is a third element in play that is affecting the neighborhood and crime rate. It is the agency of people to control their social spaces. [See Wikipedia for more details](https://en.wikipedia.org/wiki/Broken_windows_theory#Relationship_between_crime_and_disorder).

Tom doesn’t think it’s possible to fix all the windows. It’s a problem of culture. Unless you fix the team, you won’t improve. Elle and Michael pointed out that there are so many parallels to the broken window theory, from washing up to dropping rubbish on the street.

**Stone Soup and Boiled Frogs**

Elle asked, how do we actually do what the soldiers do in our jobs? No one seems to have a suggestion. Richard came up with the idea that building tooling and information dashboards is a way to emulate those soldiers. Neighborhoods cluster. See anti-vaxxer enclaves, lawn watering patterns etc.

We didn't finish talking about chapter 1, we'll finish it next week.
