### ISSUE TITLE
The Pragmatic Programmer, 20th Anniversary Edition: Chapter 2 – March 24th

### ISSUE THREAD

**Issue by mcgain** [Blackmill/book-club#57]
https://pragprog.com/book/tpp20/the-pragmatic-programmer-20th-anniversary-edition

Aiming to read:

  Chapter 2

We also need to finish discussing chapter 1. We're up to section 5 **Good-Enough Software**

MC: @lachlanhardy 
Notes: @elle

See you 12 pm Tuesday, March 24th @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand.

**Comment by lachlanhardy** [comment]
## Topic 6: Knowledge Portfolio

Did we think the stock market investor analogy holds up?

Make a habit of learning. Develop a routine.

Does the Java example hold true? Did early adopters of Java really gain that many more benefits than those who came once it was mainstream?

You've all read this book in the past, how many of you adopted and maintained this practices?

Anyone tried learning a new language each year?

Was anyone inspired by the challenge to try a new one this week?

## Topic 7: Communicate!

> A good idea is an orphan without communication.

Treating a technical document like any other formal piece of writing makes good sense to me. I don't hear that advice shared much. But then I don't hear people talk about writing docs much either...

Make it look good is never followed in my experience. Anyone?

Sharing early drafts is great too, but I suspect it only works with a certain scale.

# Chapter 2: A Pragmatic Approach

## Topic 8: The Essence of Good Design

Easy To Change as a fundamental principle underlying most "good programming" concepts. 

It's a value, not a rule. Values are things which help you make decisions.

Can anyone think of a counter-example?

> Note the situation in your engineering day book...

WTF is that? Does anybody have one?

I also don't know what "leave a tag in the source" means.

## Topic 9: DRY – The Evils of Duplication

> Every piece of knowledge must have a single,
unambiguous, authoritative representation within a system. 

> DRY is about the duplication of knowledge, of intent. It’s about
expressing the same thing in two different places, possibly in two
totally different ways. 

> Rather than writing code that represents external data in a fixed structure (an instance of a struct or class, for example), just stick it into a key/value data
structure (your language might call it a map, hash, dictionary, or even object). 

Anyone ever had a "project librarian"?

## Topic 10: Orthogonality

Helicopter analogy is terrifying.

I had just come to the realisation that orthogonality is the basis of all the modular design I advocate when they explained that.

Amazing hide in a footnote:
> In reality, this is naive. Unless you are remarkably lucky, most
real-world requirements changes will affect multiple functions in the
system. However, if you analyze the change in terms of functions, each
functional change should still ideally affect just one module. 

> Write shy code—modules that don’t reveal anything unnecessary to
other modules and that don’t rely on other modules’ implementations.

> tag bug fixes when you check the code
back in after testing. You can then run monthly reports analyzing trends
in the number of source files affected by each bug fix. 

Anyone tried this?

They wrote this whole book in Markdown, wtf? How was it edited?

Did anyone do the exercises?

## Topic 11: Reversibility

> Requirements, users, and
hardware change faster than we can get the software developed. 

Hardware, really?

> The mistake lies in assuming that any decision is cast in stone—and
in not preparing for the contingencies that might arise. Instead of
carving decisions in stone, think of them more as being written in the
sand at the beach. A big wave can come along and wipe them out at any
time.

> It’s a miracle that anything ever worked. 

## Topic 12: Tracer Bullets

> That same principle applies to projects,
particularly when you’re building something that hasn’t been built
before. We use the term tracer bullet development to visually illustrate the need for immediate feedback under actual conditions with a moving goal. 

> Look for the important requirements, the ones that define the
system. Look for the areas where you have doubts, and where you see
the biggest risks. Then prioritize your development so that these
are the first areas you code. 

> For us, the very first tracer bullet is simply create the
project, add a “hello world!,” and make sure it compiles and runs. 

I do the same. I make a hello world, and get it deployed. Preferably to production (or a production-equivalent). And keep deploying all the way through to make sure everything actually continues to work in production.

> Tracer development is consistent with the idea that a project is never
finished: there will always be changes required and functions to
add. It is an incremental approach.

> You might think that this tracer code concept is nothing more than
prototyping under an aggressive name. There is a difference. With a
prototype, you’re aiming to explore specific aspects of the final
system. With a true prototype, you will throw away whatever you lashed
together when trying out the concept, and recode it properly using the
lessons you’ve learned. 

> The distinction is important enough to warrant repeating. Prototyping
generates disposable code. Tracer code is lean but complete, and
forms part of the skeleton of the final system. Think of prototyping
as the reconnaissance and intelligence gathering that takes place
before a single tracer bullet is fired.

I'm sick of war analogies.

## Topic 13: Prototypes and Post-It Notes

> Prototyping is a learning experience. Its value lies not in the
code produced, but in the lessons learned. 

I love the assumption here that a Pragmatic Programmer will just use a different language, framework, or toolset to prototype because they can.

> Prototypes can be deceptively attractive to people who don’t know that they are just prototypes. You must make it very clear that this code is disposable,
incomplete, and unable to be completed. 

That last point is key. I don't think I've ever heard anyone put it like that.

### Exercise
Anyone?

## Topic 14: Domain Languages

> Your business users will have a vague idea of what they want to achieve, but they neither know nor care about the details. That’s part of our value: we intuit intent and convert it to code.

### Challenges
Anyone?

### Exercises
Anyone?

## Topic 15: Estimating
> To some extent, all answers are estimates. It’s just that some are more
accurate than others. So the first question you have to ask yourself
when someone asks you for an estimate is the context in which your
answer will be taken.

> One of the interesting things about estimating is that the units you use
make a difference in the interpretation of the result. If you say that
something will take about 130 working days, then people will be
expecting it to come in pretty close. However, if you say “Oh, about
six months,” then they know to look for it any time between five and
seven months from now. Both numbers represent the same duration, but
“130 days” probably implies a higher degree of accuracy than you feel.

> All estimates are based on models of the problem. But before we get too
deeply into the techniques of building models, we have to mention a
basic estimating trick that always gives good answers: ask someone who has already done it.

> Only in the simplest of cases will an estimate have a single answer. 

> You almost always get better results if you slow the process down
and spend some time going through the steps we describe in this section.
Estimates given at the coffee machine will (like the coffee) come back
to haunt you. 

### Challenges and Exercises
Anyone?

**Comment by mcgain** [comment]
# Conversation Notes

## End of chapter 1
### Topic 6: Knowledge portfolio

Does the stock investor metaphor for early adoption of software hold up?

If you were an early adopter of Java, were you better off than someone who came along later?

Maybe not is the consensus, but 

Tom says early adoption gives an opportunity to become a community leader. 

Lachlan asks whether anyone actually invested in knowledge, as described in the book.

Richard tried to learn a new language each year, but usually fails miserably.
Tom learned a bit of closure, and he doesn’t use it now, but it fundamentally affected the way he programs now. So did Michael, and he found that it changes the  way you think about problems.

### Topic 7 Communicate:
Treat documentation like any other formal communication. Michael says some guy from basecamp won’t hire people who cant write well.

Richard described the RFC(Request For Comments) process at Shopify, where we wrote up RFCs and shared within the team to polish them, then shared them with the wider org. We found that often too many comments could drag things out, so we started to share only with “stakeholders and other people who would actually be involved”. Antoine shared this experience.

## Chapter 2: A pragmatic approach
Nick couples frontend design to backend apis, using things like View Models, where only the data for the view is presented to the view. These things are lightweight, so can be thrown away when the interface changes. 

Lachlan asks wtf is a engineering daybook?
Richard thinks it’s a daily log of decisions and learnings, along with todos that becomes a record of the project.
Nick says ” The reason it is called a day book is that once it is full, they write the date range on the spine and put it on the shelf”
(This is mentioned again in the next chapter)

Antoine mentioned that git is a good source of documentation that adds timestamps etc. Michael says no one ever remembers to write the reason why they made a decision in commit messages.
Elle has a talk on this very topic. She says the code says what you did, the commit message should say why you did it. 

Nick points out that stuff that doesn’t work, and is never merged, never gets into the git commits, so you can’t actually see the bad decisions. 

### DRY – Don't Repeat Yourself
Elle – Sandi Metz says wait for 3 occurences to DRY, if you’ve only got 2, you’re likely to get the abstraction wrong.

Richard said he made the mistake of DRYing duplicate code instead of duplicate meaning for years, before realising.

Sandi Metz says “Drunk me doesn’t understand”, sometimes duplication is a good idea.

Tom says DRY is in direct contradiction to making things reusable. DRY can add coupling and makes things hard to reuse. 

Elle says mixins are the perfect example of this in Rails. We overused them as a community for a long time. 

Antoine talked about developer duplication. Tom gave an example of this with stylesheets where duplication is probably a good idea. 

Lachlan says, until you know what the abstraction should be, leave it duplicate. 
We all wax lyrical for a while about the evils of dry.
Antoine says recently he found some lower level code that was badly duplicated, so utility classes are a great candidate for drying out. 
Lachlan says institutional knowledge is key here to figuring out which stuff is utility and which stuff isn’t.

Elle says create a domain language, a dictionary of terms to help with this

Adam loves the idea of ui elements where there is a design trend to make reusable utility classes in css. How does this apply on the backend?

Naming things is hard, how do we create a domain language for low level utility stuff. 

Elle says this concept is good for the actual domain of the software, such as fabric manufacturing, or banking. Not nouns vs verbs, but “funds transfer vs top up”

Tom talks about ddd and the use of ubiquitous language and bounded concepts .

Michael says “just have a project librarian”

Lachlan refrains from making sarcastic comments about ddd

### Orthogonality
Elle says this reminds her of hexagonal design. Business logic lives in service logic, but also consider having value objects or fundamental concepts that live apart from concepts

Lachlan likes shy code. Don’t interfere with other peoples stuff

Tagging bugfixes sounds cool then we can figure out which files cause which bugs. Where is this software.
Richard said he tried this and it didn’t work. Not enough context and information in the commits. Michael analysed his commits in the same way to detect how much pairing they were doing. It would be interesting to analyse this data. 
Elle mentions a destroy all software episode where he analyses git history. 

Lachlan was blown away that the book was written in markdown and wonders how it is editied. Elle says they did this at thoughtbot and used prs to edit.

Reversability --- requirements change quickly. Wow! Lachlan was incredulous that hardware changes so quickly.

Code is not fixed, no decisions should be fixed. 

Tom says this is a trap! If anything can change, you can spend ages decoupling systems. You need to consider the idea that anything might change, but make the call that some things are not worth changing. (Unless you db is mongo – Richard)

### Topic 12. Tracer bullets. 

We ran out of time, so we'll do this next week
