### ISSUE TITLE
The Pragmatic Programmer: Topics 37-40 - April 28

### ISSUE THREAD

**Issue by elle** [Blackmill/book-club#63]
Book: https://pragprog.com/book/tpp20/the-pragmatic-programmer-20th-anniversary-edition

Aiming to cover:

Chapter 7:
- Topic 37: Listen to your lizard brain
- Topic 38: Programming by 
- Topic 39: Algorithm speed
- Topic 40: Refactoring
 
MC: @elle 
Notes: @saramic 

See you 12 pm Tuesday, April 28st @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand.

**Comment by elle** [comment]
# Chapter 7 - while you are coding

## Topic 37: Listen to your lizard brain

- Fear of the blank page
  - Or fear of making a mistake and failing
- Suggestions:
  - Take a break
  - Explain in to someone
  - Tell yourself it is a spike and this code will be thrown out
- Listen to your gut not just when coding, but bigger picture as well
- But gut feelings come from experience!

## Topic 38: Programming by coincidence

- Phantom patterns (thinking fast and slow)
  - Suggestion: don't assume it, prove it
- Deliberate programming means:
  - Conscious contexts: for example who are our users?
  - Conscious and documented assumptions
  - Don't operate on auto-pilot
  - Review code along the way
  - Consider what your expose to the outer world
  - Document behaviour, and reasonings and assumptions behind it
  - We can explain the code and its reasoning to a junior
  - Understand the technology and why it fails
  - Have a plan
  - Test your code and your assumptions
  - Prioritise work efforts
  - Don't do things because this how they were done so far

## Topic 39: Algorithm speed

> In Topic 15, ​ Estimating ​ , we talked about estimating things such as how long it takes to walk across town, or how long a project will take to finish. However, there is another kind of estimating that Pragmatic Programmers use almost daily: estimating the resources that algorithms use—time, processor, memory, and so on. 

- Bio O notation
- Think of `o` the as meaning on the _order of_.

```
O(1) = Constant
O(log n) = Logarithmic (binary search).
O(n) = Linear (sequential search)
O(n log n) = Worse than linear, but not much worse. (Average runtime of quicksort, heapsort)
O(n^2) = Square law (selection and insertion sorts) O(n^3) = Cubic (multiplication of two matrices)
O(c^n) = Exponential (traveling salesman)
```

> run. If the numbers depend on external factors (such as the number of records in an overnight batch run, or the number of names in a list of people), then you might want to stop and consider the effect that large values may have on your running time or memory consumption. 

--
> If you’re not sure how long your code will take, or how much memory it will use, try running it, varying the input record count or whatever is likely to impact the runtime. Then plot the results. You should soon get a good idea of the shape of the curve. Is it curving upward, a straight line, or flattening off as the input size increases? Three or four points should give you an idea.

Test your estimates!

## Topic 40: Refactoring

> Rewriting, reworking, and re-architecting code is collectively known as restructuring . But there’s a subset of that activity that has become practiced as refactoring

According to Martin Fowler:

> disciplined technique for restructuring an existing body of code, altering its internal structure without changing its external behavior. 

Critical parts:

1. Activity is disciplined
1. Functionality does not change
1. Tests are a must

When? along the way, all the time. There is never time to stop for a while just to clean code. Also easier when the problem is smaller.

What?

- Code duplication
- Nonorthogonal design
- Outdated knowledge
- User interaction is not as anticipated
- To improve performance

How?

> At its heart, refactoring is redesign. Anything that you or others on your team designed can be redesigned in light of new facts, deeper understandings, changing requirements, and so on.

Tips:

1. Don’t try to refactor and add functionality at the same time.
1. Make sure you have good tests before you begin refactoring. Run the tests as often as possible. 
1. Take short deliberate steps. If you keep your steps small, and test after each step, you will avoid prolonged debugging.

> Manage the pain: if it hurts now, but is going to hurt even more later, you might as well get it over with. Remember the lessons of Topic 3, ​ Software Entropy ​ : don’t live with broken windows.

**Comment by saramic** [comment]
# Discussion Notes

## Topic 37: Listen to your lizard brain

- a lot of experienced devs have an intuition that they often can't explain
- intuition is based on a lot of previous cases
    - these create unconscious patterns, similar to ideas in the previous book [thinking fast and slow](https://github.com/Blackmill/book-club/issues/44)
- from book example
    - firefighters act on instinct and can't wait long enough to consciously think, need to act
    - stock market people have zero good instincts
    - feedback loop needs to be correct and short
- need lots of experience to have gut instincts
    - learning pain points
- explain it to someone
    - if you can't explain then maybe it is not a good idea
    - working with juniors is beneficial as they will ask a lot of whys and give you an opportunity to describe these things
- to understand a problem writing a blog post may be a good thing, useful to understand assumptions and similar to a duck (as in rubber duck programming)
    - none of us has really done much rubber duck programming
- story of devs clashing on topics (in a professional manner)
    - due to different approaches to building software
    - came down to 1 small opinion on ruby module and class
    - just talk about it and understand differences allowed the devs to deal with these things and get around "lizard brain reactions"
    - understanding differences allowed for consciously dealing with them
- having a style guide is useful to solve arguments
- talking to people solves lots of problems
- ThoughtBot having a published [style guide](https://github.com/thoughtbot/guides/tree/master/style) helps people self-select for that organisation - you are not going to apply for a job there if you disagree with everything they say and do
-  intuition is good around structuring programs and solving problems
    - damaging around quoting and estimating effort
    - estimates are often wrong until you try to solve it, even based on similar problems in the past
    - people who get better - record what they said and what was the result - a way of better learning from a slow feedback loop
    - feedback does not need to be fast as long as you can refer back to the plan and result
    - soft skills don't have as easy feedback to learn from

## Topic 38: Programming by coincidence

- conscious programming - who are the users
- don't write on autopilot
- so much magic in Rails especially ActiveRecord
- bookclub for code readings, ie reading actual code/libraries Saron Yitbarek
    - [RailsConf 2014 - Reading Code Good by Saron Yitbarek - YouTube](https://www.youtube.com/watch?v=mW_xKGUKLpk)
    - https://www.codenewbie.org/
    - have to be conscious about which codebases you choose
- the accidents of implementation
    - mutation testing - talk at RORO Tom Dalling - unfortunately no video on [RORO](https://www.youtube.com/channel/UCr38SHAvOKMDyX3-8lhvJHA/videos)
    - remember to delete irrelevant code
    - Andrew Grimm's many talks on mutation testing
        - [chaser GitHub](https://github.com/agrimm/chaser)
        - [zombie-chaser GitHub](https://github.com/agrimm/zombie-chaser)
- database backups conversation
     - story from 2004, of not backing up to realise it was production critical data and managing to piece it back together
    - use SaaS service database and backups these days
- let's just rewrite this old crap - more nuanced discussion
    - could we manage if we lost this - code?
  
## Topic 39: Algorithm speed

- good explanation of Big O notation
    - some constants in an algorithm
    - example of cleaning house prior to a dinner party irrelevant how many guests are coming
    - saying hello to each guest, pass the dish to each one
- but logarithm is not explained 
    - Lachlan knows what exponential is "Elle laughs"
- no mention of benchmarking - big thing missing from the book
    - big O is **not** actual run time - a rough guide for comparison
    - Elle is having a dinner party and we all bring a friend N*2
        - Nick does not really care about the second guest
- Mention of Skiena, ["The Algorithm Design Manual"](https://link.springer.com/book/10.1007/978-1-84800-070-4) in particular the _War Stories_ and "2.8 War Story: Mystery of the Pyramids" as an example of using big O notation
    - [Knuth book](https://www-cs-faculty.stanford.edu/~knuth/books.html) description of big O is not as useful
  - [Grocking Algorithms book](https://www.manning.com/books/grokking-algorithms) has a good discussion of big O and speed of algorithms
- back to the dinner party
    - Nick - But if each guest brings a partner the confusing part is that it is O(n) even though it is really O(2n) because we drop the constant and I have this book somewhere which has a whole capture with example questions for this topic [Cracking the Coding Interview: 189 Programming Questions and Solutions](https://www.amazon.com.au/Cracking-Coding-Interview-Programming-Questions/dp/0984782850/)

## Topic 40: Refactoring

- what if a user has never refactored - just added new code?
- instead of 1 small change at a time - developers often go too big and everything breaks
- Sandi Metz - **"Horizontal refactoring"**
    - change 1 line and run your tests
    - slow but disciplined
    - don't have image of how it should work but just apply one recipe at a time by code smell
    - [99 bottles of OOP - 4. Practising Horizontal Refactoring](https://www.sandimetz.com/99bottles/sample)
    - also [Kent Beck - don't cross them beams - avoiding interference between horizontal and vertical refactorings](https://www.facebook.com/notes/kent-beck/dont-cross-the-beams-avoiding-interference-between-horizontal-and-vertical-refac/260531380646400/)
- auto refactoring tools of re-sharper allow you to move much faster and I miss in Ruby/JS
- TCR (Test Commit Reset) - sets mindest of what is the smallest change - to move the problem forward
- small change regularly
- like tax office taking tax incrementally
- Richard trying to sell to juniours "you should always be refactoring"
    - "don't tell management, make it part of your daily workflow"
    - "but that would be lying to management" - "it's a no brainier - professional responsibility"
- prefactor - ["for each desired change, make the change easy (warning: this may be hard), then make the easy change"](https://twitter.com/kentbeck/status/250733358307500032?lang=en)
- not all about the product (for us developers) about the code quality - work-life balance

## Other discussions

**Next book:** [Doing Good Better](https://www.amazon.com.au/Doing-Good-Better-Effective-Difference-ebook/dp/B00OYXWL4W)

**Next week:** rest of Ch7 (5/5), then ch8 (12/5) and ch9 (19/5 ~ 26/5) so next book likely start 26 May or 2nd June

- Adam and Lachlan keeping their hate for the book to a minimum
- Lachlan still hating any army references
