### ISSUE TITLE
The Pragmatic Programmer: Topics 41-44 - May 5

### ISSUE THREAD

**Issue by lachlanhardy** [Blackmill/book-club#64]
Book: https://pragprog.com/book/tpp20/the-pragmatic-programmer-20th-anniversary-edition

Aiming to cover:

Chapter 7:
- Topic 41: Test to Code
- Topic 42: Property-based Testing
- Topic 43: Stay Safe Out There
- Topic 44: Naming Things
 
MC: @lachlanhardy  
Notes: @elle  

See you 12 pm Tuesday, May 5th @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand.

**Comment by lachlanhardy** [comment]
## 41: Test to Code
> We believe that the major benefits of testing happen when you think about and write the tests, not when you run them.

---
> A test is a first user for your code

---
> before you can test something, you have to understand it. That
sounds silly, but in reality we’ve all launched into a piece of code
based on a nebulous understanding of what we had to do. We assure
ourselves that we’ll work it out as we go along. Oh, and we’ll add all
the code to support the boundary conditions later, too. Oh, and the
error handling. And the code ends up five times longer than it
should because it’s full of conditional logic and special cases. But
shine the light of a test on that code, and things become clearer. If
you think about testing boundary conditions and how that will work
before you start coding, you may well find the patterns in the logic
that’ll simplify the function. If you think about the error conditions
you’ll need to test, you’ll structure your function accordingly. 

> Neither school actually works, because both ignore one of the most
important aspects of software development: we don’t know what we’re
doing when we start. 

Build end-to-end instead. Again describing Agile concepts without naming them.

They view unit testing as testing against contract.

> If the code broke once, it is likely to break again.
Is that true?

> I (Dave) have been known to tell people that I no longer write tests. Partly I do it to shake the faith of those who have turned testing into a religion. And partly I say it because it 

Testing is part of programming.


## 42: Property-based Testing
Do we know other libraries like Hypothesis?

QuickCheck
https://github.com/rantly-rb/rantly

> when a property-based test fails, find out what
parameters it was passing to the test function, and then use those
values to create a separate, regular, unit test. That unit test does two
things for you. First, it lets you focus in on the problem without all
the additional calls being made into your code by the property-based
testing framework. Second, that unit test acts as a regression test .



## 43: Stay Safe Out There

1. Minimize Attack Surface Area 
2. Principle of Least Privilege
3. Secure Defaults
4. Encrypt Sensitive Data
5. Maintain Security Updates 

What would we add to this list?
 
## 44: Naming Things

Gah.

**Comment by elle** [comment]
# Chapter 7
## 41 Test to code

- The best advantage is actually thinking about tests, to help consider how to structure the code
- Tests drive coding
- A test is the first user of your code
- TDD: write the tests first
- Did they mention regression tests? to help with refactoring later
- Tests do not necessarily lead to good code architecture
- Bottom up vs top down: build things incrementally. This follows on their talk about prototyping
- Unit tests against contracts
- They believe in dependency injection without using the exact term. If I was a new developer, I would not have a reference or term to look up
- Spike is when we don't know what we're doing and we're just going to play with it and figure it out
- Dave Thomas stopped writing tests after 30 years and his code was still in similar structure. But that only works when one has enough experience
- Testing is part of the job
- A culture of testing:
  - Test first
  - Test during
  - Test later (never)

## 42: Property-based testing
> one of the biggest benefits of thinking about tests is the way it informs the code you write. You lose that when the work of testing is split from the coding. 

QA people vs developers writing the tests. **Why not both?**
Possibly someone else thinking from high level point might be useful.

- Random data generator libraries:
  - Python: [Hypothesis](https://hypothesis.works/articles/what-is-property-based-testing/)
  - Haskell: Quickcheck in Haskell
  - Ruby: [Rantly](https://github.com/rantly-rb/rantly)
- Random data generator for tests can make your tests a lot slower
- Define your bad assumptions
- Can probably be run to find the edge cases, and then add them to the test suite
- Model based testing
  - https://reactconfau.com/talks/write-fewer-tests-model-based-testing-in-react?from=talks
  - https://www.guru99.com/model-based-testing-tutorial.html
  - https://saucelabs.com/blog/the-challenges-and-benefits-of-model-based-testing
- Terms used:
  - Contracts - types
  - Invariants - constants
  - Properties - values/inputs -> validate assumptions and test boundaries
  - Model - states in a finite state machine

> property-based tests generate random values that get passed to your test, there’s no guarantee that the same values will be used the next time you run tests... We believe that property-based testing is complementary to unit testing: they address different concerns, and each brings its own benefits.

--
> When we talked about unit testing, we said that one of the major benefits was the way it made you think about your code: a unit test is the first client of your API. The same is true of property-based tests, but in a slightly different way. They make you think about your code in terms of invariants and contracts; you think about what must not change, and what must be true. This extra insight has a magical effect on your code, removing edge cases and highlighting functions that leave data in an inconsistent state. 

## 43: Stay safe out there

> In the first edition’s discussion of code coupling we made a bold and naive statement: “we don’t need to be as paranoid as spies or dissidents.” We were wrong. In fact, you do need to be that paranoid, every day. 

Just like in Covid-19 days...

- [Pundit](https://github.com/varvet/pundit): Object oriented authorisation for Rails applications
  - Warns you when things should be done

### Security basic principles

1. Minimise attack surface area - sum of access points.
  - Code complexity: simple, smaller code is better. Less code means fewer bugs, fewer opportunities for a crippling security hole. Simpler, tighter, less complex code is easier to reason about, easier to spot potential weaknesses.
  - Never trust data from external entity. Sanitise!
  - API end points should be authenticated, and kept to minimum authorised users
  - Truncate or obfuscate potentially risky information such as Social Security or other government ID numbers.
1. Principle of least privilege
  - Don’t automatically grab the highest permission level, such as `root`
  - If needs, take it for a short period of time, then relinquish permission 
1. Secure defaults
  - User's settings to default to most secure, which they can decide for themselves the trade-offs between security and convenience. 
1. Encrypt sensitive data
  - Do not check in secrets, API keys, SSH keys, passwords, or other credentials
1. Maintain security updates
  - Apply security patches quickly

Principle of least privilege can lead to data hoarding, power games, and bureaucracy at work. Most of the team should have all privileges, instead of fighting the IT department for privileges for months.
But if following "open for everyone" principle, then you should also log everything!

### Passwords anti-patterns

Strict password policies will actually lower your security. 

- Do not restrict length
- Do not restrict chars
- Do not truncate passwords
- Do not provide password hints to unauthenticated users
- Do not disable the paste function in the browser. Crippling the functionality of the browser and password managers does not make your system more secure, in fact it drives users to create simpler, shorter passwords that are much easier to compromise. 
- Do not impose composition rules
- Do not arbitrarily require users to change their passwords after some length of time.

**What app allows you to set a password that is 256 chars long?**
or don't you love when a financial institution 

> You want to encourage long, random passwords with a high degree of entropy. Putting artificial constraints limits entropy and encourages bad password habits, leaving your user's accounts vulnerable to takeover.

### Crypto
Never do it yourself!

## 44: Naming things

Lord Voldermort!

Names are important because they reveal intent and belief.

> Things should be named according to the role they play in the code. This means that, whenever you create something, you need to pause and think “what is my motivation to create this?”

- Code golf!
- Constantine Haase's talk about [Sinatra in six lines of code](https://www.youtube.com/watch?v=8IFTAVvC2Xs). He also did a similar thing with Rack, because why not?
- Good commit messages: what was done as objective rather than what actually changed in the code.

> When naming things, you’re constantly looking for ways of clarifying what you mean, and that act of clarification will lead you to a better understanding of your code as you write it. 

- Booleans in database: don't use `is_active`. Please don't.

> project glossary, listing the terms that have special meaning to the team. This is an informal document, possibly maintained on a wiki, possibly just index cards on a wall somewhere.

- Renaming things is even harder, but sometimes a necessary refactoring
- Rubocop's default of `e` is not good
- Prefer writing blocks as multi-line helps use variables with better names
- thoughtbot style guide dislikes ternary for a similar reason: to make the conditionals obvious
