### ISSUE TITLE
The Pragmatic Programmer: Chapter 8, May 12

### ISSUE THREAD

**Issue by elle** [Blackmill/book-club#65]
Book: https://pragprog.com/book/tpp20/the-pragmatic-programmer-20th-anniversary-edition

Aiming to cover:

Chapter 8: Before the Project
Topic 45: The requirement pit
Topic 46: Solving impossible puzzles
Topic 47: Working together
Topic 48: The essence of agility

MC: @mcgain 
Notes: @lachlanhardy

See you 12 pm Tuesday, May 12th @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand.

**Comment by lachlanhardy** [comment]
# Chapter 8

## Topic 45: The Requirements Pit

We agree in principle with the core of this. We spent some time talking about how to actually gather useful initial requirements in a helpful way.

Antoine:
> The ability to get your user or client to actually work with you, that's the hard part.

**What happens when arbitrary govt dept sends you a detailed spec that is internally inconsistent and expects you to deliver a working thing by _x_ date?**

Talk to them about working through the document together. "This gives me some great high-level ideas of the direction, but it raises a few questions I'd love to work through with you."

## Topic 46: Solving Impossible Puzzles

### Fortune favours the prepared mind

## Topic 47: Working Together

Elle talked through how she used mob programming with the Qantas Hotels Engineering Academy to take the whole group together through how to solve problems.

>Like with pairing, define the rules beforehand. We used to do Exercism exercises together. 30-60 minutes. Typically one person would drive for the whole session, but people would take over to show a certain idea or such.

It's different when someone is paying for people's time by the hour. It's hard to justify that expense.

Antoine talked about using pairing as a great tool for exploring problems for the first time. 

Michael pairs every line of code at work. Every time he's tried mob programming it's been horrible. Sometimes pairing gets exhausting. When a card is boring for one of them, it can be a slog. "It's hard work working with people."

Tom asks: "If you could start your own dev team tomorrow, how often would you pair?"

Michael: "4-5 days a week."

Michael:
> Play in a band that's got people better than you. You'll feel shit, but you'll learn heaps!

Mob programming with non-programmers from your team can be very useful: designers, UX, product, or other stakeholders.

## Topic 48: The Essence of Agility

Sick burn.

We did have some discussion about whether people really are still doing waterfall. The answer is yes.
