### ISSUE TITLE
The Pragmatic Programmer: Chapter 9, May 19

### ISSUE THREAD

**Issue by lachlanhardy** [Blackmill/book-club#66]
Book: https://pragprog.com/book/tpp20/the-pragmatic-programmer-20th-anniversary-edition

Aiming to finish the book:

Chapter 9: Pragmatic Projects
- Topic 49: Pragmatic Teams
- Topic 50: Coconuts Don't Cut It
- Topic 51: Pragmatic Starter Kit
- Topic 52: Delight Your Users
- Topic 53: Pride and Prejudice

MC: @HashNotAdam 
Notes: @mcgain

See you 12 pm Tuesday, May 19th @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand.

**Comment by mcgain** [comment]
Notes for the final session of “The Pragmatic Programmer: 20th Anniversary Edition”

**Pragmatic Projects**
When you have projects that need more than one person, you need to start thinking about how the team works. 

10-12 people is an appropriate team size,  but they don’t seem to justify why. They reference the Mythical Man Month a lot, but don’t really tell us why it’s a good idea. Lachlan says it shows where the authors come from. They’re used to working on massive enterprise teams and trying to get the size down to 10-12. Lachlan suggests that we should break teams up at around 8 people. At Atlassian, stuff seemed to get done, even though the team sizes got up to 20 at one point before being split in two.

Michaell says in scouting, a group of 6 is what you want. He probably got this from the military. That said, the way it works at Fresho is the opposite of how many people think about it. He says split the software first (into separate components etc), then figure out how to split the teams based on that. This Is based on bad experiences at Red bubble where splitting teams led to problems. A team at Fresho has control over what they build and deploy. Lachlan likes the sound of this approach, but suggests a hybrid where you happen to look for places to split the software based on how big your team is growing.

Elle says that at cultureamp they have “camps” that consist of multiple managers with teams that have the same objective. 1:1s are too time consuming with 10 people under you, but you can spread the load.

**Adam wonders how people take time for personal development.**
Antoine does two week sprints with a “job” week in between, where you plan for the next sprint, have workshops, personal development, retrospectives, research, prototyping etc. This has been working well for a year now. It took them a little while to figure out the structure of how this works though.
Elle doesn’t like sprints, because it implies we’re always rushing and it doesn’t necessarily function because estimates don’t work. She says that 6 week sprints with 2 weeks of cleanup also isn’t a good idea. Instead, just pick the next most important thing to work on. One day a week “breakout” (Personal Development) time works for her, but juniors need guidance on this, don’t just abandon them for the day.
Adam thinks working from home and Covid changes things, perhaps it’s better to spread breakout time out, to when it works better for the family, work at home, lifestyle. 
Elle knows companies that schedule a day to fix bugs and schedule something for every day, so that people recognise how important these things are. 

**Team Brands**
Elle doesn’t understand why people brand their teams. Perhaps because people have no identity outside of their jobs. Lachlan once ran a propaganda campaign to educate end users on what their team did and how they could use the team’s work. In this case, it was to show journos that interactability was possible. 

Richard, who didn't say anything at the time, but because he is writing these notes, can be a revisionist historian, hates stupid team names. He likes to be able to find the team he is looking for easily. When there's more than a few teams it's just impossible to know who's doing what.

Michael says some people like being completely scheduled, others hate it. At Fresho they had to make some big changes due to covid and Michael liked the additional pressure, but others hated it. Sometimes a lack of pressure can lead to slowness, Elle say that the relaxed approach doesn’t always play well with management. Michael expands on the situation at Fresho where engineering management is relaxed, but other departments are yelled at by high pressure managers. Ultimately the nice engineering situation is allowed because it’s working. It’s all about trust say Elle and Lachlan. 
Adam worked somewhere with no timelines and pressure, but in a bad way. The lead developer would “take the piss” and took the flexibility too far. Eventually there was a pushback to the other extreme. This has resulted in Adam adopting an ethos of "deadlines are good", but  keep them flexible. Michael says it’s useful to see how much manual time is saved by automating a process. Sometimes it’s not actually worth the time spent. 

The consensus seems to be that deadlines are a good thing. Lachlan suggests picking arbitrary deadlines, but use them as the starting point to push back against. “Why can’t we meet that deadline?”. 

**Automate Everything and Deliver when users need it**
Adam thinks this isn’t always possible for smaller teams, and it’s not worth the effort. 
Does anyone actually do continuous delivery? 
Michael did at Red Bubble, it was great. At Fresho, they’ve got so many tests that continuous delivery works for them. Feature toggles feature. 
Richard did this at Shopify, they added more and more automation over the years until changes are deployed every few minutes and can be rolled back automatically. Michael points out that there’s a difference between continual deployment and actually releasing things. Feature flags can help stagger actual releases until you’re ready.

Michael says you can get rid of “squash merge” behaviour when working on trunk, and you can still have as many commits as you like, and reorder before you push. 

They seem to have changed their vibe around testing a bit this chapter, a few people opine. Michael says we were reading too much into last time when the authors said they didn't bother testing anymore. 

**Final thoughts?**
A good book, but aimed at novices.

Richard said that he had some hopes from this book
He hoped it would correct the mistakes of the last book since he made mistakes for years, misunderstanding some of the points the original book made. It did succeed somewhat in this ambition, but has also introduced new things for people to misunderstand.

He hoped it would help new novices. Unfortunately, we agreed that it would help only with handholding, since there’s no much nuance missing.

He hoped it would bring new mind blowing ideas. It didn't 

Antoine said this book was too basic. We already know about version control!

And that concludes our attempts at reading The Pragmatic Programmer: 20th Anniversary edition.

Next up is [Doing Good Better](https://www.effectivealtruism.org/doing-good-better/), make sure to get the one by MacAskill, not the other one!
