### ISSUE TITLE
New Book - Doing Good Better by William MacAskill Intro & Chapter 1

### ISSUE THREAD

**Issue by mcgain** [Blackmill/book-club#67]
It's time for a new book!

Doing Good Better: How Effective Altruism Can Help You Make a Difference by William MacAskill 

![1426469800595](https://user-images.githubusercontent.com/193744/82284353-2a509380-99dc-11ea-8257-d5a26db545f1.jpg)

Aiming to read:
* Introduction
* Chapter 1
* Chapter 2

MC @antoinemacia 
notes @HashNotAdam 

See you 12 pm Tuesday, May 26th @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand.

**Comment by HashNotAdam** [comment]
[@tomdalling](https://github.com/tomdalling): The randomised controlled trials were a very interesting way to validate. A lot of people usually try to solve a big world problem by doing things that are easy and make them feel good without considering if their actions will actually help.

[@lachlanhardy](https://github.com/lachlanhardy): This brings back memories of how *Thinking Fast and Slow* discussed applying science to economics. Bummed by the PlayPumps example because, rather than being an example of a good project that neglected to validate its assumptions, it was just an all 'round piece of shit.
[@HashNotAdam](https://github.com/HashNotAdam): The icing was that they admitted they had failed and yet continue to push the product knowing it isn't suitable.

[@antoinemacia](https://github.com/antoinemacia): It's mind-blowing that so much money can be spent without any regard for the return on investment. It's hard to believe it could occur outside of philanthropic work. Basically it's just (white) saviour bias.

[@tomdalling](https://github.com/tomdalling): Reminds of waterfall: you come up with an idea that sounds good, invest a lot of money, and then realise the idea is completely wrong.

[@antoinemacia](https://github.com/antoinemacia): Based on the charts in the book, to be counted in the 1% of world income earners you need to make about $35k p/a which is slightly below minimum wage.

[@lachlanhardy](https://github.com/lachlanhardy): Had not thought he was in the 1% in the world—possibly 5%—and it's interesting to think that probably 99% of Australia is within the 1%. He has been looking at a site that represents $1k of wealth as 1 pixel and then sideways scrolls to show rectangles that represent the wealth of various people. The site expresses how little it would cost as a percentage of total wealth it would take to solve big life issues.
[@HashNotAdam](https://github.com/HashNotAdam): Unfortunately, their wealth is not in the bank to be taxed, it's mostly a representation of the value of their ownership of businesses and legislating that people need to sell control in their companies isn't feasible. He believes focusing on taxing the wealthy is a distraction from the true issue that the US is under a misguided belief that having an unlivable minimum wage and poor working conditions is acceptable. Combined with states competing to offer the best tax breaks, wealth is redirected from workers and the public to shareholders.

> [Wealth, shown to scale](https://mkorostoff.github.io/1-pixel-wealth/)

[@HashNotAdam](https://github.com/HashNotAdam): Found the 1% discussion surprising—his understanding is that the median wage in China is now (comparatively) high and, given the population size, expected that to add a little more balance to the chart.
[@elle](https://github.com/elle): Is far less interested in the idea of how much money people are earning but more what their quality of life is. Developers have the ability to work remotely, earn Silicon Valley wages, and live in Thailand where their money goes further. She would like to see an earnings to cost-of-living ratio.
[@HashNotAdam](https://github.com/HashNotAdam): Had also never considered that there could be, for instance, lower-grade rice that could be available in poorer nations but we don't see it in Australia because the market doesn't exist.
[@tomdalling](https://github.com/tomdalling): Is expecting that the book might later introduce a happiness metric similar to how Bhutan uses Gross National Happiness as a governmental guiding philosophy. This contrasts most capitalist nations which use Gross Domestic Product or similar metric.

[@antoinemacia](https://github.com/antoinemacia): Has always thought "when I'm financially secure I'll be ready to give my time and my money" but this book shows that, living in Australia, we are always in a position to have an impact on many people in the world.
[@tomdalling](https://github.com/tomdalling): This was really well described in the book by saying "you could either buy yourself a beer for $5 or buy someone else a beer for 5¢".
[@antoinemacia](https://github.com/antoinemacia): "Because we are comparatively so rich, the amount by which we can benefit others is vastly greater than the amount by which we can benefit ourselves." [Insert dream state at the thought of buying 1,000 beers]
[@lachlanhardy](https://github.com/lachlanhardy): What makes the analogy so good is that \$5 still doesn't seem much to us. You are not depriving yourself of the beer, you are getting yourself a beer for \$5 and someone else a beer for 5¢.

Nick Spragg: Is concerned that the attempts to give a bigger world perspective undermines the value of the term "the 1%". The original idea was used to highlight that there are people who are "unacceptably wealthy" and this re-framing might lead people to think that, since we're all in the 1%, no one is "unacceptably wealthy".
[@tomdalling](https://github.com/tomdalling): A different perspective is "I am the Jeff Bezos to rural Indians".

[@elle](https://github.com/elle): The book referenced a story about triaging the Tutsi of Rwanda by assigning them a number from 1 to 3. The Freakonomics podcast episode [Who Gets the Ventilator?](https://castro.fm/episode/nBtnHN) has similar themes but within the context of COVID-19. They were using QALY but when you are choosing between, say young and old, this raises questions of values and how each state decides the QALY metric to be placed into the equation.
[@antoinemacia](https://github.com/antoinemacia): These questions are heavy and God-like.

[@elle](https://github.com/elle): Does not agree with the approach that you should choose the charities/organisations to invest in based upon a metric of benefit. It implies that everyone should invest in whichever is deemed to provide the most benefit and all other charities should get nothing. A more appropriate way to look at it would be to choose an area you are interested in supporting and then finding the most efficient charity within that scope.
[@lachlanhardy](https://github.com/lachlanhardy): There is some scope for this when the book says that you need to consider what would happen if you didn't invest. If a charity is already popular and many others would donate if you don't, maybe your contribution it more valuable elsewhere.
[@HashNotAdam](https://github.com/HashNotAdam): The challenge is knowing the value of your donation and understanding when a charity has enough funding. Even if the information is available, it will be retrospective.
[@lachlanhardy](https://github.com/lachlanhardy): Openly admits to being self-absorbed and considering to value of altruism to be personal gratification.
[@antoinemacia](https://github.com/antoinemacia): Even if you do get insights into a charity, there is always going to be a level of trust required. You might know that books will be distributed but you can't know exactly which books or what value any particular book will bring.

[@elle](https://github.com/elle): Was discussing the shop with no prices analogy with [@lachlanhardy](https://github.com/lachlanhardy) and he had said normally this would be ridiculous but they are doing exactly this when they order a box of produce from local stores and they are unsure what will be in the box.
[@lachlanhardy](https://github.com/lachlanhardy): Side note—quince will make you ill if it isn't basically rotten
[@HashNotAdam](https://github.com/HashNotAdam): When contributing to a cause you need to decide whether your goal is saving the world or feeling better about yourself. If you are satisfied feeling good about yourself then it doesn't matter what's in the box.
[@lachlanhardy](https://github.com/lachlanhardy): At least with the fruit box we get the opportunity to see the box after purchase and can assign a value of worth to it.
[@elle](https://github.com/elle): And we were able to try boxes from different vendors and decide which we preferred.

[@lachlanhardy](https://github.com/lachlanhardy): Has always been a "charities at home" person given how many issues there are in our backyard but this book makes a strong case for supporting people elsewhere.
