### ISSUE TITLE
Doing Good Better — Chapters 3, 4, and 5 — June 2nd

### ISSUE THREAD

**Issue by tomdalling** [Blackmill/book-club#68]
Doing Good Better: How Effective Altruism Can Help You Make a Difference by William MacAskill

Aiming to read:

 - ~~Chapter 2~~
 - Chapter 3
 - Chapter 4
 - Chapter 5

MC @tomdalling 
Notes: @antoinemacia

See you 12 pm Tuesday, June 2nd @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand.

**Comment by antoinemacia** [comment]
## **Chapter 3**

This chapter points out how aid is can be malignant, and give some comparative statistics around death rate between smallpox, malaria or an imaginary world peace

Tom noted reading this  information about smallpox in the context of COVID made more sense or was more relatable. Overall, there is a consensus between the statistics & charts presented were very eye opening and impressive

There's a reserve on the numbers presented as what definite a QALY as well as the factors impacting it are very hard to understand

Nick raises a setback with QALY, around its attempts to put a number onto a concept that is heavily affected by which cultural lens it's been looking from

We discussed things such as colonialism as well as help from other countries, both ingrained from a saviour complex (we know what's better for you, and we left things better than they were)

We also discuss the difficult challenge between comparing life expectancy and the price of life itself with life quality and concept such as hapinness

Richard raises a thought on the effect of help & cure disease on population growth, which is potentially uncontrolled and could create more harm

## **Chapter 4**

This chapter talks brings economic concepts such as marginal utility & regression to the mean to explain the inefficiency over time to give time & money to the same cause.

We all agree there's a point where contribution's plateau, or need much much more effort/money to have a significant impact *again*

This leads to a discussion around how current events (COVID, bushfires) have been handled in terms of funding. 

We discuss the psychology of trying to optimise our help to others, putting aside our personal preferences and sentiments for the sake of the better result. There's a consensus our feelings towards a given cause is part of the equation and should not be forgotten (e.g could lead to not giving anymore because emotionally unattached)

## Chapter 5

This chapter starts with the story of prisons visit by juvenile offenders, as a mean of education and how in the example provided, the cause is televised and ends up being harmful to the offenders

We briefly talk about the ineficiency and harm of the current penitentiary system

It also talks about how much we can make of a difference during our work life at any age, and goes over the fact one's impact would be much greater if that person is in some sort of financial comfort

## **Conclusions**

Everybody enjoys the book and is getting something from it
