### ISSUE TITLE
Doing good better - chapters 6-7 - June 9

### ISSUE THREAD

**Issue by elle** [Blackmill/book-club#69]
Doing Good Better: How Effective Altruism Can Help You Make a Difference by William MacAskill

Aiming to read:
- Chapter 6: why voting is like donating thousands of dollars to charity
- Chapter 7: overhead costs, CEO pay, and other confusions

MC @elle 
Notes: @tomdalling

See you 12 pm Tuesday, June 9th @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand.

**Comment by tomdalling** [comment]
Chaper 6: Why voting is like donating thousands of dollars to charity.
----------------------------------------------------------------------
 - Key question 5: What are the chances of success, and how good would success
   be?
 - Expected value = probability * value
 - Fukushima power plant meltdown is an example of a low probability but high
   cost event (a black swan)
   - Elle: An example is voting. Small probability of having an effect, but not
     voting means nothing changes.
   - Tom: It's like the chicken example. Buying less chicken seems like it does
     nothing to prevent chickens being raised for meat, but research shows
     buying 1kg less of chicken causes about 0.6kg less chicken to be produced.
   - Richard: This is reminiscent of Pascal's wager. If the reward is
     infinitely great, then even the tiniest probability gives an infinite
     expected value, which doesn't make sense. It's a similar to climate
     change, but I do believe in that.
   - Antoine: This is like buying lottery tickets. Re climate change: We were
     talkign about climate issues in the 80s, caused by corporations acting
     badly, but there has been a shift to individual responsibility recently .
     Should we focus on putting our efforts into changing companies behaviour?
   - Elle: Re black swans like war, how can it be predicted and prevented? It
   - Richard: We can predict the scale of harm when it comes to wars, e.g. by
     looking at the countries involved.
   - Antoine: Has anyone read Antifragile by Naseem Taleb? It says black swans
     are unpredictable by nature, so instead of preventing them, we should
     become robust to negative outcomes instead. Look at chaos monkey, for
     example.
   - Richard: Antifragile is a good book, maybe we should add it to the list.
   - Richard: Government tender required me to write about risks. All software
     is about risk management, but it was difficult to balance black swan
     events with everyday risks. Also it's a tender, so I don't want to present
     such a grim outlook.
   - Lachlan: Maybe less scrupulous competitors won't list risks properly.
 - Micromorts: A one-in-a-million chance of dying (roughly 30 minutes of life
   lost)
   - Elle: People don't tend to think in micromorts, so it doesn't really
     affect their day-to-day behaviour.
   - Richard: Assessing the dangers of peanut butter sounds funny, but it
     killed people due to selmonela not too long ago.
   - Lachlan: Assessing the harm caused police brutality vs harm caused by
     spreading COVID at protests, the calculations look like it's better to
     protest than to not.
 - Richard: This chapter was boring and hard to read. The numbers were all made
   up.
 - Adam: The numbers are fudged, but they're looking for massive differences,
   so being slightly wrong shouldn't matter as much.
 - Tom: Small changes to numbers cause large effects on the final decision
 - Antoine: One thing that throws me off about the book: if it's not efficient
   don't do it. It's too black and white.
 - Why voting is like donating
   - Elle: Looking at expected value of getting into government with a PPE
     degree from Oxford, how does this apply to voting? How does this apply to
     charity?
   - Richard: Boris Johnson and friends believe that history is defined by "big
     men" who make "big decisions". I want to disagree with these people, so I
     want to reject this elitist oxford approach to getting into government.
   - Elle: I don't think you need to be in government to influence government,
     you can be a large company.
   - Tom: Anything that encourages disenfranchised people to vote is good.

Chapter 7: Overhead costs, CEO pay, and other confusions
--------------------------------------------------------

 - Comparing three charities: Books for Africa, Development Media
   International, and Give Directly.
 - Looking at the "gold standard" of less than 25% spent on administration
   costs, it's not a very good metric. Evidence of effect is better.
 - Evaluation framework:
   1. What does this charity do?
   1. How cost-effective is each programme area?
   1. How robust is the evidence behind each programme?
   1. How well is each programme implemented?
   1. Does the charity need additional funds?
 - Antoine: Did anyone make predictions about the best one?
 - Tom: I was curious if Give Directly was the best. Using direct cash
   donations as a gold standard is a good idea. Charities need to show they do
   better then just giving cash to people.
 - Elle: Evidence suggests micro loaning services are damaging, which makes me
   sad, because I was considering donating.
 - Adam: The napkin numbers are a bit fishy here, saying a single donation will
   double income for 10 years.
 - Lachlan: What did I expect to be the best? I thought Giving Directly. It
   seems looks to have less obstacles. But distributing money is complicated,
   and might change the outcome depending on how it's done.
 - Elle: For example, research shows that giving cash to women results in
   better outcomes on average. Like everything, you need monitoring. That means
   you need the charity to be transparent.
 - Richard: Give Directly has less cultural imperialism, as opposed to missionary work for example.
 - Tom: Development Media International is a good counterpoint to Give
   Directly. No amount of direct cash will make people learn about the
   connection between hand washing and diarrhoeal disease. It would need to be
   "forced" upon people, for lack of a better term.
 - Elle: COVID has made the aid dry up, leaving people in a bad place.
 - Lachlan: COVID is disproportionately affecting women in Australia. Inability to access childcare
   is causing progress towards equality to be lost.
 - Tom: Sweden's social safety net shows that welfare doesn't cause everyone to
   be lazy.
