### ISSUE TITLE
FEB 26: Chapter 7

### ISSUE THREAD

**Issue by lachlanhardy** [Blackmill/book-club#7]
Next book club chat, read chapters:

    * 7: Managing managers

Please post any comments/issues/questions for discussion here.

Leading the discussion will be @HashNotAdam. Taking notes: @nickspragg

**Comment by HashNotAdam** [comment]
## Chapter 7. Managing Managers

The job expectations for managing managers similar to managing multiple teams but you will now be responsible for far more people who may even be spread across disciplines for which you are not experienced.

### Adjusting to the role

Due to the added level of abstraction between you and the engineers, it is more difficult to work out what needs your attention and where best to spend your time, particularly if a team is working outside of your skill set. 

Initially you'll want to follow up on all the little things until you figure out what you don’t need to follow up on. This will inevitably be a lot of work until you can adjust your focus.

### The fallacy of the open-door policy

It's common to hear a manager say they have an "open-door policy" but then find that people are not lining up to tell them about their concerns. It is the managers job to proactively ferret out problems.

### Skip-level meetings

These are meetings with the people who report to the people who report to you and they provide perspective on the health and focus of your teams.

In smaller organisations, 1-1 meetings provide focused feedback but they are unrealistic with scale. A team lunch might be more appropriate at a large organisation. This approach can also make people more comfortable to see you 1-1 when there are sensitive topics to be addressed.

The skip-level process also allows you to see when you are being "managed up" and keep grounded.

### Manager accountability

Mangers should be making your life easier but they may do this by hiding problems from you—they need to be held accountable.

Even when it seems like there are mitigating circumstances, it is always the managers responsibility to keep the team moving forward although they may need your support or guidance.

People pleasers try to ensure everyone is happy and have an inability to say "no". While they think they are helping moral and creating an environment where people feel comfortable to fail, the opposite is true.

### Managing new managers

As with any new role, people new to management are going to find there are a lot of things they don't know or understand. It is in your best interests to spend more with a new manager, ensure they know what they should be doing, and that they are doing it.

Use more frequent skip-level meetings to monitor their performance and use the feedback to guide their development.

Look for signs of over-work as an indicator that maybe the manager hasn't mastered delegation or is being overly controlling.

### Managing experienced managers

An experienced manger is likely to have the skills but, if they were hired in from outside the business, it's possible their management style doesn't match the culture of the organisation. It’s easier to gain access to industry information than it is to retrain someone who doesn’t know how to work in your culture.

While you can learn from experienced managers and collaborate on areas of difference, you are responsible for cultivating the culture of your organisation.

### Hiring managers

Hiring from outside an organisation can be tough—how do you interview for management skills?

Make sure they have the skills you need and that they're a culture match for your organisation.

#### The interview

To evaluate skills:

- Roleplay:
  - 1-1s
  - dealing with an underperforming employee
  - delivering negative a performance review
  - an employee who's thinking about quitting
- Ask about:
  - a project that was running behind schedule and what they did
  - how they've coached employees who are struggling
  - management philosophy
- Present to a room (but don't overvalue this)
- Technical skills
  - abbreviated code test or Q&A
  - mediate a technical debate

When evaluating cultural fit:

- review Chapter 9
- do you need someone who dictates or collaborates

Do thorough reference checks and ask them:

- to describe the ways that the person succeeds as well as the ways they fail
- would they work with or for this person again
- what they love about the person, and what drives them crazy

When hiring outside your skill set:

- be cautious
- ask the person to teach you about the work they do
- ask lots of open questions

### Debugging dysfunctional organisations

Debugging issues with a team can be difficult and they may resist the inquiry.

- Have a hypothesis
- Check the data
- Observe the team
- Ask questions
- Check the team dynamics
- Jump in to help
- Be curious

### Setting expectations and delivering on schedule

Be aggressive about sharing estimates and updates to estimates, even when people don’t ask.

Engineers often don’t want to estimate but even inaccurate estimates can help  escalate complexity to the rest of the team.

It's possible to do up-front work to reduce the unknowns and ultimately produce a more accurate estimate. Learn from past estimates both to help increase accuracy but also to understand how to better manage communication and expectation.

When you are being unnecessarily pushed, it is usually because someone is stressed or being pushed themselves. Show empathy for the person providing pressure and being willing to help out in other ways.

Don't be afraid to work with stakeholders to cut scope.

### Challenging situations: roadmap uncertainty

Changes in strategy are where being stuck in “middle management” feels the most unpleasant.

#### Strategies for Handling Roadmap Uncertainty

- Be realistic about the likelihood of changing plans given the size and stage of the company you work for
- Think about how to break down big projects into a series of smaller deliverables
- Don’t overpromise a future of technical projects
- Dedicate 20% of your team’s schedule to “sustaining engineering”
- Understand how important various engineering projects really are

### Staying Technically Relevant

How do I remain technically relevant?

#### Your technical responsibility

- Oversee technical investment
- Ask informed questions
- Analyze and explain engineering and business tradeoffs
- Make specific requests: filter out technically infeasible ideas and map new initiatives onto ongoing projects
- Use your experience as a gut check

#### How to stay technically relevant

- Read the code (occasionally)
- Ask an engineer to explain an unknown area
- Attend postmortems
- Keep up with industry trends
- Foster a network of technical people outside of your company
- Never stop learning

**Comment by lachlanhardy** [comment]
@HashNotAdam @nickspragg Here's the article I found that gives those quotes from the Work Rules book: https://www.wired.com/2015/04/hire-like-google/

**Comment by nickspragg** [comment]
**Chapter 7: Managing Managers - Notes**

Everyone agreed that this chapter felt very similar to Chapter 6: Managing Multiple Teams.
    - Managing managers means you are directly managing about the same number of people as if you were managing multiple teams.
    - When compared to managing multiple teams, that it is a similar hierarchy for managing Tech Leads as it is to managing managers.

--

**Skip level meetings**
Discussion on this topic revolved around the fact that Australian companies don't seem to use this process and we are not sure why. Lachlan spoke about having seen it to at Github.

Discussing the process, Lachlan analogised it as being an elaborate process to check that the managers you managed are actually doing their job and are not just extremely good at managing you.

**Open door policy**
Adam introduced the open door policy to the discussion and summarised this chapter as being being a lot about the process.

Everyone agreed that none of us had ever seen an open door policy work. Adam added that with open plan offices it was even more ridiculous because it simple became a metaphor.

From open door policy we got onto accountability and discussing the section of the chapter which discusses how you are responsible for the performance of managers which you manage. We discussed how you are the manager need to support those managers below you.

--

Adam discussed how in small business common that roles cover a lot of aspects and that it is not feasible in many cases. That people often span aspects of multiple roles.

Elle added that it is easier in big business for people to have the space to specialise which aligns closer to the things being covered in this chapter.

--

Elle discussed that at Dropbox the CEO would have meetings with each office to check in. This circled back to the earlier discussion on Skip level meetings.

Elle also discussed the way policies and procedures were democratised by having them all in github so that if anyone wanted to change a policy it could be done by creating a PR to be reviewed and if agreement was reached, it would be merged.

--

**Discussion moved on to people pleasers**

Lachlan felt dissatisfied with this section of the chapter. He felt that not coming back to the good approach that maria was taking, that the example didn't really feel complete. That the example focused to much on marcus.

Adam described the chapter as very black and white.

Elle had a different perspective of the chapter. She described maria as wanting to get things done without being a therapist. Elle also added that having policies and procedures in place makes this easier and that it comes back to a previous chapter where the topic covers 'how to say no'.

Nick felt like a good manager needs to have attributes from both areas. Keeping people happy, while not sacrificing the productivity and team goals for the sack of happiness.

Elle discussed that there is a difference between new and experienced managers. That new managers need more hand holding, while experienced managers bring their own culture with them. That each end of the spectrum has it's own challenges.

Lachlan agreed and said that you need to pay close attention to both.

--

**Hiring managers**

Adam opened the discussion on this area with a statement about typically hiring managers based on feel, and discussed some questions which he hates to hear in interviews. Questions about previous projects and what people did. He discussed that he didn't think they gave any value in an interview for a manager.

Lachlan discussed that that we were talking about culture, and summarised that as a new manager you will be unproductive until you have learned how the company works. That this could take several weeks.

Lachlan then added to the discussion that years of experience is only a 3% indicator of future performance.

Adam added that as interviewers, we tend to use these questions to filter out poor candidates.

Elle discussed how when she hires for developers that she will get the candidate into the office to pair with someone for a day. That having someone work for a day with the rest of the team allows for a better perspective. She described how sometimes people who interview well can be disruptive when in a work situation; That sometimes people behave differently when on lunch with other peers; and that having them in the office was an effective way of finding out how they work.

Adam talked about a book by [Laszlo Bock - Work Rules!](https://www.wired.com/2015/04/hire-like-google/) , and that he had found it an interesting read to hear about hiring practices at google.

Lachlan discussed some additional information from the research which he had referenced for the 3% predictive performance based on years worked. That the research had found a 14% correlation between unstructured interviews and predicting future performance. That IQ test had a 26% predictive indicator, but that IQ tests were discriminatory, and that structured interviews had a 23% predictive percent.

After discussing this, Lachlan discussed that the most important thing to do is to define the role. That once you define the role (requirements) you look for someone who meets those requirements and then hire them.

Elle added that defining what you are looking for is key, and added that when interviewing, it is important to standardise the process so that you can compare candidates accurately.

**Comment by nickspragg** [comment]
Hi @lachlanhardy @HashNotAdam @elle I have written up the knows / minutes from this week. Let me know if there is anything I missed or if I miss understood. 
@lachlanhardy Thanks for providing that link, I attached it to the relevant section in the notes. Funny, because I hadn't realised you were quoting from the same book that Adam had mentioned.

**Comment by lachlanhardy** [comment]
@nickspragg I hadn't realised that either!

You're welcome to add these notes directly into the markdown file in the repo. No PRs here :)

**Comment by HashNotAdam** [comment]
@nickspragg would love to take credit but that discussion was 100% @lachlanhardy.

**Comment by elle** [comment]
Added notes to master
