### ISSUE TITLE
Doing good better - chapters 8-7 - June 16

### ISSUE THREAD

**Issue by lachlanhardy** [Blackmill/book-club#70]
Doing Good Better: How Effective Altruism Can Help You Make a Difference by William MacAskill

Aiming to read:

    Chapter 8: The moral case for sweatshop goods 
    Chapter 9: Don't "follow your passion"

MC @lachlanhardy 
Notes: @elle 

See you 12 pm Tuesday, June 16th @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand.

**Comment by lachlanhardy** [comment]
My MC notes:

## Chapter 8

American Apparel, really? By the time this book was published, their culture of sexual harassment, starting from their CEO, was public knowledge and he'd been booted from the board. They filed for bankruptcy same year this was published (2015)

### Fair-trade disappointments

1. Again with the global mathematical benefit. Yes, buying from Costa Rica is not as 'good' as buying from Ethiopia, but it's still delivering economic benefits to a country poorer than Australia.

### Environmental offsets

Type of food more important than where it was produced.

One hot bath costs more energy than a year of a phone charger plugged in.

I want details! This book is good at telling you what's wrong, not so good at suggesting what to do about it.

Literal pitch for Cool Earth. Is that a good thing?

### Vegetarianism

The implied recommendation is that (if you're not willing to stop eating meat), you can stop eating all meat except beef (doesn't even address lamb) and offset the environmental impact.

>According to Animal Charity Evaluators (a research charity I helped to set up), by donating to charities like Mercy For Animals or the Humane League, which distribute leaflets on vegetarianism, it costs about one hundred dollars to convince one person to stop eating meat for one year. If you can donate more than that to animal advocacy charities per year, then your decision about how much to donate to animal advocacy is even more important, in terms of impact, than the decision about whether to become vegetarian yourself.

### Moral licensing

https://en.wikipedia.org/wiki/Self-licensing

>In a large experience sampling study, Hofmann and colleagues found evidence for moral licensing in people's everyday behavior outside of the lab, noting that "committing a moral act earlier in the day was associated with an above-average likelihood of a subsequent immoral act and a decreased likelihood of a subsequent moral act."

>Participants in the study were divided into two groups, both of which were given placebo pills; one group was correctly informed that the pills contained no active ingredients and the other group was told that the pills were multivitamin supplements. Survey results showed that participants who thought that they had received a multivitamin were predisposed to smoking more cigarettes and more likely to believe that they were invulnerable to harm, injury, and disease as compared with subjects who knew that they were given a placebo. Participants who believed they were given a multivitamin were also less likely to exercise and to choose healthier food, and had a higher desire to engage in "hedonic activities that involve instant gratification but pose long-term health hazards", such as casual sex, sunbathing, wild parties, and excessive drinking. In the 'multivitamin' group, the more supplements a participant used, the less likely they were to exercise, and smoking was highest among participants who expressed a conscious belief that multivitamins increased health. 


## Summary 

As I've said previously, this book is all about individual action and utterly fails to address systemic change.

## Chapter Nine

### Job characteristics theory

1. **Independence** — To what extent do you have control over how you go about your work?
2. **Sense of completion** — To what extent does the job involve completing a whole piece of work so that your contribution to the end product is easily visible, rather than being merely a small part of a much larger product?
3. **Variety** — To what extent does the job require you to perform a range of different activities, using different skills and talents? 
4. **Feedback from the job** — How easy is it to know whether you’re performing well or badly? 
5. **Contribution** — To what extent does your work “make a difference,” as defined by positive contributions to the well-being of other people? 


- What’s my impact while I’m working at this job? 
- How does this job contribute to my impact later on in life?

We have "career capital". How are we spending it?

**Comment by elle** [comment]
# June 16 Notes

## Chapter 8

Chapter is about **conscious consumerism**:

- American Apparel is not a good example to start off with because of all the sexual harassment lawsuits. Also, even if they pay 30 times more that what people in sweatshops do, it is still really low in US terms.

- No sweatshop movement is performative and possible damaging.

- Cool earth does still exists and the book preaches over multiple pages how good they are. There is evidence that they buy forest plots rather than helping communities to save plots around them.
If people read the book, and go to support them, and they have an influx of new donations, what are the chances that they mismanage the funds?

- This book advocates not changing your life, just pay someone to do this for you.

**Vegetarianism:**
If you are willing to kill animals, pick to eat the bigger ones, in order to reduce hours of suffering for other animals.
A bit off topic from the rest of the book. And he didn't go into a lot of details possibly because the rest of the book is about world poverty.

Animal welfare: chickens have it bad compared to cattle, which also provide more  meat per animal. He mentions impact on the environment quickly and moves on to animal cruelty. In Australia, cattle get fed on grass by default as opposed to the US, but that is changing now.

The book advocates that you get most bang for your buck if you donate for overseas charities in poor countries. But the book is actually making some of us think about how to help our local communities.

Lachlan doesn't believe it is his responsibility to fix the world.
But isn't it what we ask of the super rich?


The book has a very capitalist of thinking: the cost of saving lives is better when you donate elsewhere to poor countries.

The book does not introduce a moral drive: why?
Maybe because the premiss of the book is that you want to help and make the world a better place.

If we all do the right thing, money will not spread well across all the places that need it.

The book doesn't teach a methodology or provide a framework on how to find and evaluate charities. He just says: I have done the research so you can just enjoy the results. The book glosses over the research and uses example figures to make a point. But these are made-up numbers. If you're trying to rationalise doing good with economic action, then at least use actual real numbers.

Worth thinking about this in probabilities: the probability of my money doing good...

Good and bad behaviours do not cancel each other out so easily, so moral offsetting is not possible.

This book is about individual action and nothing about systemic change.
Capitalism has its flaws but they should be addressed at state level, not just individual action.

For example: giving the advice that a woman should hold her car keys in her hands when walking to the car in an empty car park at night. But that only makes the woman *feel* safe.
The system should make the area safe, instead of asking the individual to do a meaningless act that will make them feel safer but not actually make them safer.

Actual numbers are useful as well as constant evaluation of what is the state of affairs.

## Chapters 9

- Job characteristics theory
- What is my impact in the current job?
- How does this job contribute to my impact later in life?
- Career capital
- 5 factors for job satisfaction

How much the charity is willing to pay for your time? If they are only willing to pay you $100 a week, then it is better to donate that money rather than your time.

Choosing a career based on talking to people in the industry and work in their companies is not good enough, because you never really know how a company is until you start working there.

This book is making some us consider giving money to charities (elsewhere, national or international) but investing our actual time in our local communities, and building roots and relationships here.
