### ISSUE TITLE
New book: Nudge: Introduction and chapter 1: June 30

### ISSUE THREAD

**Issue by elle** [Blackmill/book-club#72]
Nudge: Improving Decisions About Health, Wealth, and Happiness
by Richard H. Thaler, Cass R. Sunstein

https://www.amazon.com/Nudge-Improving-Decisions-Health-Happiness-ebook/dp/B00A5DCALY/

Aiming to read:
- Introduction
- Chapter 1: biases and blunders
MC: @HashNotAdam 
Notes @mcgain 

See you 12 pm Tuesday, June 30th @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand

**Comment by HashNotAdam** [comment]
# Introduction

## The cafeteria

- It is possible to influence what students do or don't buy by 25% simply by changing their position on the cafeteria menu, how should you wield that power? Drive healthy choices? Build profits?
- A *choice architect* architect has the responsibility for organizing the context in which people make decisions
- There is no such thing as a ‘neutral’ design; small and apparently insignificant details can have major impacts on people’s behaviour
- Men are inherently nasty and need to be guided to not piss on the floor

## Libertarian paternalism

- *Libertarian paternalists* attempt to architect better choices for others while never diminishing their ability to pick an alternative path
- Social science findings suggest people would often make better choices if they possessed complete information, unlimited cognitive ability, and complete self-control
- A nudge is any aspect of the choice architecture that alters people’s behaviour in a predictable way without forbidding any options or significantly changing their economic incentives

## Humans and Econs: why nudges can help

- Many people believe that humans think and choose unfailingly but this idea is easily debunked
- Unfailing people are hereon referred to as "Econs" while regular, fallible people are "Humans"
- Examples of human fallibility include rising obesity rates and the planning fallacy
- Thanks to the "status quo bias", people have a tendency to go along with the default option

## A false assumption and two misconceptions

- Those who oppose paternalism tend to believe that people make better choices for themselves than others could make for them
- People make good choices in contexts in which they have experience, good information, and prompt feedback
- A misconception is that it is possible to avoid influencing people’s choices
- Nudges are favoured over commands because governmental risk of mistake, bias, and overreach are read and sometimes serious
- Government making choices is unavoidable so they should be helped to make the best choices
- The second misconception is that paternalism always involves coercion. In the cafeteria example, the order of food on a menu does not enforce a diet
- Freedom to choose is the best safeguard against bad choice architecture

## Choice architecture in action

- Choice architects can make major improvements to the lives of others by designing user-friendly environments (e.g. Apple)
- When choices renew annually and someone does not make a choice, how is the decision made? It seems likely that they would have wanted to choose to keep health care over losing it. What about making contributions to retirement?
- It is important to consider what people would likely have wanted or what is best for their wellbeing

## A new path

- Policies suggested by libertarian paternalism should be non-partisan
- Better government, not bigger government

# Part 1 — Humans and Econs

## Biases and Blunders

### How we think: two systems

- Normally the human mind works remarkably well but it can be deceived
- There are two types of thinking, automatic and reflective (see Thinking Fast and Slow)
- The Automatic System is rapid and feels instinctive
- The Reflective System is more deliberate and self-conscious
- Voters tend to rely on their automatic systems which is why politicians avoid complex or statistical arguments
- Gut feelings can be quite accurate, but we often make mistakes because we rely too much on our Automatic System
- Econs never make an important decision without checking with their Reflective Systems

### Rules of thumb

- We can’t spend all our time thinking and analyzing everything so we use rules of thumb
- Although rules of thumb can be very helpful, their use can also lead to systematic biases

#### Anchoring

- When you don't know the answer, you might start with a related number you do know and adjust from there
- Asking "How happy are you?" then "How often are you dating?" provides low correlation (.11) but much higher correlation (.62) when asked in reverse

#### Availability

- Most people access the likelihood of risk by asking how readily examples come to mind
- Terrorism is considered higher risk than sunbathing; homicides more than suicides
- A good way to increase people’s fear of a bad outcome is to remind them of a related incident in which things went wrong; a good way to increase people’s confidence is to remind them of a similar situation in which everything worked out for the best

#### Representativeness

- Judging the likelihood that something belongs to a group by comparing it to a stereotype
- When people see outcomes of random processes, they often detect patterns that they think have great meaning but in fact are just due to chance
- People regularly report "cancer clusters" but probability suggests that clusters would naturally occur

### Optimism and overconfidence

- People greatly overestimate their skill level

### Gains and losses

- Losing something makes you twice as miserable as gaining the same thing makes you happy
- Loss aversion helps produce inertia, meaning a strong desire to stick with your current holdings

### Status quo bias

- One of the causes of status quo bias is a lack of attention (the ‘yeah, whatever’ heuristic)
- Default options act as powerful nudges
- In many contexts defaults have some extra nudging power because consumers may feel that default options come with an implicit endorsement from the default setter

### Framing

- Creating focus on either the positive or negative moves people towards that choice (90% live vs 10% die from having an operation)
- Credit card companies made it so the card price was "standard" and the cash price was a "discount" rather than the card price including a surcharge
- Framing works because people tend to be somewhat mindless, passive decision-makers
