### ISSUE TITLE
Nudge: chapters 7-8-9: July 21

### ISSUE THREAD

**Issue by elle** [Blackmill/book-club#75]
Nudge: Improving Decisions About Health, Wealth, and Happiness
by Richard H. Thaler, Cass R. Sunstein

https://www.amazon.com/Nudge-Improving-Decisions-Health-Happiness-ebook/dp/B00A5DCALY/

Aiming to read:

Chapter 7: NAÏVE INVESTING
Chapter 8: CREDIT MARKETS
Chapter 9: PRIVATIZING SOCIAL SECURITY: SMORGASBORD STYLE

MC: @elle
Notes: @tomdalling

See you 12 pm Tuesday, July 21st @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand

**Comment by elle** [comment]
### 7: Naïve Investing

- How to invest the money? How much risk to take?
- Asset allocation decision: stocks and equities vs government bonds?
- In retirement accounts, most investors do not choose stocks individually but rather invest via mutual funds.
- Investing in company's own shares - can blow back up in your face (Enron)
- Review periodically because stocks tend to shoot up and the 50/50 ratio of stocks and bonds will be off
- 3.7% yearly return barely keeps up with inflation rate
- Index mutual funds are good and cheaper to buy and manage (reduced fees)
- Trade off between risk and return
- How often to monitor your portfolio?
- Market timing: when to buy? (article I can't find)
- Rules of thumb:

    > the diversification heuristic. “When in doubt, diversify.” Don’t put all your eggs in one basket.
- Naïve diversification:

    > When faced with ‘n’ options, divide assets evenly across the options.”3 Put the same number of eggs in each basket.


> ERISA sets forth three fiduciary principles for retirement-plan investments: the exclusive benefit rule, requiring that plans be managed exclusively for the benefit of participants; the prudence rule, requiring that plan assets be invested according to a “prudent investor” standard; and the diversification rule, requiring that plan assets be diversified so as to minimize the risk of large losses.

- Sell more tomorrow

> Sell More Tomorrow. The idea is to solve two problems. First, even if firms recognize that company stock is not so great for employees, they do not want all or most employees to sell their stock at once, for fear that such sales will lower the stock’s price. Second, firms do not want to be signaling that they think their stock is a bad investment. The Sell More Tomorrow plan gives employees the option to sell off their shares gradually over a period of time (say, three years), with the proceeds directed into a diversified portfolio.

- Nudges:
  - Defaults:

    > Target maturity funds typically have a year in their name, like 2010, 2030, or 2040. A participant simply selects the fund that matches her expected retirement date. Managers of the target maturity funds select the degree of risk and gradually shift the allocation away from stocks and toward conservative investments as the target date approaches
  - Structuring complex choices - reduced choices with the option to select individually
  - Expect error - automatic enrolment
  - Mappings and feedback - metaphors
  - Incentives

- https://www.spaceship.com.au/learn/
- https://moneysmart.gov.au

### 8: Credit Markets

- **Mortgages** and APR (Annual percentage rate)
  - Poor and high risk borrowers
  - Subprime lending - still give disadvantaged groups a chance
  - Good faith estimates - spelling out costs and fees paid to the broker within three days of the initial application, sometimes withheld until right before the borrower signs the papers.

> When markets get more complicated, unsophisticated and uneducated shoppers will be especially disadvantaged by the complexity. The unsophisticated shoppers are also more likely to be given bad or self-interested advice by people serving in roles that appear to be helpful and purely advisory.

- **Student loans**
  - applications are too complex
  - institutes have agreements with loan brokers
  - Applications should start by cutting down number of questions, and making them uniform for all loans, federal and private
  - Should be teaching high school students how to apply for student loans

- **Credit cards**
  - Here as elsewhere, government should respect freedom of choice; but with a few improvements in choice architecture, people would be far less likely to choose badly
  - Monthly repayments are too low - to encourage interest accumulation on the remainder owed
  - Very high interest even when you are late by one day
  - Credit companies reduce the number of days between getting the bill and the day the payment is due
  - Credit companies hide their fees, so it is not easy to see how much extra we pay for their services

> The Census Bureau reported that there were more than 1.4 billion credit cards in 2004 for 164 million cardholders—an average of 8.5 cards per cardholder

--
> In the pre–credit card era, households were pretty much forced to use a pay-as-you-go accounting system. That is why people used jars of money labeled according to purpose or payee. Now if you don’t have the cash to fill your car up with gas, there is always your credit card. Credit cards inhibit self-control in other ways.

Summary:

> For mortgages, school loans, and credit cards, life is far more complicated than it needs to be, and people can be exploited...Here as elsewhere, government should respect freedom of choice; but with a few improvements in choice architecture, people would be far less likely to choose badly.

### 9: Privatising Social Security: Smorgasbord Style

- Swedish Privatisation Plan
- Default plan was better than what people actively chose for themselves because it was more balanced with less fees
- Home bias: well-known tendency of investors to buy stocks from their home country
- Advertisement decreased after the first year, so people now mainly stick with the default fund

> In summary, those who selected portfolios for themselves selected a higher equity exposure, more active management, much more local concentration, and higher fees.

--
> In summary, those who selected portfolios for themselves selected a higher equity exposure, more active management, much more local concentration, and higher fees.

**A simplified choice process:**

1. Start with a simple yes/no option. If they reject the default fund...
2. guide participants through a small set of blended funds based on age of participant
3. And only when they reject these options, give them the full set funds available

**Comment by tomdalling** [comment]
## Meeting Minutes (Anonymised)

- The book is overly political
- The book is overly US focused
- The start of the book was better than these chapters
- It's easier to read than Thinking Fast and Slow, but that doesn't necessarily mean the content is better.

### Chapter 7 - Naïve Investing

- The book has some questionable wording around "sophisticated" and "naive" investors, relating them to women and minorities.
- Timing the market doesn't work when you compare worst case, best case, and dollar cost averaging
- Term deposits, and other interest earning instruments, suck now
- APRA is cracking down on Xinja (?) bank and a lot of neobanks are scared

### Chapter 8 - Credit Markets

- Authors are pushing their American political views
- The argument for "predatory" loans is similar to the argument for sweatshops
- It's not accurate to imply that African microfinance is good therefore high-interest American loans are good
- Perhaps the situation is different since the book was written
- Middle America is slow to catch up with financial technology
- It's crazy that the average card holder has 8.5 credit cards in the US
- Credit cards per person is ~0.5 in Australia vs ~4 in US.
- Afterpay et al are a reinvention of lay-by
- Cashless economies raise questions about how easy it is to deny people access to their own money

### Chapter 9 - Privatising Social Security: Smorgasbord Style

- Investing in international stocks might be good in general, but it's bad advise for individuals, and it's one of the few actionable messages in the book so far
- The book has some questionable  wording about wives being more organised than husbands
- The book enforces the impression that the default is often the best option, which can be misleading
- Options provided by the government may be better than options provided by private companies due to alignment of incentives
- Superannuation is mostly built on shares, which could be dangerous and might be taking advantage of others in the stock market
- The assumption is that shares can grow exponentially, forever, which could be catastrophic if untrue
- People made money speculating on shares of bankrupt companies, showing how share prices can be unrealistic
