### ISSUE TITLE
New Book: How to be an Antiracist: August 18th

### ISSUE THREAD

**Issue by mcgain** [Blackmill/book-club#79]
We'll be starting a new book on the 18th of August
How to be an Antiracist by Ibram X. Kendi 
![racist](https://user-images.githubusercontent.com/193744/88623791-15356680-d0e9-11ea-8f2c-735a0068c095.jpg)

Aiming to read: 
Introduction
Chapter 1
Chapter 2

MC: @HashNotAdam
Notes: @tomdalling

See you 12 pm Tuesday, August 18th @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand

**Comment by HashNotAdam** [comment]
# Discussion

[@mcgain](https://github.com/mcgain): We can acknowledge that we are all speaking from positions of privilege and we might say things that are "wrong" but we all understand and we will learn together.
[@lachlanhardy](https://github.com/lachlanhardy): If our understanding of all of these issues didn't evolve over the course of the book, there would be a problem.
[@HashNotAdam](https://github.com/HashNotAdam): Almost hoping to get called out in order to learn.

[@HashNotAdam](https://github.com/HashNotAdam): You're a racist or an anti-racist, there is no middle ground. How do people feel about that?
[@mcgain](https://github.com/mcgain): People are not necessarily racist; people sometimes do or say racist things. So that means that I'm not necessarily a racist by not being anti-racist 100% of the time.
[@lachlanhardy](https://github.com/lachlanhardy): There is a category of terms for which we use nouns and I think we should use verbs. Rather than someone is an ally or someone is a racist, the truth is more fluid and the book describes this well.

[@lachlanhardy](https://github.com/lachlanhardy) explains the time he essentially sang [Avenue Q](https://youtu.be/D8FtsHfos-c) to a workshop.
[@lachlanhardy](https://github.com/lachlanhardy): It's not possible to be completely not racist but is possible to do things that are anti-racist.

[@mcgain](https://github.com/mcgain): Does everyone buy the initial premise that anti-racism is the opposite of racism instead of just being not racist?
John: As Black vs All Lives Matter has been bubbling, I've always thought that a neutral approach was the way to go—I'm not doing any harm and so that's okay—but it's not about that, it's about rebalancing.
[@HashNotAdam](https://github.com/HashNotAdam): I found this question very difficult. I completely appreciate the idea that if you believe that you are being race-neutral and that all races are equal but that individuals need to work harder, you are perpetuating the problem. As for whether that makes you racist is a really difficult topic and that goes to whether or not anti-racist is the opposite of racist.
[@lachlanhardy](https://github.com/lachlanhardy): The more I read about stuff like this, the more I learn that some of the things that I've done in the past and would have done now, had I not just learnt that it's bad, are bad... whoops!

[@lachlanhardy](https://github.com/lachlanhardy): Like climate change, individual action is important but that's not how you solve it.
[@elle](https://github.com/elle): Like women and technology; I don't think telling women to lean-in or men to shut up is the solution. Those things need to be proactively dealt with policy or actions from authorities.

[@gridsat](https://github.com/gridsat): I agree that doing nothing perpetuates the status quo but also you need to protect yourself. When you fight for change and you are getting nowhere, it can be emotionally challenging.

[@HashNotAdam](https://github.com/HashNotAdam): I had a lot of flashbacks to reading Invisible Women—a lot of gender inequality discussions are similar to race discussions—and this produced a lot of self-reflection regarding how racist ideas make people of colour think less of themselves and white people think more of themselves. White men, in particular, are taught to act like you know what you're doing and work it out. There's no question that the combination of that attitude and privilege has gotten me where I am in my career. Many times I've told someone I knew what I was doing, got some job I wasn't qualified for and leap-frogged my career. Then the idea that you can tell other types of people "you just gotta work harder" is really just bullshit.

[@lachlanhardy](https://github.com/lachlanhardy): At some point, I thought "I deeply care about these issues; I really wish there was more I could do but, right now, I cannot afford the headspace for it." And luckily for me, I don't have to and that was my version of protecting myself. And I choose not to do that because I'm a middle-class white male born and raised in Australia.

[@HashNotAdam](https://github.com/HashNotAdam): Cone said that "a Christian is one who striving for liberation", and I wondered whether that view is then essentially just the anti-white church. If a Christian is merely someone who is striving for liberation, then if all people were liberated would Christianity cease to exist?
[@elle](https://github.com/elle): I don't know what the original objective of the Bible and Catholicism's is but I like that the Black church has found a way like they have a distinction between the enslaving church and a liberating church.
John: Is it a positive thing that they are finding empowerment through segregation? Churches are all about supporting your own people, which is kind of the infancy of racist ideas and doesn't feel anti-racist.
[@elle](https://github.com/elle): I have a lot of issues with religion but, if it is done right, it provides a community for people that need support.
[@mcgain](https://github.com/mcgain): At the end of chapter 2 he says "to be an anti-racist is to conquer the assimilationist consciousness and the segregationist consciousness"

[@elle](https://github.com/elle): The conflict in Israel with the Palestinians has been around for decades and everybody within the conflict knows of a family that has had someone killed by the other side and I believe that it has never been fixed because there's always bad feelings and mistrust on both sides. In that case, the only way to solve that problem is by educating your children for a better future. In the same way, we can teach our children about racism.

[@HashNotAdam](https://github.com/HashNotAdam): I've had a lot of trouble dealing with the idea of calling African-American people "Black" because it feels like distilling people down to a colour but, though learning triggered by BLM, I've come to understand that it is a self-identification.
[@lachlanhardy](https://github.com/lachlanhardy): After moving to the US I decided I needed to educate myself on American culture and I started listening to American podcasts. One of the things that I initially found confronting was that one of these women referred to herself as Black and the other one referred to herself is Brown and I didn't know why. At a certain point, it just sort of became clear that Heaven didn't think of herself as Black because she was not born in America. Her family's from East Africa so she thinks she refers to herself as Brown. Whereas Tracy, who grew up in the South, thinks of herself is Black. It's taken me a while to deal with "White" being capitalised in the book.
