### ISSUE TITLE
Nudge: remaining chapters — August 11th

### ISSUE THREAD

**Issue by tomdalling** [Blackmill/book-club#80]
Nudge: Improving Decisions About Health, Wealth, and Happiness
by Richard H. Thaler, Cass R. Sunstein

https://www.amazon.com/Nudge-Improving-Decisions-Health-Happiness-ebook/dp/B00A5DCALY/

We're aiming to read to the end of the book. This includes chapters:

 - A Dozen Nudges
 - Objections
 - The Real Third Way
 - 20 More Nudges
 - the financial crisis addendum

There may be more or less chapters, depending on your version of the book.

MC: @tomdalling 
Notes: @lachlanhardy 

See you 12 pm Tuesday, August 11th @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand

**Comment by lachlanhardy** [comment]
# last session

We had a large conversation around "good design" and "nudges". Is there something revolutionary around nudges? 

Choosing sensible defaults is good design. There are decades of study into what makes good design. 

But perhaps the issue is that knowledge from that field had not been brought into areas like choice around healthcare, insurance, schools etc. We're also looking at this retrospectively. This book was so influential that it's hard to judge what was novel 11-12 years ago.

We also came back to ideas like:
 - should markets be completely unregulated?
 - why is minimal government better?
 - the rights of the individual over the rights of society

## A Dozen Nudges

We talked through each of these. Some seem weirder to us than others (presumably because of constraints that American culture normalises which are not clear to us). Some didn't seem particularly like "nudges" either.

## Objections

Some of the examples as counterparts were trivial. This chapter seemed to be defending the book against hardcore libertarians and so fell flat to us.

"True" neutrality should be afforded to:
- voting  
- religion
- free speech

But everything else can be nudged? Really?

This chapter appears to be discussing where does the line lie between things that should be dictated versus things that should be a choice.

## The Real Third Way
> In this book we have made two major claims. The first is that seemingly small features of social situations can have massive effects on people’s behavior; nudges are everywhere, even if we do not see them. Choice architecture, both good and bad, is pervasive and unavoidable, and it greatly affects our decisions. The second claim is that libertarian paternalism is not an oxymoron. Choice architects can preserve freedom of choice while also nudging people in directions that will improve their lives.

## Postscript on the GFC

We talked a bit about the GFC, sub-prime mortgages, and the authors' blame of the people taking out the mortgages.

## Would we recommend this book?

The closest we came to it is that maybe people should read the first few chapters to gain some understanding of the concepts but do further reading elsewhere.

OTOH, we're glad to have read the entire book. It's allowed us a greater understanding of the whole concept rather than the diluted shininess that we'd perceived through popular culture.

## Would we use nudges in life?

Parenting is basically all nudges...

In business terms, we're not opposed to their use. Some of us definitely use these things already. We prefer to drop the libertarian paternalism and view these ideas more as part of social psychology.
