### ISSUE TITLE
How to be an Antiracist: chapters 2, 3: August 25th

### ISSUE THREAD

**Issue by nickspragg** [Blackmill/book-club#81]
How to be an Antiracist by Ibram X. Kendi

https://www.amazon.com.au/How-Be-Antiracist-Ibram-Kendi/dp/0525509283

Aiming to read:

Chapter 2: Dueling Consciousness
Chapter 3: Power

MC: @gridsat
Notes: @HashNotAdam
See you 12 pm Tuesday, August 25th @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand

**Comment by HashNotAdam** [comment]
# Discussion

**N.B. apologies for the slim notes, I was having audio issues.**

[@gridsat](https://twitter.com/gridsat): I found [chapter 2] interesting because I completely agree that it's possible to have multiple points of view which can be in conflict.

[@lachlanhardy](https://github.com/lachlanhardy): When speaking about identifying as black:

> I still identify as Black. Not because I believe Blackness, or race, is a meaningful scientific category but because our societies, our policies, our ideas, our histories, and our cultures have rendered race and made it matter.

This is interesting because he only considered race in recent years when moving to the US and being asked for their race by an employer. Unsure of what to put, the administrator simply filled in "White". The U.S. has very little diversity in how it understands race to the degree that anyone of Middle Eastern heritage is also White. So these people are legally White but their lived experience is quite different.
[@pat](https://github.com/pat): Appreciated how this chapter reinforced that race is a construct that depends on where you're located and the point in history.
[@elle](https://github.com/elle): In Israel, hardly anyone has exclusively Israeli heritage. People always ask "what are you" but today's children might stem from four nations. And at some point in the future, it will stop making sense to ask because their children will be a combination off 8 different ethnicities.

[@gridsat](https://twitter.com/gridsat): Highlighted:

> It is one of the ironies of antiracism that we must identify racially in order to identify the racial privileges and dangers of being in our bodies.

Followed by "the six races", "Latinx and Asian and African and European and Indigenous and Middle Eastern". This took time to process because, at first, it felt counter to the whole approach that anti-racism is about saying everybody's equal. It is, however, that to be an anti-racist is about understanding your own privilege so that you can understand how it is impacting upon others.
[@elle](https://github.com/elle): He also says:

> The gift of seeing myself as Black instead of being colour-blind is that it allows me to clearly see myself historically and politically as being an antiracist, as a member of the interracial body

It's not possible to be colour-blind because, unfortunately, we live in a world where race exists.
[@gridsat](https://twitter.com/gridsat): A big part of the concept of anti-racism is about experience and understanding and that's something we get as we grow older. Part of what he's exploring in this chapter is how, when you're young, you can have a very narrow view and, as you get older, your view can broaden.
[@elle](https://github.com/elle): Black kids do not have the luxury of realising race until later in life. Families that want to keep them safe need to explain to them how the world works and how to live as a Black person in a White society, which is sad.
