### ISSUE TITLE
How to be an Antiracist: chapters 6–8: September 8th

### ISSUE THREAD

**Issue by lachlanhardy** [Blackmill/book-club#83]
How to be an Antiracist by Ibram X. Kendi

https://www.amazon.com.au/How-Be-Antiracist-Ibram-Kendi/dp/0525509283

Aiming to read:

- Chapter 6: Body
- Chapter 7: Culture
- Chapter 8: Behavior

MC: @lachlanhardy 
Notes: @elle 
See you 12 pm Tuesday, September 8th @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand

**Comment by elle** [comment]
**Re: What are we getting out of this book?**

Focused on how you think about race. Makes us think about our inactions.
Purpose of the book is not about teaching us to be an activist, but education and broadening perspectives.

**Re: Policies**

- What does it mean to support anti-racist policies?
- Helps understand which policies head towards racist inclinations.
- Voting for policies is your action. But voting is the only option available to us. It is not only about governmental policies; it could be organisational policies.
- No party in Australia is actively anti-racist. Maybe a better question to ask: which parties have influences beyond the white male perspectives?

**Re: Ebonics**

- Speaking "proper english" is a form of gate keeping. And sometimes we believe it is a socio-economics issues rather than racial issues, but they are many times tied together.
- English has always evolved over the years. Not sure there was ever a version of English that was proper.
- Language should be communicative and understood.
- African American Vernacular English is a formal language with its own grammatical structure, but that is not common knowledge, even in the US
- American speak the old fashioned English language, closest to puritan English at the time of revolution, where British English does not have as many rules for preservation.
- Entrée originated from French and defines the main part of the meal, which is what Americans stuck with, while the rest of the world moved on.

## 6: Body

**BODILY RACIST:** One who is perceiving certain racialized bodies as more animal-like and violent than others.

**BODILY ANTIRACIST:** One who is humanizing, deracializing, and individualizing nonviolent and violent behavior.

Children at the age of 13 are not allows to drink or vote, but can be tried as adults. WTF?

Bad neighbourhoods are not a function of Black neighbourhoods, but low socio-economics neighbourhoods and if their residents get better jobs, all the problems with bad neighbourhoods go away. The problem is the policies that preserve those poor neighbourhoods.

https://en.wikipedia.org/wiki/Cashless_Welfare_Card

## 7: Culture

> Cultural appropriation, at times also phrased cultural misappropriation, is the adoption of an element or elements of one culture or identity by members of another culture or identity. This can be controversial when members of a dominant culture appropriate from disadvantaged minority cultures.

Are Adele actions an example of that? or is it inappropriate?
What about indigenous artworks? Art is usually about freedom of expression.

Assimilationist have a cultural rank and that integrating a different racial group means it is not good enough and we have to raise them into the level of the higher racial group.

> Cultural integration is the blending of two or more cultures. The culture may exchange their practices, beliefs, ideas and rituals. Integration is only possible when the cultures do not have to sacrifice the characteristics that make them unique.

Is this even possible?

## 8: Bahaviour

IQ tests are racist. That's a known fact.

The education system is built to quantify and standardise results in a way that make it easier to keep track of stats and numbers. It is not set up to accommodate different kids with different needs and different ways of learning.

Revisit chapter 8 next week
