### ISSUE TITLE
How to be an Antiracist: chapters 8-10: September 15th

### ISSUE THREAD

**Issue by elle** [Blackmill/book-club#84]
How to be an Antiracist by Ibram X. Kendi

https://www.amazon.com.au/How-Be-Antiracist-Ibram-Kendi/dp/0525509283

Aiming to read:

Chapter 8: Behavior
Chapter 9: Color
Chapter 10: White

MC: @pat
Notes: @lachlanhardy

See you 12 pm Tuesday, September 15th @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand

**Comment by lachlanhardy** [comment]
## Chapter 8: Behavior

Standardised testing comes in two main forms:
 - testing the students
 - using those tests to assess the teachers and schools

Even though it attempts to level the playing field, it biases towards privilege. And teachers teach to the test, rather than for learning.

We started talking about how to implement antiracist policies to support poor performing students in an equitable fashion. 

This moved onto a conversation about reparations, whether they are justified, how they could work, and who should be responsible for paying for them.

Then on nation-building, how national wealth has been generated, how 'advanced' nations became advanced.

## Chapter 9: Color

It's becoming clearer that effectively everyone is racist. Most of us were unfamiliar with the ideas in this chapter. We hadn't thought about 'racism' within the 'races'.

The idea of choosing your eye colour as a white person is perhaps just a matter of preference. The author's example of choosing eye colour is fraught with additional weight. Is he making a statement on race? Even if he isn't, is his preference driven (tainted?) by racist ideals of moving towards whiteness/lightness?

## Chapter 10: White

Anti-white racism is not "reverse racism". 

Saying that something is racist against White people is ignoring the privileging of White people by the racist system. Do we believe that? Does reverse racism exist or is it just racism?
