### ISSUE TITLE
How to be an Antiracist: chapters 11–13: September 22nd

### ISSUE THREAD

**Issue by lachlanhardy** [Blackmill/book-club#85]
How to be an Antiracist by Ibram X. Kendi

https://www.amazon.com.au/How-Be-Antiracist-Ibram-Kendi/dp/0525509283

Aiming to read:

Chapter 11: Black
Chapter 12: Class
Chapter 13: Space

MC: John
Notes: @pat

See you 12 pm Tuesday, September 22nd @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand

**Comment by elle** [comment]
# 13. Space (Integration)

Made me think of:
- Orthodox jews in Williamsburg, Brooklyn
- Integration tactics for Jewish and Arab children in Israel
- If you were a rape victim, would you be willing to co-live with your abuser?
- Single gender schools

> White students fill most of the seats in today’s public school classrooms but are taught by an 80 percent White teaching force, which often has, however unconsciously, lower expectations for non-White students. When Black and White teachers look at the same Black student, White teachers are about 40 percent less likely to believe the student will finish high school.

https://www.npr.org/2019/06/03/729275139/people-like-us-how-our-identities-shape-health-and-educational-success

From the podcast:

> The black doctors were about 50 percent more successful than non-black doctors at getting their patients to agree to invasive tests for diabetes and the flu shot. When it came to cholesterol screening, they were 72 percent more effective.

--
>  If you're a black student and you have a black teacher, on average, you're going to have a higher test score than a black student who has a white teacher.

--
> Black students in our sample who were matched to a black teacher were less likely to drop out of high school, more likely to sit for a college entrance exam - so think, you know, SAT, ACT - and then more likely to enroll in college.

--
> The success of black students increased with every year they were matched with black teachers. Black students who spent more time with black teachers did better than black students who spent less time. These results could have huge implications. They suggest that race matching might be one way to get more at-risk black kids to stay in school and go on to higher education

**Comment by pat** [comment]
## Chapter 11

* This part focused on how racism _within_ racial groups is still racism.
* There was the anecdotal example of Black police sometimes being _more_ violent than White police (and similar slavery examples).
* Similar behaviours between different 'classes'.
* Chris Rock was described as a race-maker - a label also applied to colonising Portuguese, so feels harsh in this context, but perhaps fair.
* Some challenges with the extreme nature of this chapter, paralleled to the strong emphasis of the binary between racism and antiracism in early chapters - no grey areas. Some people feel the absolutist approach may be counterproductive.
* But perhaps that binary approach is useful as a way to recalibrate our own understandings, and is useful as a reminder that action is required. Not acting means reinforcing the racist status quo.
* Having exposure to others - for different names, cultures, etc - is important, but more than exposure is needed: active education is essential so people know how to resopnd in situations where they encounter difference.

## Chapter 12

* Appreciating the focus on the linked nature of capitalism and racism, and how the rise of colonial/racist slavery is tied to the rise of capitalism.
* Anti-capitalist and anti-racist ideas must be combined to counter these related problems.
* Discussed red-lining in the US, and the parallels in Africa due to imported ideas from US/capitalist colonisers.
* American colonisers killed bison in huge numbers while taking over land, and bison were considered the wealth of the Native nations, so colonisers stole land and wealth in one act, the destructive impacts of which continue today.
* Can see parallels between current Federal Government policy in Australia for tax cuts and welfare cuts as impacting both class and race here.
* There are situations where Australian policy can be positive - the requirement of public housing to be spread across all suburbs rather than ghettoising certain suburbs (and the same happens in NYC) - though removing the existing public housing is a major cash injection for governments while making life much harder for the former tenants.

## Chapter 13

* Appreciate the distinction of (and preference for) communal objectivity instead of complete/universal objectivity.
* On the distinction between segregation versus separation: when looked at in single-gender schools, overcoming gendered stereotypes is easier, academic performance is better (though certainly, other issues can be exacerbated).
* Also, as the book notes, having same-race teachers and doctors - especially for non-dominant races - can lead to better education and health outcomes.
* Also, see Elle's notes above.
