### ISSUE TITLE
How to be an Antiracist Chapter 17 and 18: October 6th

### ISSUE THREAD

**Issue by JohnTelfer** [Blackmill/book-club#87]
How to be an Antiracist by Ibram X. Kendi (Amazon, Readings)

Aiming to read and discuss:

Chapter 17: Success
Chapter 18: Survival

MC: Adam
Notes:  @mcgain

See you 12 pm Tuesday, October 6th @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand.

**Comment by mcgain** [comment]
# Final Antiracist Chapters Discussion Notes

@HashNotAdam asked how did we like the metaphor of racism as cancer?

@mcgain didn’t enjoy the metaphor. He felt it distracted from the points the author was trying to make.

@JohnTelfer agreed and felt the final chapters were not the right place to introduce this new concept.

@HashNotAdam said he didn’t actually provide a solution and prove its going to work 

@saramic pointed out that the afterword said “people trusted me to tell them how to be an antiracist”, but he thinks he failed to do this. 

@HashNotAdam asked what people thought about America is fundamentally racist
@pat agreed, our society is built on racism

@lachlanhardy before he read this book, thought he was post-race, but this book has changed him to properly consider race and racism.

What did we learn?
Identify racist policies in our lives and work to enact change in them
Is this in your hiring policies at work? Community groups you’re a part of, council elections? 

### On Hope: 
@HashNotAdam : Do people believe we haven’t made any progress? Has the progress stopped? Can the antiracists win?

@saramic says the last 600 years have been a hicchup. It’s a long road, but we’re significantly better off than we’ve been in the past. He believes we can get there. 

@HashNotAdam Society is slow to evolve. Do Americans feel like they’re going backwards because of trump?

@lachlanhardy Human society is not a linear progression towards equality. Even in the US it’s gone back and forth. Generally heading in the right direction.

@elle think we’re not going to eliminate racism in our time. It will get better though. 

@lachlanhardy thinks he might have missed a trick on the finale of the book. Instead of talking about hope, and his lack of it, shouldn’t he have made a call to action for people to identify racist policies and oppose them.

@saramic asked if there have been any good guides on how to spot racist polices, or even an example of a racist policies and how it affects people.

@HashNotAdam points out the “self interest” origin of racist policy. We agree that he fails to explicitly explain a lot of his ideas.

@lachlanhardy says this book is a history of racism in America. The autobiographical stuff is added to make it more accessible. Admitting he was racist in the past helps diffuse his controversial ideas. 

### Final Thoughts

@lachlanhardy and @mcgain ask, what is your summary of the book? What did you get out of it?

@HashNotAdam considered whether to recommend it. It’s too personal for him, it’s too US centric and you’d need to go get a lot of context about US history. Ultimately he decided to recommend it to people who don’t know anything about this

@saramic thought it was great for the fans, but he didn’t get anything out of reading the whole book. He’ll act more consciously after reading the book, but thought it might put a lot of people off. “It’s not a good book” for people who want to be convinced to do something about this. How can Michael make an actual difference he wonders?

@pat found it interesting but not groundbreaking. He thinks the title should have been “How to think like an Antiracts” not “How to BE an antiracist”. He wouldn’t recommend it, there are better books. Generally he enjoyed the book though, and admits it’s difficult to be prescriptive in a book like this. 

@JohnTelfer asked if it achieves its purpose. It has a catchy title to make more people read it, but it’s still pretty much an academic text. The book calls for people to challenge and change policy, but he fails to really achieve the title. He thinks that pushing these topics more into the mainstream, and if they push middle of the road white people into thinking about this more, it’s successful. 

@elle looked to the beginning and ends of each chapter where there were some useful definitions. Elle doesn’t read biographies, but picked this book because it’s a topic she wants to learn more about. The book hasn’t opened her eyes, but it has given her more language to use when discussing these topics.

@HashNotAdam wonders how this book would come across in different groups. We’re not typical people. In other book clubs he’s heard of, some people haven’t even believed the information in books like Little Women. Adam doesn’t think this book will work on “Middle Australia”.
