### ISSUE TITLE
New book: Thinking in Bets: Intro + Ch 1: October 13

### ISSUE THREAD

**Issue by elle** [Blackmill/book-club#88]
Book: Thinking in Bets by Annie Duke ([Amazon](https://www.amazon.com/Thinking-Bets-Making-Smarter-Decisions-ebook/dp/B074DG9LQF/), [Readings](https://www.readings.com.au/products/26565013/thinking-in-bets))

Aiming to read:
- Intro: why this isn't a poker book
- Chapter 1: Life is poker, not chess

MC: @lachlanhardy 
Notes: @HashNotAdam 

See you 12 pm Tuesday, October 13h @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand.

**Comment by HashNotAdam** [comment]
# Discussion

[@lachlanhardy](https://github.com/lachlanhardy): knows nothing about poker. The fact that he doesn't know something does not seem to surprise the group.

[@lachlanhardy](https://github.com/lachlanhardy): The book dives straight into a lot of references of mainstream (rather than academic) texts.

[@lachlanhardy](https://github.com/lachlanhardy): You can lose lucky hands and win unlucky hands and this is a terrible way to learn (the feedback loop is faulty). Hopefully, this book can teach us how to know if you made a good decision.

[@elle](https://github.com/elle): Had never previously thought about the idea that a decision can be correct but produce a poor outcome.
[@lachlanhardy](https://github.com/lachlanhardy): The Seahawks example was "*an amazing example*" of how a failure is frowned upon even when it is unquestionably the best statistical decision.

[@elle](https://github.com/elle): Duke says that saying "I don't know" is not a bad thing and this is something a lot of people forget under the pressure of needing to prove we know things. [@elle](https://github.com/elle) likes to hire people who know what they don't know.

[@saramic](https://github.com/saramic): Previously considered luck to be a hindrance to sport but maybe luck is just a part of life. This chapter didn't realise resonate and hoping there isn't a need to learn poker to understand the lessons.
[@mcgain](https://github.com/mcgain): Has the same concerns that maybe he will be unable to identify a situation to use probability and calculate those probabilities quickly enough.
[@elle](https://github.com/elle): The [6 P's (Prior Preparation Prevents Piss Poor Performance)](https://military.wikia.org/wiki/7_Ps_(military_adage))

[@mcgain](https://github.com/mcgain), [@elle](https://github.com/elle), & [@lachlanhardy](https://github.com/lachlanhardy): Are strongly against gambling and it's addictive properties and that makes this book difficult to read.

[@tomdalling](https://github.com/tomdalling): When Deep Blue beat the chess world champion for the first time, someone said "the computer isn't smarter than you, it just has a bigger memory than you", to which the champion responded, "yes, but at some point, a larger memory *is* intelligence".

[@lachlanhardy](https://github.com/lachlanhardy): The example of trying to find a new CEO assumes that, if the decision was thought through, it must have been a good decision. This misses the fact that there could have been factors they didn't consider.

Group references Moneyball, a [book](https://en.wikipedia.org/wiki/Moneyball) and [film](https://en.wikipedia.org/wiki/Moneyball_(film)) about the Oakland Athletics baseball team that uses analytics to assemble a competitive baseball team.

John: In so many projects, you don't see the outcomes by the time you finished the project which makes it difficult to know if the decisions made were correct.

[@tomdalling](https://github.com/tomdalling): Recently tried "thinking in bets" regarding applying for work by coming up with an initial estimate of the probability of getting the role and then making decisions on how to approach the hiring process accordingly. Speaking of which, he leaves for a job interview and fingers are crossed.

This session highlighted that [@elle](https://github.com/elle) has a propensity for poker puns.

John: If you are in a meeting with your peers, would you ever say "I don't know"? There would be connotations. Society is not comfortable with "I have no idea"; you can't say that in a professional context.
[@elle](https://github.com/elle): Disagrees, saying it can create an opportunity for discussion and collaboration.
[@lachlanhardy](https://github.com/lachlanhardy): It's easy to respond to client questions with your previous experience but the last solution may not suit the current situation. "I have to keep finding new ways to say 'I don't know the answer'"
[@mcgain](https://github.com/mcgain): This is an interesting topic to hit so late because, if you are going to say "I don't know", you need to be in an environment that understands what that means. That understands you are not saying "I am weak" but "there are unknowables in this situation". Are there ways to make an organisation more sensitive to that?
[@lachlanhardy](https://github.com/lachlanhardy): Leadership needs to show vulnerability.
