### ISSUE TITLE
Thinking in Bets: Chapter 2: October 20

### ISSUE THREAD

**Issue by elle** [Blackmill/book-club#89]
Book: Thinking in Bets by Annie Duke ([Amazon](https://www.amazon.com/Thinking-Bets-Making-Smarter-Decisions-ebook/dp/B074DG9LQF/), [Readings](https://www.readings.com.au/products/26565013/thinking-in-bets))

Aiming to read:
- Chapter 2: Wanna bet?

MC: @elle 
Notes: @lachlanhardy 

See you 12 pm Tuesday, October 20th @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand.

**Comment by elle** [comment]
# 2. Wanna bet?

- **Thirty days in Des Moines**
  - "John proved, in spectacular fashion, that the grass is always greener."
- **Employing people or finding balance**
  - "Although employers aren’t trying to entice employees to quit, their goal is similar in arriving at a compensation package to get the prospect to accept the offer and stay in the job."
  - "Betting on hiring the wrong person can have a huge cost."
- **All decisions are bets**
  - Treat our decision as explicit bet => better decision and protective measures
  - "By treating decisions as bets, poker players explicitly recognize that they are deciding on alternative futures, each with benefits and risks."
  - Definition: "a choice made by thinking about what will probably happen"
  - "Not placing a bet on something is, itself, a bet." - like choosing what or what not to wear.
  - There is always opportunity cost in choosing one path over others.
  - Investments
- **Most bets are bets against ourselves**
  - "In most of our decisions, we are not betting against another person. Rather, we are betting against all the future versions of ourselves that we are not choosing."
  - Alternatives futures, which we can't know whether it will better or worse. Just possibilities.
  - Decision should be based on some defined criteria
  - Overfitting - how many factors to consider, and the case against complexity

--
When Charles Darwin was trying to decide whether he should propose to his cousin Emma Wedgwood, he got out a pencil and paper and weighed every possible consequence.
In favour of marriage he listed children, companionship, and the “charms of music and female chit-chat.”
Against marriage he listed the “terrible loss of time,” lack of freedom to go where he wished, the burden of visiting relatives, the expense and anxiety provoked by children, the concern that “perhaps my wife won’t like London,” and having less money to spend on books.

--

- **All bets are as good as our beliefs**
  - "...I thought turkeys could fly."
  - "We bet based on what we believe about the world."
  - "how our employees will behave if we let them work from home."
- **Hearing is believing**
  
1. We hear something
1. We believe it to be true
1. Maybe later, time and inclination permitting, we vet whether it is true or false

- Did anyone fact check any of the examples?
- Reminds me of "Delusions of Gender" by Cordelia Fine
- "our default is to believe that what we hear and read is true. Even when that information is clearly presented as being false, we are still likely to process it as true."
- "We might think of ourselves as open-minded and capable of updating our beliefs based on new information, but the research conclusively shows otherwise. Instead of altering our beliefs to fit new information, we do the opposite, altering our interpretation of that information to fit our beliefs."

--
Decision making framework by Emily Oster, a prof of economics at Brown University
  
1. Frame the question. (Clearly define two or three options, instead of trying to evaluate infinite or indistinct possibilities.)
2. Mitigate risk. (What’s the safest way to execute those options?)
3. Evaluate risk.
4. Evaluate benefits. (Don’t overlook these.)
5. Decide and move on (don't linger)

- https://www.youtube.com/watch?v=mIC7XAtt6JA
- https://www.bloomberg.com/news/features/2020-10-08/economist-emily-oster-is-helping-parents-stay-sane-in-the-coronavirus-pandemic

--
- **They saw a game**
  - We all see what fits our self-narrative
- **The stubbornness of beliefs**
  - The Internet has a wealth of information, but we usually choose to use it as a way to valid our already existing beliefs
  - "Every flavor is out there, but we tend to stick with our favorite."
  - Filter bubble
- **Being smart makes it worse**
  - "We bet on our beliefs. We don’t vet those beliefs well before we form them. We stubbornly refuse to update our beliefs."
- **Wanna bet?**
  - "Being asked if we are willing to bet money on it makes it much more likely that we will examine our information in a less biased way, be more honest with ourselves about how sure we are of our beliefs, and be more open to updating and calibrating our beliefs."
  - "Once we start doing that, we are more likely to recognize that there is always a degree of uncertainty, that we are generally less sure than we thought we were, that practically nothing is black and white, 0% or 100%. And that’s a pretty good philosophy for living."
- **Redefining confidence**
  - Citizen Kane - best original screenplay and 5 other nominations
  - How certain are we that something is true? 60%?
  - "Instead of thinking of confidence as all-or-nothing (“I’m confident” or “I’m not confident”), our expression of our confidence would then capture all the shades of grey in between."
  - "Incorporating uncertainty in the way we think about what we believe creates open-mindedness, moving us closer to a more objective stance toward information that disagrees with us."
  - "When we work toward belief calibration, we become less judgmental of ourselves. Incorporating percentages or ranges of alternatives into the expression of our beliefs means that our personal narrative no longer hinges on whether we were wrong or right but on how well we incorporate new information to adjust the estimate of how accurate our beliefs are."

> **Acknowledging that decisions are bets based on our beliefs, getting comfortable with uncertainty, and redefining right and wrong are integral to a good overall approach to decision-making.**

**Comment by lachlanhardy** [comment]
# Chapter 2. - Wanna bet?

"Yo, hackers."

- **Thirty days in Des Moines**
  - This bet is fascinating to us because the people are acting more like companies. They don't think it's 30k or nothing. They go around the situation. Let's negotiate a way out of this. You pay me 15k to stop 28 days early.
  - We spent a long time on what is the deal with this guy's life? 
- **Employing people or finding balance**
  - "Betting on hiring the wrong person can have a huge cost."
- **All decisions are bets**
  - The stock market is a thing humans designed and yet most people say it is not possible to predict. If we can't predict it, how could we possibly predict actual life? 
- **Most bets are bets against ourselves**
  - A personal example about choosing a house to live in - without considering schools in the area, THEN having kids.
  - Giving confidence scores is interesting. Similar to how much you care about an outcome. But should also consider how easy a decision is to reverse.
- **Hearing is believing**
	- Did anyone fact check any of the examples?
  		- Just Lachlan with the Ellis Island Special 
	- Elle introduced everyone to "Delusions of Gender" by Cordelia Fine
- **Being smart makes it worse**
  - We didn't get enough details about what intelligence was in this, but it sucks nonetheless.
- **Redefining confidence**
  - if we start questioning things around us, we might start looking for evidence to guide our decisions
  - If we can't beat our own biases, even when we know we have them, how do we solve this? Knowing the bias allows us to design a system or process that mitigates or avoids the impact of the bias without removing it.
  - The author seems to be saying doubt is always good, which we're uncomfortable with.
  - Making decisions based on percentages of confidence etc seems good for ego - we can never be wrong! But how does one assess if the percentages had any value?
