### ISSUE TITLE
Thinking in Bets: Chapter 3: October 27

### ISSUE THREAD

**Issue by lachlanhardy** [Blackmill/book-club#90]
Book: Thinking in Bets by Annie Duke ([Amazon](https://www.amazon.com/Thinking-Bets-Making-Smarter-Decisions-ebook/dp/B074DG9LQF/), [Readings](https://www.readings.com.au/products/26565013/thinking-in-bets))

Aiming to read:
- Chapter 3: Bet to Learn: Fielding the Unfolding Future

MC: @saramic 
Notes: @elle 

See you 12 pm Tuesday, October 27th @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand.

**Comment by elle** [comment]
# Chapter 3: Bet to learn: fielding the unfolding future


- Nick the greek story: static in his views vs using every experience as a learning opportunity
- Ruby community encourage people to continue to improve, but possibly this is not the case in other fields and industries. Might be eye opening perspective for the general public.
- There are companies with many teams where each team does things differently, and it is sometimes hard to move forward with so much variety. Experimentation is useful. But this chapter is not talking about how to set an experiment for the future, but about how we reflect on what happened, and assigning credit to us vs assigning blame to others.
- She also talks about reflecting on our successes and failures is useful
- And how changing habits is hard
- Boring technologies, with an allowance for x number of tokens for innovation. Ref: https://mcfunley.com/choose-boring-technology
- Firing the CEO, they might have chosen the right decision, and the rest was luck. But they didn't consider how easy it would be to hire a new person. Some things are luck, but how much did they consider what it will look like. A pandemic can be an example of things that are out of our control and should not be factored into the calculation of how well a decision was.
- You made a bet, and things happened, and now you look at that bet (decision) and what can you learn from it when you make your next bet (decision).
- Last year there were signs of a recession coming this year, before we knew of this pandemic, but did the companies put in the efforts
- Working backward is hard: SnackWell's campaign of fat is bad, which lead to replacing it with sugar, which caused to an overweight epidemic. But it was more obvious later... https://en.wikipedia.org/wiki/This_is_why_you%27re_fat
- Insurance claims are all about "it wasn't my fault" -- pretty much like teenagers.
- Other people's outcomes reflect on us. For example comparing ourselves to others affect our happiness levels.
- How do you get confident enough to be able to say: "If it wasn't for luck, I would be winning every time". Maybe because of your parents?
- Reshaping habits:
  - Atomic habits is an easy read with many practical tips
  - Possibly out of topic for this book, which is about making bets and decisions
- Thinking about which job to take as a bet backfired. But also thinking of the government decisions about preparation of vaccines as a bet. Betting on having a vaccine ready, is a better decision than betting on not having the vaccine in place.
- Redux and the hard way: take as many opportunities to learn as you can.
- In a poker game, the person that takes the opportunity to learn, will be better in the long term. Also the same works for retrospectively thinking on what was done. Similar to Post-mortem where we try to figure out what went wrong so we can fix it for next time, instead of assigning blame.
- Conscientiously practicing and pushing through plateau  will help us improve. 
- The problem with biases, like habits, they are hard to change, which is why is is leading us to the buddy system.
- People's cultures comes through quite strongly in all these books. Violence is bad but sex is good in AU, and the opposite in the US
