### ISSUE TITLE
Thinking In Bets: second half of Chapter 6

### ISSUE THREAD

**Issue by lachlanhardy** [Blackmill/book-club#94]
Book: Thinking in Bets by Annie Duke ([Amazon](https://www.amazon.com/Thinking-Bets-Making-Smarter-Decisions-ebook/dp/B074DG9LQF/), [Readings](https://www.readings.com.au/products/26565013/thinking-in-bets))

Aiming to read:
- the second half of Chapter 6: Adventures in Mental Time Travel
  - from _Ulysses contracts_

MC: @elle   
Notes: @lachlanhardy  

See you 12 pm Tuesday, Nov 24th @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand.

**Comment by elle** [comment]
# Chapter 6: second half

## Ulysses contracts

Pre-commitement: past us prevents future us from doing something stupid. Taking precautions against irrationality. Examples: carrying healthy snacks

## Decision sweat jar

Identify language and thinking patterns that signal we veered from truth-seeking.

- Signs of the illusion of certainty: “I know,” “I’m sure,” “I knew it,” “It always happens this way,” “I’m certain of it,” “you’re 100% wrong,” “You have no idea what you’re talking about,” “There’s no way that’s true,” “0%” or “100%” or their equivalents, and other terms signalling that we’re presuming things are more certain than we know they are. This also includes stating things as absolutes, like “best” or “worst” and “always” or “never.”
- Overconfidence
- Irrational outcome fielding: "I can't believe how unlucky I got"
- Complaining about bad luck
- Generalised characterisation of people meant to dismiss their ideas
- Shutting down the message cause we don't like the messenger (Mertonian norm)
- Scope of time is not in proportion: "worst day ever"
- Signals we reject ideas without much evidence: "everyone agrees with me", "if you ask anyone"
- Using the word "wrong", which is a conclusion not a rationale
- Lack of self compassion: "I should have known", "how could I be so stupid?"
- Being overly generous in our story telling: sharing facts to emphasise our version
- Injecting our conclusion of belief when asking for advice
- Discouraging input and engagement from others

## Reconnaissance: mapping the future

- Betting on the future
- Scenario planning: figure out all the possible outcomes (futures)
- Then assign probabilities to each possible future             

> at least trying to assign probabilities, we will naturally move away from the default of 0% or 100%, away from being sure it will turn out one way and not another.
                
- Would be better if we can see ahead of the different possible futures, more than one move at a time - scenarios tree
- Dissent opinions can reveal key factors that weren't considered beforehand
- This gives is a more realistic view of the world, and better prepares us in how we respond toe different situations and outcomes. Better anticipation, being less reactive.

> Scenario planning makes us nimbler because we’ve considered and are prepared for a wider variety of possible futures.

## Scenario planning in practice                

> A $200,000 application with a 10% chance of success would have an expected value of $20,000. A $50,000 grant with a 70% chance of success would be worth $35,000. Without thinking probabilistically in this way, determining a grant’s worth isn’t possible—it leads to the mistaken belief that the $200,000 grant is worth the most when, in fact, the $50,000 grant is.

- More efficient work stack
- More realistic budgeting
- Better and more accurate estimates

> The important thing is that we do better when we scout all these futures and make decisions based on the probabilities and desirability of the different futures.

## Backcasting: working backwards from a positive future

> When we forecast the future, we run the risk of a similar distortion. From where we stand, the present and the immediate future loom large. Anything beyond that loses focus.

--
> By working backward from the goal, we plan our decision tree in more depth, because we start at the end.

--
> In backcasting, we imagine we’ve already achieved a positive outcome, holding up a newspaper with the headline “We Achieved Our Goal!” Then we think about how we got there.

## Premorten: working backwards from a negative future

> A premortem is where we check our positive attitude at the door and imagine not achieving our goals.

--
> Backcasting and premortems complement each other. Backcasting imagines a positive future; a premortem imagines a negative future. We can’t create a complete picture without representing both the positive space and the negative space.

--
> Gabriele Oettingen, professor of psychology at NYU and author of Rethinking Positive Thinking: Inside the New Science of Motivation, has conducted over twenty years of research, consistently finding that people who imagine obstacles in the way of reaching their goals are more likely to achieve success, a process she has called “mental contrasting.”
              
--
> Being a team player in a premortem isn’t about being the most enthusiastic cheerleader; it’s about being the most productive heckler.
                
--
> The premortem starts with working backward from an unfavorable future, or failure to achieve a goal, so competing for favor, or feeling good about contributing to the process, is about coming up with the most creative, relevant, and actionable reasons for why things didn’t work out.
                
--
> Once we recognize the things that can go wrong, we can protect against the bad outcomes, prepare plans of action, enable nimble responses to a wider range of future developments, and assimilate a negative reaction in advance so we aren’t so surprised

## Dendrology and hindsight bias  

> The trunk is the past. A tree has only one, growing trunk, just as we have only one, accumulating past. The branches are the potential futures. Thicker branches are the equivalent of more probable futures, thinner branches are less probable ones. The place where the top of the trunk meets the branches is the present. There are many futures, many branches of the tree, but only one past, one trunk.
                
--
> That 2%–3%, in hindsight, becomes 100%, and all the other branches, no matter how thick they were, disappear from view.

--
> If we don’t try to hold all the potential futures in mind before one of them happens, it becomes almost impossible to realistically evaluate decisions or probabilities after.

--
> When he looked back at his decisions, he couldn’t see all those branches and their likelihoods. He could only see the trunk. All he saw was a bad result.

## Ending paragraph

> We are going to do better, and be happier, if we start by recognizing that we’ll never be sure of the future. That changes our task from trying to be right every time, an impossible job, to navigating our way through the uncertainty by calibrating our beliefs to move toward, little by little, a more accurate and objective representation of the world. With strategic foresight and perspective, that’s manageable work. If we keep learning and calibrating, we might even get good at it.


# Looking back on "Thinking in Bets"

-  **Life is poker not chess**
  - Hazards of resulting: linking results with decisions, even when they are not correlated perfectly
  - Hindsight bias is the tendency, after an outcome is known, to see the outcome as inevitable
  - Use uncertainty to make better decisions
  - Instead of "wrong", using probabilities
- **Wanna bet?**
  - All decisions are bets
  - Most bets are decisions of future versions of us
  - We tend to believe what we read and hear
  - Instead of altering our beliefs to fit new information, we alter the information to fit our beliefs
  - We bet on our beliefs. We don’t vet those beliefs well before we form them. We stubbornly refuse to update our beliefs, even with diversity and abundance of information on the web, we retreat to our confirmatory bubble
  - Are we willing to bet on it? recognise degrees of uncertainty
  - Redefine confidence: instead of "all or nothing"
- **Bet to learn**
  - Outcomes are feedback
  - Betting on a future: belief -> bet -> outcome (with sometimes luck)
  - Taking credit for luck is not useful in learning
  - Being compassionate towards others when they fail
  - Reshaping habits - keep the old cue, deliver old result, but insert new routine
  - Thinking in bets -> perspective thinking instead of absolute thinking (all or nothing, lucky or unlucky)
- **The buddy system**
  - Friends inputs for new perspective, if we are willing
  - Groups can:
    - improve thinking of the individual
    - reward accuracy
    - expose us to diversity of viewpoints
   - Beware of homogeneity, and everyone thinking the same
- **Dissent to win**
  - Cudos towards objectivity
      - communism: data belongs to group
      - universalism: uniformity to claims and evidence
      - disinterestedness: vigilance against conflicts and self-interest
      - organised skepticism: encourage dissent
  - Mertonian norm: shutting down the message because we don't like the messenger
- **Adventures in mental time travel**
  - Present us doesn't care so much about future us (save for tomorrow)
  - Moving regrets in front of our decisions
  - Our feelings are not a reaction to the average, but to recent events (how was the ending of the experience)
  - Tilt: blowing an event out of proportion
  - Ulysses contracts (Pre-commitement: past us prevents future us from doing something stupid)
  - Mapping future possibilities and assigning probabilities to them
  - Backcasting: working backward from a positive future
  - Pre-mortem: working backward from a negative future

**Comment by lachlanhardy** [comment]
# Chapter 6: second half

## Decision swear jar

### Using the word "wrong", which is a conclusion not a rationale

Perhaps saying we're never fully confident of something being wrong is extreme, but this kind of futurecasting is cool because it pushes us to think about things in shades of grey. 

### Starting positions with dismissing 'typical _x_'

We had a long conversation about how to actually have conversations with opposing views in good faith. Basically we don't know.

## Reconnaissance: mapping the future

We wish she'd introduced the scenario tree analogy more comprehensively earlier in the book. It's a very strong model that we like. There were hints of it earlier, but if she'd built the book on this model, it might have been more relatable to some of us.

## Scenario planning in practice                

We had an example of someone whose work depends on grants. They regularly go for the smaller grants, because the probability of receiving them is so much higher than the big grants.

We do research in order to give us more knowledge about which future branch to choose.

## Premortem: working backwards from a negative future

Very common in SRE work. Game days to run outage and failure scenarios.

Bringing backcasting and pre-mortems into a SWOT analysis model is interesting as way of guesstimating probabilities. Separating the negative and positive streams provides extra clarity.

How do we statistically map out all the outcomes? A card deck is comparatively easy, because all potential outcomes are none and they're relatively limited in number. Reality, on the other hand...

# Our summary

This book has good ideas but is somewhat incomplete. She doesn't really address the practicality of how to incorporate these ideas into our life. You can't perpetually be in a deliberative state of mind.

Would it be better if the book was split into two types of decisions? The big deal decisions like buying a house etc vs the tiny regular decisions like eating healthy snacks.

## Would we recommend this to others?

Yes, with the caveat that it has useful information but has little advice on how to apply it.

Perhaps just read the first and last chapters, plus the section on truthseeking groups.
