### ISSUE TITLE
Sand Talk: Dec 8

### ISSUE THREAD

**Issue by lachlanhardy** [Blackmill/book-club#95]
New book: [Sand Talk](https://www.textpublishing.com.au/books/sand-talk) by Tyson Yunkaporta ([Amazon](https://www.amazon.com/dp/0062975641/), [Readings](https://www.readings.com.au/products/27439470/sand-talk-how-indigenous-thinking-can-save-the-world))
> This remarkable book is about everything from echidnas to evolution, cosmology to cooking, sex and science and spirits to Schrödinger’s cat.
> Tyson Yunkaporta looks at global systems from an Indigenous perspective. He asks how contemporary life diverges from the pattern of creation. How does this affect us? How can we do things differently?
>Sand Talk provides a template for living. It’s about how lines and symbols and shapes can help us make sense of the world. It’s about how we learn and how we remember. It’s about talking to everybody and listening carefully. It’s about finding different ways to look at things.
>Most of all it’s about Indigenous thinking, and how it can save the world.

Aiming to read:
- The Porcupine, the Paleo-mind, and the Grand Design
- Albino Boy

MC: @lachlanhardy 
Notes: @elle 

See you 12 pm Tuesday, December 8th @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand.

**Comment by elle** [comment]
# The porcupine, the paleo-mind, and the grand design


- Very different book and one that does not claims to be authoritative on the subject
- Secret talks reminds of cults which we are not a fan of
- The size of a brain is not a direct link to how smart someone is
- He is trying to put everyone on equal grounds, animals, humans, rocks...
- Indigenous history timeline is a lot longer than Western society's one

> Our knowledge endures because everybody carries a part of it, no matter how fragmentary. If you want to see the pattern of creation, you talk to everybody and listen carefully.

- We can develop into a technological society (if we can become sustainable at that) and thus look for a similar intelligence elsewhere but that doesn't have to be how other higher intelligence manifests itself

- A swimming pool was built on the initiation ground, means not being able to do the adults rites of passage. It also means there are now two generations of middle-age "kids", and within a couple more generations, there will be no elders. But also this raises the issue of not adapting to changing conditions.
- Narcissism and Emu

> The stories that define our thinking today describe an eternal battle between good and evil springing from an originating act of sin. But these terms are just metaphors for something more difficult to explain, a relatively recent demand that simplicity and order be imposed upon the complexity of creation, a demand sprouting from an ancient seed of narcissism that has flourished due to a new imbalance in human societies.
> 
> There is a pattern to the universe and everything in it, and there are knowledge systems and traditions that follow this pattern to maintain balance, to keep the temptations of narcissism in check.

- Freedom of speech vs intolerant of intolerance

> Containing the excesses of malignant narcissists is a team effort.

--

> The combination of social fragmentation and lightning-fast communication today, however, means we have to deal with these crazy people alone, as individuals butting heads with narcissists in a lawless void, and they are thriving unchecked in this environment. Engaging with them alone is futile—never wrestle a pig, as the old saying goes; you both end up covered in shit, and the pig likes it. The fundamental rules of human interaction do not apply to them, although they weaponize those rules against everyone else.

- When we have a sphere and a box with the same capacity, a sphere will use less space
- Individualism vs collectivism: Life nowadays is very easy, there is no need for any physical effort to survive. Thousands of years ago that wasn't the case. An individual wouldn't survive unless they were a part of a tribe. The concept of individualism, individual happiness, self fulfilment are new concepts. For indigenous people, individual  Identity is defined through the community. Community is above the individual. The individual does not choose their identity.
- Group ownership and collectivism ideas that don't work for Western way of thinking (for example: Facebook)
- Extremism in religions, and mechanism of control in social groups. Humans are not supposed to be separated and one can argue that people are less happy now. But the problem is who decides what the rules of engagement are? Is that a one person and based on higher conscience? Proposing that the rules should be agreed upon by everyone in the group, and can also be changed by everyone.
- Everyone usually wants to belong to something, which sometimes happen to be extremist religious groups.

> The war between good and evil is in reality an imposition of stupidity and simplicity over wisdom and complexity.

- In Western society, even though you paid your debt to society, you are supposed to be absolved. But that is not the case. They still end up living their mistakes later in life.

> that everyone is an idiot from time to time. Punishment is harsh and swift, but afterward there is no criminal record, no grudge against the transgressor.

--
> My feet, hands, and belly have become soft, and I use the term neoliberalism far more often than I use the word miintin (turtle). I may think to myself, “Oh, it’s the season to dig turtle eggs and yams now, and the wild pigs feasting on those things will have really good fat. I should go for sugar bag (wild honey) now too.” But I’m standing on a train commuting to work in Melbourne because I don’t have the patience and discipline to languish in a work-for-the-dole program in a remote community, waiting to chase pigs on the weekend.

- We should let remote communities to live the way they want to, and not throw capitalism at them.
