### ISSUE TITLE
Sand Talk: Dec 15

### ISSUE THREAD

**Issue by elle** [Blackmill/book-club#96]
New book: [Sand Talk](https://www.textpublishing.com.au/books/sand-talk) by Tyson Yunkaporta ([Amazon](https://www.amazon.com/dp/0062975641/), [Readings](https://www.readings.com.au/products/27439470/sand-talk-how-indigenous-thinking-can-save-the-world))
> This remarkable book is about everything from echidnas to evolution, cosmology to cooking, sex and science and spirits to Schrödinger’s cat.
> Tyson Yunkaporta looks at global systems from an Indigenous perspective. He asks how contemporary life diverges from the pattern of creation. How does this affect us? How can we do things differently?
>Sand Talk provides a template for living. It’s about how lines and symbols and shapes can help us make sense of the world. It’s about how we learn and how we remember. It’s about talking to everybody and listening carefully. It’s about finding different ways to look at things.
>Most of all it’s about Indigenous thinking, and how it can save the world.

Aiming to read:
- Albino Boy

MC: @mcgain 
Notes: @lachlanhardy 

See you 12 pm Tuesday, December 15th @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand.

**Comment by lachlanhardy** [comment]
## The Porcupine, the Paleo-mind, and the Grand Design

We went back over some points from this. 

We talked about the table of contents crafted as part of a shield to protect the author from some of the concepts of this book and his writing of them. Perhaps to protect him against gatekeepers in both Indigenous culture and mainstream Australian culture.

## Albino Boy

### Rocks
We talked about rocks. A lot.

How much can you disrupt a rock? 

Is sentience different to living?

Perhaps disturbing the rock inteferes with an important pattern of life.

Spirits are not benign. Some do bad things and that is the point of their stories.

There is a particular place in Kakadu there are ancient stories of, warning you'll get sick if you go there. There is rock art telling these warnings. This area is now the site of a uranium mine.

Standing stones and teleportation is a familiar concept from European mythologies but we had seen it associated with Australian Indigenous stories before.

### Emu the narcissist

The commentary on narcissicism sparked conversation about where the boundaries of society and community lie, who should be excluded, why, and what recourse do they have?

The rules of collectivism and the rules of community apply less these days because the manner of enforcing them is no longer as effective due to the internet and globalisation.

### Crime and punishment

Forgiveness following punishment is great. We're fans. It was the idea of being a willing participant in your punishment as a learning process that was fascinating. What are the implications of that? Barring mental illness (which is a larger issue), are there systems that can teach and support former criminals to return to society in a non-criminal manner?
