### ISSUE TITLE
Sand Talk: January 19th (changed to Feb 2)

### ISSUE THREAD

**Issue by pat** [Blackmill/book-club#99]
Continuing on with Sand Talk by Tyson Yunkaporta ([Readings](https://www.readings.com.au/products/27439470/sand-talk-how-indigenous-thinking-can-save-the-world), [Bookshop](https://bookshop.org/books/sand-talk-how-indigenous-thinking-can-save-the-world/9780062975645), [Amazon](https://www.amazon.com/dp/0062975641/))

Aiming to read:

Lines in the Sand
MC: @elle
Notes: @pat

See you 12 pm Tuesday, January 19th @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand.

**Comment by elle** [comment]
# Chapter 5: Lines in the Sand

- Different eras, economies, and supply chains: river, railways, highways
- Look at the past economies to map a pattern to represent the future

> But when I do that, the future I’m seeing and the future I’m selling are two different things.

- Traditional river-based economy -> mission economy -> riverboats transportation of cotton and wool -> rail transportation -> highways with oil tankers and trucks

> locals in each era believed the system to be stable and planned their future around it

- People became miners riding a boom
- New purpose for the river: with ATVs and jetskis
- Always new frontiers cause the old ones don't last

> the next generation of infrastructure—towers with broadband signals—offered hope of new lands, cyberspaces to colonize.

--
> In their digital ghettos there were endless new worlds and resources to discover, and this could last forever, without limits. Or at least until the rare earth metals required to power their devices ran out.

--
> In their digital ghettos there were endless new worlds and resources to discover, and this could last forever, without limits. Or at least until the rare earth metals required to power their devices ran out.

- Connection to nature

> Look beyond the things and focus on the connections between them, he says. Then look beyond the connections and see the patterns they make.

How?

  /\  /
 /  \/
/

- Environmental and sustainability issues in current living
- Sand movement patterns with the water and sea - sand moves around in circles
- KPI is not the solution
- Instead of looking at points of interest, look at the spaces in between, the  relational forces that connect the elements -> to be able to find a pattern outside linear time
- Trend analysis and predictive technologies

**Flocking Rules**

- https://en.wikipedia.org/wiki/Flocking_(behavior)
- https://sandimetz.com/99bottles-sample-js
- https://www.stevefenton.co.uk/2018/03/fractality-of-flocking-rules/
- https://jamiewright.dev/2019/02/04/refactoring-flocking-rules/

--
- Blockchain system cannot be a closed system. Individual nodes should remain autonomous, operate freely in a self-organising system of users.
- Example of social-control-system
- Perspective to be a custodian rather than an owner of lands, communities, or knowledge
- Relinquish artificial power and control
- Free movement of all agents and elements in the system
- Impact on management and government practices
- Systemic balance in a dynamic system
- No outside control
- Heterarchical system/structure:  composed of equal parts interacting together

> It is a risky endeavor in a culture that attaches negative meanings to words like “chaos” and “anarchy,” equating them with disorder and ruin. But chaos in reality has a structure that produces innovation, and “anarchy” simply means “no boss.” Could it be possible to have structure without bosses?

**Controlled chaos**

- Innovation: chaos within guidelines or freedom within context (Quinn, Managing innovation: controlled chaos, 1985)
- Creative thinking can breed chaos (Filipczak)

> Indigenous models of governance are based on respect for social, ecological, and knowledge systems and all their components or members. Complex kinship structures reflect the dynamic design of natural systems through totemic relationships with plants and animals.

--
> Indigenous models of governance are based on respect for social, ecological, and knowledge systems and all their components or members. Complex kinship structures reflect the dynamic design of natural systems through totemic relationships with plants and animals.

- Back to the idea that we should observe the connections between elements to try and see the patterns. Cannot see the whole without seeing the parts.
- Senior people ensure processes are maintained with safety and cohesion, there is no centralised control in Aboriginal societies
- Nothing is too complicated that a simple introduction cannot be possible

**About learning about other cultures:**

> First, check your ego and your motives. Why are you doing this? Second, you don’t need to be an expert to understand the knowledge processes of people from other cultures and enter into dialogues with them. More important, making yourself an expert in another culture is not always appreciated by the members of that culture.

Understand your own culture first!

> Understanding your own culture and the way it interacts with others, particularly the power dynamics of it, is far more appreciated.

- Have cultural humility

> This kind of cultural humility is a useful exercise in understanding your role as an agent of sustainability in a complex system. It is difficult to relinquish the illusions of power and delusions of exceptionalism that come with privilege. But it is strangely liberating to realize your true status as a single node in a cooperative network.

And again, sustainable system needs independent and autonomous parts of the interdependent whole

**Sustainability agents:**

- Diversity: keep the system open to interact with others that are dissimilar to you
- Connectedness: balance between individualism and diverse individuals
- Interactions: energy and communication to help with flow of living knowledge
- Adaptability: allow yourself to be transformed through interactions with others, do not block feedback

> There is a balance between self-definition and group identity. These two are not contradictory but entwined, and there are names for all of the roles you occupy as an agent of complexity in Aboriginal society.

- Lookout
- Narcissism, echo, and ego

> There are so many adolescent cultures in the world right now, reaching for the stars without really knowing what they are.  
> Adolescent cultures always ask the same three questions. Why are we here? How should we live? What will happen when we die? The first one I’ve covered already with the role of humans as a custodial species. The second one I’ve covered above, with the four protocols for agents in a complex dynamic system. The third one us-two will look at next.

**Comment by pat** [comment]
Extending on Elle's notes above, here's some of what we covered (hopefully doing justice to Elle's and Richard's contributions):

- Pat: found the opening of this chapter rather depressing - how through each evolution of economies, we make the same shallow-mindset mistakes, we don't learn about the interplay of larger systems.
- How to we spot the patterns between systems, not just within a specific system/economy?
- Richard: Wondering if there's analogy between the gold rush and the dot-com boom around 2000? Both were times of great wealth.
- Pat: Melbourne was perhaps the richest city in the world back then - wondering if it had the same issues with wealth centralisation vs distribution that we're seeing now?

---

* Elle: Can we see patterns, can we see and change our behaviour in nature?
* Richard: We aren't too bad at spotting patterns - the book isn't quite saying that we need to spot the patterns, but we need to change our behaviour, and this chapter doesn't give us those answers.
* Richard: there do seem to be solutions around soil quality, managing land according to First Nations approaches. Would have been good to have this covered in this book.
* Elle: A concept worth knowing: Nixtamalization - improving maize, corn, grains, flours, rediscovered in the 1930's. A lot of things have been known and lost, but also a lot of things have been learnt for the first time as well.

---

* Elle: most business objectives are not the solution for a sustainable future. The problem lies in capitalist economics.
* Elle: Looking at the spaces in between - reminded of flocking rules, learnt from Sandi Metz. Behaviour seen in flocks of birds when they fly. Computer models based on that can be applied to other species, and Sandi applies that to refactoring. Small incremental changes, one thing at a time, that can shift a flock's behaviour. Refactoring: change one line at a time, run tests, revert if tests fails.
* Richard: Have read about flocking behaviour in Vietnamese cyclists - so, humans can exhibit this behaviour as well.

---

* Richard: did anyone look into boids? Hadn't heard the term, but maybe it's what we see in Conway's Game of Life.
* Elle: References blockchain, expectation of autonomous behaviour within a shared system. In my own reading, have developed a preference for decentralised systems in organisations - like the Internet - but it's also less controllable, need to relinquish power/control, not everyone likes that.
* Elle: Most notions of power we hold is incorrect - we don't have as much control as we think we do. Hard especially for perfectionists to accept. Maybe we can control our own emotions/feelings, but even that's difficult.
* Richard: What are the implications are in wider systems? How do we change?
* Elle: Need to convince others that change is a good idea - cannot control them, cannot force the change. Need to have guidelines - links to our discussion about free speech - guidelines about what is okay, acceptable, and acknowledge that these guidelines can change. Can be a disaster depending on where the group leads, but still, cannot control society.
* Elle: felt like I would struggle in First Nations communities, being told what I can/can't do. But on reflection, seems there'd be more guidance around good behaviour, more-so than hard rules. Some freedom, within these guidelines. Free movements of agents, with balance in dynamic systems. I prefer that way of being - not being controlled, not controlling others.
* Elle: The negative connotations around chaos/anarchy make it harder for people to accept.
* Elle: Innovation = chaos within guidelines. Again, allowing freedom within the bounds of what is acceptable.
* Richard: It's tricky - others have formed communes, but they don't seem to have staying power, have remained small. Good enough within those communes perhaps, but need these groups to mix, to work together - larger movements haven't worked out (communism). How large are these indigenous groups? Maybe these things can happen in larger groups?
* Elle: reminds me of the book Reinventing Organisations, which compares old large institutions, industrial revolution, corporations evolving from carrot & stick, to using bonuses. And now - developmental-driven organisations, thinking about the people. Teal organisations come next - small, self-organising groups, still connected to the larger organisation. 5k-7k people as examples where it works. Similar to Holocracy. Needs a lot of infrastructure support - training in conflict resolution, procedures for making decisions. Feel such things are possible, but rarely see it in practice. People still want to be in control, which gets in the way.
* Back to innovation: needs some aspect of individualism, rather than collectivism, because people won't go off and do their own thing in the latter situation, not think on their own.

---

* Elle: Appreciating some of the systems of governance in Indigenous communities, struggling a bit more with the kinship and totems side of things.
* Richard: Yeah, finding this challenging too. Find I connect/respect more with people closer to me, which I know is a problem, can see how that limitation has led to tribalism, etc elsewhere. It feels like a barrier.

---

* Pat: I've appreciated the framing of the guidelines for 'sustainability agents' - connect, diversify, interact, adapt. But I've been wishing there was more detail, more examples of how this works in a practical sense.
* Elle: the system works with Indigenous communities, especially given the large number of communities. A balance between Collectivism vs Individualism is needed. The world keeps changing, so we need to keep changing. It all makes sense - I understand it in a social way, but not in a climate-related way.
* Narcissim, Echo, and ego. The Internet makes this selfishness a lot easier to do, less visibility of other people. Without a group to hold you accountable, you'll do whatever you want to do.
* Richard: Not sure. Perhaps a group can be wider society, and wider society has moral codes - that most people adhere to most of the time. Even when you do your own thing on the Internet - you've still got those norms from society ingrained.
* Elle: Sure, but there's a greater chance for people to go off the rails when 'alone' on the Internet.
* Richard: With regards to Narcissis, etc - have just read Stephen Fry's Troy. His books are great explainers for Greek mythology, very accessible.

---

* Richard: where do we go with this book, with regards to the book club. Do we want to finish the book together? Is there momentum from others?
* Is it an issue with the book, or just the time of year with holidays etc?
* Consensus between us on the call is that we're appreciating the book, want to keep reading it as part of the group, but will pick up the pace, so: switching back to two chapters a week.
